### ISSUE TITLE
Control D = No item found

### ISSUE THREAD

**Issue by Cruzhuge** [PoE-TradeMacro/POE-TradeMacro#1001]
When i Press Control + D it always says No item found. having this problem since a few hours, using this script since over 1 year never had this problem

**Comment by carrion21** [comment]
I also started having issues with pricing today

#####
### Please post this log file below to https://www.pathofexile.com/forum/view-thread/1216141/.
### Try not to "spam" their thread if a few other reports with the same error description were posted in the last hours.
#####

Request and response:
{
    "added": {
        "browserUrl": "https://www.poeprices.info/api?l=Legion&i=UmFyaXR5OiBSYXJlDQpHYWxlIFNwZWxsDQpJbWJ1ZWQgV2FuZA0KLS0tLS0tLS0NCldhbmQNClBoeXNpY2FsIERhbWFnZTogMjQtNDQNCkNyaXRpY2FsIFN0cmlrZSBDaGFuY2U6IDcuMDAlDQpBdHRhY2tzIHBlciBTZWNvbmQ6IDEuNTANCi0tLS0tLS0tDQpSZXF1aXJlbWVudHM6DQpMZXZlbDogNTkNCkludDogMTg4DQotLS0tLS0tLQ0KU29ja2V0czogUiBCIA0KLS0tLS0tLS0NCkl0ZW0gTGV2ZWw6IDgwDQotLS0tLS0tLQ0KMzUlIGluY3JlYXNlZCBTcGVsbCBEYW1hZ2UNCi0tLS0tLS0tDQoyOSUgaW5jcmVhc2VkIFNwZWxsIERhbWFnZQ0KMjUlIGluY3JlYXNlZCBGaXJlIERhbWFnZQ0KQWRkcyA0MSB0byA3NSBGaXJlIERhbWFnZSB0byBTcGVsbHMNCisxNyUgdG8gR2xvYmFsIENyaXRpY2FsIFN0cmlrZSBNdWx0aXBsaWVyDQorNDcgdG8gbWF4aW11bSBNYW5hDQorOSUgdG8gRmlyZSBSZXNpc3RhbmNlDQo=&w=1",
        "encodedData": "UmFyaXR5OiBSYXJlDQpHYWxlIFNwZWxsDQpJbWJ1ZWQgV2FuZA0KLS0tLS0tLS0NCldhbmQNClBoeXNpY2FsIERhbWFnZTogMjQtNDQNCkNyaXRpY2FsIFN0cmlrZSBDaGFuY2U6IDcuMDAlDQpBdHRhY2tzIHBlciBTZWNvbmQ6IDEuNTANCi0tLS0tLS0tDQpSZXF1aXJlbWVudHM6DQpMZXZlbDogNTkNCkludDogMTg4DQotLS0tLS0tLQ0KU29ja2V0czogUiBCIA0KLS0tLS0tLS0NCkl0ZW0gTGV2ZWw6IDgwDQotLS0tLS0tLQ0KMzUlIGluY3JlYXNlZCBTcGVsbCBEYW1hZ2UNCi0tLS0tLS0tDQoyOSUgaW5jcmVhc2VkIFNwZWxsIERhbWFnZQ0KMjUlIGluY3JlYXNlZCBGaXJlIERhbWFnZQ0KQWRkcyA0MSB0byA3NSBGaXJlIERhbWFnZSB0byBTcGVsbHMNCisxNyUgdG8gR2xvYmFsIENyaXRpY2FsIFN0cmlrZSBNdWx0aXBsaWVyDQorNDcgdG8gbWF4aW11bSBNYW5hDQorOSUgdG8gRmlyZSBSZXNpc3RhbmNlDQo=",
        "encodingError": "",
        "league": "Legion",
        "requestUrl": "https://www.poeprices.info/api?l=Legion&i=UmFyaXR5OiBSYXJlDQpHYWxlIFNwZWxsDQpJbWJ1ZWQgV2FuZA0KLS0tLS0tLS0NCldhbmQNClBoeXNpY2FsIERhbWFnZTogMjQtNDQNCkNyaXRpY2FsIFN0cmlrZSBDaGFuY2U6IDcuMDAlDQpBdHRhY2tzIHBlciBTZWNvbmQ6IDEuNTANCi0tLS0tLS0tDQpSZXF1aXJlbWVudHM6DQpMZXZlbDogNTkNCkludDogMTg4DQotLS0tLS0tLQ0KU29ja2V0czogUiBCIA0KLS0tLS0tLS0NCkl0ZW0gTGV2ZWw6IDgwDQotLS0tLS0tLQ0KMzUlIGluY3JlYXNlZCBTcGVsbCBEYW1hZ2UNCi0tLS0tLS0tDQoyOSUgaW5jcmVhc2VkIFNwZWxsIERhbWFnZQ0KMjUlIGluY3JlYXNlZCBGaXJlIERhbWFnZQ0KQWRkcyA0MSB0byA3NSBGaXJlIERhbWFnZSB0byBTcGVsbHMNCisxNyUgdG8gR2xvYmFsIENyaXRpY2FsIFN0cmlrZSBNdWx0aXBsaWVyDQorNDcgdG8gbWF4aW11bSBNYW5hDQorOSUgdG8gRmlyZSBSZXNpc3RhbmNlDQo=",
        "retHeader": "504",
        "timeoutParam": 25
    }
}

**Comment by Eruyome** [comment]
Closed because the issue is so old. Feel free to message again if the issues still persist.
