### ISSUE TITLE
Parsing league data (json) from Path of Exile API failed

### ISSUE THREAD

**Issue by geovnx** [PoE-TradeMacro/POE-TradeMacro#1010]
AHK version: AutoHotkey_1.1.30.03
Windows version: Windows 10 Version 1903, Build 18362.239

I have tried everything in the other issues. 
Moved the POE macro from documents to downloads to C:\\. Back to Documents to downloads to C:\\ after restarting and I continue to have the same error. 

This is what is in the last startup log: 
Starting up PoE-TradeMacro....

----------------------------------------------------------
2019-07-15T03:01Z
----------------------------------------------------------

Requesting leagues from api.pathofexile.com...

cURL command:
"C:\Users\geovn\Downloads\Addons\POE-TradeMacro-2.15.0\lib\curl.exe" "http://api.pathofexile.com/leagues?type=main" -sL -D - -o nul -A "Mozilla/5.0 (Windows NT 6.3; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.90 Safari/537.36" --connect-timeout 25 --max-time 40 

Answer: HTTP/1.1 307 Temporary Redirect
Location: https://media.aws.singtel.com/homefilter/index.html
Connection: close

**Comment by nqrcqn** [comment]
Someone is blocking the address from your modem settings. You can probably bypass it with https, check out this commit: https://github.com/nqrcqn/POE-TradeMacro/commit/6ba0aa5d7b9539adfb8098b38d04053c50de68f2 the change at jsonData.ahk: https://github.com/nqrcqn/POE-TradeMacro/blob/6ba0aa5d7b9539adfb8098b38d04053c50de68f2/resources/ahk/jsonData.ahk should be sufficient. If you get the other changes as well, most of the connections to poe.trade and currency.poe.trade will be encrypted as well. Let me know how it goes.

**Comment by geovnx** [comment]
Hey thank you for the reply.
I am not sure whether i did the right thing. 
I opened the link you placed and replaced my jsonData.ahk with the contents. 
Now I get the following error:

Accessing poe.trade using cURL failed!
"v2.15.0 
Cookie file found. 
Retrieving cookies failed. 
Windows Version: 10.0.18362 (10.0.18362), 64bit. 
Compiling 'getCookieData' script successful. 
Net Framework used for compiling: v4 
Internet Explorer: v11.239.18362.0"

**Comment by nqrcqn** [comment]
I'm not sure what that log means, but in case poe.trade is also blocked, try this: https://github.com/nqrcqn/POE-TradeMacro/archive/https.zip

You don't have to replace your existing files, you can test it separately and see whether it works. If poe.trade is indeed blocked, you may not get search results for items but currency search and others should still work.

Best solution is removing those filters from your modem, check https://media.aws.singtel.com/homefilter/index.html for details.

**Comment by geovnx** [comment]
thank you! i managed to remove the filter :)
