### ISSUE TITLE
Korean character in name prevents F4 to leave party

### ISSUE THREAD

**Issue by LMaxell** [PoE-TradeMacro/POE-TradeMacro#1011]
I have the Korean character ㅇ in my name and it wont accept that as a letter when I go to put my name in for kick yourself. Is this something fixable on my end?

**Comment by Eruyome** [comment]
I honestly don't know, will have to do some research into this.

**Comment by overshard** [comment]
Still seems to be an issue, Korean name shows up fine on the settings panel, when you then hit F4 it shows up as all question marks "/kick ?????????" in game.

**Comment by overshard** [comment]
Note I figured out the bug, for Korean characters to work you need to have the files encoded was "UTF-8 BOM", right now they are just encoded as "UTF-8". If you save all files as "UTF-8 with BOM" it will then work just fine.

I manually converted all my files but it would be nice if this was the default to save people the headache.

**Comment by Eruyome** [comment]
Converted all files to UTF-8 BOM in the new update.
