### ISSUE TITLE
Legion Legue not found

### ISSUE THREAD

**Issue by Zuldruck** [PoE-TradeMacro/POE-TradeMacro#1013]
Hello,

Since 2 days now, PoeTradeMacro does not find Legion league apparently.
In the settings the league is set to "tmpstandard" but when i do ctrl+d, there is only standard league info shown.

Thanks

**Comment by Eruyome** [comment]
Sorry for the late answer, since Legion is almost 2 leagues old/in the past I'll close this. Feel free to open it again if you have issues next league.
