### ISSUE TITLE
[Feature Request] Hotkeys for manipulating item price in premium stash

### ISSUE THREAD

**Issue by artofvs** [PoE-TradeMacro/POE-TradeMacro#1016]
Setting prices in the client is quite tedious and a few macro could help with that.
Ones I have in mind are:
1. Copy price (note) of the item under a cursor into clipboard.
This one is for when you have similar items in a stash and put a new one in. To be able to just copy-paste price from one of the items.
2. Reduce/Increase price of the item under cursor by X
X is a customizable step set in settings. One for small changes (for items priced in exalt; e.g. 0.1) and one for bigger ones (chaos and other; e.g. 5 or 10)

**Comment by Eruyome** [comment]
That alone would add another 4 hotkeys to the script, which is far too much since hotkeys already are a somewhat "scarce resource".

So, I don't think that I would implement it.
