### ISSUE TITLE
I got an issue with POE MACRO

### ISSUE THREAD

**Issue by zackycool** [PoE-TradeMacro/POE-TradeMacro#1017]
I am getting this error when i run the script : 

 "Parsing the league data (json) from the Path of Exile API failed.
   This should only happend when the servers are down for maintenance. 
       The script execution will be stopped, please try again a later time. " 
 

The thing is untill  this morning it worked and it always worked fine...i tryed to uninstall it...I tryed to uninstall and install again the AHK with both versions 32 and 64 bits...and the same problem 
What would be a solution to make it work ? Anyone can help me out pls

**Comment by matpag** [comment]
Same problem for me
