### ISSUE TITLE
i cant run the macro i keep getting this error

### ISSUE THREAD

**Issue by Demondreams** [PoE-TradeMacro/POE-TradeMacro#1026]
error at line 1 #include file "G:\lib\CalcChecksum.ahk"
duplicate function definition

please help me fix this i have downloaded and reinstalled the macro several times over and over keep getting the same error

**Comment by Eruyome** [comment]
Remove all old TradeMacro files near that location and properly extract the .zip file again into a folder like `G:\PoE-TradeMacro`.
Don't just extract it directly onto your drive root.

**Comment by Demondreams** [comment]
i tried that but ill try it again

**Comment by Eruyome** [comment]
Have you removed all old files?
What is the exact path to `Run_TradeMacro.ahk`?

**Comment by Demondreams** [comment]
its in a file in my games hard drive and yes i fully removed all the old files and made a new folder before i installed it

**Comment by Eruyome** [comment]
I will repeat myself:
What is the exact path to `Run_TradeMacro.ahk`?

I want to see if there could be anything wrong with that path, please follow my instruction.
