### ISSUE TITLE
Secondary currency is not used when no results are found

### ISSUE THREAD

**Issue by fashionLeek** [PoE-TradeMacro/POE-TradeMacro#1029]
If no results are found for the primary currency, it should search the secondary currency, but instead it shows no results:

![image](https://user-images.githubusercontent.com/25644323/64861749-aa8e5000-d628-11e9-944c-7ee5c01ae159.png)

![image](https://user-images.githubusercontent.com/25644323/64861812-de697580-d628-11e9-88be-8bb7c1312375.png)

AHK version: 1.1.30.03
Windows version: 10

**Comment by Eruyome** [comment]
Note to myself: Make a second request in case that exact currency option is selected and no results are found.

**Comment by Eruyome** [comment]
Added and working btw.
