### ISSUE TITLE
Duplicate Class: JSON

### ISSUE THREAD

**Issue by nuj123** [PoE-TradeMacro/POE-TradeMacro#1032]
Running POE-TradeMacro-2.15.2

Main issue when starting up the Run_TradeMacro.ahk: 

    Error at line 29 in #include file "(redacted)...\AutoHotkey\lib\JSON.ahk"

    Line Text: JSON
    Error: Duplicate class definition.

Explanation: I have my own JSON.ahk file in my default library folder (i.e `Autohotkey\lib\`), and I am using that for other scripts too. I don't want to have to remove that script in my AHK library solely for the PoE-TradeMacro, as my other scripts would *all* have to be re-written.  

I tried renaming the `JSON` file in `POE-TradeMacro\lib\`, to something else, but because because that JSON file was manually included, I got this: 

    Error at line 1664.

    #Include file "(redacted)...\POE-TradeMacro-2.15.2\lib\JSON.ahk" cannot be opened.

My current workaround is to flat out delete the `JSON.ahk` file located in the `\POE-TradeMacro-2.15.2\lib\` folder.

**Comment by Eruyome** [comment]
Well, what do you want me to do about it? Rewrite/rename everything on my end?

Unfortunately I'm not aware of a simple solution that doesn't require this. Feel free to suggest a solution, otherwise this is closed.
