### ISSUE TITLE
wont run

### ISSUE THREAD

**Issue by DJLexx42** [PoE-TradeMacro/POE-TradeMacro#1035]
trade macro was working propperly yesterday. to day when i started it i was prompted for an update and when i tried to update it said "The script couldn't be run successsfully."
i then went to github and got the newest version directly and it now comes up with this error

![Untitled](https://user-images.githubusercontent.com/55608584/65366196-a7213880-dbd5-11e9-9457-b713bf23c9fd.png)

i have tried downloading the previous version it comes up with the same error. i even tried redownloading AHK. no success
AHK version:
Windows version:

**Comment by Eruyome** [comment]
If it still doesn't work make sure to delete every old files/versions of TradeMacro in the same directory. There are similiar issues and the solution is always the same. https://github.com/PoE-TradeMacro/POE-TradeMacro/issues/590.

Feel free to reopen this issue if you can't or couldn't solve it.
