### ISSUE TITLE
Trademacro won't open (screenshot of error message in post)

### ISSUE THREAD

**Issue by PaaYn** [PoE-TradeMacro/POE-TradeMacro#1036]
Hello,

Since I got a new computer I had to reinstall PoE on it with its macros, however I for some reason am unable to run the trademacro.

AHK version: AutoHotkey 1.1.30.03
Windows version: Windows 10

https://prnt.sc/p92zgj (error message with 'path in it')

Any idea how I am able to resolve this issue?

Cheers, Paayn

**Comment by Therbeeo** [comment]
I'm having the exact same error message... haven't found a solution yet, but if I do I'll let you know.

**Comment by Therbeeo** [comment]
Hey I figured it out! So, I went to the location that contains "Run_TradeMacro" and I extracted all the files to another location. Bam! That's it lol. You should be able to double click Run_Trade Macro and it work. Good luck!

**Comment by Eruyome** [comment]
If it still doesn't work make sure to delete every old files/versions of TradeMacro in the same directory. There are similiar issues and the solution is often the same. https://github.com/PoE-TradeMacro/POE-TradeMacro/issues/590.

Feel free to reopen this issue if you can't or couldn't solve it.
