### ISSUE TITLE
Search result formatting sometimes broken

### ISSUE THREAD

**Issue by rhazor** [PoE-TradeMacro/POE-TradeMacro#104]
Sometimes it gives results in no formatting (ctrl+i):
![untitled-1](https://cloud.githubusercontent.com/assets/22996586/20809780/ceb37314-b80f-11e6-8c52-144e1c58bedb.jpg)

Also ctrl+alt+d don't work on 6s5l voll's protector
![sd](https://cloud.githubusercontent.com/assets/22996586/20809832/f8019ed0-b80f-11e6-9459-bd214ab6418e.jpg)

league: tmphardcore

**Comment by Eruyome** [comment]
Can you post the clipboard information after pressing ctrl+c or ctrl+d? I can use that to test this specific case.

**Comment by Eruyome** [comment]
I believe this is fixed (tooltip) with the upcoming 1.2.3 update, open this issue again if I'm wrong.
