### ISSUE TITLE
Wont start up

### ISSUE THREAD

**Issue by DJLexx42** [PoE-TradeMacro/POE-TradeMacro#1042]
I cannot get this program to work since the update. i have tried downloading several versions of trademacro and several versions of AHK. It keeps sayingt it cannot be run successfully giving me this error
![Untitled](https://user-images.githubusercontent.com/55608584/65822627-6b512900-e1fc-11e9-9039-e5708d240941.png)

PLEASE HELP

AHK version: tried several including 1.1.30, 1.1.31 and 1.1.26.01
Windows version: 10

**Comment by Eruyome** [comment]
If it still doesn't work make sure to delete every old files/versions of TradeMacro in the same directory. There are similiar issues and the solution is always the same. https://github.com/PoE-TradeMacro/POE-TradeMacro/issues/590.

Feel freee to reopen this issue if you can't or couldn't solve it.
