### ISSUE TITLE
[Bug:Minor] Wrong shortcut displayd at context help

### ISSUE THREAD

**Issue by SteffenSchreiber** [PoE-TradeMacro/POE-TradeMacro#1046]
After serching for an item on poe.trade (via shortcut alt + d), a wrong shortcut for the advanced serach is displayed at the popup.

Displayed (but wrong): Ctrl + Alt +d
Correct one: shift + Alt + d

AHK version: 1.1.31
Windows version: Windows 10

**Comment by Eruyome** [comment]
Thanks, fixed.
