### ISSUE TITLE
Error trying to open trade macro, da fak =/

### ISSUE THREAD

**Issue by eiser87** [PoE-TradeMacro/POE-TradeMacro#1047]
help please, I've tried everything already and I can't open the program

I leave an image of the error that happens when opening the program as administrator:

![ERROR POE TRADE MACRO](https://user-images.githubusercontent.com/57303102/68091564-19856980-fe60-11e9-92f1-7db822093bdc.png)

**Comment by Eruyome** [comment]
I'm assuming that this was a temporary issue, so I'm closing this issue. Feel free to correct me if you still need help.
