### ISSUE TITLE
Throws error message on screen when looking for update

### ISSUE THREAD

**Issue by deiga** [PoE-TradeMacro/POE-TradeMacro#1048]
Auto-update check or manual update check geenrates this dialog box. Which might kill me in-game, since it takes focus from the game window

AHK version: 1.1.31.01
Windows version: 10, latest

![image](https://user-images.githubusercontent.com/27202/68508163-fac31080-026d-11ea-924c-bb530a5dbb7b.png)

**Comment by LoneWolfHowl** [comment]
This happens to me too. It happens regularly throughout the day and overnight.

**Comment by Eruyome** [comment]
Added a GUI window instead, which doesn't take focus from the game window, or maybe I'll use a system tray tool tip, not sure yet. In any case the Msgbox is gone.
