### ISSUE TITLE
tmphardcore is defaulting to Standard right now

### ISSUE THREAD

**Issue by dsnvwlmnt** [PoE-TradeMacro/POE-TradeMacro#105]
trade_config.ini says; "tmpstandard" and "tmphardcore" are automatically replaced with their permanent counterparts if no Temp-League is active.

In actuality tmphardcore setting is defaulting to Standard search. Searched Geofri's Baptism on Hardcore.

This also affects ctrl+q poe.trade search. It's searching on Standard in this case.

**Comment by Eruyome** [comment]
Fixed (1.2.3)

**Comment by dsnvwlmnt** [comment]
There's still 1-2 issues. I set tmphardcore in the ini. The first time i ran it, it's defaulting searches to Standard, on Hardcore, still. If i open the settings from the start bar, and choose tmphardcore and click ok, it properly searches HC.

But now if you open the settings again, there are 2 lines saying "Hardcore". If you keep changing it and clicking OK, you can get more and more Hardcore lines in the settings window.

**Comment by Eruyome** [comment]
Yeah I know about this, also happens ith the currency dropdown but so far I ouldn't notice any real problem with that. It doesn't seem to mess anything up and gets reset on script reload. AHK is a bit difficult sometimes so I choose to ignore it for the time being.
