### ISSUE TITLE
Shortcuts Not Working

### ISSUE THREAD

**Issue by Cladezar** [PoE-TradeMacro/POE-TradeMacro#1050]
Hello, just installed the ahk and downloaded the script today. For some reason only the ctrl-c command is working. I have tried running as admin but no change. I do have the steam game and ahk installed in different drives not sure if that makes a difference. Also I installed the 32 bit version  of ahk because i didn't see anything that says otherwise, doesn't seem to matter which OS bit system. There are no errors upon startup or otherwise. Versions are 2.15.3 for TradeMacro and 1.1.32 for the ahk program, Windows version is 1909 and is 64 bit system. I tried to look for open issues didnt find any and the previous ones didnt really help.

Thanks,
Cladezar

AHK version: 
Windows version:

**Comment by Eruyome** [comment]
When the app is running you can right click the system tray icon and select ``Show all assgined hotkeys` which opens a window listing all of those hotkeys, can you show me that?

**Comment by Cladezar** [comment]
Here is a image of the assigned hotkeys.

![assigned_hotkeys](https://user-images.githubusercontent.com/27833924/70390049-d5204880-198c-11ea-8cc6-cd03df57d26f.png)

**Comment by Eruyome** [comment]
Seems fine.
Have you tried using the 64 bit AHK version just to make sure?
Have you tried using other AHK macros and see if hotkeys are working for you?
Have you tried all kinds of the hotkeys provided by TM, for example some of the ones that you can find under `AdditionalMacros` or just `alt + d` for example?

**Comment by Cladezar** [comment]
Okay its working fine i'm just an idiot. Pretty sure the problem was using ctrl and not alt. So tyvm for helping even though it was my fault lol.
