### ISSUE TITLE
"No Item Found." when trying to search w/ ctrl+d

### ISSUE THREAD

**Issue by OziumAir** [PoE-TradeMacro/POE-TradeMacro#1056]
I'm getting a return of "No Item Found." when trying to search w/ ctrl+d.  It was just working earlier before Trade Macro started locking up.  After a reboot i'm now getting this error.

**Comment by Versalkul** [comment]
Me and a friend of mine get the same error.

**Comment by sumonetwo-poe** [comment]
+1 getting this error, as is my friend

**Comment by Jigglyy** [comment]
same, what's up with that?

**Comment by nimutu** [comment]
same here

**Comment by Freakey1** [comment]
Same.

**Comment by jessicamorin** [comment]
I have the same error.

**Comment by Eruyome** [comment]
Fixed in the new v2.15.5

**Comment by KofiAddict** [comment]
The update gets stuck in a loop not being able to update from 2.15.4 to 2.15.5 gonna try to redownload macro from site

**Comment by KofiAddict** [comment]
Redownloaded from github, got update prompt anyway, cancelled it and it works

**Comment by Eruyome** [comment]
This was caused by an incorrect version tag, redownloading fixes it.

**Comment by KofiAddict** [comment]
You are a legend, thank you
