### ISSUE TITLE
How do you open default poe.trade homepage just like you open gamepedia homepage with ctrl+w?

### ISSUE THREAD

**Issue by rhazor** [PoE-TradeMacro/POE-TradeMacro#106]
Or maybe I could just remap ctrl+w to open poe.trade instead of gamepedia homepage?

**Comment by Eruyome** [comment]
You want it to open poe.trade without hovering over an item like the wiki open functions? You could just hover over a random item, but maybe I can implement this. Don't think its needed though. ctrl+q

**Comment by rhazor** [comment]
ok think it this way:
- you can hover over item and click ctrl+w and it opens the items page on gamepedia
- you can also just click ctrl+w without hovering and it opens homepage of gamepedia

- you can hover over item and click ctrl+q and it opens the search page on poe.trade
- you can't just click ctrl+q without hovering just to open the homepage of poe.trade

why

**Comment by Eruyome** [comment]
Well, it was quickly added by suggestion, not sure anymore why this wasn't also done for the poe.trade shortcut.
