### ISSUE TITLE
no response after update.

### ISSUE THREAD

**Issue by Qrakn1** [PoE-TradeMacro/POE-TradeMacro#1084]
Hello, I just updated from .5 version to .7 version and now I dont get any popups after hitting the shortcuts in game. the program still loads but nothing after.

maybe someone can help
cheers

to add more, cntr+c will bring up item info but nothing else works. never had this issue before. deleted all files and tried again same thing. also tried to go back to version .5 and that didnt work either. folder isnt on desktop either. :(

**Comment by tarik56** [comment]
Same Issue here, doesn't have anything to do with the AutoHotKey version and neither with the TradeMacro version. That's really weird.

**Comment by Qrakn1** [comment]
oh gosh LOL I'll blame it on being a new dad Cheers I was going nuts!
