### ISSUE TITLE
Bug: Rebinding in additional macros isn't working

### ISSUE THREAD

**Issue by mannerpots** [PoE-TradeMacro/POE-TradeMacro#109]
Here you can see that I have changed my AdditionalMacros .txt to include ctrl+d and ctrl+w, as well as rebinding them to numpad. However, using numpad for ctrl+c is wroking but using it for ctrl+d/ctrl+w is not. Both of these work if i press the actualy hotkeys. However, the additional macros is definitely doign something as my Numpad1 turns off my aura on W. I've also tried rebinding these key i na seperate ahk script but that also didn't work, so it must be an issue with the macro itself not the AdditionalMacros.txt [AdditionalMacros.txt](https://github.com/PoE-TradeMacro/POE-TradeMacro/files/631605/AdditionalMacros.txt)

**Comment by Eruyome** [comment]
I can take a look at this but why this round-about way? You can open the macro settings and change the bindings for every hotkey this macro has.

**Comment by mannerpots** [comment]
I didn't know that worked :p I used to use an old item script macro, and extra macros were the easiest way to remind it. But if it's in the settings menu that's awesome :)
