### ISSUE TITLE
Wrong stats on pricecheck

### ISSUE THREAD

**Issue by NeroMorto** [PoE-TradeMacro/POE-TradeMacro#1096]
**AHK version: 1.1.30.3 (64)
Windows version: 10 (1903/18362.535)**

Sometimes pricecheck takes wrongs stats:
![image](https://user-images.githubusercontent.com/1481943/71822204-59a5da00-30a5-11ea-9a7d-bde1891bcd84.png)

As you can see there no any Cold or Lightning damage stats.

```
Rarity: Rare
Woe Anthem
Harmonic Spirit Shield
--------
Chance to Block: 23%
Energy Shield: 55
--------
Requirements:
Level: 65
Int: 159 (unmet)
--------
Sockets: B B 
--------
Item Level: 74
--------
10% increased Spell Damage (implicit)
--------
+28 to Intelligence
55% increased Spell Damage
28% increased Mana Regeneration Rate
+9% to Lightning Resistance
```
I saved this item in case you need it for a testing.

**Comment by slugspanker** [comment]
#% increased Spell Damage mod contributed to #% increased Fire, Cold or Lightning Spell Damage. There are pseudo mods.
