### ISSUE TITLE
Your curl version

### ISSUE THREAD

**Issue by Lemmibl** [PoE-TradeMacro/POE-TradeMacro#1099]
Hey, so a discussion came up on reddit regarding the security of various POE trading programs.

It came up that the curl version in the POE-TradeMacro is a little odd.

https://www.reddit.com/r/pathofexile/comments/elmusm/psa_be_wary_of_installing_newly_announced/fdjep4b/

How was it built? It doesn't seem to match up with any of the precompiled binaries that can be found on the haxx download page.

Ideally if a checksum could be produced that matches a trusted source, that'd be great.

**Comment by grrev** [comment]
it's from here.

https://ci.appveyor.com/project/curlorg/curl-for-win/build/1.0.1380/artifacts

**Comment by Lemmibl** [comment]
Thanks! Saw you posted on reddit, too.
