### ISSUE TITLE
Disable Script using Pause

### ISSUE THREAD

**Issue by Noshei** [PoE-TradeMacro/POE-TradeMacro#110]
Would it be possible to add an option to change the key used to pause the script or to be able to disable this option.  I use Pause for other purposes and every time I run the script I have to edit it and go in and disable this part of the script.

**Comment by Eruyome** [comment]
Best solution would be an option in the settings menu (like the other hotkeys have). But I don't want to touch ItemInfo and pausing the script is part of ItemInfo. So I'd need to implement hotkey configuration for ItemInfo and make a pull request.

**Comment by zaregu** [comment]
Plz - add possibily to change key used to pause. It is rly annoying.

**Comment by Eruyome** [comment]
This was added for ItemInfo, the hotkey was moved to additionalmacros.txt, I will update TradeMacro soon with this when I'm making a new release. Until then feel free to just edit PoE-ItemInfo.ahk, the last line and change the hotkey.

**Comment by Eruyome** [comment]
Will be included in the next release, implemented on the dev branch.
