### ISSUE TITLE
Advanced search on spell damage shield searches for implicit mod

### ISSUE THREAD

**Issue by orlp** [PoE-TradeMacro/POE-TradeMacro#111]
If you use advanced search (Ctrl+Alt+D by default), and you have a spell damage shield with an explicit spell damage roll on it, the macro will search for a really high implicit spell damage mod, instead of a pseudo sum of all spell damage.

**Comment by Eruyome** [comment]
Thx for reporting, will look into it.

**Comment by osbornx22** [comment]
the same for dex on amu with implicit dex

**Comment by Eruyome** [comment]
Fixed in upcoming update.
