### ISSUE TITLE
Min / Max values are incorrect

### ISSUE THREAD

**Issue by joe7dust** [PoE-TradeMacro/POE-TradeMacro#1113]
The setting related to this is basing it off of what exactly rolled on the item, not the actual min/max rolls. It is very easy to see these in game by holding down the ALT key. This may not usually be a problem for the wishy-washy default of 20% min and 20% max, but if you want to actually change [this setting](https://imgur.com/9ZkT9x8) to something like exactly what yours rolled up to the max it isn't possible. Setting 0% will give you your roll, and setting 100% will just double that. In the example of a 15% lightning damage on jewel (16% actual max) the program attempts to search all the way up to 23%.

[So I guess as a work around in my case (I'd like to see what my exact roll and better ones sell for, am not interested usually in lower quality rolls), I'll just put something like 1000% in 2nd box.]

**Comment by aRTy42** [comment]
Further down in the settings you can untick "Pre-Fill Max-Values", this leaves the maximum open.
