### ISSUE TITLE
Allow a separate low/high mod range modifier

### ISSUE THREAD

**Issue by orlp** [PoE-TradeMacro/POE-TradeMacro#112]
Right now you can only choose a single Mod Range Modifier to change how the trade macro searches for mods. But oftentimes I'm interested in significantly better items as well, so for example I'd want 15% worse items, but 35% better items showing up in the search.

My suggestion is to allow the user to set up a % for both the lower range and higher range.

Rough mockup: 
![image](https://cloud.githubusercontent.com/assets/202547/20965900/1b7b5998-bc78-11e6-91ef-2a6555e58fb8.png)

**Comment by Eruyome** [comment]
Will look into implementing this.

**Comment by Eruyome** [comment]
Implemented on dev branch.
