### ISSUE TITLE
Pricesearch isnt working at all for me

### ISSUE THREAD

**Issue by lolsoftlight** [PoE-TradeMacro/POE-TradeMacro#113]
Hey, i would like to use it but i cant really get it to work. 
Pretty much every item i pricecheck for will give me a list of 1alteration, 1 alteration 1 alteration and so on.
if i press strg q to see what hes looking for on poe trade i get a list of items that are not even close to the one i wanted to check on.
for example i got like a pretty sweet corrupted amulet that i could prob sell for around 20 25c its ilvl75
if i press strg q i get like random amulets ilvl 3 upwards, white ones, blue ones, rares, amuletts that have completly different mods on it.  If i pricecheck on lvl 76+ rares from t8 maps guess what poe trade shows me if i hit strg q...random items ilvl2 upwards that dont even have a single matching mod than my item has (for example earlier i tried to pricecheck a rare pair of ilvl76 gloves with high double res on it. The pricecheck looked for lvl 2 gloves with critical chance or item rarity or even if theres only 1% res on it. 1 alteration, 1 alteration, 1 alteration... i dont get it :/

**Comment by Eruyome** [comment]
That's probably all right. What the search can is described in the FAQ and what you're describing here seem like you use ctrl + d or ctrl + q on rare items that are under ilvl 84. This normal search doesn't account for the mods on your item AT ALL. Only the advanced search ctrl + alt +d does this. Only stuff like the item type is used, the ilvl if 84+, the base if it's a desired crafting base with high enough ilvl, the links if 5/6 link.
