### ISSUE TITLE
Getting no item found on all searches

### ISSUE THREAD

**Issue by Smooshface** [PoE-TradeMacro/POE-TradeMacro#114]
Getting no item found on all searches, ctrl q brings up a page that says Bad Reqest.

The ctrl c ranges and ctrl w wiki all work.

64bit client, windows 10.

**Comment by Eruyome** [comment]
What league have you selected?

**Comment by Smooshface** [comment]
It says League: tmpstandard

**Comment by Smooshface** [comment]
I also redownloaded the current version and replaced it and it's behaving the same.  I use the "run this without admin elevation" version

**Comment by Eruyome** [comment]
Can you try the other on with admin elevation?

**Comment by Smooshface** [comment]
Admin elevation from the "Run Only This One" does work.  

Reloading the non admin one does not.

**Comment by Eruyome** [comment]
Then I'm not sure that i can fix it for the non admin elevation version. There shouldn't be a reason to use it anyway, the normal version is just fine, I added it just in case because someone requested it.

**Comment by Smooshface** [comment]
I can work with this, I just need to figure out how to bypass the UAC prompt

**Comment by Eruyome** [comment]
If you find a good solution please tell me, I can add it to the FAQ or something like that.

**Comment by Smooshface** [comment]
I didn't find a good solution to UAC, but 1.2.8 fixed it... :-)
