### ISSUE TITLE
The link to send item to poeprices.info is not working.

### ISSUE THREAD

**Issue by tuangd** [PoE-TradeMacro/POE-TradeMacro#1142]
AHK version:1.1.26
Windows version: 10 Home 1909

After you alt-d your item and you want to open to see it on poeprices.info.
That link just not working with Vivaldi browser.
I guess as it works on other browser this should be the problem on Vivaldi.
But I just want to report it, maybe somebody else has the same issue.

Thanks.

**Comment by tuangd** [comment]
I just realize after changing to other browsers, they are not working too!
I tried Brave and Firefox.

**Comment by slugspanker** [comment]
This should have been fixed.

**Comment by Eruyome** [comment]
Yes, fixed.
