### ISSUE TITLE
No results for price check.

### ISSUE THREAD

**Issue by yaminoryuu** [PoE-TradeMacro/POE-TradeMacro#115]
Whenever I use a price check hotkey (ctrl+d) the result is aways "No item found".
Tried on diferent items, uniques and non-uniques, all of them had sellers on poe.trade, but the macro just can't get to them.

When I use ctrl+q, it just says "Runing Search" forever.

I'm on WIN7 x64

**Comment by Eruyome** [comment]
Are you using the latest version? I don't have this problem. If yes, what league have you selected?

**Comment by Eruyome** [comment]
Please also take a look at this issue https://github.com/PoE-TradeMacro/POE-TradeMacro/issues/114

**Comment by yaminoryuu** [comment]
I've tried using both.
Tested on 1.2.7 and 1.2.8 with the same result.

**Comment by Eruyome** [comment]
That seems the cause then. Could you also delete the currentLeagues.json file in `temp/` and see if it gets downloaded on script start? Would be another indicator that there's no connection. Any chance you have another device/PC/Notebok where you can test this?

**Comment by yaminoryuu** [comment]
Deleted currentLeagues.json and it redownloaded it.
I don't have another pc/notebook to test =/
Is there anything else I can do to help finding the problem?

**Comment by Eruyome** [comment]
Try this here https://dl.dropboxusercontent.com/u/13620316/POE-TradeMacro.rar, I've added some debug output, there's a console window that should open. It also prints out the time stamp when certain actions are perfomed, maybe that tells us something. Try running a normal search (ctrl+d) and open on poe.trade (ctrl+q).

**Comment by yaminoryuu** [comment]
```
1.     Type 'help' for a list of commands (no quotes)

2.        03:20:13 domingo, 11 de dezembro de 2016

3.     Request Parameters:

4.        03:20:13 domingo, 11 de dezembro de 2016

5.     league=Breach&type=&base=&name=Clayshaper&dmg_min=&dmg_max=&aps_min=&aps_max=&crit_min=&crit_max=&dps_min=&dps_max=&edps_min=&edps_max=&pdps_min=&pdps_max=&armour_min=&armour_max=&evasion_min=&evasion_max=&shield_min=&shield_max=&block_min=&block_max=&sockets_min=&sockets_max=&link_min=&link_max=&sockets_r=&sockets_g=&sockets_b=&sockets_w=&linked_r=&linked_g=&linked_b=&linked_w=&rlevel_min=&rlevel_max=&rstr_min=&rstr_max=&rdex_min=&rdex_max=&rint_min=&rint_max=&mod_name=&mod_min=&mod_max=&group_type=And&group_min=&group_max=&group_count=1&q_min=&q_max=&level_min=&level_max=&ilvl_min=&ilvl_max=&rarity=&seller=&thread=&identified=&corrupted=0&online=x&buyout=1&altart=&capquality=x&buyout_min=&buyout_max=&buyout_currency=&crafted=&enchanted=

6.        03:20:16 domingo, 11 de dezembro de 2016

7.     HTML scraped, Characters: 0

8.        03:20:16 domingo, 11 de dezembro de 2016

9.     Parsed scraped HTML. Showing Tooltip.

10.       03:20:58 domingo, 11 de dezembro de 2016

11.    Request Parameters:

12.       03:20:58 domingo, 11 de dezembro de 2016

13.    league=Breach&type=&base=&name=Clayshaper&dmg_min=&dmg_max=&aps_min=&aps_max=&crit_min=&crit_max=&dps_min=&dps_max=&edps_min=&edps_max=&pdps_min=&pdps_max=&armour_min=&armour_max=&evasion_min=&evasion_max=&shield_min=&shield_max=&block_min=&block_max=&sockets_min=&sockets_max=&link_min=&link_max=&sockets_r=&sockets_g=&sockets_b=&sockets_w=&linked_r=&linked_g=&linked_b=&linked_w=&rlevel_min=&rlevel_max=&rstr_min=&rstr_max=&rdex_min=&rdex_max=&rint_min=&rint_max=&mod_name=&mod_min=&mod_max=&group_type=And&group_min=&group_max=&group_count=1&q_min=&q_max=&level_min=&level_max=&ilvl_min=&ilvl_max=&rarity=&seller=&thread=&identified=&corrupted=0&online=x&buyout=1&altart=&capquality=x&buyout_min=&buyout_max=&buyout_currency=&crafted=&enchanted=

14.       03:20:58 domingo, 11 de dezembro de 2016

15.    Url: 

16.       03:20:58 domingo, 11 de dezembro de 2016

17.    Trying to open in Browser...
```

There it is.

**Comment by yaminoryuu** [comment]
Hey!
Looks like I "fixed" it... I just uninstaled some recent windows updates, and reinstaled them! .-.
Looks like it was some missing library or something like that...
It's working perfectly now! =D

**Comment by Eruyome** [comment]
Well, that's new... never heard that happen before :-)
