### ISSUE TITLE
Wrong prices

### ISSUE THREAD

**Issue by animalnots** [PoE-TradeMacro/POE-TradeMacro#116]
Script show unreal prices. Running 1.2.8, tried both run_only and elevation versions.
![scamerino](https://cloud.githubusercontent.com/assets/4728576/21076671/773d4e4a-bf29-11e6-9322-4e50dd2baa96.png)
Url example on poe trade : http://poe.trade/search/anowoteokaduma

**Comment by Eruyome** [comment]
Should be fixed in the upcoming 1.2.9 update
