### ISSUE TITLE
Changes to PoE Item Info

### ISSUE THREAD

**Issue by aRTy42** [PoE-TradeMacro/POE-TradeMacro#117]
Hi,

I'm currently rewriting the python script used for building the Uniques.txt data file. I'm considering to have the info window for uniques only display those numbers as a modifier on the right side that actually have a range to roll within. Mods with a fixed number such as "+1 to Level of Socketed Gems" or "50% increased Global Critical Strike Chance" would no longer display the 1 or 50 at the side and remove it from the text part.

From what I see, the script does not store those values in globals or anything like that, but I am not entirely sure whether such a change would impact your handling of uniques. Does it?

While we are at it: What does the TradeMacro generally use from the InfoScript regarding uniques?

**Comment by Eruyome** [comment]
It uses absoulutely nothing, I have my own webscraping scripts using nodejs to scrape the files in `trade_data` like the [uniques.json](https://raw.githubusercontent.com/PoE-TradeMacro/POE-TradeMacro/master/trade_data/uniques.json). Absolutely no data-file from ItemInfo is used in the script, only the processed data like variables set by ItemInfo.
