### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by Ponzini** [PoE-TradeMacro/POE-TradeMacro#1178]
Tried it on 2  seperate computers. Followed the instructions exactly. Almost all of the hotkeys do nothing at all. The only 2 that do anything are: 

Alt+R which brings up a box that says "Item not suported by this function. Works only for currency" no matter which item I try and use it on. 

Alt+I which brings up the custom item search and seems to work correctly. 

I have tried every other macro on the list and absolutely nothing happens when I hit them. I tried running the macro in admin mode. I have the game in windowed fullscreen mode. Also tried in just windowed.

**Comment by Nivelm** [comment]
Temporal solution here https://github.com/PoE-TradeMacro/POE-TradeMacro/pull/1177#issuecomment-822774321

**Comment by Ponzini** [comment]
> Temporal solution here [#1177 (comment)](https://github.com/PoE-TradeMacro/POE-TradeMacro/pull/1177#issuecomment-822774321)

Thank you! Worked great :)
