### ISSUE TITLE
Range of implicit modifiers.

### ISSUE THREAD

**Issue by alazlamdurai** [PoE-TradeMacro/POE-TradeMacro#118]
This may be a question for ItemInfo but after posting and getting no response, I thought I would try here.  Is it possible to look up the range of implicit modifiers?  For example, Topaz Ring can have an implicit of 20% to 30% Lightning Resis.  The explicit modifiers all show but no the implicit.  Any way to show this?

**Comment by Eruyome** [comment]
ItemInfo has it's own data files and I'm not sure it that info is there. If not this info has to be scraped from the wiki for example. So technically it's possible, it just requires someone to write the needed scraper for it. But ItemInfo would be the right place to do this, not TradeMacro. I can check the files and open an issue after it, maybe it leads to something. I'll close this ticket here though.
