### ISSUE TITLE
Advanced search doesn't include Body Armour type

### ISSUE THREAD

**Issue by jn64** [PoE-TradeMacro/POE-TradeMacro#119]
Using Advanced search will fill in the item type on most other items I tried, but not body armours, causing the poe.trade search to return no results. Mods, sockets, ilvl, item base etc if selected are all filled in correctly.

**Comment by jn64** [comment]
So turns out it's quite simple, poe.trade expects the item subtype (?) `Body Armour` while ItemInfo and TradeMacro use `BodyArmour`. I got it working by throwing this somewhere in the middle of `TradeFunc_Main()`:

````
If (RegExMatch(Item.SubType, "i)BodyArmour")) {
	Item.xtype := "Body Armour"
}
````

But, I don't know the code well enough to know where you'd want to put it exactly.

**Comment by Eruyome** [comment]
Ok thanks, I'll implement it somewhere.
