### ISSUE TITLE
Stop resetting league setting on every update

### ISSUE THREAD

**Issue by rhazor** [PoE-TradeMacro/POE-TradeMacro#120]
I had like 2 updates in 2 days and had to set over my league option each time. First time I wasn't even aware so I kept checking prices in the wrong league for couple hours.

**Comment by Eruyome** [comment]
This won't change unless there's a script to automatically update TradeMacro, check if the ini file was changed and has to be updated to know if the ini file should be overwritten or not. I know of this problem and hopefully there will be a solution, I'll close this ticket for now. I have this issue in mind.
