### ISSUE TITLE
Adding elemental DPS search

### ISSUE THREAD

**Issue by orlp** [PoE-TradeMacro/POE-TradeMacro#121]
Right now it's basically impossible (to my knowledge) to effectively price elemental DPS weapons with the trade macro. Adding an elemental DPS search option in addition to physical DPS would be nice.

**Comment by Eruyome** [comment]
This should be working to be honest, I just noticed after checking it that it's just not there though. Will look into it.

**Comment by Eruyome** [comment]
Fixed on dev branch.
