### ISSUE TITLE
[Feature Request] Terminate script upon clicking "Download Update"

### ISSUE THREAD

**Issue by Corey103** [PoE-TradeMacro/POE-TradeMacro#122]
Hey, this is a very minor request but a nice little QoL request, but if you click the "Download Update" option on the update notifier, is there any chance you can cause it to terminate the script? That we, we can delete the old version of the script.

**Comment by Eruyome** [comment]
Yeah sure, I can implement that, practically an oversight to not already have it.

**Comment by Eruyome** [comment]
I'm working on a protoypte for an auto-updater so I'm gonna close this issue. I'm rewriting some stuff in any case and this will be implemented (close script on download).
