### ISSUE TITLE
Broken calculations

### ISSUE THREAD

**Issue by rhazor** [PoE-TradeMacro/POE-TradeMacro#123]
![untitled-1 copy](https://cloud.githubusercontent.com/assets/22996586/21081542/cda7aa52-bfd1-11e6-84da-335f5cf34f85.JPG)

**Comment by Eruyome** [comment]
This should be the same item and it works here, are you using the latest script version and could you post the clipboard information after ctrl + c here? 
This here: 

````
Rarity: Rare
Kraken Circle
Two-Stone Ring
--------
Requirements:
Level: 48
--------
Item Level: 74
--------
+14% to Fire and Cold Resistances
--------
+30 to Strength
+71 to maximum Life
+27% to Fire Resistance
+37% to Cold Resistance
0.34% of Physical Attack Damage Leeched as Life
Adds 9 to 22 Chaos Damage to Attacks
````
![life](https://cloud.githubusercontent.com/assets/16058242/21082200/1d9b90aa-bfd7-11e6-9f27-a5588892aeb0.png)

**Comment by rhazor** [comment]
```
Rarity: Rare
Phoenix Vise
Hydrascale Gauntlets
--------
Quality: +20% (augmented)
Armour: 110 (augmented)
Evasion Rating: 110 (augmented)
--------
Requirements:
Level: 68
Str: 108
Dex: 108
Int: 66
--------
Sockets: G-G-G-R 
--------
Item Level: 78
--------
Adds 1 to 2 Physical Damage to Attacks
+17 to Strength
+85 to maximum Life
+37% to Cold Resistance
+44% to Lightning Resistance
0.23% of Physical Attack Damage Leeched as Mana

```

**Comment by Eruyome** [comment]
Are you only using ItemInfo or TradeMacro bundled with ItemInfo? The functions used to calculate are the same (also what is displayed on TradeMacros advanced search GUI) and it works how it should work when I use the data you posted to show the advanced search for it. The pseudo life is right and the example I showed above also has 2 resists, for example the same cold resist you're suspecting to also be added to life.

**Comment by rhazor** [comment]
I'm using `Run_Only_This.ahk` that comes from the .zip with default settings, except tmphardcore league.

**Comment by Eruyome** [comment]
Then please make sure you're using TradeMacro 1.2.8 https://github.com/PoE-TradeMacro/POE-TradeMacro/releases/tag/1.2.9, I know there issues with this calcualtion, but those were fixed.

**Comment by rhazor** [comment]
Solved I guess.
