### ISSUE TITLE
20q ES calculation is incorrect for hybrid + craft items

### ISSUE THREAD

**Issue by orlp** [PoE-TradeMacro/POE-TradeMacro#124]
If you use Ctrl+Alt+D in the default bindings the interface will show you the current energy shield of an item, assuming 20 quality. However if an item has both hybrid ES and an ES master craft on it but no quality yet, this calculation is incorrect. I assume this is because the energy shield % mod is on two separate lines.

I didn't test it for hybrid + % craft for evasion, armour or any of the hybrids, but I assume the same bug occurs for them as well.

**Comment by Eruyome** [comment]
Thx for the report, will look into it.

**Comment by orlp** [comment]
It's even incorrect when the item is already 20 quality:

```
Rarity: Rare
Plague Call
Titanium Spirit Shield
--------
Quality: +20% (augmented)
Chance to Block: 25%
Energy Shield: 479 (augmented)
--------
Requirements:
Level: 68
Int: 159
--------
Sockets: B R 
--------
Item Level: 73
--------
42% increased Energy Shield
+127 to maximum Energy Shield
+38% to Fire Resistance
+8% to Lightning Resistance
15% increased Stun and Block Recovery
65% increased Energy Shield
```

Correct ES (as shown in-game) is 479, tool reports 480.

**Comment by Eruyome** [comment]
Is it always only this small of a difference? If yes that's practically negligible, probably rounding errors.

**Comment by orlp** [comment]
No, I've seen the low quality version off by more than 10 ES.
