### ISSUE TITLE
fix "^c" in PriceCheck: etc.

### ISSUE THREAD

**Issue by Uoipka** [PoE-TradeMacro/POE-TradeMacro#126]
https://github.com/PoE-TradeMacro/POE-TradeMacro/blob/master/trade_data/TradeMacro.ahk
"Send ^c" work only on english keybourd layout (or the same)
like in russian keyboard layout it's didn't work. just no copy > display old item result > and u lose good item to vendor ( like me today, bye bye my Belly of the Beast :D )
easy to fix:
replace with scan code "Send ^c" > "Send ^{sc02E}" and... it's work..

**Comment by Eruyome** [comment]
Thx for the report. I believe this should be fixed in ItemInfo, so I'm gonna suggest there, too. What about the other shortcuts, do they also need scancodes?
