### ISSUE TITLE
[Bug] Running Script From Batch File Throws Error

### ISSUE THREAD

**Issue by Chazuke** [PoE-TradeMacro/POE-TradeMacro#127]
Attempting to run the file "Run_Only_This.ahk" from a batch file created using notepad will throw "Error: Call to nonexistent function" on line 655 of main.ahk for the function GuiAddGroupBox().

Lines used to run the script (fails for both):
start "" "C:\Program Files\AutoHotkey\AutoHotkeyU64.exe" "C:\Program Files\POE-TradeMacro-1.2.9\Run_Only_This.ahk"
start "" "C:\Program Files\POE-TradeMacro-1.2.9\Run_Only_This.ahk"

Doesn't work even if files are stored on Desktop.

![capture](https://cloud.githubusercontent.com/assets/5739400/21117087/4db37410-c086-11e6-8a66-658905becb5a.PNG)

**Comment by Eruyome** [comment]
I'm using this:

````
cd /D "D:\Users\Eru\Documents\AHK Scripts\Path of Exile\PoE-TradeMacro"
start Run_Only_This.ahk
````

Works for me. Please try it and report back. I don't think there's anything with the script itself that can be changed to make it work for you, at least not to my (limited) knowledge.

**Comment by Chazuke** [comment]
Your suggestion works. I talked with a friend and found that it is also possible to create a shortcut of the script and then run the shortcut with the start command. However, I'm able to run a logout macro that also uses AHK with the start command as described. This is what led me to believe it was the script at fault, but since it's possible to run it with the start command after changing directories perhaps it's a bug with AHK? Or maybe the start command? Or perhaps a specific interaction with the function that threw the error in the first place? Probably not worth spending the resources to find out. I suggest adding this to the FAQ or troubleshooting section since I wasn't able to find any good documentation about this.

**Comment by Eruyome** [comment]
Yeah, adding this to FAQ might be a good idea, glad it also works for you.
