### ISSUE TITLE
Error:  0x80070459 - No mapping for the Unicode character exists in the target multi-byte code page.

### ISSUE THREAD

**Issue by Eruyome** [PoE-TradeMacro/POE-TradeMacro#13]
---------------------------
main.ahk
---------------------------
Error:  0x80070459 - Für das Unicode-Zeichen ist kein zugeordnetes Zeichen in der Mehrbytecodepage vorhanden.

Source:		WinHttp.WinHttpRequest
Description:	Für das Unicode-Zeichen ist kein zugeordnetes Zeichen in der Mehrbytecodepage vorhanden.

HelpFile:		(null)
HelpContext:	0

Specifically: ResponseText

	Line#
	8300: HttpObj.SetRequestHeader("Content-type","application/x-www-form-urlencoded")  
	8301: HttpObj.SetRequestHeader("Accept","text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8")  
	8302: HttpObj.SetRequestHeader("Referer","http://poe.trade/")  
	8303: HttpObj.SetRequestHeader("Accept-Encoding","gzip;q=0,deflate;q=0")  
	8305: HttpObj.SetRequestHeader("Accept-Language","en-US,en;q=0.8")  
	8307: HttpObj.Send(payload)  
	8308: HttpObj.WaitForResponse()  
--->	8314: html := HttpObj.ResponseText
	8319: Return,html
	8320: }
	8322: {
	8323: itemCount := 1
	8324: prices := []
	8325: average := 0
	8326: Title := ""

Continue running the script?
---------------------------
Yes no
---------------------------

**Comment by Eruyome** [comment]
https://autohotkey.com/board/topic/101686-objectresponsetext-error/

**Comment by abraksas14** [comment]
thx, but i'm not a guy, who understands that much about makros and there implementation, that i could just transcribe the information given in this thread.

**Comment by Eruyome** [comment]
This information is for every developer who wants to solve this problem. You don't have to understand it, just follw it to see if someone solves it.

**Comment by thirdy** [comment]
Last time I saw this error was due to gzip. And the fix to that to disable this encoding:

`HttpObj.SetRequestHeader("Accept-Encoding","gzip;q=0,deflate;q=0") `

Not sure on this one tho
