### ISSUE TITLE
Can't execute the run_only_this.ahk?

### ISSUE THREAD

**Issue by icychill9** [PoE-TradeMacro/POE-TradeMacro#130]
Whenever I attempt to run the file I get an error message saying:

----------------------------------------------------------------------------------------------------------------------

Error at line 2.

#Include file
"C:\Users\Christopher\AppData\Local\Temp\Rar$Dla0.158/trade_data/Version.txt"
cannot be opened.

The program will now exit.

----------------------------------------------------------------------------------------------------------------------

Any idea what's wrong?

**Comment by Eruyome** [comment]
Where have you extracted the TradeMacro folder to? It seems the script is trying to access a file from your Temp folder, that shouldn't be the case and could be the problem.

**Comment by Dautful** [comment]
I'm having the same issue. I extracted my TradeMacro folder to my C drive.

**Comment by s1monxyz** [comment]
Same issue here. Extracted same way I've done in months. Drag folder outside of ZIP to C-Drive and then right click the run_only_this - also tried the Without_Admin_Elevation, both gave the same error.

**Comment by Thijscream** [comment]
got the same error image included in url.
http://imgur.com/wqSyiZY

**Comment by Crymsius** [comment]
Same here, pretty sure it's because of the maintenance of the poe website : the macro tries to fetch the temporary league on it if I understand correctly.

**Comment by Eruyome** [comment]
Yeah it does and I should implement some fallback for it, using an already downloaded file (earlier use) or at leat showing an appropriate error message.

**Comment by Eruyome** [comment]
Is there still an issue here or can I close this?

**Comment by Thijscream** [comment]
For me everything is working fine, I don't think anyone else is having problems else there would be alot more comments here.

**Comment by Eruyome** [comment]
Well, this can always be reopend it something is wrong.
