### ISSUE TITLE
Update to version 11 will no longer launch.

### ISSUE THREAD

**Issue by BanditBanditBandit** [PoE-TradeMacro/POE-TradeMacro#135]
It was working fine until I just was prompted to update. Its saying something about json?

![error message poe trade macro](https://cloud.githubusercontent.com/assets/13251996/21168203/17358ce8-c167-11e6-95ac-5a372a4961fb.png)

**Comment by BanditBanditBandit** [comment]
is it because the servers for the game happened to be reset right now?

**Comment by Eruyome** [comment]
Yeah, unfortunately the entire servers and servies are down when there's an update/realm maintenance.
