### ISSUE TITLE
Crash on start when pathofexile.com is down for maintenance.

### ISSUE THREAD

**Issue by aggixx** [PoE-TradeMacro/POE-TradeMacro#136]
It seems the API it uses to fetch current leagues fails when PoE is down for maintenance. This causes the script to crash when it tries to load non-JSON content as JSON. Ideally it should handle the error without closing, perhaps with a notice of some sort.

Error:
https://imgur.com/a/t7GtY

Contents of temp/currentLeagues.json
http://pastebin.com/dPKUwTJ2

**Comment by Eruyome** [comment]
I know of this and I should implement some fallback for it, using an already downloaded file (earlier use) or at leat showing an appropriate error message.

**Comment by Eruyome** [comment]
Fixed on dev branch.
