### ISSUE TITLE
Suggestion! Add this! 

### ISSUE THREAD

**Issue by potasium56** [PoE-TradeMacro/POE-TradeMacro#138]
You should add in how long an item has been listed on poe.trade for in the ctrl - c window....It does show this in the window when you do the ctrl - alt and d - but this does take time...would be cool to add this to the first command i stated. Not sure if this is possible but just a thought...

**Comment by Eruyome** [comment]
ctrl + c is the ItemInfo tooltip,  no search involved here, you probably mean ctrl +d, but the item age is already displayed in this case. Until you prove me otherwise (some bug maybe) I'll close this issue.

**Comment by potasium56** [comment]
its not in ctrl - d window - well only if your name is in the list before when you search your item, but if your name is not below then you have to resort to the longer process like acually searching your item on poe.trade to see how long its been listed...

**Comment by Eruyome** [comment]
https://github.com/POE-TradeMacro/POE-TradeMacro/wiki/Usage---Installation There's a function/hotkey for that, "Show item age". This will not be mixed with the ctrl + d search however.

**Comment by potasium56** [comment]
Ahhh...when i used that command it gave me an name error or w.e not sure why?
