### ISSUE TITLE
[Feature] Open poe.trade after advanced search (new shortcut)

### ISSUE THREAD

**Issue by Rodrive** [PoE-TradeMacro/POE-TradeMacro#140]
First of all great work for the job done here !

I would like to know if its possible to open poe.trade after an advanced search (ctrl + alt +d)

I saw the message _(Pro_Tip: Use Alt + S/E to submit a button)_ but i'm not sure what this is supposed to do neither that what is S/E hotkey.

**Comment by Eruyome** [comment]
Oh sorry, never thought this could be misleading, it means instead of using the mouse to click the buttons on the GUI window you can use either `alt + s` and `alt + e` to "press/submit/use" the `Search` and `Open on poe.trade` button.

**Comment by Eruyome** [comment]
For the record, here my answer to the other part of the question from discrod:

I'm pretty sure I would need to add another shortcut for this, can't reuse the normal ctrl +q (open on poe.trade) for this. TradeMacro is already kind of bloated with all it's hotkeys though.

I would have to change how and when this (already existing) cache would be emptied, and without a new hotkey probably won't be able to differentiate between wanting to use the normal ctrl + q without all the selected mods and the advanced ctrl + q.
So its quite likely that I'll end up adding another hotkey and this is something I want to be careful with. I don't want the script to be too bloated with hotkeys.

Implementing this isn't ruled out, just a low priority.
