### ISSUE TITLE
Disabled Update Notification

### ISSUE THREAD

**Issue by osbornx22** [PoE-TradeMacro/POE-TradeMacro#143]
I disabled update notification, because there is every day an update, but still get update notifications.

**Comment by Eruyome** [comment]
Ok, have to check that. When I release updates too often it's mostly because there's a need to do it (fixes that are important enough), I try to not do it too frequently though ;-)

**Comment by osbornx22** [comment]
Yeah, thats wonderful, thank you very much for that, fantastic work.
