### ISSUE TITLE
[Suggestion] Select all in Advanced Search

### ISSUE THREAD

**Issue by Dagda47** [PoE-TradeMacro/POE-TradeMacro#147]
Could you add a "select all" button in the advanced search menu? It would make searching for jewels less tedious.

**Comment by Eruyome** [comment]
Yeah, still thinking about how to implement it. Updating GUIs in AHK is a bit tedious, for example to check some checkboxes when an "include all" checkbox is checked, I'd have to destroy the GUI and recreate it with different checkbox states. Not checking the other boxes would look like a bug. Anyway, for now I'm mostly doing bug fixes, all the other stuff will have to wait a few days.

**Comment by Eruyome** [comment]
added on dev branch
