### ISSUE TITLE
Not Seeing Results CTRL - D 

### ISSUE THREAD

**Issue by potasium56** [PoE-TradeMacro/POE-TradeMacro#150]
so went to try and see what my skill gem is worth and nothing showed up on the results which is weird not sure whats going on with your macro, but please fix :)

**Comment by itsmealwin** [comment]
Can confirm.

**Comment by rbarbosatoro** [comment]
Yesterday , poe.trade died for a few hours. I think they changed the Hosting though the DNS is still the same as ever.

**Comment by potasium56** [comment]
so when you think the macro will start showing results again?

**Comment by rbarbosatoro** [comment]
They should release an API to ease the develop of these scripts/programs.
For the moment, we can only wait.

Im looking into the source to find how this macro manage the connection to poe.trade, but either way don't expect a fast answer to the problem.

**Comment by potasium56** [comment]
i don't expect a fast answer lol, just wanted to know why it wasn't showing results...hopefully the actual owner of the program will reply...

**Comment by qraparta** [comment]
I can only guess, but I think it has something to do with Cloudflare. Before it CTRL-D was working as intended, but after it doesn't work anymore

**Comment by donovv** [comment]
for now just use ctrl+q to open search in browser its still working

**Comment by omriharel** [comment]
@potasium56, while I haven't looked into the source code I'm assuming that the recently introduced CloudFlare DDoS protection is what's breaking the macro. Specifically, I imagine the script sends an HTTP request to poe.trade and parses its response body, but doesn't verify that it got the expected status (200 OK) and just presents an empty table in the tooltip (instead of more elegantly reporting a connection error in the tooltip).

As to why it's getting a 5xx error code from poe.trade, probably one of the things CloudFlare does is check for the User-Agent header on requests made to the website. This is typically used by web servers to determine which browser (or other thing, such as this script) made the request and decide how and whether they want to respond to it, thus reducing the DDoS potential from external sources (again, such as the script). If @thirdy would send his requests with Chrome's UA, I imagine he'll go through.

**Comment by potasium56** [comment]
well im justing hoping that it can be fixed because this tool helps me alot ingame...thanks for explaining now we all just have to wait until its fixed...

**Comment by davideugenepeterson** [comment]
Can't you just change the user agent in a header request manually,  that shouldn't be the issue.

**Comment by omriharel** [comment]
As a developer, you have full control as to what headers are sent with the requests you're making. I'm guessing that the developer simply hasn't attached any user agent to his requests, and CloudFlare doesn't like that and drops them as part of its DDoS protection.

**Comment by davideugenepeterson** [comment]
That should be pretty easy fix let me dig through the code and suggest a merge. Sure how to do it in JS, C, JS, PHP. But I think he is using ahk without double checking it. I never use that.

**Comment by omriharel** [comment]
Hint - he's using WinHttpRequest as his client, imported via COM object support in AHK.
Usage is at https://github.com/PoE-TradeMacro/POE-TradeMacro/blob/master/trade_data/TradeMacro.ahk#L1029 - it does look like he's setting headers. If you want to delve into it, you would need to replicate his request in something like postman and see if you can get it to work

**Comment by davideugenepeterson** [comment]
Yeah been using https://www.getpostman.com trying to get it to work atm

**Comment by davideugenepeterson** [comment]
Did some research on http://stackoverflow.com/questions/31950470/what-is-the-upgrade-insecure-requests-http-header, think thats one way to get it to work. Disabled that and ctrl - Q to bring up on poe.trade in chrome is now working for me. Now i'll just implement that into the other stuff and get prices to check and such.

**Comment by Jiinnx** [comment]
It is not only about user agent.
Main issue is with cookies. CF need you to present with cookies that he provide you first time you try to reach poe trade site.

Once i added in my script the cookies from my browser i can use it as before without an issue.

**Comment by omriharel** [comment]
Awesome, I'm sure it's a matter of not too long before @thirdy would make the change (or until your fix gets pulled in provided that it works). :)

**Comment by davideugenepeterson** [comment]
Oh sweet, if that works that will be much better than how I went about fixing it myself.

**Comment by tradingaddict** [comment]
Any temporary fix until it gets an official update? Going nuts without this script.

**Comment by kyri0** [comment]
#149
