### ISSUE TITLE
Currency search working but not item search

### ISSUE THREAD

**Issue by Xaxifer** [PoE-TradeMacro/POE-TradeMacro#151]
I recently did the bypass for cloudfare protection, and now whenever I use the ctrl-d macro on items it will return with "No item found." However, when using ctrl-q or ctrl-w on an item, it works just fine. I am also able to use ctrl-d on currency with no problems. I have also reinstalled the macro as well.

**Comment by nooksXS** [comment]
same problem here, even with the new version 1.3.0

currency is working fine, item search wont work at all

**Comment by Eruyome** [comment]
With the current implementation I see no difference between both searches, if one works, the other should also. I'll try to find something.

**Comment by Xaxifer** [comment]
I updated to 1.3.0 and am still receiving the same results.

**Comment by nooksXS** [comment]
UPDATE

i change the default browser from Chrome Version 55.0.2883.87 to Firefox 50.1.0 and use the firefox web console to fint the user agent, cfduid and cf_clearance und used these information

now it works for currency and item search

**Comment by Eruyome** [comment]
Ok, that's interesting, but suggests the problems are on the users side.

**Comment by mktums** [comment]
> suggests the problems are on the users side

Unfortunately it's not.
Since last update poe.trade is using CloudFront's Anti-DDoS Protection, and without cookies it'll not let you on site.

**Comment by jn64** [comment]
@mktums the user changed cookies and it worked, proving that the workaround method works. The most likely cause is the first pair of cookies was input incorrectly.

**Comment by Eruyome** [comment]
I'm gonna close this for now, if it's still a problem for someone just reopen it.
