### ISSUE TITLE
Need help! Ctrl+d not working.

### ISSUE THREAD

**Issue by Alex2817** [PoE-TradeMacro/POE-TradeMacro#152]
Ctrl+d not working. POE-TradeMacro-1.2.12.
When i press ctrl+d http://i.imgur.com/S8fUQVs.png
poe.trade works fine.
Please, help me.

P.S sorry for bad english.

**Comment by jamesblack** [comment]
Please See #149

**Comment by Alex2817** [comment]
Thank you very much all happened.
