### ISSUE TITLE
Error at script launch "StringReplace requires that parameter #3 is not blank"

### ISSUE THREAD

**Issue by Eruyome** [PoE-TradeMacro/POE-TradeMacro#153]
http://prnt.sc/dmkon2

@Fredsloko made you a new issue, seems unrelated to the cloudflare problem.

**Comment by Eruyome** [comment]
Please make sure you're using the latest version 1.3.0, and that you're using `Run_only_this.ahk`.

**Comment by Fredsloko** [comment]
@Eruyome just for to verify, i'm using 1.3.0 and using `Run_only_this.ahk` :3

**Comment by Eruyome** [comment]
Anything else you can tell me? Win version, AHK version.

**Comment by Fredsloko** [comment]
Win 8.1 pro, ahk the last, i download today.

**Comment by Eruyome** [comment]
Can you test one of the older versions? I'm running 1.1.24.01
https://autohotkey.com/download/1.1/

**Comment by Fredsloko** [comment]
Same problem. in 1.1.24.1, the last version is 1.1.24.04

**Comment by Eruyome** [comment]
That's really annoying, will have to look at this later, can't find the problem right now. It's likely some problem on your end, since this part of the code exists for a very long time now without changes and I never heard of this problem.

**Comment by Eruyome** [comment]
https://github.com/PoE-TradeMacro/POE-TradeMacro/issues/164

**Comment by Eruyome** [comment]
I'm gonna close this issue for now, if you still have this problem just reopen it.
