### ISSUE TITLE
Mod rolls are being ignored

### ISSUE THREAD

**Issue by BasimAsghar** [PoE-TradeMacro/POE-TradeMacro#156]
!! Mod rolls are being ignored !! error shows up when I attempt to search item.
[Image](http://imgur.com/2HOqDqF)

Attempts to fix issue:
Re-download 1.3.0
Check if data inputted to cookie file was incorrect.
Issue still appears

Downloaded v 1.2.12
Attempt to use old fix.
Fix applied successfully
Issue still appears

Edit: I have chrome set up as the default web browser.

**Comment by Eruyome** [comment]
That's no error, that's a notice so that you don't think they are actually being considered.

Use ctrl + alt +d to not ignore them.
