### ISSUE TITLE
A possible Solution for the cloudflare problem

### ISSUE THREAD

**Issue by ZeroCool940711** [PoE-TradeMacro/POE-TradeMacro#157]
Hi there, I saw you have lot of troubles with cloudflare now that poe.trade is using it, a possible solution to fix this or that you could be used with something else to get the required thing for the script to work would be to use a python module called [cfscrape](https://pypi.python.org/pypi/cfscrape) , you could use that module to get the cloudflare cookie and other info or use it to make request directly to poe.trade, my advice would be to create a simple script that make a few request to poe.trade and compile the script to an .exe using py2exe or an alternative to it and include that file with the macro, run the script to get the cookie from poe.trade and put it on a file and then every time the macro is execute if the cookie is not present then the script can be run again to get the cookie and the user doesn't have to do anything manually. Hope it help, have a good day.

**Comment by Eruyome** [comment]
Thanks for your suggestion, this is/was already discussed along some other solutions. You could probably start reading from here https://github.com/PoE-TradeMacro/POE-TradeMacro/issues/149#issuecomment-268762611
