### ISSUE TITLE
[Bug] Advanced Search does not clear stats after searching

### ISSUE THREAD

**Issue by Aerinx** [PoE-TradeMacro/POE-TradeMacro#158]
Reproduction steps:
1. Ctrl+Alt+D (Advanced Search) on Abyssus
2. Select Increased physical damage taken
3. Type 45 in max field, delete min field and leave it empty
4. Press search
5. Ctrl+Alt+D (Advanced Search) on Rive (any unique I think)
6. Press search

Result: Empty results because it is searching with Increased physical damage taken mod with Rive name as you can see when you use Open on poe.trade.

Restarting the script fixes it.

Ninja update: After some more testing it seems to happen when you leave the min option on any mod empty and blank.

**Comment by Eruyome** [comment]
Fixed on dev branch, stupid error, really...
