### ISSUE TITLE
 [Bug] Unintended search results on some items

### ISSUE THREAD

**Issue by Aerinx** [PoE-TradeMacro/POE-TradeMacro#159]
When searching prices for some items like prophecies and divination cards you will get other items with similar names that are of a different type and you can not know which is what nor filter them.

Eg: Search for The Void divination card, you will get prices from prophecies mixed with the cards.

Possible solutions:
 |> Show Item Base or Item Name on search results.
 |> Limit search by including Item Base on any search that does not allow you to do an Advanced Search.

Additional notes: It might also happen with Vortex and Blade Vortex gems, I have not tested that, but it happens when you search for Vortex in poe.trade

**Comment by Eruyome** [comment]
Thought this was all fixed by now, will check. In case of Vortex and Blade Vortex, I don't think I can do much about it.

**Comment by Eruyome** [comment]
Works for me when searching div cards, maybe it was the other way around and you got div cards mixed in when searching prophecies, I think I don't check them.

**Comment by Aerinx** [comment]
I just tested it now and it does not filter prophecies out. I used Ctrl+D on "The Void" divination card, I get low prices mixed with the 10c that the card is sold for and when I go to poe.trade and check the results I can see that I got "A Call into the Void" prophecy results mixed in with the card results, prices and sellers match.

**Comment by Eruyome** [comment]
Have to check that specific card then, can you press ctrl + c and post the data copied to your clipboard here? I can use that to test the item without actually having it. Maybe ItemInfos parsing fails on this card, normally all div-cards should use the base (Divination Card) in the search.

**Comment by Eruyome** [comment]
Should be fixed in the upcoming release, ItemInfo parsed some cards incorrectly, because cards like The Void don't have a stack size and this was a requirement.
