### ISSUE TITLE
CTRL-D: "No item found."

### ISSUE THREAD

**Issue by deemera** [PoE-TradeMacro/POE-TradeMacro#161]
When I use CTRL-D to get a price check on an item (rare, unique, doesn't matter), it says "No item found."

I installed the latest version (1.3.0). When I start it up (using Run_Only_This.ahk), I got the message about the cookie data workaround. I used the instructions  [here](https://github.com/PoE-TradeMacro/POE-TradeMacro/issues/149#issuecomment-268639184) to update the cookie_data.txt file with my useragent, cfduid, and cfclearance. Then I reloaded the script.

Went into POE Trade Item Info Settings and verified that my league is set to tmpstandard.

Started up POE, and tried out the CTRL-C to check what the random roll ranges are for a few items, no problem. But when I use CTRL-D to check prices, it says "No item found." And when I use CTRL-Q to open a poe.trade search, I get dumped [here](https://www.cloudflare.com/5xx-error-landing/?utm_source=iuam).

I've tried disabling UAC and my firewall, verified that I'm logged in under an Admin account. I'm running 64-bit Windows 10. Oh, and I found a link to a debug version of the [script,](https://dl.dropboxusercontent.com/u/13620316/POE-TradeMacro.rar) but it just says it's an old outdated version, and won't load.

**Comment by Eruyome** [comment]
https://github.com/PoE-TradeMacro/POE-TradeMacro/releases/tag/1.4.0-beta Try this here please.

**Comment by deemera** [comment]
Awesome! Looks like you guys figured out how to have it read in the cookie info automatically. Great work. :-D
