### ISSUE TITLE
CTRL+W don't work on Chaotic Disposition

### ISSUE THREAD

**Issue by rhazor** [PoE-TradeMacro/POE-TradeMacro#168]
```
Rarity: Divination Card
Chaotic Disposition
--------
5x Chaos Orb
--------
Life isn't what you make of it, it's already been made for you.
```

Neither in inventory or stash. Ctrl+Q works.

**Comment by Eruyome** [comment]
Works for me, are you using 1.4.1?

**Comment by rhazor** [comment]
i don't know. on About it say 2.5.01 where else do you check?

**Comment by Eruyome** [comment]
2.5.01 is ItemInfo, you can hover over the system tray icon for example.

**Comment by rhazor** [comment]
Probably that was it
