### ISSUE TITLE
main.ahk code issue (need help please)

### ISSUE THREAD

**Issue by jamison654321** [PoE-TradeMacro/POE-TradeMacro#169]
When I try to run Run_Only_This I get an error saying 

main.ahk
error at line 10521
line text: ;
error: the leftmost character above is an illegal expression.

So I open main.ahk with notepad++ and go to line 10521
The entire line is posted below. So I tried to delete the leftmost ; 
restart run_only_this and it still doesnt work. Go back to notepad++ and the ; character was back. so repeated the last steps a couple times making sure im clicking the save button. But it still comes back and still gives me the same error

this is line 10521 in my main.ahk
HttpObj.SetRequestHeader("User-Agent", Mozilla/5.0 (Windows NT 6.1; WOW64; rv:50.0) Gecko/20100101 Firefox/50.0)

Also this is with the latest version

**Comment by Eruyome** [comment]
main.ahk gets generated on every script start, chaing something here is pointless. You'll have to change the corresponding line in trademacro.ahk/trademacroinit.ahk.

Anyway, what version are you using? 1.3.0 where you have to edit the files yourself? If that's the case what's the reason for not using 1.4.1?

**Comment by jamison654321** [comment]
I am using 1.4.1

**Comment by Eruyome** [comment]
But it still seems you're editing the script, and not just because you get an error msg? Otherwise there should be variables in the line you posted, not the actual values.

**Comment by Eruyome** [comment]
Please test the latest release 1.5.0 and close this issue if the mentioned problems are resolved.

**Comment by jamison654321** [comment]
Seems to be working ok now. thanks.
