### ISSUE TITLE
Error 0xc0000142 (Chrome)

### ISSUE THREAD

**Issue by darkkaos** [PoE-TradeMacro/POE-TradeMacro#170]
Using W10 14393.577, lastest version of poe trade macro (1.4.1)

When I try to use the ctrl+q shortcut or the advanced search, ctrl+alt+d, chrome just stuck on this error. 

Chrome is set to be the default browser. If I switch to Edge, it run smooth.

The weird part is, it just happen if I use the "Run_Only_This". If I launch the PoE-Trade-Macro.exe, all goes fine. No errors.

Any ideas? What is the problem (or the difference) to run the exe?
![sem titulo](https://cloud.githubusercontent.com/assets/24784189/21488340/8f50434a-cbc5-11e6-9327-88c3cdc93fa1.png)

**Comment by Eruyome** [comment]
I don't really know what the difference is, will have to read up on that as well. 
Aside from that, it would be helpful if you could roughly translate your error msg ;-)
It's probably "The application was unable to start correctly", right?

**Comment by darkkaos** [comment]
Oh, yeah. Sorry about that. The translation is really that. I forgot that I was typing in english but my system is brazilian portuguese :P

**Comment by mrvice** [comment]
Run the exe file in 1.4.1

**Comment by darkkaos** [comment]
@Eruyome So, I found the problem. Win10 fresh install wasn't with C++ redistributable installed. After install it, the "Run_Only_This" works perfect. Ty for your answer and I wish that this solution helps you in other situations :)

**Comment by Eruyome** [comment]
Added this to the FAQ.
