### ISSUE TITLE
1.4.1 bugs

### ISSUE THREAD

**Issue by mrvice** [PoE-TradeMacro/POE-TradeMacro#171]
System Windows 10  - 64

I used 1.3.0 before and deleted the folder and replaced it with the new one.

Frist time i run the exe i get an error message ( seems like cannot retrive cookie data ) my default browser is chrome never used internet explorer. 
2nd run of the exe program started working no error message(s)

BUT the format is off when you use the macro on a unique price tags and so on are not formatted correctly anymore.

i rolled back to 1.3.0

**Comment by Eruyome** [comment]
Your default browser doesn't matter, it also doesn't matter what browser you use. 
I'll make a release today, in a few hours, Try that then, repeat starting the .ahk file if the bypass fails, you can also overwrite the automatic cookies and set them yourself again (settings menu), the .exe is the fallbacl if everything else fails, I'm aware of the formatting issues.

**Comment by Eruyome** [comment]
Please test the new release and close this issue if the mentioned problems are resolved (aside from the .exe formatting).

**Comment by mrvice** [comment]
Downloaded 1.5.0 extracted it in a seperate folder .
starting the run_only_this.ahk worked instantly fine.
Running the Exe poped up an cokkie error window , clicked the X at top right corner after a few seconds started working too , except the formating you already aware off.

Only thing i could complain now is its not working in fullscreen mode under Directx9EX
(Direct9 is not an option because alt+enter or chanenging in graphic settings to window or window borderless mode will make the game crash, playing in bordless window mode is not possible because of the performance issues of the game, so thats my current solution using directx9ex and alt+enter every time i use the makro.)

Nice work btw

**Comment by Eruyome** [comment]
Well, ther's simply no work-around to display ahk tooltips/guis in fullscreen applications.
