### ISSUE TITLE
Extremely small documentation issue

### ISSUE THREAD

**Issue by InfiniteIce** [PoE-TradeMacro/POE-TradeMacro#172]
In Tradeconfig.ini:

`RemoveMultipleListingsFromSameAccount =1
; Removes multiple listings from the same account from the search results (combat market manipulators)
; Default is 0 = off, set to 1 = enabled`

Clearly the default is set to 1 in version 1.4.1, and is stated as being default of 0.

Should be changed to say default is 1 = enabled for clarity of documentation.

Thanks for your continuing work <3

**Comment by Eruyome** [comment]
Fixed.
