### ISSUE TITLE
Support fetching cookies with Chrome/Firefox

### ISSUE THREAD

**Issue by Eruyome** [PoE-TradeMacro/POE-TradeMacro#173]
EDITED/replaced original post:
There still seem to be quite some people having problems with the automatically fetched Internet Explorer cookies while the manually retrieved cookies from Chrome/Firefox are working for them.

The IE cookies and user agent are fetched by `\lib\getCookies.cs` (c# script, compiled via .Net Framework on scriptstart).

This seems interesting [https://www.codeproject.com/Articles/330142/Cookie-Quest-A-Quest-to-Read-Cookies-from-Four-Pop]( https://www.codeproject.com/Articles/330142/Cookie-Quest-A-Quest-to-Read-Cookies-from-Four-Pop), it doesn't work for Chrome though. There's a fix in the [comments](https://www.codeproject.com/Articles/330142/Cookie-Quest-A-Quest-to-Read-Cookies-from-Four-Pop?msg=5094629#xx5094629xx), still had no success.
Could probably be done with powershell, too.

Goal: 
- Make some script to automatically fetch Firefox and Chrome cookies/useragent.    
- Cookies: `__cfduid` and `cf_clearance`, even better all `poe.trade` cookies.

Requirements: 
- If possible no pre-compiled .exe, instead some script everyone can run on a default windows installation with ahk. Compiling on script start with default windows software or something commonly used like .Net Framework also works.
- If not possible, I'm open to use every scripting/programming language you can think of, the more user-friendly, the better.

Using Firefox/Chrome it may be neccessary to open the browser and visit poe.trade to generate/create those cookies. No idea if this can be done hidden, if not that's not problem either.

**Comment by OzoneH3** [comment]
In the other Thread 4 days ago DoctorVanGogh already did prot it to 2.0.

> I've changed the code slightly so every compiler from 2.0 and up will work: http://pastebin.com/epg6cAE0 (No var, no object initializer).

**Comment by Eruyome** [comment]
Hm, might have missed the part about it working from 2.0 and up.

**Comment by Eruyome** [comment]
@OzoneH3 , @DoctorVanGogh, I hope I'm not bothering you too much, anyway, still wanting to look into readeing Firefox/Chrome cookies. This seems interesting [https://www.codeproject.com/Articles/330142/Cookie-Quest-A-Quest-to-Read-Cookies-from-Four-Pop]( https://www.codeproject.com/Articles/330142/Cookie-Quest-A-Quest-to-Read-Cookies-from-Four-Pop), it doesn't work for Chrome though. There's a fix in the [comments](https://www.codeproject.com/Articles/330142/Cookie-Quest-A-Quest-to-Read-Cookies-from-Four-Pop?msg=5094629#xx5094629xx), still had no success.

Of course this can only read existing cookies, not generate them first.
There seem to be quite some people having issues with those retrieved IE cookies, while manually adding the chrome/firefox cookies works.

**Comment by OzoneH3** [comment]
Looks promising but couldn't get the Sqlite running and don't want to install visual studio.

**Comment by Eruyome** [comment]
Don't have Visual Studion installed, too. Only this https://en.wikipedia.org/wiki/Visual_Studio_Tools_for_Applications

**Comment by Dillybob92** [comment]
Illegal.

**Comment by jdlovins** [comment]
Well just doing some tinkering around I managed to bypass the cloudflare stuff using https://github.com/elcattivo/CloudFlareUtilities . Still looking for a way to grab cookies from it, probably have to expose the cookie stuff to make it easier. 

[heres a picture of some of the output](http://i.imgur.com/gk2dXVA.png)

Would this be worth going further into or do you explicitly want to grab from chrome/firefox?

**Comment by Eruyome** [comment]
Bypassing is not the problem, this works already if you have the user agent and cloudflare cookie pairs. IE cookies should work for everyone (not for a few people though), Firefox/Chrome seem to work for everyone, I just don't have the cookies from those 2 Browsers.

**Comment by jdlovins** [comment]
I dont think this utility uses IE though. It builds the request it self and uses a cookie container to get the cookies so they are always fresh. I was going to test more but i think poe.trade just went down

**Comment by Eruyome** [comment]
poe.trade is working fine.
Maybe your idea is not so bad either.

**Comment by jdlovins** [comment]
it was down for a few minutes for me but its back up. I modified it so it returns the 2 cookie values and can do anything with them like insert them into a .ini file or something. Its worth a shot since i think getting encrypted cookies will be a pain

**Comment by jdlovins** [comment]
@Eruyome Just tested it and it does work with the generated cookie data. I'll keep using it for a few hours and make sure nothing weird happens but I'm thinking this might be a good solution. Perhaps a few of the people who were having trouble with the IE cookies should try this out and see if it works for them?

**Comment by Eruyome** [comment]
Sure, if you can upload something that can be used by the dumbest assumable user ;-)

**Comment by jdlovins** [comment]
@Eruyome isnt that what programming is all about? Do you want me to upload a executable or have a way for the user to compile the source?

**Comment by Eruyome** [comment]
for simple testing an executable should be ok, but in the end it'd be better if we can compile the source on script start.

**Comment by jdlovins** [comment]
okay ill try to get something up in the next half hour

**Comment by jdlovins** [comment]
Hmm now it seems to be giving me problems and it fails to solve the cloudflare stuff. I'm not sure if i got semi blacklisted so i think ill come back to this in a few hours and see if it works after that.

**Comment by Dillybob92** [comment]
Lol, the guy deletes my post here saying it's Illegal.

**Comment by jdlovins** [comment]
Because its not illegal? Bypassing a service is not illegal.

**Comment by Dillybob92** [comment]
@jdlovins Bypassing cookie authentication / headers is illegal. If it's not illegal why delete my post genius?

**Comment by jdlovins** [comment]
@Dillybob92 I'd like to see where thats illegal. Perhaps it violates a ToS for cloudflare and if pomfpomfpomf really cared he would ask us not to do it which he hasnt as far as I know. Stop your fear mongering.

**Comment by Eruyome** [comment]
Because it's bullshit. You're either trolling or have no clue. If you had tried to make some argument I wouldn't have deleted anything but "Illegal" is nothing but pointless spam that nobody here needs.

**Comment by Dillybob92** [comment]
>  it's bullshit. You're either trolling or have no clue

So if an opinion is bullshit you delete it? You don't even know the laws, lmao.

**Comment by Dillybob92** [comment]
>"Illegal" is nothing but pointless spam that nobody here needs.

Lol, coding in AHK is really an intuitive and such hard language.

**Comment by Dillybob92** [comment]
> Perhaps it violates a ToS for cloudflare and if pomfpomfpomf really cared he would ask us not to do it which he hasnt as far as I know. Stop your fear mongering.

Saying something is illegal doesn't make me fear mongering. I don't think you understand what fear mongering means..

**Comment by jdlovins** [comment]
@Eruyome the C# variant seems to be pretty unstable and doesn't work for me anymore which is weird. I found a python one that seems to be much more reliable. The only thing is they would need to install python or we find a portable one type deal.
[It's a really simple script though](http://i.imgur.com/78uPVHo.png)

**Comment by Eruyome** [comment]
This issue is a place for people trying to help on this matter to talk about it. If I think any message has no place here I'll delete it to keep this conversation clear. If you want to voice any complaints please do it on reddit, the gitter channel or the discord server.

**Comment by Eruyome** [comment]
@OzoneH3 @doctorvangogh Some people reported that the cookie script fails for them (it writes for example the user agent and cfduid cookie, but noth the cf_clearance). Manually running the .exe give the message "vector smash protection is enabled", any ideas?

https://www.google.de/search?q=Vector+smash+prot+is+enabled&ie=utf-8&oe=utf-8&client=firefox-b-ab&gfe_rd=cr&ei=sMVvWMiPNeuv8weIqKSQCQ#safe=off&q=Vector+smash+protection+is+enabled

**Comment by Eruyome** [comment]
Poe.trade doesn't use cloudflare protection at the moment, will implement some check if this is the case and skip the cookie reading stuff. I'll close this until the protection comes back.
