### ISSUE TITLE
[Suggestion] Option to include max link = 4 in advanced search

### ISSUE THREAD

**Issue by loleriz** [PoE-TradeMacro/POE-TradeMacro#176]
Sometimes i do a search on rare items and am shocked at the price, then i do a search for it on poe.trade and find out that it's got 6 links...

Somehow allow us to search for sockets/links min/max as well? :+1: That would be great :3

**Comment by Eruyome** [comment]
Using the advanced search (ctrl + alt +d) you can at least decide if you want to include the 5/6 sockets/links in your search or not. And all other socket/link combinations should't matter.

**Comment by loleriz** [comment]
True! But being able to include the 4 sockets or less would negate wondering why a 4 socket or less item can cost up to 1.5 ex on the search xP

**Comment by avgjoe** [comment]
When you search rares doesn't it just ignore mods and look for the item name anyway? I've never used anything but advanced search for rares since that's how I thought it worked.

**Comment by loleriz** [comment]
probably. Ive been checking the boxes on the side of the mods when advanced search shows up. I thought that includes the checked mods in the search?

**Comment by Eruyome** [comment]
Advanced search doesn't use the item name unless it's a unique item. It uses item type (body armour) and everything you choose to include. There are cases where the item subtype is used (Cells Map).

**Comment by Eruyome** [comment]
implemented on dev branch

**Comment by loleriz** [comment]
it is awesome that you added this! Though it doesn't take into consideration the 4 link max thing yet.

**Comment by Eruyome** [comment]
I'm pretty sure it does. Do we talk past each other? Is there some misunderstanding?

The purpose of this feature was to exclude items with 5/6 sockets/links from the search (include max sockets/links = 4) so that you're not shocked to see that your 3l belly of the beast is worth 8ex because there are only 6linked ones online. Right?

I didn't check right now but I'm sure I made this possible and it works as intended. Those options are only displayed for items that can have more than 4 sockets btw.

**Comment by loleriz** [comment]
Exactly what it should do! But.. here is an example

http://imgur.com/a/nwhN6

And the ctrl + C info (like you asked for last time I did something similar to this)

Rarity: Magic
Athlete's Crimson Raiment of the Apt
--------
Evasion Rating: 189
Energy Shield: 55
--------
Requirements:
Level: 48 (unmet)
Dex: 48 (augmented)
Int: 48 (augmented)
--------
Sockets: G B-G G-B G 
--------
Item Level: 73
--------
+82 to maximum Life
32% reduced Attribute Requirements
--------
Note: ~b/o 15 chaos
