### ISSUE TITLE
Trying to search for anything results in Cloudflare error page

### ISSUE THREAD

**Issue by Farami** [PoE-TradeMacro/POE-TradeMacro#178]
No matter what I do I get no results. When trying to open something on poe.trade I get redirected to
https://www.cloudflare.com/5xx-error-landing/?utm_source=iuam (Something went wrong (but it’s not your fault)).

This, of course, results in me not getting any results what so ever.

**Comment by Eruyome** [comment]
I'll refer this ticket here since it's roughly the same issue and close this here. https://github.com/PoE-TradeMacro/POE-TradeMacro/issues/177
