### ISSUE TITLE
Searches result in incorrect pricing...

### ISSUE THREAD

**Issue by loleriz** [PoE-TradeMacro/POE-TradeMacro#179]
http://imgur.com/a/y4C6Q

I made an album of the process so you guys can see what's going on and maybe help me figure out what's going wrong? This is happening on numerous rare items of mine.

**Comment by Eruyome** [comment]
Can you press ctrl + c (copies item data to clipboard) and post that here? I can use different rare items to test but i always like to reproduce issues as best as possible.

**Comment by loleriz** [comment]
I vendored that one, but found another messed up one. Here's the imgur album:

http://imgur.com/a/yjKgf

and the stats:

Rarity: Rare
Domination Cord
Studded Belt
--------
Requirements:
Level: 57
--------
Item Level: 75
--------
23% increased Stun Duration on Enemies
--------
+252 to Armour
+42% to Fire Resistance
+44% to Cold Resistance
+43% to Lightning Resistance
--------
Note: ~b/o 8 exa
