### ISSUE TITLE
Automatic cookie/user-agent/cfduid/cf_clearance fetching is not pulling correct values for Chrome user

### ISSUE THREAD

**Issue by BigCholsMD** [PoE-TradeMacro/POE-TradeMacro#181]
After some trouble shooting, I noticed that the automatic pulling for user-agent, cfduid, and cf_clearance were NOT matching up to what I was finding when I manually went into chrome to inspect the data for those pulls. This was easily resolved by manually overriding the auto pull, and putting the correct data I came across for those values in the TradeMacro AHS file with notepad++ as the tutorial illustrates and overriding the auto pull settings to be manual in the settings after right clicking the system tray icon and clicking poe (trade) item info settings. Hope this helps some of you, and hopefully a dev can investigate why for chrome users its pulling different user-agent cfduid and cf_clearance values. Maybe address this with a formal post?

**Comment by Eruyome** [comment]
There is nothing to investigate, it's clearly stated that the macro reads your Internet Explorer cookies. It's mentioned in multiple places and further explained in the [FAQ](https://github.com/POE-TradeMacro/POE-TradeMacro/wiki/FAQ), "question" #1. 

It doesn't read Chrome cookies, or Firefox cookies, or Opera cookies. So comparing those retrieved cookies with them can only fail. They are all different.

**Comment by BigCholsMD** [comment]
But yesterday it was pulling them just fine for some reason lol, stopped pulling correctly today *shrugs*
