### ISSUE TITLE
Problem with getCookieData

### ISSUE THREAD

**Issue by hlskar** [PoE-TradeMacro/POE-TradeMacro#182]
So every time I start the script, I get [THIS ERROR MESSAGE](http://i.imgur.com/baeU3CM.png), the script then shows a message that staying on top, that its searching for my cookies, but nothing happens and it gets stuck. Really want to know what that is about ^^

**Comment by BigCholsMD** [comment]
this looks like what pops up when you have it try to pull cookies but you have no cookie text file for it to open

**Comment by Eruyome** [comment]
It seems it can't find the getCookieData.cs file.

**Comment by hlskar** [comment]
I fixed it, for whatever reason AHK was bugged when using the x64 bit version. Reinstalling with the 32 bit version fixed it for me. I don't know the reason, I mean, I got a x64 OS. Well, thanks for the help. ^^
