### ISSUE TITLE
"Show currency value in chaos" giving the wrong amount

### ISSUE THREAD

**Issue by rushtothesun** [PoE-TradeMacro/POE-TradeMacro#188]
Using Orb of Regret as an example: Ctrl+D lists  1:0.95 and 1:1 ratios of Regret to Chaos. So Ctrl+C on 4 Orb of Regrets should show about 4 Chaos Orbs. Instead it says 6 Chaos Orbs. Ctrl+C on 1 Orb of Regret shows a value of 1.50 Chaos Orbs. 

League is set to tmpstandard, not sure where it's getting the values from.

**Comment by Eruyome** [comment]
ctrl + c is ItemInfo and ItemInfo only has hardcoded currency ratios in data\CurrencyRates.txt. Don't use it.

**Comment by Eruyome** [comment]
I suppose I could do that, in this case I would use the rates from poe.ninja instead since its far easier to get those (it's highly inefficient to get ALL currency ratios from poe.trade at once). I'm not quite sure if that functionality shouldn't be moved to ItemInfo somehow instead of overwriting it.

**Comment by rushtothesun** [comment]
What about only getting the ratios for the currency you're searching for? So for example Ctrl+C on an Orb of Regret would look at the 5 or so latest posts, average them, then display the amount in Chaos. Would that then allow the use of poe.trade instead of poe.ninja? I just feel that using poe.trade as the source is important since that is where the latest data is obtained. For example. poe.trade has Silver Coins 1:4.6 to 1:5 ratios, with the most recent posts starting at 1:4.7 whereas Poe.ninja has 1:4.6

**Comment by Eruyome** [comment]
There are a few things you have to know/keep in mind:

- ItemInfo is strictly used as a dependency in TradeMacro, so no editing of that projects files.
- I can't simply inject code into ItemInfo at runtime, so I can't add or change functions.
- Basically the only way to influence ItemInfo from TradeMacro is by overwriting/changing some global variables after they were set/initialized by ItemInfo. There are exceptions like adding additional GUI elements to windows.

This mean, there is no "search" when using ctrl + c, ItemInfo will read `data\CurrencyRates.txt` at script start and calculate the equivalents with that and that's it. I can overwrite the parsed currency values from that file with some global variable. Adding all the search functionality to ItemInfo is overkill and not neccessary. Poe.ninja should be accurate enough to do this job.

When using TradeMacro I can see only one useful application of ItemInfos currency rates: When you're too lazy to calculate how much your 30 scourings are worth in chaos knowing the ratio. I believe it's acceptable to have those small differences between TradeMacros currency search to get the ratio and ItemInfos total equivalent using poe.ninjas ratio.

I made this issue on ItemInfo for now: https://github.com/aRTy42/POE-ItemInfo/issues/42

**Comment by rushtothesun** [comment]
I see now, thanks for explaining it.

**Comment by Eruyome** [comment]
Implemented currency fetching from poe.ninja (dev-branch and open Pull Request on the ItemInfo repository). All 4 leagues are being displayed if available.

**Comment by rushtothesun** [comment]
Works great, thanks for implementing it. Would it be possible to add an indented checkbox under "Show currency value in chaos" that, when checked, only shows chaos values for your selected league? Maybe "Show currency value for selected league"

**Comment by Eruyome** [comment]
ItemInfo doesn't have a league selection and we don't want to add one just for this feature. I'd rather not add extra global variables to ItemInfo just to decide what to show when it's bundled with TradeMacro. Maybe this opinion will change, but for now I'd rather not do it.
