### ISSUE TITLE
Retrieving Cookies Failed

### ISSUE THREAD

**Issue by abraksas14** [PoE-TradeMacro/POE-TradeMacro#189]
Hi,

I have no idea what the problem is. I tryed the work around already and it does not work for me.

-the contents of <scriptdirectory\temp\cookie_data.txt> seem to be invalided/incompleted.
-cookies were deleted on script start

Cookie file found. 
Retrieving cookies failed. 
Windows Version: 10.0.10586 (10.0.10586), 64bit. 
Compiling 'getCookieData' script successful. 
Net Framework used for compiling: v4 
Internet Explorer: v11.306.10586.0

help would be very nice!

p.s. : english is not my first english, so please excuse my lake in writing this more elaborative.

**Comment by javidang** [comment]
same error here

**Comment by abraksas14** [comment]
which old method?

**Comment by javidang** [comment]
just go for developer mode on your browser, and look for cloudfire datas for poe.trade and add them to cookie_data file

**Comment by abraksas14** [comment]
tried that but, i get the same massage. i followed the stap exatly like in the description, but i get the same massage.

**Comment by javidang** [comment]
just press continue, then do that method. your searchs will work as normal.

**Comment by abraksas14** [comment]
oh you are right xD 
i had it running the hole time in the back round and never even tried it and it totally work!!
thank you very much^^

**Comment by javidang** [comment]
you welcome

**Comment by Eruyome** [comment]
just to make sure, are you 2 editing the cookie_data.txt? if yes please use the settings menu instead, it has fields for those cookies values.

**Comment by abraksas14** [comment]
why is that important?

**Comment by Eruyome** [comment]
because it's the right way to do it and the temp folder with the cokie file gets deleted on every script start

**Comment by abraksas14** [comment]
ok, thx for your answer.
bye, stay safe and have a nice day

**Comment by rauwman** [comment]
the problem occurs in 1.5 is still in 1.6. I just have to delete the cookies my own in internet explorer.

**Comment by Eruyome** [comment]
poe.trade doesn't have cloudflare protection anymore (for now), I'll close this issue until its relevant again.
