### ISSUE TITLE
Avoid case-sensitive filenames

### ISSUE THREAD

**Issue by jn64** [PoE-TradeMacro/POE-TradeMacro#190]
Latest release adds a `Lib` folder next to `lib`, this may be problematic for most case-insensitive Windows users. Can I suggest changing the names or reorganising the lib folder somehow?

git threw a fit when trying to merge latest. I had to nuke my whole folder and start over.

**Comment by Eruyome** [comment]
Huh, I thought this was only a problem on linux servers. I also believe the Lib folder was written like that since forever, anyway I can optimize that.
