### ISSUE TITLE
[Bug] Cast while Channelling reports no results

### ISSUE THREAD

**Issue by Aerinx** [PoE-TradeMacro/POE-TradeMacro#193]
This support gem reports no results but I've just checked in poe.trade and there are gems for sale. I also checked with other gems and they work fine.

Ctrl+D results in No item found. This time I will add the Ctrl+C info before I sell the item :) Thank you.

```
Rarity: Gem
Cast while Channelling Support
--------
Support, Channelling, Spell
Level: 1
Mana Multiplier: 140%
Experience: 1/388,734
--------
Requirements:
Level: 38
Dex: 27
Int: 39
--------
You cannot Cast Supported Triggerable Spells directly
Cast a Supported Spell every 0.45 seconds while Channelling Supported Skills
--------
This is a Support Gem. It does not grant a bonus to your character, but to skills in sockets connected to it. Place into an item socket connected to a socket containing the Active Skill Gem you wish to augment. Right click to remove from a socket.

```

**Comment by Eruyome** [comment]
I recently switched from using the search forms "name" field for gems to using the "base" field. While all other gems (I believe) use their name without "Support" as value for this field, this isn't the case for cast while channeling.

**Comment by Eruyome** [comment]
Added gem name fetching from poe.trade to compare the names and make sure they match. (dev branch)
