### ISSUE TITLE
Custom Input Search searches for uncorrupted items by default; no results on always-corrupt items

### ISSUE THREAD

**Issue by aktai0** [PoE-TradeMacro/POE-TradeMacro#194]
For example, using Ctrl+I and typing in Chill of Corruption (corrupt unique jewel) will return no results from Custom Input Search because it searched with "Corruption: No" option on poe.trade. Note this is only from Custom Input Search because it doesn't know the item might only be available corrupted.

Bad, fast solution: Make the Custom Input Search use "Corruption: Either" by default.

Better solution: Add a checkbox on the Custom Input Search dialog to indicate whether the search should exclude corrupted items or not.

I might try doing this myself tomorrow if AHK's GUI code isn't too hard to learn.

**Comment by Eruyome** [comment]
AHKs GUIs are really annoying. The custom search dialog is an InputBox, a simple form of a GUI, you could say a standalone GUI. So adding a checkbox is a bit more work than just adding a checkbox, but not that complicated either. For now I've added corrupted = either as POST parameter.

`RequestParams.corrupted := "x"`

I've opened this issue https://github.com/PoE-TradeMacro/POE-TradeMacro/issues/195 and will close this here.
