### ISSUE TITLE
Prophecies

### ISSUE THREAD

**Issue by Shander9515** [PoE-TradeMacro/POE-TradeMacro#197]
Hi there, not a secret that there are as shitty prop which price is 0 scroll fragment and very good prop which price is about 40 ex (Jesus!)
Many ppl (including me) don't know many really expensive prop and can miss it!
Is it possible to add function Ctrl+Q (ant other) to the non-sealed prophecies to not to waste coins? :c 
(http://i.imgur.com/U1JlE73.png)

P.S. Sry for my english, hope u understood the main idea!

**Comment by Eruyome** [comment]
https://github.com/PoE-TradeMacro/POE-TradeMacro/issues/33
No chance
