### ISSUE TITLE
need help for the macro that toogles stash tab

### ISSUE THREAD

**Issue by Ayced** [PoE-TradeMacro/POE-TradeMacro#198]
hey all i have trouble with the command :

ctrl-mouse wheel up toggles stash tabs left
ctrl-mouse wheel down toggles stash tabs right  i removed the ; on the line but that doesn't work  maybe  i do something wrong so if someone can help  me it would be nice 

thanks.

**Comment by Ayced** [comment]
find the problem thanks

**Comment by IrmatDen** [comment]
For the record, his issue was related to an obsolete POE-TradeMacro version. The issue he had was simply fixed by updating.

**Comment by Eruyome** [comment]
Ok, thx for the clarification.
