### ISSUE TITLE
ItemInfo configs

### ISSUE THREAD

**Issue by 4GForce** [PoE-TradeMacro/POE-TradeMacro#201]
Fresh install from the latest release ( 1st time using TradeMacro )
I posted here but I'll have to check the ItemInfo script behavior concerning this issue.

The release .zip contains \data\defaults.ini with weird characters
- config.ini being generated from that file causes 'afix detail delimiter' errors
- deleting config.ini and defaults.ini causes the script to generate new config files without values
- cannot revert settings to default but still can save new settings

That never happened to me from the ItemInfo branch, I'll look into it later but defaults.ini should be removed from the release. There still seem to be another problem with the default config generation.

**Comment by Eruyome** [comment]
I converted defaults.ini to UTF-8 (Windows) using Notepad++, after downloading it, it was UCS-2 LE (Macintosh). That seems to fix this issue.

**Comment by aRTy42** [comment]
I'm currently not sure if there are still ansi vs. unicode AHK installations, but the config file was meant to be in ansi, because utf-8 seems to not work for some systems or installations.
