### ISSUE TITLE
Impossible to start macro

### ISSUE THREAD

**Issue by Zarremgregarrok** [PoE-TradeMacro/POE-TradeMacro#205]
Since you renamed trade_data to data_trade, you also need to update references to the folder in the code ;)

**Comment by Eruyome** [comment]
Should have done that, but I know I forgot to recompile the fallback exe, are you using that?

**Comment by Zarremgregarrok** [comment]
I was using RunOnlyThis and got impossible to read trade_data/<somethingIDoNotRemember> error.
I did not check the newer version, so maybe you already fixed it.

**Comment by Eruyome** [comment]
Yeah I fixed it immediatly after reading your issue. Was caused by some git related problems, I reverted/lost changes somehow without noticing.
