### ISSUE TITLE
Seach takes forever

### ISSUE THREAD

**Issue by Lordaduss** [PoE-TradeMacro/POE-TradeMacro#206]
Sometimes it takes 30 seconds to search, a lot of the time more than 1 minute, I'm running everything on an SSD and my internet speed is fine, what should I do?

**Comment by Eruyome** [comment]
Don't think there's anything you can do. Aside from your connection there's nothing slowing down your search. Keep in mind that every search currently has to download 700kb to 1.5mb (at least that's the resulting filesize, not sure what's actually transferred. Hopefully I get to use gzip compression soon.
