### ISSUE TITLE
Release 1.7.2 files/folders thoughts

### ISSUE THREAD

**Issue by 4GForce** [PoE-TradeMacro/POE-TradeMacro#207]
Nothing that really affects the script, just some observations

I don't think those files belong in the release
- .gitattributes
- .gitignore
- _compileRelease.ahk

Wouldn't make more sense to have those files in the lib folder
- TradeMacro.ahk
- TradeMacroInit.ahk
- jsonData.ahk

Rename those to .txt for ease of use ( double click to open )
- LICENSE
- README.markdown

And you already mentioned those as resources
- AUTHORS*.txt
- Updates*.txt

And I don't really get the use of 
- PoE-TradeMacro_(Fallback).exe

**Comment by 4GForce** [comment]
Any Chinese translator in the room ?

; WinHttpRequest.ahk
;	v1.03 (2016-01-18) - 增加“加载 gzip.dll 失败”提示，防止忘记复制 gzip.dll 到脚本目录。
; 	v1.02 (2015-12-26) - 修复在 XP 系统中解压 gzip 数据失败的问题。
; 	v1.01 (2015-12-07)

**Comment by 4GForce** [comment]
Well nvm about that last post ... we are not alone : https://gist.github.com/tmplinshi/a74c7f0cc7f1510ce0ad
I'm not the only one seeing Chinese characters right ?

**Comment by Eruyome** [comment]
Hehe, no you're not the only one. I never really got around to use that library for the request (for the gzip compression).

Well, some people had problems running the script as .ahk file but had success with a precompiled .exe file. I don't like publishing an .exe-file but included one as fallback anyway.

-   LICENSE
-   README.markdown

These are genereated by github and the readme is the one used on the repo, I'm not sure you can use something different as `.markdown` here to have it work.

You can't decide which files from the repo to include in the release, you just point to the branch. At least I don't know of any way. 

- TradeMacro.ahk
- TradeMacroInit.ahk
- jsonData.ahk

To my understanding a `lib` folder is used for libraries, not for main source/script files. The right way would be to create a `src` folder. Could be unnecessary clutter though.

**Comment by Eruyome** [comment]
Let me make a correction, cou can deiced waht to release but only by making a local zip file and adding it as a package to the github release, like they do here https://github.com/h5bp/html5-boilerplate/releases.

**Comment by 4GForce** [comment]
I never created a release from GitHub so far, those were only my noob toughts, I really didn't knew how that worked but still seems strange.  Most of all, I still don't get the fallback.exe file, for me it seems like it tries to run previous version ( i get an update warning ) but the actual resulting running script seems to be working fine with latest config and data even after skipping that warning.

**Comment by 4GForce** [comment]
Not sure this would be proper release procedure, and I'll have to look into it further, but the idea would be to branch from master before release ( create release x.x.x branch or something ), remove unwanted files from that branch and then create the release from that branch ...
Meh, I'm too tired to think, don't pay attention to what I'm saying

**Comment by Eruyome** [comment]
Wouldn't that require the same work I mentioned you would have to do manually or with scripts though? You could copy the master branch to a new one, but would still have to manually delete all unnecessary files by hand or git console and push that. At least I think that would be required^^

**Comment by 4GForce** [comment]
You just fried my brain ... bbl =p
