### ISSUE TITLE
Just me or the 1.7.2 update doesnt work?

### ISSUE THREAD

**Issue by redviles2035** [PoE-TradeMacro/POE-TradeMacro#208]
Tried to run it and it says 'error at line 3'

**Comment by 4GForce** [comment]
Just to make sure,
Did you get the release from here : [https://github.com/POE-TradeMacro/POE-TradeMacro/releases/tag/1.7.2](url)

Did you start the script using : Run_Only_This.ahk ?

Please give us more details, its working fine on my end.

**Comment by redviles2035** [comment]
yeah, I downloaded the zip file from:  https://github.com/POE-TradeMacro/POE-TradeMacro/releases/tag/1.7.2
And I did start the script using Run_Only_This.ahk, 
Been using this macro for like a month now and only this update doesnt work for me, one thing i see thats different is that the PoE-TradeMacro_(fallback) file doesnt have the PoE logo on it anymore which it usually does in the icon. 

Also, when i try to start the Run_only_this.ahk file, it says 'error at line 3' and 'POE-TradeMacro-1.7.2/resources/VersionTrade.txt cannot be opened'
 Hope this gives enough info!

**Comment by 4GForce** [comment]
Well, there has been modifications to some of the files encoding and other stuff within the last patch but I don't have any issue with my admin account under windows 7 so I'm a bit clueless about what the problem might be.
Would you be kind enough to try and follow these instructions to unblock the VersionTrade.txt file and try running the script again : https://blogs.msdn.microsoft.com/delay/p/unblockingdownloadedfile/

If this works for that file, script will probably encounter the same issue with other files, not the IMPORTANT text at the bottom of the linked page, you might want to try to unblock the zip before extracting.

Not sure this helps, keep us updated.  ( what is your Windows version ? )

**Comment by redviles2035** [comment]
Oh! that's odd, I had to extract the files from the PoE-TradeMacro_(fallback) file and its working now, but thanks anyways for trying to help! :)

**Comment by 4GForce** [comment]
Extract files from a .exe ??
Now I'm really confused, but glad that it worked, enjoy !

**Comment by redviles2035** [comment]
yeah, when I clicked on it, it gave me an option to extract or run it, so i extracted it and it opened a new folder with basically the same files, but this time it worked :)

**Comment by Eruyome** [comment]
Just a quick question, did you try to run the macro from inside the .zip archive without extracting it?

**Comment by redviles2035** [comment]
maybe, but I usually dont have to manually extract from the .exe file in the past updates, but guess i had to for this one

**Comment by Eruyome** [comment]
This shouldn't be neccessary, I suspected you navigated isnide the .zip file since windows lets you do this without any problems, then tried running the script from inside the script but actually extracted it then by "extracting the .exe file", not sure that's really the case though.
