### ISSUE TITLE
Item showing as unidentified

### ISSUE THREAD

**Issue by 4GForce** [PoE-TradeMacro/POE-TradeMacro#209]
Well, this happened to me and I figured out how to reproduce it, this might even be related to an issue reported by BloodRaziel on the forum ( https://www.pathofexile.com/forum/view-thread/1757730/page/17 )

To reproduce
- after a ctrl+d on any item
- ctrl+c an unidentified item
- further ctrl+c on other items will show as unidentified

![bug_unidentified_items](https://cloud.githubusercontent.com/assets/25257792/22320609/b6ef529e-e35b-11e6-8e1a-3ea3f24dda98.jpg)

**Comment by 4GForce** [comment]
I think I'm up to something that might actually be the cause of multiple problems.

In any cases, calls to ParseItemData() should only be made once per user action.
As a casual noob I added a MsgBox within the function to see the state of the Item object.

I'm afraid that in some cases the clipboard is parsed by both script and ParseItemData() is called more than once, I'm still digging.

**Comment by 4GForce** [comment]
Ok, I got it, the base of the  problem is this : **Item := {}**
Quick fix is to remove all those lines ( 6 ) within TradeMacro.ahk
Overall would be to check all the global objects and global declarations.

What I suggest
- Remove all the global declarations that are made within functions
   > not required ( maybe it was in early ahk ) and can be confusing
- Make sure globally accessed objects are initialized properly
   > a Init method for each like I did for the Item object
- Make sure object instances don't have the same id as their classes
  > ahk and devs can confuse Item.Init() as instance/method call ( avoid Item := new Item )
- Retrace all cases causing multiple calls to ParseItemData() wich can cause major issues in data parsing
   > simultaneous calls would modify the same object

I'll commit the quick fix shortly and wait for your comments on the rest.

**Comment by 4GForce** [comment]
I'm so confused, sorry about the bad pull request, I'll have to go back reading some GitHub how to 0.o

**Comment by 4GForce** [comment]
Even with a fried brain, I'm still curious about your thoughts on this topic ...

**Comment by Eruyome** [comment]
At least one of your proposed fixes should be implemented, I'm a bit busy currently with other TradeMacro related things so I haven't paid much attention to this issue.

**Comment by 4GForce** [comment]
Well if you approve, Ill work on it tomorrow, I need some sleep now

**Comment by Eruyome** [comment]
Sure, do that. As long as you don't break anything else there's no reason for me say anything against it :p

**Comment by 4GForce** [comment]
Waiting on your confirmation before sending ItemData fix pull request because I think I messed up again.

And thinking about it, you inherit the work load of updating the ItemInfo branch with my commits or should I commit there too ( which actually makes no sense ) ???
I wouldn't want to create more problems than fixes.

**Comment by Eruyome** [comment]
There are two wyas to handle this:
1. You commit what you want and I also commit it to ItemInfo. (not really a problem)
2. I invite you as a a colaborator so that you don't have to fork TradeMacro, that way you can fork ItemInfo and are able to make PRs to both repos.
