### ISSUE TITLE
Error in jsonData.ahk

### ISSUE THREAD

**Issue by Artyfice** [PoE-TradeMacro/POE-TradeMacro#211]
I've been using the 1.3.0 version of this script for a long time without any error, but yesterday it started breaking. I updated to 1.7.0, worked fine so I thought it was fixed. I stopped it and reloaded it, only to see the same error again.

Looks like the first run creates some additional files, which makes the script break later on.

[Image of the error](http://imgur.com/wM4iOYl)

**Comment by 4GForce** [comment]
1.7.0 had known issue, please try 1.7.2 and report back.
https://github.com/POE-TradeMacro/POE-TradeMacro/releases/tag/1.7.2

**Comment by Artyfice** [comment]
It works indeed. Can close it. Thanks
