### ISSUE TITLE
Starting POE-TradeMacro closes my personal AHK scripts

### ISSUE THREAD

**Issue by DrLeh** [PoE-TradeMacro/POE-TradeMacro#212]
I POE-TradeMacro set to run on startup, but i have to manually run my own scripts because POE-TradeMacro closes my other scripts. Any way around this?

**Comment by Eruyome** [comment]
Does this also happen when you don't run it on startup but run it manually?

**Comment by DrLeh** [comment]
Yes, it happens when I run mine then run POE.  My script is also called Main.ahk in case that could be a problem.

**Comment by 4GForce** [comment]
could be ... how about renaming your personal script file to something like myPersonalAwesomeUniquelyNamedScripts.ahk

**Comment by Eruyome** [comment]
Well, `CloseScript("main.ahk")` this happens on script start, I should rename main.ahk to TradeMacroMain or something like that.

**Comment by DrLeh** [comment]
yeah i think it'd be a good idea to change it to something that's less likely to overlap with user's script names. Main.ahk is a pretty popular one, i'd guess. Thanks!

**Comment by Eruyome** [comment]
Changed it.
