### ISSUE TITLE
Empty custom search bug

### ISSUE THREAD

**Issue by 4GForce** [PoE-TradeMacro/POE-TradeMacro#219]
You'd have to be dumb like me to commit an empty form but after doing so further ctrl+i result in this message.
Not a big deal, I'll look into it later

![error_message_after_empty_custom_search](https://cloud.githubusercontent.com/assets/25257792/22363168/614df86e-e436-11e6-992b-73c15280a3e3.jpg)

**Comment by Eruyome** [comment]
Fixed it, not commited yet.
