### ISSUE TITLE
[Feature] Add option (setting) to always pre-select all mods (advanced search)

### ISSUE THREAD

**Issue by Eruyome** [PoE-TradeMacro/POE-TradeMacro#230]
Helps with jewel crafting and price checking a lot of them.

**Comment by 4GForce** [comment]
Just some random toughts:
A) Would that only apply to advanced search or also ctrl+d and ctrl+q. ?
B) How about an edit + checkbox for the item name in the advanced search gui so you could choose to include the name or at least part of it ?

**Comment by Eruyome** [comment]
A) Only advanced.
B) There may be cases where this makes sense. But what are these cases? Uniques are searched by name anyway. Non-unique item names are generated via their mods, so is it useful to search for the name instead of using the mods? I'm not saying that's a bad idea but does it really help anyone?
