### ISSUE TITLE
Questions about the class Item and its usage in functions

### ISSUE THREAD

**Issue by chanz** [PoE-TradeMacro/POE-TradeMacro#232]
Hi,

I'd like to help with issue #83 but I have questions about the POE-ItemInfo.ahk code.
Probably I just don't see the reason, but why is the "Item" object not just passed as parameter into functions?

As example if you look at the funtion "ParseItemType", the "BaseType" is a parameter which uses "ByRef".
Why not just pass the Item object and set the type by "Item.BaseType = Weapon"?

So instead of
```
ParseItemType(ItemData.Stats, ItemData.NamePlate, ItemBaseType, ItemSubType, ItemGripType, Item.IsMapFragment, RarityLevel)
Item.BaseType := ItemBaseType
Item.SubType := ItemSubType
Item.GripType := ItemGripType
```
calling the function like
```
ParseItemType(ItemData, Item)
```

Hope you can clear that up to me. :-)

Thanks for continuing POE-ItemInfo and the addition POE-TradeMacro.

Best regards,
Chanz

**Comment by Eruyome** [comment]
Without taking a deeper look into that code right now I can only say that you're probably right about that, at least it makes sense for that example. But I didn't write ItemInfo, only made additions/improvements/fixes so I can't say much about why some things are written as they are ;-)

Also, this question is probably better asked here https://github.com/aRTy42/POE-ItemInfo since it specifically targets ItemInfo.

**Comment by 4GForce** [comment]
Code is old and restructuring everything would require lot of work.

To me it should be something like this 
Item.ItemData
Item.AffixeLines
Item.Mods
Item.ParseType()

**Comment by chanz** [comment]
Yeah POE-ItemInfo is kinda dead - fork of a fork of a fork...

But thanks for clearing that up to me.

**Comment by 4GForce** [comment]
Not dead, but hard to maintain.

**Comment by chanz** [comment]
Oh, I didn't get that there is an very old item info at https://github.com/andreberg/PoE-Item-Info and a newer one at https://github.com/aRTy42/POE-ItemInfo

Yeah its not dead, but the andreberg one is dead. Sorry, but thanks for clearing that up for me. :-)
