### ISSUE TITLE
[Suggestion] Hotkey to toggle league

### ISSUE THREAD

**Issue by avgjoe** [PoE-TradeMacro/POE-TradeMacro#235]
FIrst, thanks for this script, I couldn't play poe without it. I play softcore and hardcore. Switching in the settings is simple enough but can sometimes be tedious. I'm not sure if this is a feature other people could benefit from, but having a hotkey to switch between softcore/hardcore, or even std/tmp would be awesome. If you think it's something too specific, a step in the right direction of modifying it for myself would be appreciated. Thanks in advance.

**Comment by Eruyome** [comment]
Sure, we could implement this, will keep it in mind.

**Comment by Eruyome** [comment]
I have implemented it in my dev branch, would you like to test it a bit before I merge it? https://github.com/PoE-TradeMacro/POE-TradeMacro/archive/devEru.zip 
Default hotkey is ctrl + l, it should change the league and also update the settings ui.

**Comment by avgjoe** [comment]
Sorry man, just now getting around to testing it. I'll let you know. I think with only 4 leagues cycling is sufficient. I'm going to check it out now. Thanks again.

**Comment by avgjoe** [comment]
Works great, the only thing I can see that might be an improvement is to list the league on the search window for advanced price checks. Since the results window displays the league next to the item name, it's not really necessary. Thanks for adding this in as quickly as you did.

**Comment by Eruyome** [comment]
Yeah, you're right about that.
