### ISSUE TITLE
[Bug] Problems with caching/determination affixes on rares

### ISSUE THREAD

**Issue by dein0s** [PoE-TradeMacro/POE-TradeMacro#236]
Ok guys, some weird things going on here. Right now I'm sitting on v1.7.2, but as I can remember this started happening to me few versions ago.
The only file I keep from version to version is my own AdditionalMacros.txt.
After I launch macro everything goes fine, but after a while (or after some condition, don't have exact steps to reproduce yet) this happens:
![first](http://i.imgur.com/eOYPhLh.png)
![second](http://i.imgur.com/wn9rL5G.png)

I've also attached my current version
[POE-TradeMacro.zip](https://github.com/PoE-TradeMacro/POE-TradeMacro/files/762889/POE-TradeMacro.zip)

**Comment by Eruyome** [comment]
This seems to be an issue with ItemInfo, can you check the latest stndalone version https://github.com/aRTy42/POE-ItemInfo/releases and see if you still get thtat problem?

Btw, while  I'm also a contributor to ItemInfo and can look into this, this issue might be better opened at the ItemInfo repository._

**Comment by aRTy42** [comment]
It's a TradeMacro issue. Something is not properly reset for the item parsing once the Ctrl+D function was used at least once (at all, not on a necessarily on a specific item).

I can break the Ctrl+C function reliably by starting the script, using Ctrl+D on any item and then using Ctrl+C on a corrupted item with a skin.

Example items:
```
Rarity: Unique
The Whispering Ice
Vile Staff
--------
Staff
Quality: +20% (augmented)
Physical Damage: 40-74 (augmented)
Critical Strike Chance: 6.60%
Attacks per Second: 1.25
Weapon Range: 11
--------
Requirements:
Level: 72
Str: 114
Int: 111
--------
Sockets: B-R-R-B R-W 
--------
Item Level: 80
--------
12% Chance to Block
--------
+1 to Level of Socketed Support Gems
Grants level 1 Icestorm Skill
11% increased Cast Speed
1% increased Spell Damage per 10 Intelligence
18% increased Intelligence
--------
Guard your darkest thoughts well, for they are
the cracks through which the Nightmare crawls.
--------
Corrupted
--------
Has Prophecy Weapon Effect
```

```
Rarity: Rare
Rage Vise
Fingerless Silk Gloves
--------
Quality: +20% (augmented)
Energy Shield: 135 (augmented)
--------
Requirements:
Level: 73
Str: 151
Dex: 111
Int: 155
--------
Sockets: R-R-G-B 
--------
Item Level: 82
--------
+1 to Level of Socketed Gems
--------
+50 to Intelligence
+31 to maximum Mana
54% increased Energy Shield
+45% to Fire Resistance
+41% to Cold Resistance
17% increased Stun and Block Recovery
67% increased Energy Shield
--------
Corrupted
--------
Has Minotaur Gloves
```

**Comment by aRTy42** [comment]
Correction: Corruption alone is enough, a skin is not needed.

**Comment by Eruyome** [comment]
Ok, will take a look at it then sometime.

**Comment by Eruyome** [comment]
So I tested the latest code and couldn't reproduce this, tried the version used by @dein0s and could. Can you confirm this? Latest code: https://github.com/PoE-TradeMacro/POE-TradeMacro/archive/dev4GForce.zip

**Comment by aRTy42** [comment]
Confirmed.

**Comment by dein0s** [comment]
Also checked the latest version (from above comment) - couldn't reproduce by @aRTy42 steps.
Will try more tomorrow, but looks like it's been fixed.
