### ISSUE TITLE
Current T1 affix shows up as T2.

### ISSUE THREAD

**Issue by severudolf** [PoE-TradeMacro/POE-TradeMacro#241]
The legacy prefix is shown as t1. The **Incandescent** Prefix on energy shield based shields is now t1 (107-135 flat ES) because apparently Resplendent (136-145 flat ES) - the old t1 - is now legacy. I think it would be better for the current t1 to show as t1 in the tool and not as t2. 
![t1 prefix is shown as t2](https://cloud.githubusercontent.com/assets/17460474/23093867/6d5e7e5c-f5ee-11e6-92e5-e6eb3f102e32.png)

**Comment by Eruyome** [comment]
@aRTy42 I'm too lazy to open this issue on the ItemInfo repo.
@severudolf That's an https://github.com/aRTy42/POE-ItemInfo issue but since I and aRTy42 are working on ItemInfo you can just leave it here.

**Comment by aRTy42** [comment]
Fixed. Should be in the next release.
