### ISSUE TITLE
Advanced price check failed with Unique Jewel

### ISSUE THREAD

**Issue by xSirk** [PoE-TradeMacro/POE-TradeMacro#248]
This happened with Fireborn Crimson Jewel
http://puu.sh/urGMJ/34ea2817ee.jpg

**Comment by Eruyome** [comment]
Please read that message again. What reason would there be to use the advanced search on an item that doesn't differ from all the other 5000 ones for sale in any way?

**Comment by xSirk** [comment]
because I wanted to search it in poe.trade to look the corrupted ones

**Comment by xSirk** [comment]
I'm sorry my bad.

**Comment by Eruyome** [comment]
No problem,
