### ISSUE TITLE
Ctrl+i, close, Ctrl+i results in Error: 

### ISSUE THREAD

**Issue by dsnvwlmnt** [PoE-TradeMacro/POE-TradeMacro#249]
1) Run Run_TradeMacro.ahk
2) Ctrl+i
3) Close the search window. **UPDATE: specifically using the X in the top right of the popup window**
4) Ctrl+i
5) Error: "The same variable cannot be used for more than one control." [line 12992]

v 2.0.0

Note that i call your macro from another macro, so if you can't duplicate this it's probably on my end.

http://i.imgur.com/iyejEur.png

**Comment by Eruyome** [comment]
No, just a little oversight on my part, will be fixed in the next update.
