### ISSUE TITLE
Getting Error: Too few parameters passed to function

### ISSUE THREAD

**Issue by Smooshface** [PoE-TradeMacro/POE-TradeMacro#250]
![capture](https://cloud.githubusercontent.com/assets/23107338/23553097/2c1a7118-ffed-11e6-856d-79cb71238682.PNG)

I THINK I've attached a screenshot.

**Comment by Smooshface** [comment]
I did attach a screenshot, go me!

**Comment by daish0** [comment]
Hi, you are probably trying to start it using the old Run_only_this.ahk. Try it instead with the Run_TradeMacro.ahk for example!

**Comment by Smooshface** [comment]
That worked, are the old ones being deprecated?

**Comment by TheOne320** [comment]
The old ones are not included. That is also why it says to always copy a new version into its own folder.

**Comment by Eruyome** [comment]
The new auto updater also purges all old files from the install directory.

**Comment by Smooshface** [comment]
Thanks, I must have missed that instruction. I appreciate all the help and your work on the macro! 


Thanks, David Horan 
-------- Original message --------From: TheOne320 <notifications@github.com> Date: 3/3/17  10:02 AM  (GMT-05:00) To: PoE-TradeMacro/POE-TradeMacro <POE-TradeMacro@noreply.github.com> Cc: Smooshface <david.horan@gmail.com>, Author <author@noreply.github.com> Subject: Re: [PoE-TradeMacro/POE-TradeMacro] Getting Error: Too few parameters passed to function (#250) 
The old ones are not included. That is also why it says to always copy a new version into its own folder.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/PoE-TradeMacro/POE-TradeMacro","title":"PoE-TradeMacro/POE-TradeMacro","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/PoE-TradeMacro/POE-TradeMacro"}},"updates":{"snippets":[{"icon":"PERSON","message":"@TheOne320 in #250: The old ones are not included. That is also why it says to always copy a new version into its own folder."}],"action":{"name":"View Issue","url":"https://github.com/PoE-TradeMacro/POE-TradeMacro/issues/250#issuecomment-283976438"}}}
