### ISSUE TITLE
enchant on white base doesnt get recognized

### ISSUE THREAD

**Issue by Torcrob** [PoE-TradeMacro/POE-TradeMacro#251]
wanted to check white hubris bases with enchant, the search doesnt enter the enchant, not broken for bases with other rarity

**Comment by Eruyome** [comment]
Are you talking about the default search not using "enchanted = true" or the advanced search not recognizing the enchant? Just tested with this item and it worked:

Rarity: Normal
Eternal Burgonet
--------
Armour: 324
--------
Requirements:
Level: 69
Str: 138
--------
Sockets: G-R 
--------
Item Level: 84
--------
30% chance for Discharge not to consume Charges


Please post your item (this data is in your clipboard after ctrl +c )

**Comment by Torcrob** [comment]
tested the same item again, and it worked this time.. sry for the derp post

**Comment by Eruyome** [comment]
np
