### ISSUE TITLE
Items search for TmpStandard comes up as ( SSF HC Legacy)

### ISSUE THREAD

**Issue by OphidianShade** [PoE-TradeMacro/POE-TradeMacro#253]
Under settings with  TmpStandard selected it keeps searching poe.trade under SSF Hc Legacy mode and  Displays no items

**Comment by muzzol** [comment]
go to line 615 and add this modification:

            Else If (InStr(val.id, "SSF")) {
                leagues["ignore"] := val.id
            }

**Comment by muzzol** [comment]
full function should look like this:

```
; ------------------ GET LEAGUES ------------------ 
TradeFunc_GetLeagues(){	
     ;Loop over league info and get league names    
	leagues := []
	For key, val in LeaguesData {
		If (!val.event)  {
			If (val.id = "Standard") {
				leagues["standard"] := val.id			
			}
			Else If (val.id = "Hardcore") {
				leagues["hardcore"] := val.id			
			}
			Else If (InStr(val.id, "SSF")) {
				leagues["ignore"] := val.id			
			}
			Else If (InStr(val.id, "Hardcore")) {
				leagues["tmphardcore"] := val.id			
			}
			Else {
				leagues["tmpstandard"] := val.id			
			}
		}
	}
	Return leagues
}

```

**Comment by Smooshface** [comment]
Thank you!

**Comment by Laiq91** [comment]
I have the same issue, edited _TradeMacroMain to the info in the post above and it still says SSF HC Legacy.

What else could it be? Or am i doing it wrong?

**Comment by Razunter** [comment]
_TradeMacroMain.ahk gets rewritten on every launch

**Comment by MrJuicyBacon** [comment]
go to \resources\ahk\TradeMacroInit.ahk and replace line 618 with `Else If (!InStr(val.id, "SSF")) {`
The function will be
`TradeFunc_GetLeagues(){	
     ;Loop over league info and get league names    
	leagues := []
	For key, val in LeaguesData {
		If (!val.event)  {
			If (val.id = "Standard") {
				leagues["standard"] := val.id			
			}
			Else If (val.id = "Hardcore") {
				leagues["hardcore"] := val.id			
			}
			Else If (InStr(val.id, "Hardcore")) {
				leagues["tmphardcore"] := val.id			
			}
			Else If (!InStr(val.id, "SSF")) {
				leagues["tmpstandard"] := val.id			
			}
		}
	}
	Return leagues
}`

**Comment by Laiq91** [comment]
Thanks! Now it works :)

**Comment by OphidianShade** [comment]
Awesome, thank you very much!
