### ISSUE TITLE
2.0.1 dated as dec 15, 2016

### ISSUE THREAD

**Issue by InfiniteIce** [PoE-TradeMacro/POE-TradeMacro#257]
2.0.1 dated as dec 15, 2016, so it doesn't show up in the releases page, only the version that does not include the SSF fix shows (2.0.0), and 2.0.1 is not shown.

This: 
https://github.com/POE-TradeMacro/POE-TradeMacro/releases/tag/2.0.1

Does not show up on this:
https://github.com/PoE-TradeMacro/POE-TradeMacro/releases/

2.0.1 Legacy League hotfix
@Eruyome Eruyome released this on **Dec 26, 2015** · 615 commits to master since this release

**Comment by Eruyome** [comment]
... damn github

**Comment by Eruyome** [comment]
no idea whats wrong, have to do some research... happened again to the latest release 2.0.2

**Comment by NubScrub** [comment]
I believe it's from the reused version tags

**Comment by Eruyome** [comment]
Yes, noticed that too.
