### ISSUE TITLE
Fixed Width Font

### ISSUE THREAD

**Issue by hbwhbw** [PoE-TradeMacro/POE-TradeMacro#258]
Font used to be fixed width. Now display is jagged because it seems the font was switched.

**Comment by Eruyome** [comment]
This happens often when using the fallback exe, shouldn't happen aside from the first use with `Run_TradeMacro.ahk`. Please tell me if that's the case.

**Comment by hbwhbw** [comment]
I think you are correct. I was also getting one of the other bugs and that had me starting it using fullback.exe.  Now everything is better. Thanks.
