### ISSUE TITLE
[Fixed] Not Sure How To Fix This Error? (Too few parameters passed to function)

### ISSUE THREAD

**Issue by potasium56** [PoE-TradeMacro/POE-TradeMacro#259]
Pls help, updated my macro files and this pops up everytime i try and run the script...

<img src="https://i.gyazo.com/abe30c9dc7d740b526b0656942101646.png" width="225" height="151" alt="Photo of Milford Sound in New Zealand" />
`

**Comment by potasium56** [comment]
Figured it out....you can close this thread...

**Comment by 3dop** [comment]
Hey man, if you figured it out, post the answer for other folks that encounter this error

**Comment by potasium56** [comment]
Solution Is Always Delete Previous Release Files - Don't Copy New Release Files In With Old Files....You Have To Delete Your Old Version 100%......

**Comment by Eruyome** [comment]
That's right, that should be the solution, will keep it open for a bit for others to see.
