### ISSUE TITLE
Additional Macros file not working

### ISSUE THREAD

**Issue by 3dop** [PoE-TradeMacro/POE-TradeMacro#261]
Despite uncommenting the additional macros I wanted in the additional macros file, they didn't work when playing the game. Uncommenting them in the main.ahk file made them work, but that doesn't resolve the underlying issue. I'm guessing the additional macros file isn't being read for some reason.

**Comment by copy0660** [comment]
I've had the same problem. I tried everything and i even looked at the code, despite not knowing this programming language :D The final solution i found was to make the additional macros contents into a new file with the .ahk extention and run it along with the main macro. And it works fine on it's own. Although it might work outside of the game too, which could be a problem(?), but i haven't had any problems with it yet.

**Comment by Eruyome** [comment]
Could you tell me where you have TradeMacro installed/saved to?

**Comment by Eruyome** [comment]
Can confirm it doesn't work when using the Fallback.exe, no problems otherwise.

**Comment by 3dop** [comment]
I have it installed to a folder on my desktop called POETRADEMACRO (creative, I know) and I'm using the main .ahk file, not the fallback.exe nor the no-admin-elevation.

**Comment by Eruyome** [comment]
Shouldn't be relevant. Any luck using the newset 2.0.4 version or moving the macro to lets say C:\ProgramFiles\?

**Comment by 3dop** [comment]
2.0.5 fixed whatever the issue was. Thanks!

**Comment by Eruyome** [comment]
nice
