### ISSUE TITLE
Not able to run macro - language error and blank error message

### ISSUE THREAD

**Issue by HYDubs** [PoE-TradeMacro/POE-TradeMacro#264]
Hi there,

I'm trying to launch the macro and am receiving the attached errors. Either i'm getting a blank error message or it says i should set the default keyboard language to English, which i did by going to intl.cpl and setting language to English. I've even tried unchecking the inputs that were blank . Anyone know what's going on?

Thanks!

![issue2](https://cloud.githubusercontent.com/assets/26205165/23590072/6fd66c2a-01a7-11e7-99d1-117d1f337fdb.png)
![issue1](https://cloud.githubusercontent.com/assets/26205165/23590071/6fd58e86-01a7-11e7-949c-dcd043d165a6.png)

**Comment by Eruyome** [comment]
Couldn't really look in to it yet. Can you open the ini files and see if they look all right? Right click the system tray icon to open the user settings folder.

Can you fix something there by editing the ini file?
