### ISSUE TITLE
Average price and median price are not accurate

### ISSUE THREAD

**Issue by intoxicx** [PoE-TradeMacro/POE-TradeMacro#265]
The average price and median calculations do not seem to be accurate. The average price seems to be lower than the lowest price listed.  Tested with legacy hc only.

**Comment by Eruyome** [comment]
Will take a look at it.

**Comment by intoxicx** [comment]
Any progress with this? One of the main things I use to price check is to use the average and median price ranges.  Also thank you for taking a look into it.

**Comment by Eruyome** [comment]
Was a bit busy, will probably look for the issue tomorrow/the next days.
