### ISSUE TITLE
Searching Only Standard League

### ISSUE THREAD

**Issue by kellogzpoe** [PoE-TradeMacro/POE-TradeMacro#271]
Since the update all searches are being done only with the standard and hardcore league, changing to the "tmpstandard" and pressing ok, does not solve this and going back into settings it is set back to "standard". If you chose "tmphardcore" it reverts back to "hardcore" also.

**Comment by vadash** [comment]
Git same shit. Change code according to screen
https://lh3.googleusercontent.com/-t7bihGMTzk0/WL7gd9ZEImI/AAAAAAAAOYw/AholxENI8o8/s0/sublime_text_2017-03-07_19-31-49.png
Nobody play standart so u wont lose much :D

**Comment by Eruyome** [comment]
fixed
