### ISSUE TITLE
Dosen't returning searching valors after 2.0.5

### ISSUE THREAD

**Issue by Bizaugski** [PoE-TradeMacro/POE-TradeMacro#274]
Itens and Curr

![image](https://cloud.githubusercontent.com/assets/26261747/23680116/de2e7114-0368-11e7-9771-a981d5d4459c.png)

![image](https://cloud.githubusercontent.com/assets/26261747/23680237/42c02ce4-0369-11e7-9b5c-fa13a482b9f0.png)

Config Settings

![image](https://cloud.githubusercontent.com/assets/26261747/23680279/6a1a3906-0369-11e7-9ec4-4b1ce2afe569.png)

![image](https://cloud.githubusercontent.com/assets/26261747/23680286/6fecf5c6-0369-11e7-91e8-0f42334fed17.png)

**Comment by Eruyome** [comment]
Are you sure that you completely reinstalled the script? Removing all files, maybe even your config files. Btw you don't need the cookie stuff anymore. 2.0.05 didn't change anything that could possibly cause your searches to fail (as far as i can see).

**Comment by Bizaugski** [comment]
Sorry, but what files i have to delete?

Just the folder?

Something else on C:?

**Comment by Eruyome** [comment]
just the macro folder, before that open the trade macro user settings folder (right-lick system tray icon and use the option for that) and remove the .ini files

**Comment by Bizaugski** [comment]
I already do the FAQ solutions for this error.

Something more to try?

Cookie file found. 
Retrieving cookies failed. 
Windows Version: 10.0.14393 (10.0.14393), 64bit. 
Compiling 'getCookieData' script successful. 
Net Framework used for compiling: v4 
Internet Explorer: v11.576.14393.0

![image](https://cloud.githubusercontent.com/assets/26261747/23684008/e32d4f34-037a-11e7-8fcf-79a08967002e.png)


![image](https://cloud.githubusercontent.com/assets/26261747/23684027/eee2a946-037a-11e7-870e-70e40050dae4.png)

**Comment by Eruyome** [comment]
Can you run this in a windows console and show me the output?

`netsh winhttp show proxy`

**Comment by Bizaugski** [comment]
![image](https://cloud.githubusercontent.com/assets/26261747/23684797/9b51940e-037f-11e7-8863-f6128e1ec918.png)

**Comment by Eruyome** [comment]
Please edit `resources\ahk\TradeMacro.ahk` (version 2.0.5) line 1152 and add:

```
FileDelete,  %A_ScriptDir%\result.txt, 1
FileAppend,  %html%, %A_ScriptDir%\result.txt
```

This is directly before the line 
`Return, html`

Now, when you use the macro by running `Run_TradeMacro.ahk` every search will output the downloaded html to the `result.txt` in the macro root directory. Please upload this file somewhere for me. Don't paste the contents here.

**Comment by Bizaugski** [comment]
Is that correct?

![image](https://cloud.githubusercontent.com/assets/26261747/23724772/c4d22b92-042c-11e7-8aa0-d9e4b5ab457c.png)

**Comment by Bizaugski** [comment]
Not Working yet 

T_T

![image](https://cloud.githubusercontent.com/assets/26261747/23724833/fdc4808a-042c-11e7-8455-7aedcb21c0bd.png)

**Comment by Bizaugski** [comment]
File is blank.

![image](https://cloud.githubusercontent.com/assets/26261747/23730189/fb0167a6-0444-11e7-9a23-99dacec111a2.png)

**Comment by Eruyome** [comment]
Then I believe that the WinHttpRequest AND UrlDownloadToFile function (default AHK function) are failing completely for you. In that case your problem is not directly related to the macro itself.

I'm releasing v2.0.6 now, please run `resources\tests\Test_WinHTTPRequest.ahk` and show me the console outputs (a console window should open) .

**Comment by Bizaugski** [comment]
Sure!!

![image](https://cloud.githubusercontent.com/assets/26261747/23757521/db943d40-04c5-11e7-9699-59e27d0dfaf1.png)

![image](https://cloud.githubusercontent.com/assets/26261747/23757549/e6b7a478-04c5-11e7-8655-c43efba528c8.png)

![image](https://cloud.githubusercontent.com/assets/26261747/23757577/002d2400-04c6-11e7-9e87-aa5288808d09.png)

**Comment by Bizaugski** [comment]
Ty bro!!

The macro is running fine no.Add me on game, i will tip you. 

Thanks for your time and patience.

![image](https://cloud.githubusercontent.com/assets/26261747/23758277/10e47512-04c8-11e7-95d5-349e7f5c1059.png)

**Comment by Eruyome** [comment]
So, your adodb stream class was not registered/missing. How did you fix it?

If you want to find me ingame add `MrLeonardNimoy`

**Comment by Bizaugski** [comment]
Yeah. Just install AHK 32 bits. version: v1.1.25.01 - March 5, 2017.
Obs: My computer is 64bits and works perfect with the ahk 32.
If you have any doubt whisp me .
Thanks mate.
;]
