### ISSUE TITLE
Error: Call to nonexistent function

### ISSUE THREAD

**Issue by dirtstink** [PoE-TradeMacro/POE-TradeMacro#275]
Getting Error: Call to nonexistent function. Specifically: StartSplashScreen()

**Comment by Eruyome** [comment]
Have you read the FAQ https://github.com/POE-TradeMacro/POE-TradeMacro/wiki/FAQ?
Are you on v2.0.5?
Could you show me the entire error msg?

**Comment by dirtstink** [comment]
![0000000error](https://cloud.githubusercontent.com/assets/11741819/23683767/9e5dc22e-034f-11e7-9b15-19226c679c2d.JPG)

**Comment by dirtstink** [comment]
Just started happening with v2.0.5, was fine before then.

**Comment by Eruyome** [comment]
Is your AHK up to date and have you completely removed all old files?

**Comment by dirtstink** [comment]
Yup

**Comment by xSirk** [comment]
I have the same issue

**Comment by dingmutt** [comment]
Same problem here

**Comment by Eruyome** [comment]
I hate this issue since its likely not an issue with the macro inself (with that I mean bugs and errors) though I can't completely rule that out. Could you check if you have the latest AHK version and check if there's a difference when using the 32bit or 64bit AHK versions?

**Comment by dirtstink** [comment]
So I got it to work. Doesn't make sense to me why but I'll do step by step what i did. I downloaded the files for the 2.0.0 version. I ran the item info script and used the updater to update to 2.0.6 creating a new folder. I then ran the 2.0.0 trademacro script and used the updater to update that to 2.0.6 and created another new folder. So now I have a separate folder for the info script and the trade macro. The item info script runs fine when started from its folder but still breaks when ran from the trade macro folder.

**Comment by dirtstink** [comment]
So I got it to work. Doesn't make sense to me why but I'll do step by step what i did. I downloaded the files for the 2.0.0 version. I ran the item info script and used the updater to update to 2.0.6 creating a new folder. I then ran the 2.0.0 trademacro script and used the updater to update that to 2.0.6 and created another new folder. So now I have a separate folder for the info script and the trade macro. The item info script runs fine when started from its folder but still breaks when ran from the trade macro folder.

**Comment by dirtstink** [comment]
![poe-iteminfo](https://cloud.githubusercontent.com/assets/11741819/23802190/5c58b1ee-0567-11e7-9ec3-609286064a04.JPG)

**Comment by dirtstink** [comment]
![poe-trademacro](https://cloud.githubusercontent.com/assets/11741819/23802216/7925d8f6-0567-11e7-9973-403ba59d131c.JPG)

**Comment by dirtstink** [comment]
The first image is what the item info folder looks like. When I run the script from there it works fine.
The second image is what the trade macro folder looks like. When I run the item info script from there it breaks

**Comment by Eruyome** [comment]
Well, just don't run it then :p 
It's included in TradeMacro anyway, starting TradeMacro is enough to have both.
