### ISSUE TITLE
Slow Searchs

### ISSUE THREAD

**Issue by vitorhor** [PoE-TradeMacro/POE-TradeMacro#276]
Is there any specific reason to my searches now takes 1 minute to ctrl+d an item? It"s not because the update, i was using normally, and for no reason known, the searchs now takes forever to complete..

**Comment by Eruyome** [comment]
Probably your connection to poe.trade. Restart your router, see if you have some network issues in general or maybe poe.trade is slow atm. Or you're using some proxy that got slower.

**Comment by Riktheprick** [comment]
I'm having the same issue. Was working perfectly fine until just today. I've tried reinstalling the script, reinstalling auto hotkey, restarting, running it with compatibility, and even admin privs. 

The script also seems to take several minutes just to initialize, and the tray icon equally responsive.

None of this was an issue before literally today. Even early this morning it worked fine.

**Comment by vitorhor** [comment]
Restarting modem worked for me! Thanks!

**Comment by Eruyome** [comment]
@Riktheprick That shouldn't have any relation to the macro.

**Comment by Riktheprick** [comment]
@Eruyome Well it's definitely not an issue with my local machine, considering the issue was repeated across multiple computers.

**Comment by Eruyome** [comment]
Not sure, but yesterday poe.trade was slow for me at times (the website). The macro itself was sloo wtto at times, at others not. If the same version is sometimes slow and sometimes fast it's very like not an issue with the macro itself.
