### ISSUE TITLE
Can't search blue leaguestones.

### ISSUE THREAD

**Issue by Zibokwe** [PoE-TradeMacro/POE-TradeMacro#278]
Magic Leaguestones return no results, every time. Specifically, I want to know the ever changing value of the cadiro league stone for one, and maybe if some other league stones have some hidden values. but when searching these it comes up blank even as poe trade search

**Comment by Eruyome** [comment]
Ok, just ifexed that (nothing released). What I'm unsure of yet is how the default search should beahve. 

1. Search the exact Name ("Libationary Onslaught Leaguestone of the Wind")
2. Search the subtype ("Onslaught Leaguestone")

For now I tend to use the complete name.

**Comment by Zibokwe** [comment]
yes, complete name is good, since that includes the affixes, and it's all you need to price the item. thanks for the quick update!
