### ISSUE TITLE
Corrupted: Either option doesn't work

### ISSUE THREAD

**Issue by DocumentRoot** [PoE-TradeMacro/POE-TradeMacro#281]
I don't want to  ctrl+q or ctrl+alt+d searches only non-corrupted, 
so i set in settings "Corrupted: Either".

But it seems it doesn't work, it still looks for "Corrupted: No" on poe.trade.

Also it will be good to have some smart system, that will be override only when it not-needed.
I mean - for gems - its very important, is it corrupted or not.
But for other items, like jewels/accessories, it not so important, and only causes inconvenience in pricecheck

**Comment by Eruyome** [comment]
This system is in place, at least it should be. Will have to take a look at it.

**Comment by Eruyome** [comment]
fixed in next update
