### ISSUE TITLE
Fix for 'reload script' in context menu

### ISSUE THREAD

**Issue by sicu** [PoE-TradeMacro/POE-TradeMacro#283]
File:   master/resources/ahk/POE-ItemInfo.ahk
Line:   590
Replace:   `Menu, Tray, Add, Reload Script (Use only this), ReloadScript`
With:   `Menu, Tray, Add, Reload Script (TradeMacro), ReloadScript`

**Comment by Eruyome** [comment]
I wouldn't call this a "fix", anyway that won't be enought. The same code has to work when used in the standalone ItemInfo so you can't hardcode the scriptname there.
