### ISSUE TITLE
Error: Expecting JSON value 

### ISSUE THREAD

**Issue by EvilSantaGit** [PoE-TradeMacro/POE-TradeMacro#286]
When i start the script it shows me this error , and than trie to launch it for infinite ammount of time
![12](https://cloud.githubusercontent.com/assets/15078634/23831606/afb7d3ac-072d-11e7-93c9-45c49c9fd8cf.png)

**Comment by Eruyome** [comment]
https://dl.dropboxusercontent.com/u/13620316/POE-TradeMacro.rar try this and open upload `temp\poe_trade_search_form_options.txt` somewhere so that I can take a look at it.

**Comment by EvilSantaGit** [comment]
[poe_trade_search_form_options.txt](https://github.com/PoE-TradeMacro/POE-TradeMacro/files/836495/poe_trade_search_form_options.txt)

or link on google docs
https://drive.google.com/file/d/0B_cO0T-qPRUxV3E5RXZMT2o0QTQ/view?usp=sharing

**Comment by Eruyome** [comment]
That file contains the entire poe.trade front page source code. For some reason it's incomplete, as if the download canceled midway but saved the rest.

**Comment by EvilSantaGit** [comment]
What should i do , i've re-donwnloaded it for 5 times, it doesn't help

**Comment by Eruyome** [comment]
I don't know that yet.

**Comment by EvilSantaGit** [comment]
It seem's that truoble is caused beacaue of wi-fi connection, i tried it now and it works now , so i think the problem is with my internet
Should i close an issue  ?

**Comment by Eruyome** [comment]
Since I can't see anything that could be fixed/done to prevent this on my end (the script) we can probably close this.
