### ISSUE TITLE
'Error : Call to nonexistent function' when running 'Run_ItemInfo'

### ISSUE THREAD

**Issue by DeadPixelz01** [PoE-TradeMacro/POE-TradeMacro#288]
I when I go to run 'Run_ItemInfo' I'm hit with this error:
http://i.imgur.com/mWCGNcz.png

I just downloaded the latest release (2.0,6), I've been out of the loop when it comes to PoE and this macro, am I still meant to run 'Run_ItemInfo' and 'Run_TradeMacro'?

EDIT: Whoops, didn't realise this was fixed in the Master branch :p

**Comment by Eruyome** [comment]
Aside from that you were never supposed to run both.
