### ISSUE TITLE
Getting an "Error at line 6"

### ISSUE THREAD

**Issue by YYZHawk** [PoE-TradeMacro/POE-TradeMacro#294]
Every time I try to run the TradeMacro.ahk file I get this error:

Error at line 6.
#Include file "C:\Users\MyUserName\AppData\Local\Temp\Temp1_POE-TradeMacro-2.0.7zip\resources\VersionTrade.txt" cannot be oppened.

The program will exit.

I have the latest version of both the TradeMacro and AHK. Any help would be appreciated!

**Comment by Eruyome** [comment]
Extracting the macro from the zip file should help.

**Comment by Eruyome** [comment]
Seem to be a simple user error, will close it for now. If this issue still persist, please reopen it.

**Comment by ELcup** [comment]
I have the same error- I unzipped and moved the contents to the documents/my games/poe directory just to be safe.

I've downloaded and extracted several times but always get the same message.  My AHK version I downloaded is AutoHotkey_2.0-a076-aace005.zip

Any suggestions, please?

**Comment by aRTy42** [comment]
Use AHK v1.1.26.01, not a 2.x version.

**Comment by ELcup** [comment]
I could have sworn I've tried this multiple times and made the switch when banging my head against the wall.  Thanks for suggesting it again, IDK when I might have circled back around to it.  Happy holidays :)
