### ISSUE TITLE
the last thing i search continuously pops up

### ISSUE THREAD

**Issue by forestasog** [PoE-TradeMacro/POE-TradeMacro#296]
it continuously pops up at random times, probably like 1-3 times a minute.

i tried refreshing the macro, i tried running as admin, i tried restarting.
these things do work temporarily, until i ctrl+c or d search something, then it starts doing it again.

also ingame text starts glitching out (not sure if that's related)

and it seems to get worse the longer i go without resetting

**Comment by Eruyome** [comment]
Never heard of this before. If possible I'd like to see this in a video/gif, no problem if that's too much trouble for you though. 
Glitched ingamed text is in no way related to the macro since the macro doesn't interact with the game in any way besides reading the clipboard contents.

**Comment by forestasog** [comment]
https://youtu.be/AaVtvKPurzc

ok there's the video, i started recording after the first time it happened, but it start again for a few mins.
around 4 mins i start the map and around 5 i macro the item and then after than it happens multiple times.

i was thinking, you said that you haven't heard of this happening before, and i have a pen tablet, which is something that people don't normally use.  later i'll try fully disabling the tablet and seeing what happens then.

**Comment by Eruyome** [comment]
Please try that.

Did you only press ctrl + d or also ctrl + c after that? The second tooltip that keeps popping up is from ItemInfo and shouldn't show at all when using ctrl +d.
Does this tooltip alos keep popping up when you only use ctrl +c? Does it only happen when using TradeMacro or also when using the standalone ItemInfo?

**Comment by forestasog** [comment]
it pops up with both.

and i tried disabling all programs related to pen tablet and it didn't change.

**Comment by forestasog** [comment]
are you saying that because it pops up with item info i should go there?

**Comment by Eruyome** [comment]
I also contribute to ItemInfo and ItemInfo's caretaker/maintainer @aRTy42 also likes to take a look at TradeMacro issues, so it should be ok. 
The main reason for asking was because now I can probably rule out that its related to TradeMacro. It's either related to ItemInfo or AHK in general, that should make finding the problem a "little bit" easier.

**Comment by aRTy42** [comment]
That is very odd indeed. I'm not really familiar with tablets, so here are a few questions:
* What keys or buttons are you using for the game and the script? Did you bind commands to something or are you using a keyboard?
* As Eruyome asked: What commands did you use in the video? Just Ctrl+D or also Ctrl+C afterwards? Are you pressing anything close to those two commands while playing?
* Do you know whether the tablet is using the clipboard function? The script uses the Ctrl+C command to get the raw item data from the game. This is not a command coming from the script, this function comes from PoE itself. The script is waiting for the clipboard to change while PoE is the active window and then parses the clipboard. Consequently if the tablet is doing something with the clipboard that makes the script consider the clipboard to have changed, it would display the info sheet again.

**Comment by forestasog** [comment]
yes it pops up when i use standalone iteminfo also.

i didn't bind any extra scripts, but i do have additional macros enabled.  i didn't change any of the macros or scripts.

in the video i did use ctrl+d and ctrl+c, but it'll keep popping up regardless of which command i use

i fully disabled the tablet and it still pops up, so i don't think it's related.

hmmm i'll try to see if i have anything that's messing with the clipboard

**Comment by Eruyome** [comment]
Any progress in your search to find the issue?

**Comment by forestasog** [comment]
i found another program that does something with the clipboard, i haven't quite tested it yet

**Comment by forestasog** [comment]
yup, i exited the program and that was it :c

**Comment by Eruyome** [comment]
which software was it?

**Comment by forestasog** [comment]
a book reading program that i keep open all the time.  it had some kind of clipboard thing
