### ISSUE TITLE
Change "Ctrl+I" hotkey to smth else.

### ISSUE THREAD

**Issue by OmikronGamma** [PoE-TradeMacro/POE-TradeMacro#297]
Hello,
for the love of god, REMOVE/CHANGE said hotkeys to smth else, please! 
Whenever i sort my items, using ctrl to quickly toss items to and from stash and inventory, i naturally press ctrl+i, because ctrl is a obvious hotkey and I is hotkey for inventory.  And of course this window, for custom search, pop up. EVERY TIME.

**Comment by dein0s** [comment]
How about changing it by yourself via settings?
![settings](http://i.imgur.com/9ycpg5X.png)

**Comment by Eruyome** [comment]
Like he said, you can change it yourself.
