### ISSUE TITLE
Advanced search, Mod range Modifier % values incorrect, being halved.

### ISSUE THREAD

**Issue by Chameleonica** [PoE-TradeMacro/POE-TradeMacro#299]
In settings the values set for Mod Modifier % are being halved when applied to advanced search.

![poetrademacrolyingsettingsscreen](https://cloud.githubusercontent.com/assets/26643794/24282950/ce3ab2bc-10b6-11e7-819f-a77c53f328a2.gif)

Tested for multiple values. I presume it's being divided by 2 erroneously somewhere.
Hopefully easy find and fix. Thanks for helpful tools.

**Comment by Eruyome** [comment]
Without checking I remember halving those values for rare items. Unique items should use the full value. I'm not sure if this is communicated somewhere but I guess it is mentioned, have to check all of this later.

EDIT: Just looked at the code, `(lowered for non-unique items)` this should be appended to the green values on the GUI, according to your screenshot it isn't.

**Comment by Eruyome** [comment]
Fixed the label, won't do more for now.
