### ISSUE TITLE
[Request] Native support for sale macro

### ISSUE THREAD

**Issue by davideugenepeterson** [PoE-TradeMacro/POE-TradeMacro#300]
Didn't see a discord or forums link for discussion so i'll plop this here. Not really an issue but a observation. Been getting A LOT of people asking what i use for my sales macro and I always direct them to download POE-TradeMacro and to put http://pastebin.com/v28dghv9 into default_additionalMacros. Very ugly code all hard coded no objects or functions for the actual inviting, csv, kicking etc don't have the time. 

I think a built in trade macro with logging in future versions would be used by a lot of people that dislike poe trade helper. Once I have more free time and familiarize with your code I'd be happy to help with this endeavor.

**Comment by Eruyome** [comment]
First of I don't dislike your macro, but here are my first thoughts.

1. TradeMacros goals are to let you price check your items, not to make the trading process itself easier.
2. As mentioned there are other macros/programs to do this like [trades helper](https://www.pathofexile.com/forum/view-thread/1755148) and [mercury trade](https://www.reddit.com/r/pathofexile/comments/5xjof4/introducing_mercurytrade_the_ultimate_solution/). I'm sure everything that I could add to TradeMacro would pale compared to mercury trade for example. Not sure if they have any logging though.
3. TradeMacro shouldn't be a jack of all trades (pun not intended), but specialized in a certain field, so I'm hesitant to add functionalities and let it get bloated (it's already heavy on hotkeys).

Considering the above points I'm not saying this can't or won't be happening but I'm not sure yet if it should.

**Comment by davideugenepeterson** [comment]
Oh there it is, found the discord. I should be contributing to this hub more and try to close a few open bugs, i rather enjoy your macro. I'll keep that in mind about the user folder. 

That's a valid point about specializing and not being a jack of all trades makes sense; Just wish there was one tool I could go to to do both ends of sales.  If you ever decide to add such a feature in the future let me know I would love to be on board for programming, i'm sure we could find a niche that mercury trade doesn't have, even if it's only an optional standalone plugin for trade macro.
