### ISSUE TITLE
[Request] Multi language support (chinese) 界面汉化

### ISSUE THREAD

**Issue by q7924115** [PoE-TradeMacro/POE-TradeMacro#302]
我想把界面汉化  汉化的UI 我已经做好了 请教怎么加到软件里 或者给个教程 也可以  谢谢
[General ; 一般.zip](https://github.com/PoE-TradeMacro/POE-TradeMacro/files/871626/General.zip)

**Comment by Eruyome** [comment]
You should at least try to translate this for me^^

`I would like to help the finished language UI I have done to ask how to add to the software or to a tutorial can also thank you`

That's what google translate returns and I get what you're asking. I've run your ahk file and have seen your GUI translations, there are a few problems though.
1. TradeMacro/ItemInfo currently have no multi language support, all texts are hardcoded, so to get this to work we would have to read all texts from language files instead using variables.
2. The dropdownlist values are used in hardcoded string comparisons, so translating `tmpstandard` or the currency names for example would break the current script. Basically translating any dropdownlist value is a very bad thing at the moment and aside from that the currencies are not hardcoded anywhere but scraped from poe.trade at scriptstart.
3. If you translate the UI you should translate all of it, maybe all menus but definitely the tooltips that you get by hovering over the settings menu entries.

**Comment by davideugenepeterson** [comment]
@Eruyome  I'll work on some i18n when i finish up the current freelancing project i'm on; It's long overdue. Might be awhile before i'm free though.
