### ISSUE TITLE
Only Ctrl + C works.

### ISSUE THREAD

**Issue by keith009** [PoE-TradeMacro/POE-TradeMacro#306]
Title, for some reason only Ctrl + C works while everything else doesn't, i tried it without having other macros on but it didnt work either. Have the latest AHK update.

**Comment by Eruyome** [comment]
Please describe your issue in more detail.
How are you starting the macro (which file do you use)? If you don't know what to describe but can easily capture your "workflow" including the issue on a video/gif feel free to do so. It's possible that this is just a simple user error.

**Comment by keith009** [comment]
Isn't much to describe.

I start Run_TradeMacro as i used to, this time everything besides ctrl + c just doesn't work. gif wouldn't help since the window is in fullscreen windowed as it should.

**Comment by Eruyome** [comment]
I find this very odd. Just to make sure, does not a single hotkey work? No custom search (ctrl+i), no wiki page (ctrl+w)?

**Comment by keith009** [comment]
Yeah, none of them work, tried all.

http://i.imgur.com/1MuMo4R.png

http://i.imgur.com/FKg8UeU.png

i deleted few lines from additional macros but i dont see how that would affect it(already reinstalled as well to make sure that's not the fault).

**Comment by Eruyome** [comment]
ItemInfos Ctrl + c isn't actually a hotkey, the script just does something when your clipboard changes since PoE copies the items information into the clipboard via ctrl +c.

Are any other macros working for you? Like http://lutbot.com/#

**Comment by keith009** [comment]
Yeah, all the lutbot ones work as they should.

**Comment by Eruyome** [comment]
The folder gets replaced, the documents stay untouched unless a change has to be made (in most updates thats not the case). To get a completely fresh install just delete the trademacro folder in documents, too.

**Comment by Eruyome** [comment]
@aRTy42, any idea? I see no reason why the hotkeys suddenly won't work anymore....

**Comment by aRTy42** [comment]
Try executing the script explicitely with admin privileges (via rightclick). If the script has a lower access level than the game, then the game likely refuses input. The Ctrl+C command is an exception because that comes from the game itself and the script only then reads the clipboard.

**Comment by keith009** [comment]
Ayy, i figured it out, i had changed the name "PathOfExile_x64" to "64" (was having trouble starting the game with .bat file).

**Comment by Eruyome** [comment]
Wow, unexpected... I usually don't change game file names^^
