### ISSUE TITLE
No item found

### ISSUE THREAD

**Issue by mati43** [PoE-TradeMacro/POE-TradeMacro#307]
When I use CTRL + D or anything else really i get "no item found" as a result. Did everything that FAQ says.

**Comment by Eruyome** [comment]
Run `resources\tests\Winhhtprequest.ahk` and show me the result.

**Comment by mati43** [comment]
1.     Type 'help' for a list of commands (no quotes)

2.        21:07:53 wtorek, 28 marca 2017

3.     Download test with url : https://api.github.com/repos/PoE-TradeMacro/PoE-TradeMacro/releases

4.        21:07:54 wtorek, 28 marca 2017

5.     Testing UrlDownloadToFile: No errors.

6.      Output saved in: C:\Users\mati\Desktop\Nowy folder\resources\tests\test_temp\urlDownloadToFile_output.txt

7.     Content Length: 70013

8.        21:07:55 wtorek, 28 marca 2017

9.     First test downloading to variable using WinHTTP adodb.stream successful.

10.    Content Length: 70013

11.       21:07:55 wtorek, 28 marca 2017

12.    Second test downloading to variable using WinHTTP adodb.stream successful.

13.    Content Length: 70013

14.       21:07:55 wtorek, 28 marca 2017

15.    -----------------------------------------

16.       21:07:55 wtorek, 28 marca 2017

17.    Download test with url : http://poe.trade

18.       21:07:56 wtorek, 28 marca 2017

19.    Testing UrlDownloadToFile: No errors.

20.     Output saved in: C:\Users\mati\Desktop\Nowy folder\resources\tests\test_temp\urlDownloadToFile_output.txt

21.    Content Length: 766834

22.       21:07:56 wtorek, 28 marca 2017

23.    First test downloading to variable using WinHTTP adodb.stream successful.

24.    Content Length: 766819

25.       21:07:57 wtorek, 28 marca 2017

26.    Second test downloading to variable using WinHTTP adodb.stream successful.

27.    Content Length: 766819

28.       21:07:57 wtorek, 28 marca 2017

29.    -----------------------------------------

**Comment by mati43** [comment]
```
> 1.     Type 'help' for a list of commands (no quotes)
> 
> 2.        21:07:53 wtorek, 28 marca 2017
> 
> 3.     Download test with url : https://api.github.com/repos/PoE-TradeMacro/PoE-TradeMacro/releases
> 
> 4.        21:07:54 wtorek, 28 marca 2017
> 
> 5.     Testing UrlDownloadToFile: No errors.
> 
> 6.      Output saved in: C:\Users\mati\Desktop\Nowy folder\resources\tests\test_temp\urlDownloadToFile_output.txt
> 
> 7.     Content Length: 70013
> 
> 8.        21:07:55 wtorek, 28 marca 2017
> 
> 9.     First test downloading to variable using WinHTTP adodb.stream successful.
> 
> 10.    Content Length: 70013
> 
> 11.       21:07:55 wtorek, 28 marca 2017
> 
> 12.    Second test downloading to variable using WinHTTP adodb.stream successful.
> 
> 13.    Content Length: 70013
> 
> 14.       21:07:55 wtorek, 28 marca 2017
> 
> 15.    -----------------------------------------
> 
> 16.       21:07:55 wtorek, 28 marca 2017
> 
> 17.    Download test with url : http://poe.trade
> 
> 18.       21:07:56 wtorek, 28 marca 2017
> 
> 19.    Testing UrlDownloadToFile: No errors.
> 
> 20.     Output saved in: C:\Users\mati\Desktop\Nowy folder\resources\tests\test_temp\urlDownloadToFile_output.txt
> 
> 21.    Content Length: 766834
> 
> 22.       21:07:56 wtorek, 28 marca 2017
> 
> 23.    First test downloading to variable using WinHTTP adodb.stream successful.
> 
> 24.    Content Length: 766819
> 
> 25.       21:07:57 wtorek, 28 marca 2017
> 
> 26.    Second test downloading to variable using WinHTTP adodb.stream successful.
> 
> 27.    Content Length: 766819
> 
> 28.       21:07:57 wtorek, 28 marca 2017
> 
> 29.    -----------------------------------------
> 
```

**Comment by chobu** [comment]
I've got the same problem.

**Comment by Eruyome** [comment]
Please use the current development version https://github.com/PoE-TradeMacro/POE-TradeMacro/archive/devEru.zip. If it doesn't exist anymore I have merged it into the main version and you can use that. 

Then enable debug mode in the settings menu and make  a search (ctrl+d). This should create the file `resources\DebugSearchOutput.txt`, please upload that file somewhere for me.

**Comment by mati43** [comment]
Welp it creates empty .txt file 0 bytes

**Comment by Eruyome** [comment]
Are you sure that the WinHttpRequest test still succeeds? An empty file can only be created if the request fails completely.

**Comment by mati43** [comment]
Well yeah. When I use its it creates this 2 files 

http://www22.zippyshare.com/v/tsXJCLK8/file.html
http://www22.zippyshare.com/v/kTEFipcO/file.html

**Comment by Eruyome** [comment]
Every search outputs an empty file?

**Comment by mati43** [comment]
So DebugSearchOutput file is empty but WinHttpRequest show this 

`4.     Download test with url : https://api.github.com/repos/PoE-TradeMacro/PoE-TradeMacro/releases

5.        20:41:16 czwartek, 30 marca 2017

6.     Testing UrlDownloadToFile: No errors.

7.      Output saved in: C:\Users\mati\Downloads\POE-TradeMacro-devEru (1)\POE-TradeMacro-devEru\resources\tests\test_temp\urlDownloadToFile1_output.txt

8.     Content Length: 70013

9.        20:41:17 czwartek, 30 marca 2017

10.    First test downloading to variable using WinHTTP adodb.stream successful. (Catching Errors)

11.    Content Length: 70013

12.       20:41:17 czwartek, 30 marca 2017

13.    Second test downloading to variable using WinHTTP adodb.stream successful. (Not catching Errors)

14.    Content Length: 70013

15.       20:41:17 czwartek, 30 marca 2017

16.    -----------------------------------------

17.       20:41:17 czwartek, 30 marca 2017

18.    ---------------------------------------------------

19.    Download test with url : http://poe.trade

20.       20:41:18 czwartek, 30 marca 2017

21.    Testing UrlDownloadToFile: No errors.

22.     Output saved in: C:\Users\mati\Downloads\POE-TradeMacro-devEru (1)\POE-TradeMacro-devEru\resources\tests\test_temp\urlDownloadToFile2_output.txt

23.    Content Length: 766821

24.       20:41:18 czwartek, 30 marca 2017

25.    First test downloading to variable using WinHTTP adodb.stream successful. (Catching Errors)

26.    Content Length: 766819

27.       20:41:19 czwartek, 30 marca 2017

28.    Second test downloading to variable using WinHTTP adodb.stream successful. (Not catching Errors)

29.    Content Length: 766819

30.       20:41:19 czwartek, 30 marca 2017

31.    -----------------------------------------

32.       20:41:19 czwartek, 30 marca 2017

33.    ---------------------------------------------------

34.    Download test with url : http://poe.trade/search/seridonomosure

35.       20:41:20 czwartek, 30 marca 2017

36.    Testing UrlDownloadToFile: No errors.

37.     Output saved in: C:\Users\mati\Downloads\POE-TradeMacro-devEru (1)\POE-TradeMacro-devEru\resources\tests\test_temp\urlDownloadToFile3_output.txt

38.    Content Length: 1248444

39.       20:41:21 czwartek, 30 marca 2017

40.    First test downloading to variable using WinHTTP adodb.stream successful. (Catching Errors)

41.    Content Length: 1248318

42.       20:41:22 czwartek, 30 marca 2017

43.    Second test downloading to variable using WinHTTP adodb.stream successful. (Not catching Errors)

44.    Content Length: 1248318

45.       20:41:22 czwartek, 30 marca 2017

46.    -----------------------------------------
`

http://www12.zippyshare.com/v/crLRSRcs/file.html
http://www12.zippyshare.com/v/yvu0XeQh/file.html
http://www12.zippyshare.com/v/4ms5K453/file.html

**Comment by Eruyome** [comment]
What about the console window when searching, what does it say about the returned content-length?

**Comment by mati43** [comment]
>Search finished. Returned content length: 0

**Comment by Eruyome** [comment]
![grafik](https://cloud.githubusercontent.com/assets/16058242/24552411/94f2a422-1626-11e7-8352-5e33c75baedb.png)

I've added additional debug information to every search, use the newest dev version again https://github.com/PoE-TradeMacro/POE-TradeMacro/archive/devEru.zip

**Comment by mati43** [comment]
![debug](https://cloud.githubusercontent.com/assets/26747627/24554113/b60ab3ec-162c-11e7-9e78-900a762f4207.png)

**Comment by Eruyome** [comment]
Really? A return success (-1) but no/empty response headers, no status or statustext?...
@thirdy Help me out here, shouldn't a POST request with return code -1 (success) not at least return a statuscode/text or response headers?

**Comment by mati43** [comment]
Yup, thats what I got. Did update to 2.09 and same effect.

**Comment by thirdy** [comment]
Damn. This is one of those annoying mystery. It might be worth it to replace Winhhtprequest with a more reliable one. Some dll.

**Comment by thirdy** [comment]
Try this:
http://www.confusedbycode.com/curl/#downloads

AHK should be able to call that.. hopefully easily.

**Comment by Eruyome** [comment]
I'll close this for now, just reopen it if there still are issues.
