### ISSUE TITLE
The tempest

### ISSUE THREAD

**Issue by Flaeng** [PoE-TradeMacro/POE-TradeMacro#310]
Please try and price-check (Ctrl + D) a "**The Tempest - Long bow**".
The search result shows as:
"1 alt"
"2 chromatic"
"1 change"
"1 alc" (rest is 1 alc).
If i Ctrl + Q it goes to this url: http://poe.trade/search/urataosiaminag
which is far from a long bow. Please fix.

(btw. awesome macros - but im gonna stick with Ctrl + Q from now on)

**Comment by Eruyome** [comment]
Should have added the rarity and TypeName (Base, for example Simple Robe) to unique searches since the name is not sufficiant in some edge cases. Implemented in the dev version. Haven't checked with your particular example but that should work now.
