### ISSUE TITLE
Windowed mode problem ?

### ISSUE THREAD

**Issue by binbinhfr** [PoE-TradeMacro/POE-TradeMacro#311]
Hi, 
POE-trade was perfectly working until a few days ago : now when I press ctrl-D, the little window is not appearing on top of the game window. I have to type alt-esc under windows 7 to read it (because it was displayed underneath the game window). I checked that I was in windowed-fullscreen mode. When going to windowed-bordered mode, it is working again. I do not understand what changed since last time it was working under full-windowed mode...

**Comment by Eruyome** [comment]
No, it was never working with fullscreen and never will. Maybe you're mistaken about having run PoE in fullscreen?

**Comment by binbinhfr** [comment]
There are 3 options in POE : fullscreen, windowed (with border), windowed-fullscreen (window no border). I always used the last one, and it worked perfectly...

**Comment by Eruyome** [comment]
Yeah no way unless you have some software that could interfere and make this possible but I highly doubt it. Feel free to look it up, showing AHK tooltips in fullscreen applications is not possible unless you use code injection or maybe in some cases this here https://autohotkey.com/board/topic/42069-lib-gpf-v11c-overlaying-direct3d-games-dx-89-fixed/. It's a common question/request in the AHK world but there are no other ways.

**Comment by binbinhfr** [comment]
Excuse me, but my english is not so good, so I did not understand perfectly what you just said : did you say that it was never supposed to work in windowed-fullscreen (i.e. windowed borderless) ?
Because in the wiki, I read (https://github.com/POE-TradeMacro/POE-TradeMacro/wiki/Usage---Installation) :
"Make sure to run PoE in (borderless) windowed mode. Otherwise it won't work!"
I noticed that it did not work in true-fullscreen, but it always worked in borderless windowed mode from now on.
Are you the guy who developped the code ?

**Comment by Eruyome** [comment]
It works in fullscreen windowed (borderless), as it is supposed to.
It does not, never has and never will work in true fullscreen. From your comments I understood that you're complaining that it worked in fullscreen for you but not anymore. 

I am that guy.

**Comment by binbinhfr** [comment]
No no, I agree that it never worked in true fullscreen. My problem is under borderless-windowed mode.

**Comment by Eruyome** [comment]
Sry, then I misunderstood your issue^^

**Comment by binbinhfr** [comment]
No problem. But I still do not understand what is the problem ;-)
The behaviour is random. Sometimes it works, but most of the time it does not.

**Comment by binbinhfr** [comment]
by the way, I wonder, what version of AHK is supposed to be installed ? 1.1 or 2.0 ?

**Comment by Eruyome** [comment]
1.1.x, not sure if 2.0 works.

Update is released. Your issue seems odd, especially if it's really not consitent.

**Comment by binbinhfr** [comment]
I updated POE-trade and AKH 1.1.x last version, but it's not better.

Other wise, yes I am playing POE from a steam account, so yes, steam has always been running in background.
I tried to disable Steam overlay feature, but it does not change anything : now, most of the time when I press Ctrl-D, the POE-trade window appears under the game (I can see it if I press alt-esc to switch back to the desktop). I would say that 1 time out of 10, it appears correctly on top of the game window. Very strange.

**Comment by Eruyome** [comment]
Steam shouldn't cause any issues, I use that too, like many others.

**Comment by aRTy42** [comment]
> @aRTy42, any idea?

I'm not using steam for PoE. Is there an option that forces games into the foreground?

Other than that no idea, unfortunately.

**Comment by Eruyome** [comment]
Well, Steam shouldn't be the problem anyway, don't think there's such an option.

**Comment by sskorzh** [comment]
I have a similar problem with version 2.0.9, window is not appearing.
But version 2.0.8 works perfectly, so while I'm using it.

**Comment by Eruyome** [comment]
So we can assume something changed with your pc setup causing this?

**Comment by sskorzh** [comment]
Nothing has changed

**Comment by binbinhfr** [comment]
for me, it is the same : nothing has changed in my PC setup (no driver update, nothing...).

but I noticed something : if I remap the Ctrl-D key to F5, it's working again !  So is it a problem with the Ctrl-D used by another program ? But as I told, my PC setup did not changed and I have no program running in background, instead AVAST and ZoneAlarm.

**Comment by Eruyome** [comment]
I really have no idea... but if it really just suddenly started to not work right on any version there has to be something different.

**Comment by cokoboko1** [comment]
Hello, I have had similar problem, I didn't change anything in my options menu (both in poe and in the macro) and I can't seem to make the macro text show up above Path of Exile's window. I can see it under the game window as shown in the picture here.
![problem](https://cloud.githubusercontent.com/assets/27153462/24839536/19c31660-1d65-11e7-9b5f-cbba5475d666.jpg)
I don't know if i should have made a new topic or post here so I decided to post here.
Also recently I have been using MercuryTrade a similar program, for the first two days it was fine but had the same problem and I just decided to uninstall it because it wasn't really necessary, but i can't live anymore without this glorious script.

**Comment by binbinhfr** [comment]
hi cokoboka,
just a note to say that my problem (the same as yours) is still not solved). For the moment I use Ctrl-Q and switch to windows, but it's not very handy. I tried everything : reinstall graphic drivers, reinstall AHK, reinstall POE-trade, verifying POE files, changing POE options, but nothing solves the problem. Most of the time, I also have the POE-trade windo under the window's game, as you show in the screencopy. What graphic card do you have ? (I have a Nvidia GTX750ti)

**Comment by cokoboko1** [comment]
Hey, binbinhfr I have Nvidia GeForce GTX 660 and thanks for reminding me Ctrl + Q exists, might be not as good but it does the work

**Comment by Eruyome** [comment]
Could you both save this as an ahk file, run it and press F1 (or whatever you want to use) when PoE is running and is active? This tooltip is from the ahk documentation. Let's see if that works, should display the tooltip where your cursor is.

```
#SingleInstance force

; To have a ToolTip disappear after a certain amount of time
; without having to use Sleep (which stops the current thread):
#Persistent

F1::ShowTooltip()

ShowTooltip() {
	ToolTip, Timed ToolTip`nThis will be displayed for 5 seconds.
	SetTimer, RemoveToolTip, 5000
	return

	RemoveToolTip:
	SetTimer, RemoveToolTip, Off
	ToolTip
	return
}
```

**Comment by cokoboko1** [comment]
![untitled](https://cloud.githubusercontent.com/assets/27153462/24839983/426ebfc6-1d6d-11e7-8a09-7dd06c3ca140.jpg)
Here's my experience with it- It showed up the first time right after I installed it, I pressed it again a few seconds later , didn't show up. After reloading the script it showed up now for multiple clicks

**Comment by Eruyome** [comment]
The ItemInfo/TradeMacro tooltip is a bit more complicated, but it's good to know that at least this small example works.

**Comment by binbinhfr** [comment]
It works perfectly for me too ! :-)

**Comment by Eruyome** [comment]
What about this one? Copied some ItemInfo code, minimal changes.

```
#SingleInstance force

; To have a ToolTip disappear after a certain amount of time
; without having to use Sleep (which stops the current thread):
#Persistent

ToolTipTimeout := 0
text := "Test tooltip. bla bla bla`nbla bla" 

F1::ShowTooltip(text)

ShowToolTip(String, Centered = false)
{
	Global X, Y, ToolTipTimeout

	; Get position of mouse cursor
	MouseGetPos, X, Y

	If (Centered)
	{
		ScreenOffsetY := A_ScreenHeight / 2
		ScreenOffsetX := A_ScreenWidth / 2

		XCoord := 0 + ScreenOffsetX
		YCoord := 0 + ScreenOffsetY

		ToolTip, %String%, XCoord, YCoord
		ToolTip, %String%, XCoord, YCoord
	}
	Else
	{
		XCoord := (X - 135 >= 0) ? X - 135 : 0
		YCoord := (Y +  35 >= 0) ? Y +  35 : 0
		ToolTip, %String%, XCoord, YCoord
		ToolTip, %String%, XCoord, YCoord
	}

	; Set up count variable and start timer for tooltip timeout
	ToolTipTimeout := 0
	SetTimer, ToolTipTimer, 100
}

ToolTipTimer:
	Global ToolTipTimeout
	ToolTipTimeout += 1
	MouseGetPos, CurrX, CurrY
	MouseMoved := (CurrX - X) ** 2 + (CurrY - Y) ** 2 > 40 ** 2
	If (MouseMoved or (ToolTipTimeout >= 150))
	{
		SetTimer, ToolTipTimer, Off
		ToolTip
	}
	return
```

**Comment by cokoboko1** [comment]
![problem2](https://cloud.githubusercontent.com/assets/27153462/24840255/875acb70-1d72-11e7-980d-90dbfa3adb2d.jpg)
Not quite as consistent: here's my exp with this script
First click worked good, second didn't show up
After reload the first two clicks showed up
and it showed up as many times and I have restarted it before(not sure if this is helpful or I'm just an RNG god)
After the 6th or 7th reload it began showing up only once then disappearing until reloaded
Also the screenshot is just a weird thing I wanted to point out, it might help

**Comment by binbinhfr** [comment]
same thing here : first F1 call works, but not the following ones...

**Comment by binbinhfr** [comment]
note : the problem seems to come from the timeout : if I change the code like this
If ((ToolTipTimeout >= 150))
;If (MouseMoved or (ToolTipTimeout >= 150))

it works everytime I type F1.
it's the MouseMoved detection that seems to have problem.

**Comment by binbinhfr** [comment]
ok, so the guys have the same problem ?
Note that now, even in bordered-window mode, the Ctrl-C works, but not the Ctrl-D. Nothing...
The Ctrl-Q still works in either windowed mode.

Note also that reverting back to 1.7.2 solves the problem : so it seems that neither AHK nor my graphic drivers are the problem. It seems that something changed between 1.7.2 to 2.0.11 about the toolip display.

More precisely, I checked every version in between : 
since 2.0.0 and in next version, it was working but sometimes the tooltip disappear as soon as it appears, even if I do not touch the mouse...
and from one version to the next, strangely, i have the impression that this bad behaviour is getting progressively worse... (is it possible ?)
and in 2.0.10, I almost never have access to the display (sometimes it flashes very briefly, but most of the time, I do not even see it.)

hope that it can help.

**Comment by binbinhfr** [comment]
no news ? you gave up ?  :-)

**Comment by Eruyome** [comment]
Had some hardware issues and didn't check on TradeMacro for like a week.

**Comment by binbinhfr** [comment]
The problem is the same with "PoE-ItemInfo standalone version".
BUT I have a clue : I installed the standalone version of POE (the non-steam one), and everything is working fine !!! So it is coming from the steam-version. Do you have steam ?
I checked in steam options and disabled anything that could interfere with display (steam popup, streaming, etc...), but it does not solve the problem. Infact, i wonder if the steam version really uses the borderless-window mode settings. It seems to me that it overwrites it with a true-fullscreen-mode...

**Comment by Eruyome** [comment]
I have both version installed but never use the standalone one, always steam. I'm not aware of such behaviour from steam but I wouldn't say that's impossible. I also don't use windows 7 and can't say if there's any relation to using both together. I can try to do some research on this topic when I find the time, until then you'd ahve to try and find a solution or simply use the standalone version.

**Comment by binbinhfr** [comment]
For the moment, I am using the non-steam version. I also send an email to GGG tech support to see if there is something on the steam side...
Strange that your steam-version works and mine not. What OS do you have ? win 10 ?

**Comment by Eruyome** [comment]
I'm using 8.1

**Comment by binbinhfr** [comment]
answer from GGG : "I'm afraid we're not able to offer support for third party software, as they are not officially supported by Grinding Gear Games."

**Comment by Eruyome** [comment]
Well, that's expected, what you could be asking is whether they are aware of any kind of issues with Steam messing with the windowed mode or something in that direction. You'll never get direct support for third party software from them.

**Comment by binbinhfr** [comment]
Well basically, my concluding question was yours : are they aware of a difference in windowed mode between steam and non-steam. But I guess they do not even read the end of my email, as soon as they understood that it was a third party soft problem... If I just ask, without explaining my issue or problem encountered, they won't try to help me either...

**Comment by Eruyome** [comment]
I'll close this for now, just reopen it if there still are issues.
