### ISSUE TITLE
Failed attempt to launch

### ISSUE THREAD

**Issue by OneSickBasta** [PoE-TradeMacro/POE-TradeMacro#316]
After updating 2.0.9 have such a problems http://images.vfl.ru/ii/1491137658/c22a1618/16707592_m.png

**Comment by dein0s** [comment]
If I understand everything correct - there's no program in your system associated with `.html` extension and therefore you're getting that error.
You can try following steps to fix this:
1. Create an empty text file and change it's extension to `.html` (like `test.html` for example)
2. Right-click that file and call `Properties`
3. At the top of `General` tab you'll see `Opens with` field and `Change` button near it
4. Click that button and choose the browser you like 
5. Apply changes

Then try to run macro again and post your results.

---
Из текста ошибки похоже на то, что макрос не может найти в системе приложение, предназначенное для запуска файлов с расширением `.html`.
Попробуйте следующее:
1. Создайте пустой текстовый файл и измените его расширение на `.html` (что-нибудь вроде `test.html`)
2. Правым кликом на файл и открываем `Свойства`
3. В верхней части закладки `Общие` будет поле `Приложение` и рядом кнопка `Изменить`
4. Кликаем кнопку и выбираем любой браузер (свой любимый:))
5. Применяем изменения

После этого попробуйте запустить макрос снова и сообщите о результатах. 
И прошу придерживаться английского языка при дальнейшем общении, т.к. я не мейнтейнер/разработчик макроса (он в русский не может), а просто пытаюсь помочь по мере возможностей :)

**Comment by OneSickBasta** [comment]
Do exactly as u say,but problem didn't solved. May be im doing smth wrong ( 
But anyway thank you for trying to help.

**Comment by dein0s** [comment]
And error message is still the same?

**Comment by OneSickBasta** [comment]
Yup

**Comment by dein0s** [comment]
Well, I've no clue then as I'm not that familiar with AHK. 
Let's wait for @Eruyome

**Comment by OneSickBasta** [comment]
After few trying,im figured out how to fix it.
Just in poe item info settings click button Open browser Win10fix and its start working

**Comment by Eruyome** [comment]
Nice, will close this then.
