### ISSUE TITLE
[Request] Highlight Items macro

### ISSUE THREAD

**Issue by Eruyome** [PoE-TradeMacro/POE-TradeMacro#319]
https://gist.github.com/Nightblade/81d7bbbe6b01c8d598d7f1d6463f7d6d

**Comment by Eruyome** [comment]
Thinking about using ctrl + f as hotkey.
Advantage: no additional hotkeys to remember.
Disadvantage: search (highlighting) can't be used without filling the field while hovering over an item, could be inconvenient if you're not accustomed to it.

**Comment by Nightblade** [comment]
Perhaps it just send a ctrl + f to the client if there's nothing in the clipboard to parse?

**Comment by Nightblade** [comment]
By the way, something is already removing "Superior" from the item name, for maps at least.

**I just did some tests on items in my stash:**

_**Ancient Reliquary Key**_ -> nothing happens at all.  Same with _**Open Item (Wiki)**_ on this item.  _**Price Check**_ and _**Show Item Age**_ work though.

## Tested working:
- skill gems, vaal skill gems
- sac fragments
- essence
- divination cards
- maps, superior maps, shaped maps  (should "Shaped" be removed?):
- unique jewels
- unique items

## Tested not working:
- leaguestones -> Leaguestone
- flasks -> Flask

- **non-uniques:**
  -  belts, rings, amulets	->	Item
  -  jewels			->	Item
  - armor			->	Armour

**Comment by Eruyome** [comment]
> Perhaps it could send a ctrl + f to the client if there's nothing in the clipboard to parse?

Of course, that's for sure.

**Comment by Nightblade** [comment]
Fixed Leaguestones.

**Comment by Eruyome** [comment]
@aRTy42 do you think we should implement this for ItemInfo? The function built into ItemInfo but the hotkey and function call for it in AdditionalMacros.txt?
I don't find this important enough to implement it with a configurable hotkey directly in TradeMacro.

**Comment by aRTy42** [comment]
I'm not really sure why that function would be useful. At least I don't find myself searching for an item that I have that often.

Implementing it does not really hurt though, so I'm fine with it. I would disable it by default in the AdditionalMacros though, as for most functions.

(Using Ctrl+F sounds like a good choice by the way)

**Comment by Eruyome** [comment]
I wouldn't use it much either but it could be useful for sorting your Standard Stash if you have dozens of remove only tabs and want to find and sort certain items. Or in general for quick searches when you have a lot of unsorted tabs. I often have 10+ tabs full of unidentified items because I'm too lazy to sort them out while mapping/between lab runs.

**Comment by Eruyome** [comment]
So I started to implement this.

But I thought about whether it's always a good idea to use the item name for the search. This should be a good idea for uniques, div cards, gems.
How about currency? Is it better to use the name to find the same currency item or the type "Currency" to find other currencies? For example when I have dumped 10+ tabs full of items while mapping I like to fish out all currency items to put them in my currency stash. 

- Leaguestones should use the base, "Nemesis Leaguestone".
- Flasks should use the base, "Greater Life Flask".
- Maps should use base type, "Dunes Map".
- Jewels should use the base, "Cobalt Jewel", but should they also use the rarity, "magic"? If I wanted to just find all cobalts the first would be better while the second would be better when I want to find all cobalts that can be easily crafted from my jewel stash tab.
- Other items should use the base type.

**Comment by Eruyome** [comment]
First version of this implemented on the ItemInfo dev branch https://github.com/aRTy42/POE-ItemInfo

**Comment by Nightblade** [comment]
I use my version of this when moving maps to my stash, which is often.

Personally, I think it would be most useful to simply use the item's name, even for currency.  

Maybe move the core "name grabbing" part out to a separate  function, which the OpenWiki function can use too, avoiding some code duplication.

(Sorry if this isn't making sense, I'm not well and having trouble thinking straight today!)

**Comment by Eruyome** [comment]
I think I get what you mean. It's just that this function doesn't give the user any way to influence it's behavior and I don't intend to implement options for it. That's overkill. So, I can only implement one string of search tems per item/item type. Therefore it should be the one most useful.
In my personal experience that would be "Currency" instead of "<CurrencyName>" to quickly sort my dump stash tabs. 
For Flasks I have implemented "Quicksilver Flask" but thinking about it now it's probably better to just use "Flask" since you can differentiate them easily anway but fishing out your flasks from tabs filled with random items is not quite as easy. I've also tought about adding "Quality" if a flask has it, but that may be too much.

**Comment by aRTy42** [comment]
It seems I'm not really the target user for that function. Using things like Flask/Amulet/Ring/Dagger seems better to me than Greater Life Flask, Golden Kris, Leather Belt etc. though.

**Comment by Nightblade** [comment]
I think we all have very different ideas of how we would use this function.  `:-)`

Is there no easy way we can influence the function's behaviour when called from AdditionalMacros?  Something like this:
```
^f::HighlightItems()        ; "standard" format -- mostly sanitised item name 
+^f::HighlightItems(true)   ; "base type" format

HighlightItems(filterBaseType = false)
{
    ...
}
```

Or could there be a `HighlightBaseType` func we could bind instead of / in addition to `HighlightItems` in AdditionalMacros?


Personally I feel it would be counter-intuitive (and of limited use) to have it filter by `Currency` when mousing over a `Chaos Orb` (for example), especially if it's going to filter by item name generally.  And it's easy to make an AdditionalMacro to cover that specific task:   `F3::SendInput ^fCurrency{Enter}` 

---

This is what I would find the most useful (by no means an exhaustive list):

**Straight item name**:
- uniques
- essence
- divination cards
- currency

**Sanitised item name / sub type:**  (no mods, no Superior/Shaped/Quality etc)
- skill gems (including vaal skill gems)
- maps
  - `Anarchic Shaped Arcade Map` --> `Arcade Map`
- leaguestones
  - `Fearsome Invasion Leaguestone` --> `Invasion Leaguestone`
- flasks
  - `Quicksilver Flask of Resistance` --> `Quicksilver Flask`
- jewels
  - `Viper Ornament Crimson Jewel` --> `Crimson Jewel`
- armour, weapons, offhands, belts, rings, amulets, etc.
  - `Storm Nail Two-Stone Ring` --> `Two-Stone Ring`


In any case, i'm not able to do the heavy-lifting so it's up to you guys!   `:-)`

(Again, sorry if this is unclear, still fighting brain fog.  Also, I'm no AHK pro.)

**Comment by Eruyome** [comment]
I'm still not a fan of implementing options for this feature, if at all then as some simple "ini-like" text file in the user folder. Having a hotkey modifier could work though, the normal search uses the specific terms while the modified search uses a more broader term, for example:    

- "Mjölner" <-> "Unique"
- "Shaped Strand Map" "tier:11" <-> "Map" (maybe including the same tier, but without the tier you can quickly search for maps in your dum tabs or while sorting your standard stash after a league.
- "Greater Life Flask" <-> "Flask"
- "Chaos Orb" <-> "Currency"
- "Defeaning Essence of Something" <-> "Essence"

By the way, I think "shaped" shouldn't be stripped from the map name.

**Comment by Eruyome** [comment]
I reworked this according to my suggestions https://github.com/aRTy42/POE-ItemInfo/compare/devEru, please give it a thorough test, it got a bit complicated.

Example:    

```
; other items (weapons, armour pieces, jewelry etc)
Else {			
	If (broadTerms) {
		If (Item.IsWeapon or Item.IsAmulet or Item.IsRing or Item.IsBelt or InStr(Item.SubType, "Shield")) {
			; add the term "Chance to Block" to remove items with "Energy Shield" from "Shield" searches
			If (InStr(Item.SubType, "Shield")) {
				terms.push("Chance to Block")
			}
			
			; add grip type to differentiate 1 and 2 handed weapons
			If (Item.GripType == "1H" and RegExMatch(Item.Subtype, "i)Sword|Mace|Axe")) {
				prefix := "One Handed"
			} Else If (Item.GripType == "2H") {
				prefix := "Two Handed"
			}
			; add a space since all these terms have a preceding one, this reduces the chance of accidental matches
			; for example "Ring" found in "Voidbringers" or "during Flask effect"
			terms.push(prefix " " Item.SubType)	
		} 
		; armour pieces are a bit special, the ingame information doesn't include "armour/body armour" or something alike. 
		; we can use the item defenses though to match armour pieces with the same defense types (can't differentiate between "Body Armour" and "Helmet").
		Else If (InStr(Item.BaseType, "Armour")) {
			For key, val in ItemData.Parts {
				If (RegExMatch(val, "i)(Energy Shield:)|(Armour:)|(Evasion Rating:)", match)) {
					Loop, 3 {
						If (StrLen(match%A_Index%)) {
							terms.push(match%A_Index%)
						}
					}
				}
			}
		}
	} Else {
		terms.push(Item.TypeName)
	}
}
```

**Comment by Eruyome** [comment]
Implemented and relased. I'll close this, if there are suggestions to alter this or some bugs just create a new issue.
