### ISSUE TITLE
[Request] Put on the readme instructions that you need to play the game in english

### ISSUE THREAD

**Issue by gvieiraaa** [PoE-TradeMacro/POE-TradeMacro#320]
It seems pretty obvious, I know...
But I'm from the brazilian community and A LOT of players play with the game in portuguese, and I've seen multiple times people complaining that they followed the instructions and the tool doesn't work because the game wasn't in english.

**Comment by Eruyome** [comment]
Seems obvious to you, I actually haven't thought of it though. Will do it.
