### ISSUE TITLE
Wrong wiki lookup for Cameria's Maul Gavel

### ISSUE THREAD

**Issue by VADemon** [PoE-TradeMacro/POE-TradeMacro#321]
Pressing Ctrl+W on a Cameria's Maul Gavel open's up the wiki page for [Gaul](https://pathofexile.gamepedia.com/Gavel), when it must be [Cameria's Maul](https://pathofexile.gamepedia.com/Cameria%27s_Maul)

Please redirect this to POE-ItemInfo (2.6.01) if it's not an issue within TradeMacro (2.0.9).

Thanks

**Comment by Eruyome** [comment]
Thanks, will take a look at it soon.

**Comment by Eruyome** [comment]
Works for me, granted I use a newer TradeMacro version but there weren't any changes related to this.

**Comment by VADemon** [comment]
I don't know what happened. I have bought this item and tried again: negative, everything is working. However I do have /Gavel page in browser history. Maybe it's some underlying general issue with lookups.

**Comment by VADemon** [comment]
Mystery solved: An unidentified "Cameria's Maul Gavel" is only titled "Gavel" in-game. That's why the lookup of the unidentified CMG opened the wiki page for "Gavel"
