### ISSUE TITLE
Reading Cookie data failed.

### ISSUE THREAD

**Issue by Rippy56** [PoE-TradeMacro/POE-TradeMacro#322]
I checked the FAQ and did everything that was listed there even tho I knew nothing would change since none of those options have changed in the last couple of days (Didn't do scans/defender related stuff - Didn't update Windows - Didn't open Explorer) 
     I get this;
![d83321d8110016967422ff56bba54bc3](https://cloud.githubusercontent.com/assets/27005957/24796437/a8668d88-1b95-11e7-9759-54fffa3675e2.png)
     Then this;
![36fc3dc9bae607f2d8f081ac14c5afef](https://cloud.githubusercontent.com/assets/27005957/24796455/b5e3f36a-1b95-11e7-8dee-cf505a3a37ad.png)
     If I make it try and delete cookies it gives this error;
![8eb3a7808f446c947e19f59149aa20c9](https://cloud.githubusercontent.com/assets/27005957/24796479/c811c92c-1b95-11e7-8463-5c426b11d968.png)
     Given I deleted the cookies manualy afterwards.
     If you'd require any additional info feel free to ask me. It was open in the background since I don't always shut down my pc and when I tried to use it the advanced search options returned no results. I checked the trade.poe site if it had gone down or something but it was fine. I tried restarting the program and this happened. I can click continue and it will act the same way. No results etc. The item info function works, i guessed it was already in the folders or something like that but I don't really know.

**Comment by Eruyome** [comment]
You don't have any issues with cookies, it just seems that may because the error handling it not precise enough. Please make sure to have the latest version and run `resources\tests\WinHttpRequest.ahk` and show me the results.
The cookie error window should only appear when you can't get any connection to poe.trade via WinHttp, this could have 2 reasons at that point, one is that you neeed cookies but poe.trade doesn't require them at the moment. The second is that you have some WinHttp issues. Maybe there are more that I'm not aware of though.

**Comment by Rippy56** [comment]
1.     Type 'help' for a list of commands (no quotes)

2.        21:11:02 7 Nisan 2017 Cuma

3.     ---------------------------------------------------

4.     Download test with url : https://api.github.com/repos/PoE-TradeMacro/PoE-TradeMacro/releases

5.        21:11:03 7 Nisan 2017 Cuma

6.     Testing UrlDownloadToFile: No errors.

7.      Output saved in: C:\Users\Emre\Desktop\POE-TradeMacro\resources\tests\test_temp\urlDownloadToFile1_output.txt

8.     Content Length: 71171

9.        21:11:04 7 Nisan 2017 Cuma

10.    First test downloading to variable using WinHTTP adodb.stream successful. (Catching Errors)

11.    Content Length: 71171

12.       21:11:04 7 Nisan 2017 Cuma

13.    Second test downloading to variable using WinHTTP adodb.stream successful. (Not catching Errors)

14.    Content Length: 71171

15.       21:11:04 7 Nisan 2017 Cuma

16.    -----------------------------------------

17.       21:11:04 7 Nisan 2017 Cuma

18.    ---------------------------------------------------

19.    Download test with url : http://poe.trade

20.       21:11:04 7 Nisan 2017 Cuma

21.    Testing UrlDownloadToFile: No errors.

22.     Output saved in: C:\Users\Emre\Desktop\POE-TradeMacro\resources\tests\test_temp\urlDownloadToFile2_output.txt

23.    Content Length: 5474

24.       21:11:04 7 Nisan 2017 Cuma

25.    First test downloading to variable using WinHTTP adodb.stream successful. (Catching Errors)

26.    Content Length: 5474

27.       21:11:05 7 Nisan 2017 Cuma

28.    Second test downloading to variable using WinHTTP adodb.stream successful. (Not catching Errors)

29.    Content Length: 5474

30.       21:11:05 7 Nisan 2017 Cuma

31.    -----------------------------------------

32.       21:11:05 7 Nisan 2017 Cuma

33.    ---------------------------------------------------

34.    Download test with url : http://poe.trade/search/seridonomosure

35.       21:11:05 7 Nisan 2017 Cuma

36.    Testing UrlDownloadToFile: No errors.

37.     Output saved in: C:\Users\Emre\Desktop\POE-TradeMacro\resources\tests\test_temp\urlDownloadToFile3_output.txt

38.    Content Length: 5474

39.       21:11:05 7 Nisan 2017 Cuma

40.    First test downloading to variable using WinHTTP adodb.stream successful. (Catching Errors)

41.    Content Length: 5474

42.       21:11:05 7 Nisan 2017 Cuma

43.    Second test downloading to variable using WinHTTP adodb.stream successful. (Not catching Errors)

44.    Content Length: 5474

45.       21:11:05 7 Nisan 2017 Cuma

46.    -----------------------------------------
This is the result for the test.

**Comment by Eruyome** [comment]
Looks good, do you get the cookie reading error every time?

**Comment by Rippy56** [comment]
Yes, I've tried launching it more than 20 times. I get this every time. I just thought I should share it, let me know if you find something and I'll do the same.

**Comment by Eruyome** [comment]
I'll get back to this when some other current issues are resolved, shouldn't take too long.

**Comment by buza83** [comment]
Maybe this is due to the fact that poe.trade makes a robot check you or a person. I just have the same problem. If you open poe.trade in the browser, then there is a check on the person.

**Comment by Rippy56** [comment]
No, it wasn't that. I always had that and it still worked at the time. Anyway it seems to be fix now maybe with the update to the script or maybe with something completely different. I'll be closing this issue now. Thanks for everything.

**Comment by Eruyome** [comment]
Ok, good to know, I hope it stays fixed.

**Comment by Rippy56** [comment]
It's back again, kind of a bummer. I thought maybe it was due to me not updating my windows for a while etc but did the update and it changed nothing. Still get the same error. It's saddening.

**Comment by Eruyome** [comment]
I'll close this for now, just reopen it if there still are issues.

**Comment by mub1992** [comment]
Hi, I am getting this issue now as well. Was there anything specific done in getting it resolved?

**Comment by Eruyome** [comment]
Do you also get the script execution error, not only the windwo shwoing you the issue?
Also which v ersion are you using? Stable or beta?

**Comment by mub1992** [comment]
Thank you for the response.. I am unsure what I did but it all of a sudden worked the last time I tried to boot it up and was able to get it updated and functioning. I threw it into a new folder on my desktop even though it says not to and that worked.


________________________________

**Comment by Tycoon75** [comment]
anyone help me. Some time macro work. sometime not work
![screenshot 54](https://user-images.githubusercontent.com/33839128/33029042-cae585e6-ce17-11e7-9d28-01008982dbce.png)

**Comment by mrriuz9** [comment]
i have same issue with @Tycoon75  any body got the fix ?

**Comment by Eruyome** [comment]
https://github.com/PoE-TradeMacro/POE-TradeMacro/issues/672#issuecomment-373228598
Could you read my last comment here and tell me if that has any relation to your issue? And maybe use the linked version and show me the mentioned temp\test.txt

Also, does it sometimes work and sometimes not, like Tycoon75 mentioned?

**Comment by mrriuz9** [comment]
mine issue i always can like check the price ctrl d , ctrl w . only the hotkey for poetrade that cant intact with .strange the others i thinks its fine .and im using hotspot cellular is that affect the scripting? wait for ur respond . thanks
