### ISSUE TITLE
can't open macro

### ISSUE THREAD

**Issue by virus1155** [PoE-TradeMacro/POE-TradeMacro#323]
i have some problems with macro, im using ahk, and when im trying to open run_trade macro, lastest relase, im gettin stuff like this https://gyazo.com/cdc53a2eef9fa0f3ab7355774992c62f is there any chance to open it somehow? Feelsbadman

**Comment by dein0s** [comment]
Well, at first you can unpack contents of the archive into a folder with shorter path than is it right now.

**Comment by Eruyome** [comment]
It certainly looks like you're trying to run the macro from inside the zip archive, this won't work. I'll simply close this ticket because I've seen your issue before and it was always resolved by properly extracting the script. If it still won't work just report back.
