### ISSUE TITLE
"No admin evaluation" is missing

### ISSUE THREAD

**Issue by lerby** [PoE-TradeMacro/POE-TradeMacro#327]
Is it on purpose? Why this feature was removed?

**Comment by dein0s** [comment]
It was changed, not removed.
Check https://github.com/POE-TradeMacro/POE-TradeMacro/wiki/FAQ#12-where-is-the-no-admin-elevation-run-script and/or https://github.com/PoE-TradeMacro/POE-TradeMacro/issues/314.
