### ISSUE TITLE
Still crashing/freezing when searching Currency

### ISSUE THREAD

**Issue by swatzlol** [PoE-TradeMacro/POE-TradeMacro#328]
I can search gear just fine. However searching currency, whether its in currency tab or in my inventory. It just sits there spinning "Running Search..."

**Comment by BassMuffinFive** [comment]
Also. every time I price check a rampage leaguestone of miracles, it crashes the program,

**Comment by Eruyome** [comment]
poe.trades html was changed again.... so it broke again

**Comment by Eruyome** [comment]
Fixed now.

**Comment by BassMuffinFive** [comment]
Thank you!
