### ISSUE TITLE
Memory leak when opening browser for search fails

### ISSUE THREAD

**Issue by Xezz** [PoE-TradeMacro/POE-TradeMacro#329]
Not sure how to reproduce it, but the search (by pressing CTRL+Q on an item) gets stuck, then it appears to create a memory leak.

System: win 7
Browser Chrome ( around 20 -30 tabs open on two windows)
Version: 2.0.10
Steam POE windowed fullscreen
Other AHK Macros: Lutbot macro
YOLO Mouse

Longer report:
I've had it before that a search failed and the tooltip for the search got basically stuck. But usually I recovered at some point.

This time, I had the search not opening (tried around 2-3 times) and when I tabbed I still had the tooltip showing.
After opening the task manager, AHK for PoeTradeMacro was at 290MB and rising. When I killed the process YOLO Mouse also stopped working (thats why I mention it in the system info).
After restarting POE, YOLO Mouse and TradeMacro, TradeMacro uses 29MB so a tenth of what it used while "leaking"

**Comment by Xezz** [comment]
I down graded to the backup version and it seems to work fine.
Had some more crashes until then, which lead me to downgrade

**Comment by Eruyome** [comment]
Is this related to the broken currency search that freezes/crashes the macro? While this ws fixed it's broken again because poe.trades html changed again.

**Comment by Eruyome** [comment]
Check the new version again.

**Comment by Xezz** [comment]
Seems to work atm, will report back if it hangs again on a search

**Comment by Eruyome** [comment]
The script tried to get and use values from an object, using non-existing keys. This caused the script to crash/freeze. Up until a few days poe.trade used the actual ingame currency names as html tooltip text (which I parsed) to get all available currencies for the currency search. Now that changed to some manually selected names and abbreviations ("gcp", chrome") so I had to map the poe.trade names to the ingame names. While this is prone to errors when these names change again it won't freeze anymore because of it, the implementation wasn't the best.

So I highly believe this is what caused your issues.

**Comment by Eruyome** [comment]
Can this be considered fixed or still an issue?

**Comment by Mjestic** [comment]
I still had this Problem today really love your  tool would be nice if u could fix this issue ... not sure if its the same problem tho programm worked and 6 hours later after the poe patch it crashed after trying to launch after a couple tries it finaly launched but then crashed on use ! just started using it so if thats normal after a Patch ignore what i said

**Comment by Eruyome** [comment]
So, you had the macro running, installed a Path of Exile patch and the macro crashed? Then repeatedly crashed on startup?
That's certainly not normal, but it doesn't look like some memory issue when it's crashing on startup. How does that crash look like? Some windows popup/error telling you it stopped working?

**Comment by Mjestic** [comment]
It just stops working and says "no response" and then all i can do is wait forever and it might work or i just shut it down.

**Comment by Eruyome** [comment]
I don't think that's a memory issue. What ahk version do you have installed, 32 or 64bit? You could try removing ahk and installing it again, testing both 32 and 64bit. Could be unrelated but I don't think it's an issue with the script per se.

**Comment by Mjestic** [comment]
Idk maybe it was on my end or just the poe trade servers yesterday after the patch works fine now again thanks for this awesome Tool have a nice day :)

**Comment by Eruyome** [comment]
Then I'll close this for now, if there are further (or still) issues related to this topic just say something.
