### ISSUE TITLE
Ctrl-D skips first item

### ISSUE THREAD

**Issue by aDuke1** [PoE-TradeMacro/POE-TradeMacro#332]
To reproduce:
- do a Ctrl-d
- do a Ctrl-q for the same item
- compare the results

Usually not a biggie if there are many items for sale. But if there are just 1-2, that can make quite a difference ...

**Comment by aDuke1** [comment]
I guess I found it :)
Around line 12340, function TradeFunc_ParseHtml(), there is this loop:
`While A_Index < NoOfItemsToShow {`
It searches for
`item-container-" A_Index`
A_Index is implicitly initialized to 1, whereas the first item is in **item-container-0**.
==> so if you do something like idx := A_Index-1 it should do the trick.

**Comment by Eruyome** [comment]
I believe I had that fixed some time ago... will do it, consider this fixed and closed.

**Comment by aDuke1** [comment]
Sorry, I was on 2.0.0 :(
Fix confirmed.

**Comment by Eruyome** [comment]
Not sure about that, could be that I included it as "Minor fix."
