### ISSUE TITLE
Buggy interactions 

### ISSUE THREAD

**Issue by theBroccolized** [PoE-TradeMacro/POE-TradeMacro#333]
For a few days I've had problems with the overlay of searching for similar items via ctrl d, and looking at the tiers of items via ctrl c. At times nothing will happen, others the window for each will pop up for a split second and then disappear. I can sometimes force it to work when i ctrl alt D to bring up the advanced search. When i switch back to game, and try to ctrl d or c, it will pop up then disappear, and i can do that a few times and it will eventually come up. Its almost like it is going behind the game screen, or the game is forcing itself on top. Love the program, thanks!

**Comment by DogeisReady** [comment]
Yea same problem for me :/

**Comment by Eruyome** [comment]
There are some similiar issues reported already, please look at this here for example (I linked some specific comment) https://github.com/PoE-TradeMacro/POE-TradeMacro/issues/326#issuecomment-293818103

**Comment by Eruyome** [comment]
I'll close this for now, just reopen it if there are still issues.
Also take note of this here https://github.com/PoE-TradeMacro/POE-TradeMacro/issues/326#issuecomment-301263424
