### ISSUE TITLE
Another trouble with Ctrl+w and Ctrl+q

### ISSUE THREAD

**Issue by OneSickBasta** [PoE-TradeMacro/POE-TradeMacro#334]
Can someone help me to explain, why crtl+q and crtl+w doesnt work?
![clip2net_170413032513](https://cloud.githubusercontent.com/assets/26852916/24984818/024d9ce6-2001-11e7-8928-dde481e9bea1.png)

**Comment by OneSickBasta** [comment]
Specifically: 
The specified file is not associated with any application to perform this operation translation

**Comment by dein0s** [comment]
Check #316 for possible solutions.

**Comment by OneSickBasta** [comment]
It was my thread,so the trouble is came back

**Comment by Eruyome** [comment]
So, have you any program associated to html files?

**Comment by Eruyome** [comment]
I'll close this for now, just reopen it if there are still issues.
