### ISSUE TITLE
"Couldn't find the chaos equiv. value for 1 item(s). Please report this"

### ISSUE THREAD

**Issue by kittax** [PoE-TradeMacro/POE-TradeMacro#336]
http://i.imgur.com/t9oi0jq.png

v. 2.0.11

Not sure of what else to report

Cheers

**Comment by Nauze** [comment]
![image](https://cloud.githubusercontent.com/assets/27470805/25078134/a3083e36-2306-11e7-829f-6e649f8af4ff.png)
 same here, couldn't price chisels

**Comment by Eruyome** [comment]
Maybe I should improve that tooltip, I do need to know what currency is listed as price for these reports. Will take a look into this.

**Comment by Eruyome** [comment]
Chisels should work again (currency search), I'm not sure about the default item search though.
