### ISSUE TITLE
hotkeys with alt is not working

### ISSUE THREAD

**Issue by JumpAttacker** [PoE-TradeMacro/POE-TradeMacro#337]
ctrl+d is working
but ctrl+alt+d is not

https://vgy.me/w62022.png

**Comment by Eruyome** [comment]
I assume you're not using english (for example) as keyboard language but maybe russian? If not try switching to english. I know there are some issues with certain languages that I couldn't fix so far.

**Comment by Eruyome** [comment]
I'll close this, if you still have this issue please reopen it.

**Comment by JumpAttacker** [comment]
Yes, I just reset the settings and it fixed the error, ty anyway
