### ISSUE TITLE
Currency again.

### ISSUE THREAD

**Issue by funi9** [PoE-TradeMacro/POE-TradeMacro#339]
Currency search isn't working properly again. Probably aware of the issue i just haven't seen any topics created. Cheers

**Comment by Svampen** [comment]
There is a pull request waiting to fix this issue.
https://github.com/PoE-TradeMacro/POE-TradeMacro/pull/338

**Comment by Eruyome** [comment]
Had some hardware issues so I didn't check in for a week or so. Have to catch up to some issues, will fix it soon.
