### ISSUE TITLE
Ctrl + D open debug print arry

### ISSUE THREAD

**Issue by Manaio** [PoE-TradeMacro/POE-TradeMacro#343]
Hi everybody,
as title i can't use macro ctrl + d because the program open a window "Debug Print Array"
![poe](https://cloud.githubusercontent.com/assets/27745172/25155761/0c3b8e80-2497-11e7-89a3-de4efc1600bf.JPG)
How i can resolve?
Thanks for the help

**Comment by Eruyome** [comment]
I'm a bit stumped. That's the second report of this issue but when I download the latest version and run it I don't get this window. I know my local code doesn't use the function `DebugPrintArray()` anywhere (that's where this window comes from).

**Comment by potato404** [comment]
im also having this problem i did a clean install and still getting this

**Comment by Eruyome** [comment]
Please open `POE-TradeMacro\resources\ahk\` and search all .ahk files for `debugprintarray`, then show me the code block where this is found.

**Comment by potato404** [comment]
im using the fallback.exe and the only search result for debugprintarray was a line that had #include

**Comment by Eruyome** [comment]
Tested it on all kinds of items, try the ahk run script, maybe I forgot to remove that line before compiling the exe.

**Comment by potato404** [comment]
ok i ran the ahk instead of fallback.exe and its back to normal

**Comment by Manaio** [comment]
Same..resolved running the ahk file

**Comment by KGabQr** [comment]
same, no work. sad.
Please new update fix. thx.

**Comment by Eruyome** [comment]
Fixed now.
