### ISSUE TITLE
#include path

### ISSUE THREAD

**Issue by aDuke1** [PoE-TradeMacro/POE-TradeMacro#344]
I have several files which I #include via additionalMacros.
But where am I supposed to place them ??
- in the user dir ie. users/docs/mygames/poeTrade they are not found
- in the TradeMacro dir they are backed up and removed from the dir on version update

**Comment by Eruyome** [comment]
Why do you include those files? Just to start some macros along with TradeMacro?

**Comment by aRTy42** [comment]
If you use the full path for the users/docs/mygames/poeTrade folder in the include command it should work.

**Comment by aDuke1** [comment]
Why ? Some of those macros re-use internal trade funcs
AdditionMacros ? Those includes sum up to some 4k lines ...
=> I guess I'll go with the fullPath
thx guys :)
