### ISSUE TITLE
The macro window, shows behind poe window.

### ISSUE THREAD

**Issue by camelo1994** [PoE-TradeMacro/POE-TradeMacro#348]
title. maybe im doing something wrong?

v2.1.0-windowed mode-w10-dx11

**Comment by dein0s** [comment]
Sounds similar to #311

**Comment by Eruyome** [comment]
I'll close this for now, just reopen it if there are still issues.
Also take note of this https://github.com/PoE-TradeMacro/POE-TradeMacro/issues/326#issuecomment-301263424
