### ISSUE TITLE
Kicking yourself from group

### ISSUE THREAD

**Issue by Jellybe4n** [PoE-TradeMacro/POE-TradeMacro#349]
How do we set this up?
In the additional macro script it shows F4::SendInput {Enter}/kick kick_own_char{Enter}
Do we do anything to that?

**Comment by dein0s** [comment]
This only works for the specified character name and only if you rights to perform kick action (group leader).
So, it'll look like `F4::SendInput {Enter}/kick MyImbaSparkerr{Enter}` for example.
And yes, you need to edit this everytime you switch characters.

**Comment by aRTy42** [comment]
Just saw this while looking for another issue. It is not that important, but you can kick yourself without being the group leader. Otherwise the function would be not that useful most of the time, so we wouldn't have added it.
