### ISSUE TITLE
Error at line 11803

### ISSUE THREAD

**Issue by Jellybe4n** [PoE-TradeMacro/POE-TradeMacro#350]
I was messing around with additional macro script, and then this started showing up whenever I launch the script. I tried deleting the trademacro folder and then reinstalling it, but it still says this. Anyone know how to fix? Not sure if the two are connected.
<img width="275" alt="screenshot_1" src="https://cloud.githubusercontent.com/assets/27900911/25308383/c6bbb28a-2767-11e7-9251-9bc731373ed2.png">

**Comment by Eruyome** [comment]
AdditionalMacros is located in the user folder, not in the TradeMacro folder. If you messed tha file up it won't help removing TradeMacro.
