### ISSUE TITLE
HighlightItems: Clipboard emptied on CTRL+F

### ISSUE THREAD

**Issue by lemasato** [PoE-TradeMacro/POE-TradeMacro#352]
I know this is a really(really really) useful feature but...
It's causing an issue with my tool.  
Basically, upon receiving a new poe.trade whisper the item is put in the clipboard to make it easier to find it in the stash. But due to this new feature, when pressing CTRL+F (to focus the IG search), the clipboard is emptied.  

If I get it right, this new feature uses CTRL+C to parse the item's infos.
My fix for this would be to revert (or leave untouched) the clipboard if the parsing failed.

**Comment by Eruyome** [comment]
Good idea, will implement it.

**Comment by Eruyome** [comment]
I believe I can always revert the clipboard OR oly revert it upon failing to parse an Item. Does this matter in any way since reverting it would cause a clipboard change? Maybe it doesn't matter for your tool but for others?

**Comment by lemasato** [comment]
I don't see how it would matter for any other tool tbh.  
Unless it's based on clipboard change detection. But even then, it would simply require storing the old clipboard content in a variable, then upon detecting a clipboard change compare it with the current content. So yeah. Unless an unknown tool is based on clipboard change, it doesn't matter. (?)

**Comment by Eruyome** [comment]
Should work, you can test it if you want but there's probably no need to. Implemented on the ItemInfo dev branch https://github.com/aRTy42/POE-ItemInfo/archive/devEru.zip

**Comment by lemasato** [comment]
Tested. Results: 

- Works when hovering an item.
- Still clears the clipboard when no item is hovered.

**Comment by Eruyome** [comment]
Well, it seems I messed that up again after it worked. :P

**Comment by Eruyome** [comment]
Yeah, really dumb, I tested something.... Works now. Please close the issue when you're satisfied ;-)

**Comment by lemasato** [comment]
Yep, works just fine!
