### ISSUE TITLE
adv search not available for this item ? (all rare quivers)

### ISSUE THREAD

**Issue by binbinhfr** [PoE-TradeMacro/POE-TradeMacro#355]
I have this error message on a classic yellow quiver named "havoc nails".
What is the problem with this item ?

**Comment by binbinhfr** [comment]
same thing with quiver "blight arrow" ("Spike-Point Arrow Quiver")

**Comment by Eruyome** [comment]
Please post the entire item, press ctrl +c and then copy your clipboard contents here.

**Comment by binbinhfr** [comment]
arf sorry, the item has been sold.
newt one with the same problem, i will copy it here.

**Comment by binbinhfr** [comment]
another example of "adv search not available for this item"  : 

Rarity: Rare
Foe Spike
Spike-Point Arrow Quiver
--------
Requirements:
Level: 45
--------
Item Level: 75
--------
24% increased Global Critical Strike Chance
--------
16% increased Elemental Damage with Weapons
+13 to Dexterity
+72 to Accuracy Rating
+21 to maximum Life

**Comment by binbinhfr** [comment]
infact I have the same error message on any rare quiver.

**Comment by Eruyome** [comment]
Finally had some time to look into it. Really small error. This should have been an issue for months, it seems you're the only one using the advanced search for quivers :p 
I'll make a new release soon.

**Comment by binbinhfr** [comment]
thanks guy !  :-)
