### ISSUE TITLE
missing mod "+ Mana gained for each Enemy hit by Attacks"

### ISSUE THREAD

**Issue by binbinhfr** [PoE-TradeMacro/POE-TradeMacro#356]
hi, one mod "+ Mana gained for each Enemy hit by Attacks" seems to be missing and return a red  exclamation point ;

not to be confused with "Mana gained for each Enemy hit by YOUR Attacks"

example 
--------
Rarity: Rare
Woe Hunger
Twin Claw
--------
Claw
Quality: +11% (augmented)
Physical Damage: 23-71 (augmented)
Elemental Damage: 26-57 (augmented)
Critical Strike Chance: 6.30%
Attacks per Second: 1.59 (augmented)
Weapon Range: 9
--------
Requirements:
Level: 57
Dex: 103 (unmet)
Int: 103
--------
Sockets: R-B 
--------
Item Level: 76
--------
+28 Life gained for each Enemy hit by Attacks
+10 Mana gained for each Enemy hit by Attacks
--------
Adds 26 to 57 Cold Damage
6% increased Attack Speed
+39 to maximum Mana
0.3% of Physical Attack Damage Leeched as Life

**Comment by Eruyome** [comment]
As stated on the overlay, it doesn't exist on poe.trade and can't be used. That's nothing that I can fix.

**Comment by binbinhfr** [comment]
ok, so i will try to contact trhe guys from poe.trade
