### ISSUE TITLE
Just started being seen as a trojan today

### ISSUE THREAD

**Issue by Vakal** [PoE-TradeMacro/POE-TradeMacro#357]
Been using this for a good while now, and just this morning as I started trademacro, AVG flags it and gets me all scared about it being a trojan. Anyone else getting this, or know why it just started out of nowhere?

**Comment by Eruyome** [comment]
No idea why, is it flagging the ahk script or the fallback exe? Anyway, I don't think I can do much about it except assuring you that there's no need to worry.

**Comment by aRTy42** [comment]
A few weeks ago Avast virus-containered autohotkey, after an Avast update. I think in that case it didn't like that the run script called the updater part and falsely flagged that.
