### ISSUE TITLE
Direct proxy

### ISSUE THREAD

**Issue by Notnx** [PoE-TradeMacro/POE-TradeMacro#360]
[urlDownloadToFile1_output.txt](https://github.com/PoE-TradeMacro/POE-TradeMacro/files/994284/urlDownloadToFile1_output.txt)

WinHttpRequest to poe trade failed!The correct winhttp setting is:Direct acces(no proxy)''.
Two options appear, one is reset proxy which results in a loop of the same error appearing again and again, the other is to close the window which results in "No poe.trade connection possible, exiting script".

WinHTTPrequest test
```
1.     Type 'help' for a list of commands (no quotes)

2.        23:02:12 11 мая 2017 г.

3.     ---------------------------------------------------

4.     Download test with url : https://api.github.com/repos/PoE-TradeMacro/PoE-TradeMacro/releases

5.        23:02:13 11 мая 2017 г.

6.     Testing UrlDownloadToFile: No errors.

7.      Output saved in: D:\Chrome Downloads\POE-TradeMacro-2.1.1 (1)\POE-TradeMacro-2.1.1\resources\tests\test_temp\urlDownloadToFile1_output.txt

8.     Content Length: 78636

9.        23:02:14 11 мая 2017 г.

10.    Exception thrown!

11.    

12.    what: :=

13.    file: D:\Chrome Downloads\POE-TradeMacro-2.1.1 (1)\POE-TradeMacro-2.1.1\resources\tests\Test_WinHTTPRequest.ahk

14.    line: 42

15.    message: 0x80040154 - Класс не зарегистрирован

16.    extra: 

17.       23:02:16 11 мая 2017 г.

18.    Second test downloading to variable using WinHTTP adodb.stream returned an empty string.
```

**Comment by Eruyome** [comment]
https://www.google.de/search?q=winhttp+class+not+registered&oq=winhttp+class+not+registered&aqs=chrome..69i57.7660j0j7&sourceid=chrome&ie=UTF-8#q=adodb+class+not+registered

Try reading this, WinHttp and an adodb stream are used and I believe the adodb class is not registered. Please see if you can manage to fix that by reading it up. I can't say I could simply give you a step by step solution.

**Comment by Notnx** [comment]
i dont even have any idea what to look for oO
what does it even mean "adodb class is not registered"? some dll file ?

**Comment by Notnx** [comment]
all i see in search bunch of ppl with Visual Studio problems, im not even programmer )

**Comment by Notnx** [comment]
well "gg bb" i guess

**Comment by Eruyome** [comment]
Glad to hear that, I know that I asked a bit much since I didn't know your background but if it really was a missing dll it would have been hard for me to help you without you trying to read up on the issue a bit and trying some things ;-)
