### ISSUE TITLE
Been trying to test how Advanced Price Search works but it doesn't

### ISSUE THREAD

**Issue by zakt4n** [PoE-TradeMacro/POE-TradeMacro#362]
So I've been trying to understand how the script/code works and testing some stuff but when I try to search for unique items with a specific roll ranges accordingly to what I want the macro fails to gather the info of those items within the specified range. Instead, it's ignoring the specified ranges and showing the cheapest overall for the item.

Ex: I tested with astramentis and I selected rolls between 97-100 (explicit) and it shows me the cheapest as the first one in poe.trade which is 87. Tested with devoto's devotion.  Same kind of result.

**Comment by Eruyome** [comment]
Is that happening for every unique item / any mod or just for specific items / specific mods?

I just used the advanced search on a devotos (first with the armour roll, then with the dex roll) and everything works as expected. I only get results with rolls between what values I have specified.

Can you further elaborate on your issue? Is there something that I misunderstood?

**Comment by zakt4n** [comment]
Well, i tested only with astra and devoto's and both didn't work, i changed all the mods to the values i wanted (in devoto's case, cuz in astra there is only 1) i can try testing with other items if necessary.

**Comment by aRTy42** [comment]
Did you use the checkboxes to mark which mods to use? If you just change the values, nothing will be selected.

**Comment by Eruyome** [comment]
@zakt4n So, do you still have any issue? I'm not sure since you didn't answer aRT42y's question.

**Comment by Eruyome** [comment]
I'll close this for now, just reopen it if there are still issues.
