### ISSUE TITLE
[Request] Report Map Mod Warnings in party chat.

### ISSUE THREAD

**Issue by Nightblade** [PoE-TradeMacro/POE-TradeMacro#368]
To let your group know about potentially dangerous mods when doing fast map runs.

Maybe just put the info into the clipboard so the user can choose when and where to report?

**Comment by Eruyome** [comment]
Arty42 and I decided not to implement this. Putting this information into the clipboard requires additional options to be handled since this interferes with other parts of the script.
Aside from that we think it's unnecessary. For now I'll mark it as "wont fix" instead of simply closing it.
