### ISSUE TITLE
error while running makro

### ISSUE THREAD

**Issue by morgoroth** [PoE-TradeMacro/POE-TradeMacro#370]
---------------------------
_TradeMacroMain.ahk
---------------------------
Error:  Too many parameters passed to function.

Specifically: HighlightItems(false,true,false)

	Line#
	11884: }
	11885: }
	11903: Return
	11903: TogglePOEItemScript()  
	11903: Return
	11904: WinMinimize,A
	11904: Return
--->	11906: HighlightItems(false,true,false)  
	11906: Return
	11911: HighlightItems(true,true,false)  
	11911: Return
	11916: SendInput,{Enter}/hideout{Enter}
	11916: Return
	11917: SendInput,{Right}
	11917: Return

The program will exit.
---------------------------
OK   
---------------------------

**Comment by Eruyome** [comment]
Please delete your AdditionalMacros.txt in the user folder. It seems to be an old one, the new one has one function argument less.
