### ISSUE TITLE
PoeTradeMacro is extremely slow

### ISSUE THREAD

**Issue by zackdave** [PoE-TradeMacro/POE-TradeMacro#374]
Hi,

For some reason the macro started to load/initialize very slowly. I am using w10 and v2.3.2 macro. Some W10 updates were installed yesterday but no other changes were initiated to my system. Router was resetted to close out connection issue. Ctrl+D and Ctrl+Q functions takes minutes and script initialize also. Ctrl+C works fine. Latest AHK core is installed.
winhttprequest runs without errors: 
[urlDownloadToFile1_output.txt](https://github.com/PoE-TradeMacro/POE-TradeMacro/files/1083117/urlDownloadToFile1_output.txt)

Could you please help me solve the problem?

Thanks a lot,

UPDATE: It seems the problem was with this w10 update KB4022725. After removed and reinstalled everything is working fine.

**Comment by Eruyome** [comment]
Ok, good to know. In general such issues are related to a slow internet connection though.
