### ISSUE TITLE
[Bug/Request] Allow searching by just name in Advanced Search

### ISSUE THREAD

**Issue by Ayitaka** [PoE-TradeMacro/POE-TradeMacro#376]
Currently when you search for a leaguestone using the Advanced Search it will automatically search poetrade using all the mods on the leaguestone even if you have intentionally left them all unselected. It would be nice if there was some way to only search by name. 

Having it either obey not selecting any mods or adding a checkbox for 'select none' to search without mods would be useful. (Or maybe an entry in the script's Options for 'No Mods Selected': Search with no mods or search with normal mods)

League is nearly over so its not gonna be an issue much longer, but in the future items may be added to the game again where the best way to search (sometimes) is by item name. 

Thank you for listening and for the script!

**Comment by Eruyome** [comment]
In that cas you could just use the default search (ctrl + d). In most cases it simply searches by item name. Or if you just want to open it on poe.trade use ctrl + q. Aside from that since leaguestones can only be magic I believe that all stones with the same name also have the same mods.
