### ISSUE TITLE
Mercury Trade conflict

### ISSUE THREAD

**Issue by garralab** [PoE-TradeMacro/POE-TradeMacro#380]
Hi,
since version 2.2.0 (my previous one was 2.1.1) if I have POE-TradeMacro active no chat command from Mercury Trade will work (99% of the time actually). I initially blamed it on them and opened an issue on their repository, but I'm 100% sure the problem is here. If I run 2.1.1 everything works fine. From 2.2.0 onward Mercury Trade can't send messages or invite/trade/kick other pgs. If I stop POE-TradeMacro all fine again. 
I really hope I don't have to choose between these two awesome programs because it would be a really hard choice.

thanks and kutvgw

**Comment by Eruyome** [comment]
For reference https://github.com/Exslims/MercuryTrade/issues/90#issuecomment-310822096
