### ISSUE TITLE
Request to poe.trade contains empty params and gets CloudFlare error

### ISSUE THREAD

**Issue by nadav-shemer** [PoE-TradeMacro/POE-TradeMacro#382]
When using the "Advanced Search" dialog to open poe.trade, the request URL is too long (or something) which causes CloudFlare to deny it (I get "Error 502 [...] Bad gateway").
I found that this is the cause by removing some of the empty arguments ('&dps_min=&...') and then the same request worked.
I tested a quick and ugly workaround by making entire sections of the URL optional if the arguments there are empty (in ToPayload()):
```
		p := "league=" this.league "&type=" this.xtype "&base=" this.xbase "&name=" this.name
		If ((StrLen(this.dmg_min) > 0) or (StrLen(this.dmg_max) > 0) or (StrLen(this.aps_min) > 0) or (StrLen(this.aps_max) > 0)) {
			p .= "&dmg_min=" this.dmg_min "&dmg_max=" this.dmg_max "&aps_min=" this.aps_min "&aps_max=" this.aps_max 
		}
		If ((StrLen(this.crit_min) > 0) or (StrLen(this.crit_max) > 0) or (StrLen(this.dps_min) > 0) or (StrLen(this.dps_max) > 0) or (StrLen(this.edps_min) > 0) or (StrLen(this.edps_max) > 0) or (StrLen(this.pdps_min) > 0)) {
			p .= "&crit_min=" this.crit_min "&crit_max=" this.crit_max "&dps_min=" this.dps_min "&dps_max=" this.dps_max "&edps_min=" this.edps_min "&edps_max=" this.edps_max "&pdps_min=" this.pdps_min 
		}
		If ((StrLen(this.pdps_max) > 0) or (StrLen(this.armour_min) > 0) or (StrLen(this.armour_max) > 0) or (StrLen(this.evasion_min) > 0) or (StrLen(this.evasion_max) > 0) or (StrLen(this.shield_min) > 0)) {
			p .= "&pdps_max=" this.pdps_max "&armour_min=" this.armour_min "&armour_max=" this.armour_max "&evasion_min=" this.evasion_min "&evasion_max=" this.evasion_max "&shield_min=" this.shield_min 
		}
```

Now the same dialog opens a correct poe.trade search instead of a CloudFlare error

**Comment by Eruyome** [comment]
Can you give me an example of a search (the item information) that failed for you? I never had such an issue. Since I was lazy I tried to simply remove all empty arguments but this failed in a few cases, some of them seem to be required, at least in combination with others.

**Comment by nadav-shemer** [comment]
Yes, this string (produces by the macro) causes a CloudFlare error here:
```
http://poe.trade/search?league=Legacy&type=&base=Gladius&name=Scaeva&crit_min=&crit_max=&dps_min=&dps_max=&edps_min=&edps_max=&pdps_min=&pdps_max=&armour_min=&armour_max=&evasion_min=&evasion_max=&shield_min=&shield_max=&block_min=&block_max=&sockets_min=&sockets_max=&link_min=&link_max=&sockets_r=&sockets_g=&sockets_b=&sockets_w=&linked_r=&linked_g=&linked_b=&linked_w=&rlevel_min=&rlevel_max=&rstr_min=&rstr_max=&rdex_min=&rdex_max=&rint_min=&rint_max=&mod_name=Adds%20%23%20to%20%23%20Physical%20Damage&mod_min=94&mod_max=&mod_name=%23%25%20increased%20Critical%20Strike%20Chance&mod_min=17&mod_max=&group_type=And&group_min=&group_max=&group_count=2&q_min=&q_max=&level_min=&level_max=&ilvl_min=&ilvl_max=&rarity=unique&seller=&thread=&identified=&corrupted=0&online=x&has_buyout=&altart=&capquality=x&buyout_min=&buyout_max=&buyout_currency=&crafted=&enchanted=
```

Have you tried the code snippet I quoted?
I'd like to get something upstream so I won't have to maintain a local fork

**Comment by Eruyome** [comment]
Haven't tried anything yet but if this can be fixed (using your solution or something similiar) without any other issues then it will be in the next release. So having a new release should invalidate your need to use some local copy that you edited. I will take a look at it soon.

**Comment by Eruyome** [comment]
Made some changes to the devEru branch, here's a pull request showing all changes in comparison to the master. https://github.com/PoE-TradeMacro/POE-TradeMacro/pull/383/files

Now all empty arguments should be removed, aside from necessary ones and everyhting should be correctly URI encoded (even values that shouldn't be something else than simple numbers). Please test it thoroughly, doing all kinds of different searches.

**Comment by nadav-shemer** [comment]
Thanks!
It works for some searches, but I have managed to find a problem, where the request does go through but poe.trade (with the shortened URL) gives an error (Internal Server Error)

I don't know how to wrestle the original request from chrome. But I know how to reproduce it. It happens when a mod is searched with a minimum and no maximum, or a maximum and no minimum
It seems to occur with every mod (but not energy shield or dps or other non-mod attribute)

Gotta go to work now. Thanks for the quick response! I'll be available later

**Comment by Eruyome** [comment]
Ok, will take a look at it later, shouldn't be hard to fix.

**Comment by Eruyome** [comment]
Well, already fixed it. Hope there are no other issues now. Don't have the time to make extensive tests though.

**Comment by nadav-shemer** [comment]
Thanks! Everything I tried with mods works perfectly (and every reasonable search works now).
There's a similar oddity with pdsp/edps/ES/armor/(etc?): If I fill in 'min' or min&max, it works. But if I only fill in 'max', the property is ignored

**Comment by nadav-shemer** [comment]
Oh, and leaguestone searching broke :)
Sorry, I forgot to test that. Have no idea what's broken about it, though

**Comment by Eruyome** [comment]
Those mentioned issues are fixed. Are there any searches you haven't tested yet?

**Comment by nadav-shemer** [comment]
Seems like everything works.
I don't know what I haven't tested :) I didn't miss leaguestones because of laziness, but because I didn't think of it.
I think I covered everything now. I tested mods with armor and weapons, dps,es,etc. (non-mod attributes) (min, max and both), flasks, gems, leaguestones, currency, essences, div cards

**Comment by Eruyome** [comment]
Also tested a few things, can't think of something that still needs any testing.

**Comment by nadav-shemer** [comment]
I'm sorry, the problem seems to have gotten worse (something must have changed with cloudflare again) - only the shortest requests go through. I tried playing with the requests' URL but I can't get anything usable to work.
I reverted back to 2.3.2 and everything works there.
(2.3.2 used POST and 2.3.3 uses GET?)
(note that this didn't start with 2.3.3, nor with 2.3.4 - everything was fine just a couple of days before I opened with ticket. Something must have changed at the cloudflare end)

I feel like I wasted your time on a goose chase and I'm sorry for that.

**Comment by Eruyome** [comment]
In general the changes made were good and could have been made sooner, but I was just too lazy to do that. I can't simply revert back to using POST requests though because that's the only working solution for some people where cloudflare gives a captcha challenge. Maybe an option to choose between POST and GET requests would be a solution but I find it pretty weird whats happening to you.

**Comment by nadav-shemer** [comment]
I concur on all fronts - it's good that the GET requests are now shorter,
it'll be good to have a config option to revert to using POST, and what's
happening with cloudflare is weird.
I'm at work right now. Tested the URL from the beginning of this thread,
and it works over here, so it's not even a region issue.
Perhaps the problem was with my browser all along? I'll try and clear
cookies when I get home


On 9 Jul 2017 2:13 p.m., "Eruyome" <notifications@github.com> wrote:

In general the changes made were good and could have been made sooner, but
I was just too lazy to do that. I can't simply revert back to using POST
requests though because that's the only working solution for some people
where cloudflare gives a captcha challenge. Maybe an option to choose
between POST and GET requests would be a solution but I find it pretty
weird whats happening to you.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/PoE-TradeMacro/POE-TradeMacro/issues/382#issuecomment-313913656>,
or mute the thread

**Comment by nadav-shemer** [comment]
Whelp. I cleared poe.trade's cookies in chrome and everything works (in all three versions - 2.3.2, 2.3.4, and the branch)

**Comment by Eruyome** [comment]
Huh, good to know. It Seems I can close this.
