### ISSUE TITLE
Macro Issue

### ISSUE THREAD

**Issue by twistedbam** [PoE-TradeMacro/POE-TradeMacro#384]
Hey, I`ve been using the macro for quite some while now, but lately i cannot start it! It freezes during initialization, and it won`t open, no matter how long I wait! I`ve deleted the files the macro creates, but even after that, I am not unable to open it! Any suggestions?

**Comment by Eruyome** [comment]
Updated AHK? Maybe even uninstalled and reinstalled it?

**Comment by twistedbam** [comment]
Tried that, it s not working! It`s stopping at Initializing script... ! I have no idea what is causing it! I can run other macros - like logout and stuff like that!

**Comment by Eruyome** [comment]
Could you try some older versions? Even going back to 2.x.x versions. I would be surprised if it's related to any specific versions but who knows.

**Comment by Eruyome** [comment]
I'll close this until I get some more feedback.
