### ISSUE TITLE
Reduced Max Charge Leaguestones

### ISSUE THREAD

**Issue by JaredKreft** [PoE-TradeMacro/POE-TradeMacro#385]
Squeaking Talisman Leaguestone and similar leaguestones don't work correctly in the mod. 

There are several of these listed in Legacy on POE.Trade
Doing a macro lookup shows none.

Reason: I did a websearch using the macro and found out that it is requiring the "Number of current charges" mod to exactly match its fields, but is not setting a min or a max for it. Therefore, no stone can match this.

It isn't having the same problem for stones that have the usual 5 charges.

I think it would be solved by properly setting the current charges required to the max charges of the item, if you can pull that; but if not, perhaps dropping that as a requirement?

**Comment by Eruyome** [comment]
I can think of something, but the main reason of forcing the current value is that the actual charges on the stone can make a huge price difference. So seeing some short result overview and average/median prices calculated with these mixed results can give an extremely skewed price overview.

**Comment by JaredKreft** [comment]
This stone has 1 max charge. The Squeaking prefix carries a mod of -4 max charges, so the stone is 1/1. The fields on the web search have Min/max on current charges left blank, and "must match exactly", which is causing the problem.

The issue isn't about a stone that is partially charged, it's about one whose max charges are 1.

**Comment by Eruyome** [comment]
Ok, will take a look at it. If you still have one of thise lying around please post the item information here, makes it easier to work on this.

**Comment by JaredKreft** [comment]
I don't have one (and I'm not sure what item info you need), but here's a link to the item on poe.trade:

http://poe.trade/search/uketamasitosin

**Comment by Eruyome** [comment]
What I need is the data that you get by using ctrl + c on any item. To test any item parsing/pricing I need either the item or this information. Of course I can also write that information myself using some other stone as a template but simply getting the correct information the best solution.

**Comment by JaredKreft** [comment]
Got someone to link it to me.

Rarity: Magic
<<set:MS>><<set:M>><<set:S>>Squeaking Talisman Leaguestone
--------
Currently has 1 of 1 (augmented) Charge
--------
Item Level: 82
--------
Next Area will contain a Monster possessed by an Ancient Talisman
Next Outdoor Area has 25% chance to contain a Stone Circle
--------
-4 to Maximum Charges
Next Area will contain an additional Three Rat Talisman
--------
Right-click to open your Legacy Panel and place a Leaguestone in an empty slot. It will apply to the next new area you enter.
--------
Corrupted

**Comment by Eruyome** [comment]
Thx, btw I formatted that a bit for you ;-)

**Comment by Eruyome** [comment]
Fixed on the dev branch.
