### ISSUE TITLE
error: Expecting JSON value

### ISSUE THREAD

**Issue by Daermalkin** [PoE-TradeMacro/POE-TradeMacro#386]
I had no problem using trade macro on my old pc with win 7. After i got my new pc with win 10 i got this error.
http://imgur.com/siEtMie

**Comment by Eruyome** [comment]
Show me the contents of `temp\currencyData.json`

**Comment by Daermalkin** [comment]
when i checked the content of the json, i saw that problem was with some configuration with my isp. i corrected it and its working now.

thank you for your reply.

**Comment by Eruyome** [comment]
Cool 👍

**Comment by sandwitcher** [comment]
Hello. What exactly did you do? I'm having the same problem here on windows 7.

**Comment by aRTy42** [comment]
It should be fine now, see #468. The poe.ninja api seems to have been down temporarily.

**Comment by sandwitcher** [comment]
Thanks for the info!
