### ISSUE TITLE
No results for some items 

### ISSUE THREAD

**Issue by 4leite** [PoE-TradeMacro/POE-TradeMacro#388]
No results for some items on latest pre-release

No result found for:
Rumi's concoction
Mortem Morsu

On 2Week Turmoil SC Using default settings, Ctrl-D search.
Was working prior to update

Showing correct results for:
Empyrean Leash Leather Belt (random rare)

**Comment by Eruyome** [comment]
It's a rather weird issue, anyway it's already known and I'll work on it.

**Comment by 4leite** [comment]
let me know if you need any help with testing or whatever.

Cheers

**Comment by 4leite** [comment]
Seems to be items where the Item Level Is in the first line?

**Comment by Eruyome** [comment]
This issue is obsolete with the newest beta release, try it and open a new issue if you still have any issues.
