### ISSUE TITLE
Exception thrown during script initialization [2.3.5-beta]

### ISSUE THREAD

**Issue by haruozzie** [PoE-TradeMacro/POE-TradeMacro#390]
![12333](https://user-images.githubusercontent.com/25824749/28317484-685e74f8-6bc7-11e7-808a-3d26d12d2df2.png)
which results into;
![xmvtq53](https://user-images.githubusercontent.com/25824749/28317502-7c71fcee-6bc7-11e7-9f9d-6427cb27bc0b.png)

Issue does not happen for me on 2.3.4

**Comment by jliu777** [comment]
I am having this issue also. I also tried to completely uninstall all the versions of Trade Macro and reinstalling it, but still doesn't work.

**Comment by Eruyome** [comment]
This issue is obsolete with the newest beta release, try it and open a new issue if you still have any issues.
