### ISSUE TITLE
Updating to v2.3.5-beta.2 doesn't work.

### ISSUE THREAD

**Issue by n1emad** [PoE-TradeMacro/POE-TradeMacro#392]
Hi, I've been manually installing the v2.3.5-beta.2 update and it keeps asking me to update from the v2.3.5-beta.1 version. In game the macro will sometimes search poe.trade and other times asks me to download the newest version, which I have several time now. 

If you need more information I would be happy to supply it

Have a nice day

**Comment by Eruyome** [comment]
Can you please open `resources\VersionTrade.txt` and show me it's contents?

**Comment by n1emad** [comment]
TradeReleaseVersion := "v2.3.5-beta.2"
TradeAHKVersionRequired := "1.1.24.01"

**Comment by Eruyome** [comment]
Seems fine. I don't quite understand what's going on here, can you elaborate a bit more? There are no frequent update checks, that only happens when starting the script or using that menu option. You also seem to say that you're using the search hotkey, sometimes it works, sometimes it asks you to update instead?

> In game the macro will sometimes search poe.trade and other times asks me to download the newest version

**Comment by n1emad** [comment]
So I have deleted the folder and gotten a new zip to start fresh. 

![tradeupdate](https://user-images.githubusercontent.com/6776210/28417745-1cc1b1fa-6d51-11e7-9103-2223aa919bde.PNG)

In the picture you will see the zip I used the version text file and the update message that I get when starting the script. 

I only get that update message when I start the script like you have said. When the search hotkey does not work a text field appears with download as the title and some fields below with no data added to them.

**Comment by n1emad** [comment]
This is the error window: 

![error](https://user-images.githubusercontent.com/6776210/28417910-be26c756-6d51-11e7-90ea-3e1eb4866d37.PNG)

**Comment by Eruyome** [comment]
Please download the dev version https://github.com/PoE-TradeMacro/POE-TradeMacro/archive/devEru.zip.
I changed some error handling, the window that you get should have more information (returned request headers).
Aside from that please open the settings menu and enable debug output. You'll get a console window on script start. It will print 2 sets of strings for every GEt/POST request made by the macro after initialization, meaning for every search that you make.

 If you make a search that fails (error) please show me the last 2 console outputs. Example:
![grafik](https://user-images.githubusercontent.com/16058242/28419358-0005c6ce-6d5f-11e7-868a-0f352cb01ae3.png)

**Comment by n1emad** [comment]
I've extracted the dev version and it has asked me to update on launch again. The search appears to be working but I will post when I gives an error.

**Comment by Pudgebone** [comment]
Ive also been having the issue of the update not actually updating. not a big deal but thought i'd let you know

**Comment by Eruyome** [comment]
`C:\Users\<UserName>\AppData\Local\Temp\POE-TradeMacro` should have some files, `release.zip` is the downloaded update. Does it exist and contain the update that you wanted to install?

**Comment by Pudgebone** [comment]
Checked that, extracted the files, ran them and got the same result. Still
says I'm on beta 1 and need to update to beta 2. If it's somehow on my end
I'm not worried, the script still runs.

**Comment by Eruyome** [comment]
So, does it not update like you said or just still thinks it's not updated?

**Comment by Pudgebone** [comment]
Sorry for slow response. Hard work day yesterday. So I just deleted old
macro files, downloaded newest version from ur gh repo, ran that and got
same results. Tells me I'm out of date and need to update. And icon in menu
tray says
beta 1.

**Comment by Eruyome** [comment]
You download the beta.2 release, started it and the try icon says beta.1? That shouldn't happen, it reads this version number from `resources\VersionTrade.txt` and if you have the latest version this file shouldn't be wrong.

**Comment by Pudgebone** [comment]
yeah, so, basically the newest version isnt giving me the newest version.
if others arent having a problem it must be on my end somehow. I'll give
the download another try

**Comment by Pudgebone** [comment]
did it fresh one more time and got exact same results.

**Comment by Pudgebone** [comment]
forgot to mention that the release version in the .txt file says version
beta2, but icon tray still says beta1 and fallback tells me to update when
i initially run it

**Comment by Eruyome** [comment]
Hm, I can try to find the issue later, is it somehow possible that you have more than one installation, for example the backup and that the wrong (older) version runs instead of the latest?

**Comment by Pudgebone** [comment]
I scraped my pc for any trade macro file or related file and shift deleted
them off my pc. Downloaded trade macro version beta 2 from ur gh repo,
installed and ran it. And still at same result: tells me to update, icon
tray reads beta 1. Again, it runs for me but isn't updated to version beta 2

**Comment by PoohFinger** [comment]
Hi mate... I also have the very same problem as the guy above. I have POE-TradeMacro-2.3.5-beta installed and i get the update at start.  I did the same as that guy hit update and it wont let me. Some thing about update scripted failed to run. Picture below.  I then thought right delete all of that old poe trade off and download the beta 2 and run from desktop. As soon as i run it.  It says update to beta 2. Let me go see if i can get some pictures for you.. Maybe the same as the guy above.
![untitled1](https://user-images.githubusercontent.com/30428730/28558602-7a3071ca-710a-11e7-925a-796ba36e4501.jpg) ....................... Then we have this the next time i go to run beta 235 beta again 
![untitled2](https://user-images.githubusercontent.com/30428730/28558672-d19b0ae2-710a-11e7-8df4-c33d58de36ae.jpg) ............................Ok i then go and delete all that beta files of computer and run the downloaded beta 2 and this is what i get at start up. 
![untitled3](https://user-images.githubusercontent.com/30428730/28558784-59cd5f32-710b-11e7-81db-3f5ef5d1ce95.jpg) .................. Close that and i then get this 
![untitled4](https://user-images.githubusercontent.com/30428730/28558837-9bb590b8-710b-11e7-9d3c-29e348cdb530.jpg) .........................No poe trade possible exiting script ............

**Comment by Eruyome** [comment]
@PoohFinger Try this version here, when you start it there are a bunch of requests and every one of those will show a message box like this: 
![grafik](https://user-images.githubusercontent.com/16058242/28598140-f007e2ce-71a1-11e7-8216-4cf28bb82273.png)

The one shown here to poe.trade should be the one failing for you. What it shows is the command the macro uses to execute cURL. You can copy everything and paste it into a windows cmd/terminal window and execute it. You should get a response like this:
![grafik](https://user-images.githubusercontent.com/16058242/28598311-0f559594-71a3-11e7-8d7c-3a962a0e2e49.png)

Actually this response should be included in that error message that you get, so if you really use the beta.2 version your response should be empty. I'd like to see this response.

**Comment by Eruyome** [comment]
@Pudgebone If you're downloaded the beta.2 version and didn't choose to update when you're prompted to you should still have the latest version. I guess you skipped updating, or did I misunderstand this step?

**Comment by PoohFinger** [comment]
No i tried updating first. let me go and delete every part of that poe trade off and see if there ant ref in the registry dell that out so system is clean then run it from c:\ see if that does it

**Comment by PoohFinger** [comment]
No still will not work.....Clean the registy out took every thing off then downloaded cleen install.  Ran it from different parts c drive documents my games poe desktop program files all over the shop and same thing.... Put old beta back on then click update and same as above 6 pictures up.   Asked in poe global if anyone is running poe beta 2 and no response so got me beat

**Comment by PoohFinger** [comment]
OK I got it working........Easy peachy. Nothing wrong with BETA2. It was all my end.....Now i cleaned all the old vertions off the computer and put beta 2 on C:\ and ran a short cut to my desktop... I have all ways ran it straight from desktop so i will imagine i still can.  NEXT the problem... I use COMODO antivirus. I also use Ccleaner. and Malwarebytes. All o0f those 3 monitor my system.... So i exit all 3 shut them down. Open program manager ctrl alt del. Even tho i had exited they were still going strong so Click end program.. All is OFF. Went back to Poe Trade Beta 2 and clicked Run_TradeMacro.ahk, And yep she went straight in and works... Now i would again imagine if i had done a update from beta to beta 2 it would work. In fact i will go try........... YES ok i just ran the old BETA and clicked update and it updated and works and shows BETA 2. I will now go and start BETA 2 and turn comodo and malwarebytes and Ccleaner back on and pop into poe and see if all works....OK No turned all 3 back on and will not run so i will now turn Malwarebytes off and Ccleaner and try to run. OK its not Malwarebytes or Ccleaner its as i thought comodo stopping it so i will see if i can somehow allow it in settings. .....Cant find it at the minute but will post as soon as i do or if anyone knows the setting to turn on or off or allow the files or so on please do tell me under comodo settings.

**Comment by Eruyome** [comment]
In the TradeMacro folder `lib\` there's the file `cURL.exe`, it's used for all the requests, I made a post on this file on this issue here https://github.com/PoE-TradeMacro/POE-TradeMacro/issues/395#issuecomment-317906354. Maybe Comodo blocks this file or at least it's traffic and you have to make an exception for it.

**Comment by PoohFinger** [comment]
Yep....Found it....On Comodo right in the middle of the settings screen is AUTO CONTAINMENT you click that and right in the middle of you it again say Auto Containment. You click ADD on the right side screen . A box will open and at the TOP it says Run VIRTUALLY. Click that and say IGNORE.  Then look down and it says CRITERIA ....Click EDIT.  Click File Location and BROWSE. then FILES..... Find the file CURL.EXE in the poe beta2 folder under folder named LIB. Then Just click OK and you should be good to go.  Maybe with a different antivirus it will be ish the same.

**Comment by Eruyome** [comment]
Every antivir software allows you to make exceptions, either for files or entire folders, finding that option should be easy also.
