### ISSUE TITLE
line 2237 Target label does not exist - FRESH install

### ISSUE THREAD

**Issue by ost3g0** [PoE-TradeMacro/POE-TradeMacro#396]
v2.3.5-beta.2 macro version
1.1.26.01 AHK
Win10 64bit

As soon as I try and run the script on this version it errors with the titled mention.

Error: Target label does not exist.
Specifically: AM_AssignHotkeys

Line 2237: Gosub,AM_AssignHotkeys

Help :(

**Comment by Eruyome** [comment]
This label exists in ÀdditionalHotkeys.txt` (`\Users\%USERNAME%\Documents\PoE-TradeMacro\`), any chance that this file is missing for you or that you edited it?

**Comment by ost3g0** [comment]
I cannot check right now since I'm at work but I can absolutely say I
downloaded beta2 - extracted, and ran the script.  Nothing was edited or
deleted.  100% stock from the archive file.  I downloaded it twice to be
safe.  Even tried a dev build that I saw linked a few posts down, also same
exact error.

**Comment by Eruyome** [comment]
This user folder is being created on script start and the AdditionalMacros file is copied over then, This happens before starting the actual macro so you shouldn't get any error but you'd get one if this folder creation/file copying fails. Please check if something went wrong there.

**Comment by ost3g0** [comment]
Deleting that file fixed this for me, thank you for your assistance.

It must have conflicted with a previous install.

**Comment by Eruyome** [comment]
Hm, if the file existed it should have been overwritten, you should make sure that the folder/file is not protected/readonly.

**Comment by Severinus3** [comment]
Just letting you know that I had the same problem, deleting the AdditionalMacros.txt in \Documents\PoE-TradeMacro fixed the issue. Took me a long time to find this solution, might be a good idea to add this to known issues so others can find it easier? And the AdditionalHotkeys.txt that you mentioned was indeed missing, unless you meant AdditionalMacros.txt, which I later deleted and it worked again.

v2.3.6 macro
v1.1.26.01 AHK
Win 7 Ultimate 64bit

**Comment by Eruyome** [comment]
Yeah, I meant AdditionalMacros.txt

**Comment by Eruyome** [comment]
Added it: https://github.com/PoE-TradeMacro/POE-TradeMacro/wiki/FAQ#16-error-target-label-does-not-exist-specifically-am_assignhotkeys
