### ISSUE TITLE
[Bug] PoE crashing after identifying portal effects

### ISSUE THREAD

**Issue by kajfik000** [PoE-TradeMacro/POE-TradeMacro#397]
When someone links me a portal skin effect with ctr+alt+click in a whisper and I try to identify with ctrl+d, PoE crashes.

**Comment by Eruyome** [comment]
What? O_o
Beta or normal client?

**Comment by kajfik000** [comment]
Normal client.
You are right, it does also happen when not running the macro and using ctrl+c. So I guess it must be a problem with PoE, sorry for disturbing you.
