### ISSUE TITLE
[PSA] No support for the first few days of 3.0/Harbinger League

### ISSUE THREAD

**Issue by Eruyome** [PoE-TradeMacro/POE-TradeMacro#402]
I'll be on vacation until Monday, so don't expect any support/fixes except maybe updates to the uniques and mods (poe.trade) data until then. 

I don't expect anyone to experience any breaking/critical issues, if there are some related to the newest version using cURL just use the older versions (up to 2.3.4). They should work still work fine.

https://github.com/PoE-TradeMacro/POE-TradeMacro/releases

**Comment by KheopsGaming** [comment]
I still can't connect at poe trade since cURL was used :/ So where i can download 2.3.5 version of poetrademacro ?

**Comment by Eruyome** [comment]
Why not? 2.3.6 doesn't really have any updates for 3.0 and updated to the data files (poe.trade mods and unique items are downlaoded by the macro on every start. Those files are version independent, so you'll get those as soon as I update them.

**Comment by Eruyome** [comment]
This is the last thing I could do before I'm gone:
Here's a development version, it may not help with your issue but with others (no connection to poe.trade possible). 
https://github.com/PoE-TradeMacro/POE-TradeMacro/archive/devEru.zip

And here is a batch script to seperately test a curl request, it's improved over the request that version 2.3.6 has and if needed you can edit it and set your cloudflare cookies, instructions are inside, just edit it wiht some text editor. It has to be placed in the TradeMacro root directory and saves it's output to `outresult.txt`.
https://www.dropbox.com/s/wbcwfbkh2ghsti2/curl_test.bat?dl=0
