### ISSUE TITLE
Missing Cookie cf_clearance [fixing the reading cookie data failed error]

### ISSUE THREAD

**Issue by raketenbrudi** [PoE-TradeMacro/POE-TradeMacro#407]
I Tried to follow this guide here 
https://github.com/PoE-TradeMacro/POE-TradeMacro/issues/149#issuecomment-268639184
for fixing the reading cookie data failed error.

but only have the cfduid cooke and league harbringer cookie
missing the cf_clearance cookie, what should i do?

I try´d run cmd in /lib with curl.exe -I poe.trade

and this:
The problem does only if the path to the macro folder contains spaces. After I copied the macro folder to the root directory (c:\ in my case) and made sure the macro folder itself doesnt have any spaces, the script started working correctly without any errors.

**Comment by Eruyome** [comment]
I heard about this (spaces), I probably forgot to wrap some path in quotation marks somewhere.
Aside from that, you don't really have any cookie issues, you don't need them, you don't get a cloudflare page that would/could genereate the clearance.

**Comment by raketenbrudi** [comment]
okay thank you sir :)

**Comment by raketenbrudi** [comment]
So this is the error i get

<a href="https://picload.org/view/rwopirri/readingcookiedatafailed.png.html" target="_blank"><img src="https://picload.org/thumbnail/rwopirri/readingcookiedatafailed.jpg" /></a>

<a href="https://picload.org/view/rwopirar/exceptionthrown.jpg.html" target="_blank"><img src="https://picload.org/thumbnail/rwopirar/exceptionthrown.jpg" /></a>

<a href="https://picload.org/view/rwopiral/noitemfound.png.html" target="_blank"><img src="https://picload.org/thumbnail/rwopiral/noitemfound.jpg" /></a>

don´t know what i do wrong or whats wrong. any help?

**Comment by raketenbrudi** [comment]
I tried the curl_test and RunCurlTestPowershellScript.bat but no tempoutput folder will be created.

**Comment by Eruyome** [comment]
Hm, even weirder...
Are you able to open a powershell window and execute `.\curl_test.ps1` after navigating to that folder? Meaning do you need further instructions?

**Comment by raketenbrudi** [comment]
When i open the powershell in the resources\test folder it says script deactivated from system.

 CategoryInfo          : Sicherheitsfehler: (:) [], PSSecurityException
    + FullyQualifiedErrorId : UnauthorizedAccess

does that mean my powershell blocks your script?

**Comment by Eruyome** [comment]
Edit from above comment.
Edit: I just updated the dev version to run the curl_test.ps1 as admin, does that create the folder?

**Comment by raketenbrudi** [comment]
yea now a word doc will open after the RunCurlTestPowershellScript.bat 
It says
"ÿþH#T#T#P#/#1#.#1# #2#0#0# #O#K#"
does that help?

**Comment by Eruyome** [comment]
A Word document? Is that your default for .txt files?

**Comment by raketenbrudi** [comment]
yep, but i can easy change it if you want

**Comment by raketenbrudi** [comment]
HTTP/1.1 200 OK
Date: Mon, 14 Aug 2017 17:53:41 GMT
Content-Type: text/html; charset=utf-8
Connection: keep-alive
X-Frame-Options: DENY
Content-Encoding: gzip
Server: cloudflare-nginx
CF-RAY: 38e5c66770ba27b0-FRA

looks better ^^

**Comment by Eruyome** [comment]
Seems fine, are you still getting those errors/no search results?

**Comment by raketenbrudi** [comment]
yep, checked with and without firewall/antivirus

**Comment by Eruyome** [comment]
After launching there should be a file `temp\cookieData.exe`. Could you open a windows console and execute that file? Double clicking also works but it may be easier to see any errors that way since the window stays open. Your isseu shouldn't be cookie related but I'm still intrigued why reading `temp\cookie_data.txt` fails.

**Comment by raketenbrudi** [comment]
there is a exe getCookieData.exe, I started it, new txt file is created called cookie_data with this inside:

useragent=Mozilla/4.0 (compatible; MSIE 7.0; Windows NT 6.2; Win64; x64; Trident/7.0; .NET4.0C; .NET4.0E; .NET CLR 2.0.50727; .NET CLR 3.0.30729; .NET CLR 3.5.30729)
cfduid=d10f0dadc2e1f4aeadfe9ce9503f600671502735988

**Comment by Eruyome** [comment]
Weird, your error message claims it failed. Shouldn't be that case. Anyway this shoudln't matter anyway. The curl request from the test script works. So in theory all request made by the macro should also work.

**Comment by raketenbrudi** [comment]
Weird is the right word :D

**Comment by Eruyome** [comment]
Here's a [dropbox link](https://www.dropbox.com/s/lc7en78b84tt4g7/PoE-TradeMacro_dev.rar?dl=0) to a version with added messageboxes. Every curl request to poe.trade shows a box with the used curl command and the response headers. Show me such a messagebox.

**Comment by raketenbrudi** [comment]
this one?

[URL=http://www.directupload.net][IMG]http://fs5.directupload.net/images/170814/5jccpo7m.png[/IMG][/URL]

**Comment by Eruyome** [comment]
So, the test script returns response headers while the macro returns nothing? Interesting.

**Comment by raketenbrudi** [comment]
Yeah seams so, I have no idea what to do, if you have an idea im gladly here for you to help :)

**Comment by Eruyome** [comment]
I asked you to copy the command and execute it in a terminal, don't forget it ;-)

**Comment by raketenbrudi** [comment]
i did but didn´t get anything real from it. I ctrl +c this in the cmd:
---------------------------
curl response
---------------------------
cURL request:

"C:\Users\Kekser\Desktop\poe-testing\lib\curl.exe" -ILks -H "User-Agent:Mozilla/5.0 (Windows NT 6.3; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/59.0.3071.115 Safari/537.36" -H "Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8" -H "Accept-Encoding:gzip, deflate" -H "Accept-Language:de-DE,de;q=0.8,en-US;q=0.6,en;q=0.4" -H "Connection:keep-alive" -H "Host:poe.trade" -H "Upgrade-Insecure-Requests:1" "http://poe.trade"


Response headers:


---------------------------
OK   
---------------------------

**Comment by Eruyome** [comment]
You pasted the entire thing in? Should I have been more clear that you only paste this part in?
```
"C:\Users\Kekser\Desktop\poe-testing\lib\curl.exe" -ILks -H "User-Agent:Mozilla/5.0 (Windows NT 6.3; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/59.0.3071.115 Safari/537.36" -H "Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,/;q=0.8" -H "Accept-Encoding:gzip, deflate" -H "Accept-Language:de-DE,de;q=0.8,en-US;q=0.6,en;q=0.4" -H "Connection:keep-alive" -H "Host:poe.trade" -H "Upgrade-Insecure-Requests:1" "http://poe.trade"
```

**Comment by raketenbrudi** [comment]
yep you should have :)
I passed it in, system cant find this path

**Comment by Eruyome** [comment]
Can you show the exact error message? Can you find the pat manually, does it exist?

**Comment by raketenbrudi** [comment]
I overlooked a " now it worked.
heres a picture of the cmd (changed the location of the folder).

<a href="http://www.directupload.net/file/d/4815/g4tr98zq_png.htm" target="_blank"><img src="http://fs5.directupload.net/images/170815/temp/g4tr98zq.png" border="1" title="Kostenlos Bilder und Fotos hochladen"></a>

**Comment by Eruyome** [comment]
So you're telling me that this command also works in your console, but not when used from the macro? Or did anything change and it works? I find all of this very weird.

**Comment by raketenbrudi** [comment]
The poe-trade marco still doesn´t work. I meant the command.

the massage I get from the box is still:

---------------------------
curl response
---------------------------
cURL request:

"D:\poe-testing\lib\curl.exe" -ILks -H "User-Agent:Mozilla/5.0 (Windows NT 6.3; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/59.0.3071.115 Safari/537.36" -H "Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8" -H "Accept-Encoding:gzip, deflate" -H "Accept-Language:de-DE,de;q=0.8,en-US;q=0.6,en;q=0.4" -H "Connection:keep-alive" -H "Host:poe.trade" -H "Upgrade-Insecure-Requests:1" "http://poe.trade"


Response headers:


---------------------------
OK   
---------------------------

and after that a window opens like 10 times saying this:

---------------------------
_TradeMacroMain.ahk
---------------------------
Exception thrown (download)!

what: 
file: 
line: 
message: 
extra: 
---------------------------
OK   
---------------------------


I am not a programmer I don´t know how to execute a .ahk file, if possible i allways install 64bit versions.

**Comment by Eruyome** [comment]
Paste the code in a .ahk file of your choosing, double click it.

**Comment by raketenbrudi** [comment]
Thanks, I have 64 as expected

**Comment by raketenbrudi** [comment]
I have the Problem!

I wrote my the firewall support from Comodo, my firewall, they remotly changed something, seams the firewall was to strict for this macro. Something about the webfilter. Its kinda weard, because I tried to run poe-trade-macro with deactivated firewall and it did't worked. Theams that maybe  the firewall changed something, but don't know what.

**Comment by raketenbrudi** [comment]
Thanks to you for your effort and your patience if i get an awnsere form comodo what they changed i will post it here.

**Comment by Eruyome** [comment]
Hm, any chance you can get to the bottom of this or at least give a slightly better explanation of what happend or may have happend? Could even be in german.

EDIT: That would be nice.

**Comment by raketenbrudi** [comment]
Comodo seems to have a auto-contaiment function, this will execute questionable programms in a sandbox mode.

**Comment by Eruyome** [comment]
So basically I can add this to the FAQ, mentioning that some firewalls like COMODO have this and it should be disabled, right? https://help.comodo.com/topic-399-1-790-10323-.html

**Comment by raketenbrudi** [comment]
Yeah, every Firewall that has an active sandbox mode (Comodo called it auto-contaiment mode) will filter the poe-trade-macro.

Thx again for you efford and go on buddy! This macro is gold woth! :*

**Comment by Eruyome** [comment]
You're welcome, also thanks to you, finding this issue may save a lot of time for others (and especially me, trying to help such these people.
