### ISSUE TITLE
How and Where do I add more Macros?

### ISSUE THREAD

**Issue by PoeMacroNewbie** [PoE-TradeMacro/POE-TradeMacro#408]
I like adding my own macros and used to do it in the default_additionalmacros file but now it says to put it in the "\CustomMacros". Using "the \CustomMacros" makes me think there should already be a folder named that but I don't see one. Any help? Do I just make my own? Where do I put it? And what do I name the file that should hold my personal macros?

**Comment by Eruyome** [comment]
Using version 2.35 and higher should create this folder in your TradeMacro user folder. You can open this folder via system try context menu (where you can select TradeMacro settings and so on). Also you should never edit default_AdditionalMacros, always the one in the user folder.
