### ISSUE TITLE
Error when launching 

### ISSUE THREAD

**Issue by PastaAdventures** [PoE-TradeMacro/POE-TradeMacro#409]
http://i.imgur.com/3pb5MGb.png

downloaded a new version and still occurred

**Comment by ScullyJack** [comment]
https://github.com/PoE-TradeMacro/POE-TradeMacro/issues/396

I'm having the exact same issue. Try this.
The problem I have with this though is the PoE-TradeMacro folder in <users>\Documents doesn't exist.

**Comment by Eruyome** [comment]
Simply deleting the files in the TradeMacro user fodler and running the script again should also work. That's what I heard. For some reason it seems that the old AdditionalMacros.txt doesn't get overwritten by the new one, causing this error.
