### ISSUE TITLE
[ToDo] Improve crafting bases list

### ISSUE THREAD

**Issue by Eruyome** [PoE-TradeMacro/POE-TradeMacro#41]
https://github.com/thirdy/POE-TradeMacro/blob/development/trade_data/crafting_bases.txt

There should be nothing listed here that isn't worth at least 1-2 chisel if item level >= 83/84

**Comment by kyri0** [comment]
Noticed you haven't added weapons. Is that meant? I'll add some bases, anyway.

**Comment by Eruyome** [comment]
> There should be nothing listed here that isn't worth at least 1-2 chisel

I may simply be bad informed, at least I never sold a weapon base unless => 5L
