### ISSUE TITLE
Cant pick Harbringer League

### ISSUE THREAD

**Issue by Wafflenips** [PoE-TradeMacro/POE-TradeMacro#410]
Hi, have an issue were i only can chose from 4 different leagues (TmpStandard,TmpHardcore,Standard and Harcore) the new harbringer league doesnt show for me, got the lastest version aswell 2.3.7

Any Solutions?

**Comment by aktai0** [comment]
TmpStandard and TmpHardcore are Harbinger and Harbinger HC respectively, since those are the current temp leagues

**Comment by Eruyome** [comment]
Correct answer.
