### ISSUE TITLE
Increased Ele Damage with Attack Skills not parsed at all

### ISSUE THREAD

**Issue by ihelmer07** [PoE-TradeMacro/POE-TradeMacro#411]
Please see the image links below but the Prefix "Increased Elemental Damage With Attack Skills" is not being read by Trade Macro.

[Link to picture of issue](http://i.imgur.com/cdlLIUK.png)

**Comment by Eruyome** [comment]
That's an ItemInfo issue. @aRTy42
I'll check it out but asking anyway, is this with the newset version or an older one?

**Comment by aRTy42** [comment]
That should be an older version. Not all 3.0 mods are in yet, but that one was simply a rename and I changed it.
