### ISSUE TITLE
Trade macro closes after being unable to connect to poe.trade when starting

### ISSUE THREAD

**Issue by 3dop** [PoE-TradeMacro/POE-TradeMacro#412]
Current version: several of 'em including devEru and 2.3.6

I have many uses for this program which do not in fact require being able to connect to poe.trade

Additional macros is one really big one. Checking the wiki is another.

Closing the whole macro because it cannot connect to poe.trade is not the proper failure mode for a multi featured program. Popping an error window and then continuing to function in all other ways is the way to do stuff. Retrying poe.trade as needed and popping an error message if/when one occurs again would be even spiffier, but I'd settle for just not shutting down the whole damn thing when one portion fails.

**Comment by Eruyome** [comment]
This behaviour should have been changed in the latest relase 2.3.7
If it really is not I'll have to take a look at this again.
In the meantime try using 2.3.4, should still work quite decently.
