### ISSUE TITLE
new flat ES+life hybrid rolls counting as a prefix and a suffix

### ISSUE THREAD

**Issue by Dogtordog** [PoE-TradeMacro/POE-TradeMacro#416]

**Comment by Eruyome** [comment]
https://github.com/aRTy42/POE-ItemInfo/issues
That should be reported here but I'll just mention @aRTy42 since he maintains ItemInfo.

**Comment by aRTy42** [comment]
The new hybrid rolls are not in yet. That was listed in the notes for ItemInfo. The problem is that the whole system needs to be reworked and likely needs to display several possibilities since more mod combinations became ambiguous.
