### ISSUE TITLE
Crashes

### ISSUE THREAD

**Issue by artofvs** [PoE-TradeMacro/POE-TradeMacro#417]
Lots of crashes last 2 days (not sure it might have started before 2.3.8 update)
Normal windows crash window for autohotkey shows up and my inputs freeze kinda (keyboard does not work, mouse lag very hard) for 30 seconds or so and then it goes back to normal and trade macro is not running anymore.
I run like 3-4 other autohotkey scripts at the same time, but they do not seem to be affected.
Can I find logs somewhere to provide more information on this problem?

**Comment by Eruyome** [comment]
There are no logs, wouldn't really know what to log...
Have you installed other software recently? Maybe uninstall and install AHK (different from "reinstall/update").

**Comment by artofvs** [comment]
This has fixed itself (maybe new update helped?)
Most likely was due to my poor network connection at the time
