### ISSUE TITLE
HCtemp league is being searched as nonHC temp league

### ISSUE THREAD

**Issue by Seminko** [PoE-TradeMacro/POE-TradeMacro#419]
Despite having manually selected tmphardcore the macro searches tmpnormal.

EDIT: as per previous experience I manually changed the INI file. Now that I read the instructions there is a GUI to do it.

**Comment by Eruyome** [comment]
Not happening for me, are you using the latest vesion?

**Comment by Seminko** [comment]
Maybe an old ini file is still included. Once I set the league using the GUI it worked
