### ISSUE TITLE
Error when trying to launch trade macro

### ISSUE THREAD

**Issue by FrigidZero** [PoE-TradeMacro/POE-TradeMacro#420]
Recently, I installed a fresh copy of Windows 10 on my desktop and I have been trying to get the trade macro to work. Whenever I try to run the macro, I get this message,

> Error at line 6.
#Include file
"C:\Users\...\AppData\Local\Temp\Temp1_POE-TradeMacro-2.3.9.zip\resources\VersionTrade.txt" cannot be opened.
The program will now exit

Now, the macro works perfectly fine on my Windows 7 laptop. So, I'm assuming that I'm missing something, right?

**Comment by Eruyome** [comment]
You're trying to run it from inside the zip file. Extract it first.

**Comment by FrigidZero** [comment]
Thanks!
