### ISSUE TITLE
Error after launching app

### ISSUE THREAD

**Issue by Imbawolf** [PoE-TradeMacro/POE-TradeMacro#421]
Got this error and then app launching as usual, and working
![default](https://user-images.githubusercontent.com/30905480/29180507-b80ee0dc-7e00-11e7-82a2-44d7c4dfa13a.png)

**Comment by Imbawolf** [comment]
ye its works afterwards

**Comment by Eruyome** [comment]
Yeah but do your searches work or does the macro run but doesn't give you any results?

**Comment by Imbawolf** [comment]
its run as usual except this error

**Comment by Imbawolf** [comment]
wanna now what causes an error

**Comment by Eruyome** [comment]
Was that error a one time thing or does it occur frequently?

**Comment by Imbawolf** [comment]
every time i launch an app

**Comment by Eruyome** [comment]
Curl is failing to connect to http://api.pathofexile.com/leagues?type=main... does that link work in your browser?

I've read up a bit on reasons for curls 404 here https://stackoverflow.com/questions/21001264/curl-returnin-404-error/21863524, anyway, I added some request headers to that particular request in the currenct dev version, maybe try it https://github.com/PoE-TradeMacro/POE-TradeMacro/archive/devEru.zip

**Comment by Imbawolf** [comment]
link is working, will try new verison

**Comment by Imbawolf** [comment]
nope, still getting this error

**Comment by Eruyome** [comment]
Please use the newest dev version, navigate to the subfolder `resources\tests\` and double click `RunCurlTestPowershellScript.bat`. It should open a text document ,if it's opened with Word please change the default program to notepad or something similiar. Post the file's contents here.

**Comment by Eruyome** [comment]
Sry, maybe I wasn't clear enough. Double clicking `RunCurlTestPowershellScript.bat` should run some scripts and create a new file `resources\tests\tempOutput\outfile.txt`. This file should also be automatically opened. I only want to see this files contents.

**Comment by Imbawolf** [comment]
its not creating a file, but making a error with no delay, i capture it with prtscr. Its says on russian dat curl_test.ps1 cant launch on this system cuz havent digital signature. 
![4lzxzawp814](https://user-images.githubusercontent.com/30905480/29372811-e4b1eb4e-82b4-11e7-98a4-36f22cfa622d.jpg)

**Comment by Eruyome** [comment]
I have updated `RunCurlTestPowershellScript.bat`, does it work now?

**Comment by Imbawolf** [comment]
ye, below info from file
HTTP/1.1 200 OK
Date: Wed, 16 Aug 2017 19:48:25 GMT
Content-Type: text/html; charset=utf-8
Connection: keep-alive
X-Frame-Options: DENY
Content-Encoding: gzip
Server: cloudflare-nginx
CF-RAY: 38f6e938b3fb0f69-FRA

**Comment by Eruyome** [comment]
So the request to poe.trade seems ok, in contrast to the one to pathofexile.com. Actually i have the same returned headers as you (error message), was confused because of the 404 code. But I don't have any exception thrown.

Please try the newest devVersion, I made some error handling improcements.

**Comment by Imbawolf** [comment]
well, with newest dev version error didnt occur, ty for help

**Comment by Eruyome** [comment]
So, the macro runs completely fine now, everyhting resolved?

**Comment by Imbawolf** [comment]
yep
