### ISSUE TITLE
Problems with Trade Macro and Anti Virus

### ISSUE THREAD

**Issue by shoes6699** [PoE-TradeMacro/POE-TradeMacro#424]
I have having this problem ever since I updated to the new trade macro.  I think my anti virus is blocking the launching for the trade macro.  I get a message from Norton and POE, see photos below.  But it says "Connection Failure, Request to poe.trade failed!"  has anyone else encountered this?  If I turn off my Norton it works but i don't want to have to turn off my antivirus to play the game.

![20170806_021632](https://user-images.githubusercontent.com/30937348/29228733-028e552c-7ea9-11e7-8c54-f31db63d4644.jpg)
![20170806_021744](https://user-images.githubusercontent.com/30937348/29228734-0292c9e0-7ea9-11e7-83fb-c20137321f63.jpg)

**Comment by artofvs** [comment]
Had those empty errors too. No AV software tho

**Comment by Eruyome** [comment]
In the FAQ I describe this antivir software issue. `lib\curl.exe` gets blocked for some people by their antivir software, you can simply make an exception for the TradeMacro folder. https://www.lifewire.com/exclude-files-from-norton-antivirus-scans-153348

**Comment by shoes6699** [comment]
K thanks, I'll try that when I get home.  I tried going in before and white listing Auto Hotkeys because I thought that was the problem but didn't know about excluding certain folders.

**Comment by shoes6699** [comment]
Thanks this worked!!!
