### ISSUE TITLE
Can't run trade macro? 

### ISSUE THREAD

**Issue by HelpPlzz** [PoE-TradeMacro/POE-TradeMacro#427]
![image](https://user-images.githubusercontent.com/30955837/29241366-1eedfd88-7f46-11e7-8c53-804ccc2d75fb.png)

I get this error whenever I open it. I followed the steps given.

**Comment by HelpPlzz** [comment]
Fixed the problem. AHK needed to be updated

**Comment by Eruyome** [comment]
Thanks for the report.
