### ISSUE TITLE
Connection Failure

### ISSUE THREAD

**Issue by 5FX** [PoE-TradeMacro/POE-TradeMacro#428]
I have no idea what's the problem. I deleted other browser and I only have IE, Chrom and Microsoft Edge. What do I need to do?
![capture](https://user-images.githubusercontent.com/30970099/29246381-41f6ddd8-7fc6-11e7-8a56-4e5e6d6d122a.JPG)
![capture2](https://user-images.githubusercontent.com/30970099/29246382-41f70448-7fc6-11e7-8152-07d775a18cae.JPG)

**Comment by WielandF** [comment]
@5FX I have the same problem!

**Comment by 5FX** [comment]
@WielandF Yeah? I'm stuck. Turned off AV and same thing.

**Comment by Eruyome** [comment]
Have you read the FAQ #2, point 8? Maybe it's not intuitive enough, anyway navigate to `resources\tests\` and execute (double click) the file `curl_test.bat`. You could also use the current development build https://github.com/PoE-TradeMacro/POE-TradeMacro/archive/devEru.zip where I improved this script using powershell. In that case you would execute `RunCurlTestPowershellScript.bat`.

With the current stable version you'll get a text file in the subfolder `tempOutput`, containing the curl commands output, but if the curl command fails completely you won't see why except that you'll have an empty file. 
With the dev version this file is automatically being opened and you'll see any error message given by powershell. 

In either case I need to see this files contents.

**Comment by WielandF** [comment]
![output](https://user-images.githubusercontent.com/13366088/29282202-430bd338-8122-11e7-8f0f-2b0a4175c68f.png)

I did as instructed with the release version ( the development  build didn't create the tempOutput folder but i couldn't get a error message for that ...sorry:/).
Hope this helps!

**Comment by Eruyome** [comment]
Actually I expected a different result... everthing seems fine and the macro should work for you. Are you sure it still doesn't work?

**Comment by WillyDO** [comment]
![image](https://user-images.githubusercontent.com/30986378/29441200-24092bb0-838f-11e7-80e7-52a0383ea8af.png)
I get this result :/ yesterday it worked fine but now i get same problem again help pls =(

**Comment by Eruyome** [comment]
See this comment https://github.com/PoE-TradeMacro/POE-TradeMacro/issues/431#issuecomment-323382968
