### ISSUE TITLE
Map Mod Warnings bug (Avoid Elemental Ailments)

### ISSUE THREAD

**Issue by artofvs** [PoE-TradeMacro/POE-TradeMacro#430]
Mod that gives monsters chance to avoid elemental ailments seems to not work with map mod warning. I imagine its due to the fact they renamed it.

**Comment by artofvs** [comment]
Reported that bug on ItemInfo repository.
Quick fix:
Regexp should be
"Monsters have \d+% chance to Avoid Elemental Ailments"
instead of
"Monsters have \d+% chance to Avoid Elemental Status Ailments"

**Comment by Eruyome** [comment]
Thanks.
