### ISSUE TITLE
Connection problem

### ISSUE THREAD

**Issue by WillyDO** [PoE-TradeMacro/POE-TradeMacro#431]
When I run run_trademacro.ahk it shows me this

![error](https://user-images.githubusercontent.com/30986378/29253079-1f1934ea-803a-11e7-8ca3-f38066439e15.jpg)

how can i fix it pls =(

**Comment by Eruyome** [comment]
https://github.com/PoE-TradeMacro/POE-TradeMacro/issues/428#issuecomment-322209874 Please read my comment and follow my instructions.

**Comment by WillyDO** [comment]
Ty it worked =)

**Comment by WillyDO** [comment]
@Eruyome sorry to bother you again, but i'm having same problem again, i get this from curltest
![image](https://user-images.githubusercontent.com/30986378/29441263-a84cf802-838f-11e7-9976-8a3964fcf546.png)
what should i do? help pls =(

**Comment by Eruyome** [comment]
You can also message me on discord if you have the time and patience. https://discord.gg/taKZqWw
I need "guinea pigs" like you to solve those issues, getting close and fast feedback helps me very much. Even if manual cookies work for you there still seems to be an issue with retrieving cookies automatically.
