### ISSUE TITLE
Unable to run

### ISSUE THREAD

**Issue by nick101010** [PoE-TradeMacro/POE-TradeMacro#434]
After extracting and opening the file. My Run_iteminfo and Run_trademacro is set to open with explorer. Im not able to just right click and select run

**Comment by nick101010** [comment]
My issue may actually be with the installation of autohotkey. I'm unable to perform the installer process

**Comment by Eruyome** [comment]
You're unable to install autohotkey?

**Comment by nick101010** [comment]
I had to delete it and restart. I'm not able to open it but not use it because i have to create a script? Sorry i am very unfamiliar with these programs.

**Comment by Eruyome** [comment]
So, first of you install AutoHotkey from https://autohotkey.com/, if that's done the `.ahk` files should be associated with autohotkey, double clicking them should simply run them. 
Running `Run_TradeMacro.ahk` should start the macro.

**Comment by nick101010** [comment]
I believe the problem is with autohotkey. I attempt to run the script to start it but right clicking on my home screen and clicking "autohotkey script". I believe my problem is not knowing what to open it with. It defaults to explorer.

**Comment by Eruyome** [comment]
https://support.microsoft.com/en-us/help/18539/windows-7-change-default-programs
It shouldn't be hard to associate .ahk files with an installed autohotkey. There should be a few ways described, but even right clicking -> open with -> select default program should work.

**Comment by nick101010** [comment]
I was able to get it to work. Was definitely user error. I appreciate the
response.

**Comment by Eruyome** [comment]
You're welcome.
