### ISSUE TITLE
Unable to install script

### ISSUE THREAD

**Issue by BootieTrap** [PoE-TradeMacro/POE-TradeMacro#435]
When trying to install the script I get an error saying. File "C:\Users\MyUser\Documents\PoE-TradeMacro\AdditionalMacros.txt" doesn't exist.

Closing Script...

Then I tried creating that file.  Then I get the error

Error: Target label does not exist.

---> 2267: Gosub, AM_AssignHotkeys

**Comment by Eruyome** [comment]
So, this file should be copied over from <TradeMacroFolder>\resources\ahk\default_AdditionalMacros.txt` (including renaming it to AdditionalMacros.txt). It seems that for some poeple this copy process fails.
What windows version are you using and are there special permissions on the user folder that might prevent this copy process?

**Comment by BootieTrap** [comment]
I am using windows 10. But might still be using windows insider.

**Comment by BootieTrap** [comment]
Oh and thanks for the help. Worked now.

**Comment by Eruyome** [comment]
I hate that... the script should run with admin priviliges and AHK's copy funtions should work, maybe I have to use console/powershell for that... I may have to bother you with trying the dev version a bit to make sure this copy process works.

**Comment by iangd** [comment]
I'm having the same issue. I copied the file over from  \resources\ahk\default_AdditionalMacros.txt and renamed it, but now I'm getting a different error 
Script file not found: 
C:\Users\Ian\Desktop\TradeMacro\_tradeMacroMain.ank

**Comment by Eruyome** [comment]
Please don't use your desktop as "install" directory. Maybe that fixes it already.

**Comment by Eruyome** [comment]
You guys could do me a favour and test the following script, save it as an .ahkfile and place it in your trademacro folder (root):

```
#SingleInstance force
#NoEnv ; Recommended for performance and compatibility with future AutoHotkey releases.
#Persistent ; Stay open in background

TestCopy()
RunAsAdmin()
ExitApp

TestCopy() {
    userDirectory := A_MyDocuments . "\PoE-TradeMacro"
    FileAppend, test, %A_ScriptDir%\temp\testfile.txt

    ErrorLevel := 0
    FileCopy, %A_ScriptDir%\temp\testfile.txt, %userDirectory%, 1
    If ErrorLevel {
        Msgbox % A_IsAdmin ? "Run as admin:`nFileCopy failed." : "FileCopy failed."
    } Else {
        Msgbox % A_IsAdmin ? "Run as admin:`nFileCopy success." : "FileCopy success."
    }

    ErrorLevel := 0
    FileMove, %A_ScriptDir%\temp\testfile.txt, %userDirectory%, 1
    If ErrorLevel {
        Msgbox % A_IsAdmin ? "Run as admin:`nFileMove failed." : "FileMove failed."
    } Else {
        Msgbox % A_IsAdmin ? "Run as admin:`nFileMove success." : "FileMove success."
    }

    FileAppend, test, %A_ScriptDir%\temp\testfile.txt
    file := A_ScriptDir "\temp\testfile.txt"
    admin := A_IsAdmin ? "Run as admin: " : "Run without admin elevation:"
    RunWait %comspec% /c "chcp 1251 & echo "%admin%" & xcopy /y "%file%" "%userDirectory%" & pause"
    
    Return
}

RunAsAdmin() {
    ShellExecute := A_IsUnicode ? "shell32\ShellExecute":"shell32\ShellExecuteA"
    If Not A_IsAdmin 
    { 
        If A_IsCompiled 
            DllCall(ShellExecute, uint, 0, str, "RunAs", str, A_ScriptFullPath . " " . arguments, str, A_WorkingDir, int, 1) 
        Else 
            DllCall(ShellExecute, uint, 0, str, "RunAs", str, A_AhkPath, str, """" . A_ScriptFullPath . """" . " " . arguments, str, A_WorkingDir, int, 1) 
        ExitApp
    }
    
    Return
}
```

You should get:
- A messagebox telling you whether FileCopy worked.
- A messagebox telling you whether FileMove worked.
- A windows cmdlet window/console showing the output from the xcopy command.
In all successful cases there should be a file testfile.txt being copied to your trademacro user folder.

This gets repeated a second time with admin elevation.

**Comment by iangd** [comment]
You were right, I moved it to Program files and that fixed the issue.
However I did run the script above, and the filecopy and filemove worked correctly.

**Comment by iangd** [comment]
Thank you so much for the help!
