### ISSUE TITLE
open Atm the suffix-prefix dont reflect the new changes of 3.0 

### ISSUE THREAD

**Issue by Aledark789** [PoE-TradeMacro/POE-TradeMacro#438]
When we do CTRL C to check tiers and which prefix and suffix are present...
Severals arent read thru the macro..
For example chance to freeze on wand dont show
Cold dmg leeched
etc

**Comment by Eruyome** [comment]
This is part of ItemInfo, which is maintained by aRTy42, while I do a lot of development there he is working on that suff, some is not finished yet, some is and will be updated for TradeMacro in the next release.
