### ISSUE TITLE
Initializing Script

### ISSUE THREAD

**Issue by Ayalinn** [PoE-TradeMacro/POE-TradeMacro#439]
Hello. 

I've been trying to run this script. But whenever I try to launch it I get to this "screen" 
https://s3.postimg.org/im0xxk8ub/initializing.jpg
And after that it closes and nothing happens. Any idea what might be causing this?

**Comment by Eruyome** [comment]
Not a single error message? And you're sure it's not just starting like supposed to, since it's just running in the background then?

**Comment by Eruyome** [comment]
Closed until I get further feedback.
