### ISSUE TITLE
Reading cookies via cs script fails partially

### ISSUE THREAD

**Issue by Eruyome** [PoE-TradeMacro/POE-TradeMacro#441]
I have at least one (probably more) users where automatically reading Internet Explorer cookies fails. partially. Script in question: https://github.com/PoE-TradeMacro/POE-TradeMacro/blob/master/lib/getCookieData.cs

User @guifa11 showed me these screenshots of his IE cookies (IE v 11.494.10589.0 Win10), which work when used manually in TradeMacro. The only cookie collected by the script is "cfduid" though, "cf_clearance" is missing, even when collecting all cookies, not only the ones containing "cfduid" or "cf_clearance". I don't know why that is the case.
Anyone having any idea? @DoctorVanGogh @OzoneH3

Also, another user has the issue that his manually retrieved IE cookies work while the automatically ones don't (they are complete). The reason being that the manual user agent is different than the one retrieved by the script.

Manual:
```
User-Agent:Mozilla/5.0 (Windows NT 6.1; WOW64; Trident/7.0; rv:11.0) like Gecko
```
Automatic:
```
User-Agent:Mozilla/4.0 (compatible; MSIE 7.0; Windows NT 6.1; Win64; x64; Trident/7.0; .NET CLR 2.0.50727; SLCC2; .NET CLR 3.5.30729; .NET CLR 3.0.30729; Media Center PC 6.0; .NET4.0C; .NET4.0E; InfoPath.3)
```

![image](https://user-images.githubusercontent.com/16058242/29496937-054d5a42-85de-11e7-9a78-1d67e7f318a2.png)
![image](https://user-images.githubusercontent.com/16058242/29496934-eedb3324-85dd-11e7-85a0-a80b2f21ff07.png)

**Comment by DoctorVanGogh** [comment]
No clue - but I'm astonished that you're still trying to play cat & mouse with cloudflare.... That is a game you will not win in the long run.

So: that hack still works (mostly) - nice. Enjoy it while it lasts ;)

**Comment by Eruyome** [comment]
I'm not sure that there will anything that changes anytime soon. As long as you have valid cookies + user-agent you can make requests to poe.trade, even if there's a captcha challenge. So at least using manually retrieved cookies after visiting poe.trade works. There are only a "handful" of users who need this anyway (at the moment). You can also start IE via com objects with AHK, maybe I can get the "right" user-agent that way, will have to test that soon. I'm just very confused about that missing cookie.

**Comment by Eruyome** [comment]
`Mozilla/5.0 (Windows NT 6.3; WOW64; Trident/7.0; .NET4.0E; .NET4.0C; .NET CLR 3.5.30729; .NET CLR 2.0.50727; .NET CLR 3.0.30729; InfoPath.3; Tablet PC 2.0; Creative AutoUpdate v1.41.07; rv:11.0) like Gecko `

`Mozilla/5.0 (Windows NT 6.3; WOW64; Trident/7.0; rv:11.0) like Gecko`

I believe that I simply have to remove everything in the brackets besides Windows NT, WOW64, Trident and rv information.

**Comment by Eruyome** [comment]
I guess reading these keys

```
HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Internet Settings\5.0\User Agent\Post Platform
HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Internet Settings\5.0\User Agent\Pre Platform
HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Internet Settings\5.0\User Agent\Post Platform
HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Internet Settings\5.0\User Agent\Pre Platform
```

and removing their values from the useragent is the way to go, maybe better than [regex matching](https://regex101.com/r/grG5Vd/1) "valid" strings.

**Comment by Eruyome** [comment]
I guess that works:

```
#SingleInstance, force

featureTokenRegPaths := ["SOFTWARE\Microsoft\Windows\CurrentVersion\Internet Settings\5.0\User Agent\Post Platform", "SOFTWARE\Microsoft\Windows\CurrentVersion\Internet Settings\5.0\User Agent\Pre Platform"]
featureTokenRegRoots := ["HKEY_LOCAL_MACHINE", "HKEY_CURRENT_USER"]

ua := "Mozilla/5.0 (Windows NT 6.3; WOW64; Trident/7.0; .NET4.0E; .NET4.0C; .NET CLR 3.5.30729; .NET CLR 2.0.50727; .NET CLR 3.0.30729; InfoPath.3; Tablet PC 2.0; Creative AutoUpdate v1.41.07; rv:11.0) like Gecko"
ua_b := ua

For key, root in featureTokenRegRoots {
	For k, path in featureTokenRegPaths {							
		Loop %root%, %path%, 1, 1
		{
			If (A_LoopRegType <> "KEY") {
				RegRead Value								
				ua := RegExReplace(ua, "i)\s?+" A_LoopRegName "\s?+;", "")
			}
		}		
	}
}

Msgbox % ua_b "`n`n" ua
```
