### ISSUE TITLE
Error on reinstallation

### ISSUE THREAD

**Issue by Xephus1** [PoE-TradeMacro/POE-TradeMacro#442]
![picture of trademacro](https://user-images.githubusercontent.com/31055132/29502575-e789a2ec-85e5-11e7-99f0-e21898c20c3c.jpg)

Get this error when I try to run Trade Macro had no issues prior to reinstalling a fresh copy of windows. After I hit okay on the above error I get a message saying: 
Parsing the league data (json) from the Path of Exile API failed. This should only happen when the servers are down for maintenance. 
The script execution will be stopped, please try again at a later time.

**Comment by Eruyome** [comment]
Were the servers down at the time?
Anyway, if it still doesn't work please try the dev version https://github.com/PoE-TradeMacro/POE-TradeMacro/archive/devEru.zip.

**Comment by Xephus1** [comment]
No they were up at the time. Will do.
