### ISSUE TITLE
Weapon Tooltip Should Display Phys-Only Projected Q20 DPS

### ISSUE THREAD

**Issue by maarxx** [PoE-TradeMacro/POE-TradeMacro#444]
Weapon Tooltip Should Display Phys-Only Projected Q20 DPS

CTRL+C tooltip for weapon stats includes ...

- Phys DPS: (phys only, current quality)
- Elem DPS: (elem only, current quality)
- Total DPS: (total, current quality)
- Q20 DPS: (total, projected for Q20 quality)

... but is notably missing ...

- Phys Q20 DPS (phys only, projected for Q20 quality)

... as a phys character commonly evaluating phys weapons, I think projected Phys Q20 would be very useful to have.

It is worth noting that the CTRL+ALT+D ("Select Mods to Include in Search") popup displays exactly this value, but it is less convenient to access.

I also recognize that I can sometimes compute the value easily in my head as "Q20 DPS" minus "Elem DPS" but that is sometimes a lot of extra thinking for high-frequency item evaluation.

**Comment by Eruyome** [comment]
@aRTy42

**Comment by aRTy42** [comment]
Seems easy enough, will be added.

**Comment by Eruyome** [comment]
Added
