### ISSUE TITLE
Error at line 18

### ISSUE THREAD

**Issue by hezu** [PoE-TradeMacro/POE-TradeMacro#446]
![error](https://user-images.githubusercontent.com/13300311/29592076-fdfd2b8a-8756-11e7-9003-088ee343636f.jpg)
I don't if it matters but i run win 7. Also I tried various versions of ahk, reinstalled macro multiple times, and checked if anti virus blocked any files recently (it didnt).

**Comment by Eruyome** [comment]
So far such issues wer always related to the installed AHK version. I guess you installed the latest version? 64bit or 32bit?

**Comment by hezu** [comment]
I tried latest version of ahk 2. And the latest version of ahk 1/original.

**Comment by hezu** [comment]
Eventhough I have 2 versions of AHK in my folder. 
![ahk versions](https://user-images.githubusercontent.com/13300311/29593093-2b2c47a2-875d-11e7-929b-a79840a3c277.jpg)
It lets me open macro only with 32 bit one. 
![ahk versions](https://user-images.githubusercontent.com/13300311/29593119-62d326d0-875d-11e7-9aaf-7554cca6396e.jpg)
My operational system is 64 bit. Also I noticed that i have different error with ahk 2 (2.0-a076). Which says 
![ahk versions](https://user-images.githubusercontent.com/13300311/29593173-af57a0e4-875d-11e7-9798-33513370c475.jpg)

**Comment by Eruyome** [comment]
It won't be compatible with ahk2. Saving this as a .ahk file and running it tells you if the used AHK exe is 32/64 bit.
```
bit := A_PtrSize = 8 ? "64" : "32"
MsgBox % bit
```

**Comment by hezu** [comment]
![untitled-1](https://user-images.githubusercontent.com/13300311/29593692-be0deaa0-8760-11e7-8a14-660828d294f2.jpg)
I installed version 1.0.44. It is located in program files (x86) if it helps.

**Comment by Eruyome** [comment]
Current version: v1.1.26.01 - July 16, 2017, https://autohotkey.com/download/ahk-install.exe

**Comment by hezu** [comment]
Seems everything works well now. Thank you for your time. I appreciate it a lot.
