### ISSUE TITLE
Stuck on Initializing script (Request to GGG takes too long)

### ISSUE THREAD

**Issue by TrevorFails** [PoE-TradeMacro/POE-TradeMacro#447]
When I try to load the script, the script just gets stuck without any error messages. I only get this message. "Initializing script". It does not respond until I force close it from task manager.

I have updated to the latest version of AHK as well as the trade macro. Still no luck. It worked earlier today, but I have no idea what happened.

Hope you can help. :|

**Comment by DaxxTrias** [comment]
Also noticed it a few minutes ago. Was working fine last night, no changes to the script on github so most likely some external web resource its pinging.

**Comment by pedrolucasmag** [comment]
Same. btw in the  last few weeks it was taking a lot longer to load the script :S

**Comment by DaxxTrias** [comment]
Seems to be working again. However the initialization portion took a good minute.

**Comment by Eruyome** [comment]
There are 4 sites being requested on script start, github, GGGs league API, poe.trade and poe.ninja. I can only guess that one or more of those requests took/still takes an unusual amount of time.

**Comment by PeteAndersen** [comment]
Mine failed today, looks to be due to GGG server not responding

```
---------------------------
_TradeMacroMain.ahk
---------------------------
Exception thrown (download)!

what: 
file: 
line: 
message: 
extra: 

HTTP/1.1 302 Found
Server: nginx/1.8.1
Date: Fri, 25 Aug 2017 22:32:29 GMT
Content-Type: text/html; charset=UTF-8
Connection: keep-alive
Expires: Thu, 19 Nov 1981 08:52:00 GMT
Cache-Control: no-store, no-cache, must-revalidate
Pragma: no-cache
Set-Cookie: POESESSID=removed; path=/; domain=.pathofexile.com; HttpOnly
Location: /login/?redir=%2Fleagues%3Ftype%3Dmain
X-Frame-Options: SAMEORIGIN

HTTP/1.1 404
Server: nginx/1.8.1
Date: Fri, 25 Aug 2017 22:33:03 GMT
Content-Type: text/html; charset=UTF-8
Connection: keep-alive
Expires: Thu, 19 Nov 1981 08:52:00 GMT
Cache-Control: no-store, no-cache, must-revalidate
Pragma: no-cache
Set-Cookie: POESESSID=removed; path=/; domain=.pathofexile.com; HttpOnly
```

**Comment by Eruyome** [comment]
Yeah, had it just myself, loading the website in the browser took ages, too. Nothing I can do about, but I guess I'll leave this issue open for others to see it.

**Comment by dein0s** [comment]
Just sneaking around - if this requests (I'd say at least github and ggg) not 100% necessary for the script to start/work, add some failsafe loading with later re-check?

**Comment by Eruyome** [comment]
It's GGG in this case and I read the current active leagues, I wouldn't say it's impossible to have a fallback for this but looking at rarely this happens I don't think it's that critical for now.
