### ISSUE TITLE
Unable to start script

### ISSUE THREAD

**Issue by pentakillmorde** [PoE-TradeMacro/POE-TradeMacro#448]
![untitled](https://user-images.githubusercontent.com/31281850/29619635-2248af94-884e-11e7-91ee-cd01e27923ce.png)

This pops up every time i try to run the macro. And even before this it was taking quite a while to initialize the script.

**Comment by RoryTate** [comment]
I found a temporary solution...the problem appears to be with the mods.json file in the data_trade folder. This is getting downloaded anew each time you run the script, but right now all that it contains is:

<h1>Error 503 first byte timeout</h1>

There should be a mods.json.bak file in the folder. So here's the step-by-step temporary workaround:

1. Copy mods.json.bak over top of mods.json
2. Go into the resources\config\default_config_trade.ini file and change

DownloadDataFiles =1

to

DownloadDataFiles =0

This will stop the script from downloading new data files (which are returning an error, and instead use the last good working data file).

Hope that helps!

**Comment by pentakillmorde** [comment]
Sorry for the late reply, but i am having trouble finding the mods.json.bak file you're writing about. Are you talking about the version previous to 2.3.9 or am i misinterpreting ;
> last good download

**Comment by Eruyome** [comment]
https://raw.githubusercontent.com/PoE-TradeMacro/POE-TradeMacro/master/data_trade/mods.json

I you can't find it, it's this one here.

**Comment by pentakillmorde** [comment]
yup, got everything working again. Thanks!
