### ISSUE TITLE
Arcane Surge Quality 20% data not shown

### ISSUE THREAD

**Issue by SirKori** [PoE-TradeMacro/POE-TradeMacro#449]
As title, the Arcane Surge Quality % info on CTRL+C of gem just says "No gem quality data found. Please report it." And so here I am =)

**Comment by aRTy42** [comment]
Thanks for the report. Gem-Info (like all Ctrl+C stuff) comes from ItemInfo, which I do. It has been updated there, Eru just needs to include it in the next TradeMacro release which should be out soon.

**Comment by Eruyome** [comment]
Soon<sup>TM</sup>
