### ISSUE TITLE
Hybrid mods not showing correctly

### ISSUE THREAD

**Issue by xSirk** [PoE-TradeMacro/POE-TradeMacro#450]
[This armour](https://prnt.sc/gcl4l3) has these mods:

```
# to Evasion Rating / # to maximum Life
# to Evasion Rating
```

**Comment by dein0s** [comment]
You have to wait until TradeMacro will be updates with the latest ItemInfo.

**Comment by Eruyome** [comment]
Soon<sup>TM</sup>

**Comment by aRTy42** [comment]
Even the latest ItemInfo does not solve that combination (yet), but I'm well aware that new hybrid mods exist.
