### ISSUE TITLE
how can I disable f5 as a macro?

### ISSUE THREAD

**Issue by KingAroan** [PoE-TradeMacro/POE-TradeMacro#455]
I do not want f5 as a macro, I use it for something else but this script keeps claiming it as its own.

**Comment by dein0s** [comment]
Well, first off you can read wiki https://github.com/PoE-TradeMacro/POE-TradeMacro/wiki/AdditionalMacros

**Comment by Eruyome** [comment]
The FAQ describes everything in detail, if you still have issues please describe what you're not understanding.

**Comment by KingAroan** [comment]
I right clicked went to edit and clicked additional macro, I then changed the f5 to off and then turned on f11 for my afk message. Clicked save. Right clicked again on the bottom and I then clicked "Reload Script (Use only this)" and I get an error immediately saying Script file not found E:\ChromeDL\POE-TradeMacro\.ahk

**Comment by aRTy42** [comment]
What happens when you start the script as usual again?

**Comment by KingAroan** [comment]
Weird. It started but said it couldn't read the cookies this time. but now f5 is disabled, and I had to redo the changes to the afk message, but that time the Reload Script (Use only this)
 worked

**Comment by KingAroan** [comment]
So I am good now
