### ISSUE TITLE
Cant run script says error line 6

### ISSUE THREAD

**Issue by chaosx666** [PoE-TradeMacro/POE-TradeMacro#456]
hi i downloaded ahk then downloaded poe trade zip  there is no option to run trade macro only item info and run trade macro when i click on either its says  error at line 6  and this program will close any help would be much appreciated i also folowed ziggy d's youtube vid but still no luck as on his video in the zip folder there is  a run only this option where the zip i downloaded doesnt?

**Comment by Eruyome** [comment]
There are two projects, [ItemInfo](https://github.com/aRTy42/POE-ItemInfo/releases) and [TradeMacro](https://github.com/PoE-TradeMacro/POE-TradeMacro/releases), if you only have run_ItemInfo then I'd guess you have the wrong project.

**Comment by chaosx666** [comment]
what is the right one too download i went to github and downloaded latest version

**Comment by chaosx666** [comment]
i downloaded the one with run trademacro but keeps saying error on line 6 ?

**Comment by aRTy42** [comment]
Did you unzip the download or are you trying to run it from the still zipped folder?

Did you install a recent autohotkey version?

Are you running it on a drive (or the desktop) that might have access restrictions?

**Comment by Eruyome** [comment]
If you have errors please always show the error message (the complete one).

**Comment by chaosx666** [comment]
it says error line 6      #include "c/users/owner/downloads/poe-trademacro-2.4.0   
                                   
                                    (4)/poetrademacro-2.4.0/resources/version trade txt  cannot be opened 
                                  
                                      this program will exit

**Comment by aRTy42** [comment]
Did you properly unzip the whole thing into a regular folder?

You also cannot move the .ahk file away from the other files, in case you tried to place only the "Run_TradeMacro.ahk" on the desktop or something like that.

**Comment by chaosx666** [comment]
how do i unzip into a regular folder?  thanks again for help =)

**Comment by Eruyome** [comment]
By right clicking the .zip file and selecting "extract" (depending on your installed Zip software this option name will vary, Windows should also have a built-in option). It's just that some people simply don't extract the file because Windows lets users navigate into this zip file like into any other folder.

**Comment by chaosx666** [comment]
yeah i have right clicked and pressed extract

**Comment by Eruyome** [comment]
I have asked you about a screenshot of the error message, please do that.

**Comment by chaosx666** [comment]
finally got it working thanks guys for the help very much appreciated and sorry for the hassle
