### ISSUE TITLE
No "Total Resists" and "Total Life" in advanced search?

### ISSUE THREAD

**Issue by OmikronGamma** [PoE-TradeMacro/POE-TradeMacro#457]
Hello,
after latest update there is no "Total Res" and "Total Life" sections in advanced search.
I hope its actually a bug, not a deliberate thing to remove, i used it quite often.

**Comment by darkkaos** [comment]
Yeah. I hope so too. Went back in version because that's a powerful toll to be lost.

**Comment by Eruyome** [comment]
I guess it's a bug, last time I checked it was there.

**Comment by Eruyome** [comment]
Can you show me an example of that because I still have those mods.
![image](https://user-images.githubusercontent.com/16058242/29741759-f8aa709c-8a72-11e7-9d54-e264f93e400a.png)

**Comment by darkkaos** [comment]
Even that belt having only cold resistance, it's always nice to use total elemental resistance to search itens with the same amount of resistance but that can be any other.
![image](https://user-images.githubusercontent.com/24784189/29741834-b5431f2a-8a4a-11e7-84fe-c63fb3fcd61f.png)

**Comment by Eruyome** [comment]
Oh, it's missing if you only have a single resist or single life roll.

**Comment by OmikronGamma** [comment]
![advsearch](https://user-images.githubusercontent.com/23458700/29745541-0c5f0dc8-8ad7-11e7-8be9-41430265a8cb.jpg)
Unique items also dont have "total res" option, QotF as an example.

**Comment by Eruyome** [comment]
Fix is released.
