### ISSUE TITLE
Trouble using currency

### ISSUE THREAD

**Issue by CAJOS** [PoE-TradeMacro/POE-TradeMacro#460]
While the trade macro is running, I have trouble right clicking currency. It will double click a few times then eventually will single click after 3-4 tries. Turning off the macro will instantly fix the problem so this isn't a hardware issue. I have turned off all the additional macros and there is no option in the settings pages related to "clicking" I can run other macros fine, even ones which modify my right click but poe trade macro (even with it being the only script running) will cause right clicking currency a nightmare to the point where I have to open the macro, use it, then close it right away. I can make a short video showing this in action if needed.

**Comment by Eruyome** [comment]
A video could help, but first please test the standalone ItemInfo https://github.com/aRTy42/POE-ItemInfo/releases. You know, just the tooltip via Ctrl + C.

**Comment by CAJOS** [comment]
Ok, doing a bit of testing, it seems that on its own, the trade macro has no problem. When i put on my other macro (lutbot poe macro + hold shift while right clicking) it breaks. When I have that other macro on its own, there are no issues. So there is something between poe trade macro, lutbot macro and my edited lines.

For reference, my edited lines are:
`#IfWinActive, Path of Exile
RButton::
{
	{
		Sendinput, {Shift down}{RButton down}
		keywait, RButton
		Sendinput, {RButton up}{Shift up}
	}
	Return
}`

**Comment by Eruyome** [comment]
Did you make an progress on solving this?

**Comment by CAJOS** [comment]
So the conflict occurs between the right click/shift macro I use and the poe trade macro. I can hold shift and i click currency fine, just normal right clicking doesn't work. Not sure why this happens though. I just use the trade macro in bulk now and open it, use it on my dump tab then close again. It is not the best but its my work around.

**Comment by aRTy42** [comment]
Setting the macros to "off" doesn't prevent key assignments, it just stops them from being active.

The scroll tab function has default keys involving the right mouse button and might be the collision here. You could try opening the AdditionalMacros file and commenting out the two lines that actually assign the key by putting a ";" at the start.

```
;	Hotkey, % AM_ScrollTabRight[3]	, AM_ScrollTabRightAlt_HKey	, % AM_ScrollTabRight[1]
;	Hotkey, % AM_ScrollTabLeft[3]	, AM_ScrollTabLeftAlt_HKey	, % AM_ScrollTabLeft[1]
```
Note that there are four lines in total that involve ScrollTab, you want to change the lower two which have a "[3]" and the "Alt" in AM_ScrollTabRight**Alt**_HKey / AM_ScrollTabLeft**Alt**_HKey in them.

Save the file and restart the script.

**Comment by CAJOS** [comment]
yeah already went through to find anything affecting right click and disabled it with ;

**Comment by CAJOS** [comment]
I have found a change to my right click macro and that version seems to be working perfectly fine alongside the trade macro. For reference the old macro was:

`#IfWinActive, Path of Exile
RButton::
{
	{
		Sendinput, {Shift down}{RButton down}
		keywait, RButton
		Sendinput, {RButton up}{Shift up}
	}
	Return
}`

and the new one that works with the trade macro:
`#IfWinActive, Path of Exile
*RButton::Send {shift Down}{RButton down}
*RButton Up::Send {shift Up}{RButton up}`
