### ISSUE TITLE
Minion Speed Prefix should be Suffix

### ISSUE THREAD

**Issue by livejamie** [PoE-TradeMacro/POE-TradeMacro#462]
I crafted this with an Essence and it's reporting the Minion Speed as a prefix when I believe it should be a suffix.

![image](https://user-images.githubusercontent.com/49513/29752287-d2d1be62-8b20-11e7-8739-ffffec508f69.png)

![image](https://user-images.githubusercontent.com/49513/29752285-ca0bfcfc-8b20-11e7-981a-caa7d63c4fb8.png)

**Comment by dein0s** [comment]
Related to the [ItemInfo](https://github.com/aRTy42/POE-ItemInfo)

**Comment by livejamie** [comment]
Oh sorry, should I post this on @aRTy42 's repo?

**Comment by aRTy42** [comment]
Would have been correct, but Eruyome and I usually check both places, so I've seen it here aswell. Special essence mods are not matched at the moment, I think the script is reading the mod as regular movement speed (and thus as a prefix).

The whole "n/a (0)" shows you though that it wasn't found properly, so the "P" at the end shouldn't be relied on.

When I'm done solving the new hybrid mod issues, I'll probably do essence mods and implicits next.

**Comment by livejamie** [comment]
Good to know, thank you.
