### ISSUE TITLE
_TradeMacroMain.ahk Script Not Found Error

### ISSUE THREAD

**Issue by MorteNoir** [PoE-TradeMacro/POE-TradeMacro#463]
I'm using the latest version of AutoHot Key and TradeMacro, but im getting an error when i try to run the script. It says the following:

Script file not found:
C:\Users\(username)\Documents\POE AHK\_TradeMacroMain.ahk

I have looked all over for a fix to this and i cant find it anywhere. Any help would be greatly appreciated.

**Comment by Eruyome** [comment]
Did you type that path ba hand? Because it doesn't look ok at all. There should at least be a `\` before `_TradeMacroMain.ahk`. It also doesn't seem like you simply extracted the install zip into it's own folder.

**Comment by MorteNoir** [comment]
I did type it by hand, i had to manually copy the additionalmacros.txt file as well. I unzipped the folder into my Documents folder after i made a folder for it. 
---------------------------
_TradeMacroMain.ahk
---------------------------
Script file not found:
C:\Users\<username>\Documents\POE AHK\_TradeMacroMain.ahk
---------------------------
OK   
---------------------------
That is the error i am getting.

**Comment by Eruyome** [comment]
I don't get what's going on here. That path should read 
```
C:\Users<username>\Documents\POE AHK\_TradeMacroMain.ahk
```
it's missing a `\` again. Does it go missing while copying the message? Can you show me a screenshot of your trademacro folder where I can see the path in the explorer window? Btw, no need to hide your username.

**Comment by MorteNoir** [comment]
Sorry about the username this, force of habit. It goes missing when i copy or type it myself. Below is a screenshot of the trademacro main folder:
![image](https://user-images.githubusercontent.com/31398606/29786429-211bf78a-8bf9-11e7-91e9-7d9c1e0e8aac.png)

**Comment by Eruyome** [comment]
Do you have "show hidden files" enabled? The file in question is the result of the merge process of ther different scripts, and the actual main file that will be executed. It is hidden though since it shouldn't be started directly. 
It it's not there you may have some file write/permission issues.

**Comment by Eruyome** [comment]
If you edit `Run_Trademacro.ahk` you'll find the following lines:
```
FileAppend, %info%		, %A_ScriptDir%\_TradeMacroMain.ahk
FileAppend, %addMacros%	, %A_ScriptDir%\_TradeMacroMain.ahk
FileAppend, %trade%		, %A_ScriptDir%\_TradeMacroMain.ahk
```
by replacing them with this:
```
FileAppend, %info%		, %A_ScriptDir%\_TradeMacroMain.ahk
msgbox % ErrorLevel
FileAppend, %addMacros%	, %A_ScriptDir%\_TradeMacroMain.ahk
msgbox % ErrorLevel
FileAppend, %trade%		, %A_ScriptDir%\_TradeMacroMain.ahk
msgbox % ErrorLevel
```
you will get messageboxes after each file append, showing a "1" for an error or "0" for success.

**Comment by MorteNoir** [comment]
I have "show hidden files" enabled, the issue is that the file just isn't there.

**Comment by Eruyome** [comment]
You may have posted without seeing my last reply since we posted almost at the same time.

**Comment by MorteNoir** [comment]
It came back with a "1" 
---------------------------
Run_TradeMacro.ahk
---------------------------
1
---------------------------
OK   
---------------------------

**Comment by Eruyome** [comment]
Clicking OK, shows the next messagebox, do all of them return 1?

**Comment by MorteNoir** [comment]
Yes, i get two messages with a "1" message.

**Comment by Eruyome** [comment]
Ok, first of you could right click the folder and check for readonly and/or some special permission settings. Secondly you could just move it somewhere else. Maybe your Programs folder and see if the result is different.

**Comment by MorteNoir** [comment]
Moved in into the AHK folder and it worked. Sorry to bother you with such a simple fix.

**Comment by Eruyome** [comment]
That's ok, I still don't know whats up with those random file write issues some people have, the script already uses admin elevation. maybe you can save this code as an .ahk file and place it in your trademacro root folder. I have edited the path used in this script to match the one that you used before run trademacro from. It created a temporary file and tests some methods to copy it over.

```
#SingleInstance force
#NoEnv ; Recommended for performance and compatibility with future AutoHotkey releases.
#Persistent ; Stay open in background

TestCopy()
RunAsAdmin()
ExitApp

TestCopy() {
    userDirectory := A_MyDocuments . "\AHK Scripts"
    FileAppend, test, %A_ScriptDir%\temp\testfile.txt

    ErrorLevel := 0
    FileCopy, %A_ScriptDir%\temp\testfile.txt, %userDirectory%, 1
    If ErrorLevel {
        Msgbox % A_IsAdmin ? "Run as admin:`nFileCopy failed." : "FileCopy failed."
    } Else {
        Msgbox % A_IsAdmin ? "Run as admin:`nFileCopy success." : "FileCopy success."
    }

    ErrorLevel := 0
    FileMove, %A_ScriptDir%\temp\testfile.txt, %userDirectory%, 1
    If ErrorLevel {
        Msgbox % A_IsAdmin ? "Run as admin:`nFileMove failed." : "FileMove failed."
    } Else {
        Msgbox % A_IsAdmin ? "Run as admin:`nFileMove success." : "FileMove success."
    }

    FileAppend, test, %A_ScriptDir%\temp\testfile.txt
    file := A_ScriptDir "\temp\testfile.txt"
    admin := A_IsAdmin ? "Run as admin: " : "Run without admin elevation:"
    RunWait %comspec% /c "chcp 1251 & echo "%admin%" & xcopy /y "%file%" "%userDirectory%" & pause"
    
    Return
}

RunAsAdmin() {
    ShellExecute := A_IsUnicode ? "shell32\ShellExecute":"shell32\ShellExecuteA"
    If Not A_IsAdmin 
    { 
        If A_IsCompiled 
            DllCall(ShellExecute, uint, 0, str, "RunAs", str, A_ScriptFullPath . " " . arguments, str, A_WorkingDir, int, 1) 
        Else 
            DllCall(ShellExecute, uint, 0, str, "RunAs", str, A_AhkPath, str, """" . A_ScriptFullPath . """" . " " . arguments, str, A_WorkingDir, int, 1) 
        ExitApp
    }
    
    Return
}


```

You should get:
- A messagebox telling you whether FileCopy worked.
- A messagebox telling you whether FileMove worked.
- A windows cmdlet window/console showing the output from the xcopy command.
In all successful cases there should be a file testfile.txt being copied to your trademacro user folder.

This gets repeated a second time with admin elevation.

**Comment by MorteNoir** [comment]
Had the following errors:
---------------------------
Testscript.ahk
---------------------------
Run as admin:
FileCopy failed.
---------------------------
OK   
---------------------------

---------------------------
Testscript.ahk
---------------------------
Run as admin:
FileMove failed.
---------------------------
OK   
---------------------------
Also, only ^c works in game, no other shortcuts work. Im in Windowed Fullscreen.

**Comment by Eruyome** [comment]
Did the windows cmdlets work?

**Comment by MorteNoir** [comment]
Apologies, but im not sure i understand you question. A command window did open after i ran the script.

**Comment by Eruyome** [comment]
Ok, this window should print a report of the xcopy command, saying if files were copied or if there was an error. You could also just show me those windows.

**Comment by MorteNoir** [comment]
---------------------------
Testscript.ahk
---------------------------
FileCopy failed.
---------------------------
OK   
---------------------------

---------------------------
Testscript.ahk
---------------------------
FileMove failed.
---------------------------
OK   
---------------------------
They worked the first time, but now they aren't.

**Comment by Eruyome** [comment]
I don't care about the filcopy or filemove commands right now, I care about this here:
![image](https://user-images.githubusercontent.com/16058242/29788451-f1699ac6-8c32-11e7-86a9-4b49bfe5100a.png)
You're saying those xcopy commands worked the first time but not anymore? That wouldn't really make sense.

**Comment by MorteNoir** [comment]
Sorry, 
![image](https://user-images.githubusercontent.com/31398606/29788543-04d7b5e8-8c01-11e7-8a19-38ed6b7a9090.png)

**Comment by Eruyome** [comment]
I have edited the code above, can you try it again?

**Comment by MorteNoir** [comment]
Same outcome.
![image](https://user-images.githubusercontent.com/31398606/29789115-0228cf24-8c03-11e7-9355-a63a9a2f1bd9.png)

**Comment by Eruyome** [comment]
Are you sure that you copied the new code? Anyway, made another msall change.

**Comment by MorteNoir** [comment]
I did, copied it again and got the same outcome.
![image](https://user-images.githubusercontent.com/31398606/29789253-72f24d34-8c03-11e7-8233-04556c75b2ee.png)

**Comment by Eruyome** [comment]
Huh, I was sure I could get it so skip this dialog... anyway just press "D", then enter, should continue the command.

**Comment by MorteNoir** [comment]
The command continued to run after pressing "D". It comes up with access denied both times.

**Comment by Eruyome** [comment]
Are you using an account/user without any admin privileges?
Can you right click that folder -> properties -> security and show me that tab?

**Comment by MorteNoir** [comment]
![image](https://user-images.githubusercontent.com/31398606/29789530-54969fd8-8c04-11e7-9a99-0f979ff2fb02.png)

**Comment by Eruyome** [comment]
Is the selected user the one that you're currently using?

**Comment by MorteNoir** [comment]
yes

**Comment by MorteNoir** [comment]
I clicked on my name in the listing and changed to full and got this error message:
![image](https://user-images.githubusercontent.com/31398606/29789620-a6940a00-8c04-11e7-84b3-84086e092e8a.png)

**Comment by Eruyome** [comment]
So you should have write permissions but you don't according to this menu?

Never seen that last window...

**Comment by MorteNoir** [comment]
It comes up when you try to change permission on a folder that you dont have rights to. This should be the case since im the admin, creator, and owner of the folder.

**Comment by Eruyome** [comment]
I guess that's nothing I can or should try to fix programmatically, but I can make a file write check to warn about missing permissions at least.

**Comment by MorteNoir** [comment]
Correct, that is an issue inherit to microsoft for security issues. Now if i can just get the other control functions to work.

**Comment by Eruyome** [comment]
Hm, could you edit `AdditionalMacros.txt` in the user folder and add the line 
```
ListHotkeys
```
inside the Label `AM_AssignHotkeys:` (line 29 - 67) right before the `return`?

You could add this line at multiple places but this may be the easiest to find. It opens a window listing all assigned hotkeys.

**Comment by MorteNoir** [comment]
A screen shows up like so:
![image](https://user-images.githubusercontent.com/31398606/29790541-3aee94a6-8c08-11e7-8124-efd00305533d.png)

**Comment by Eruyome** [comment]
Aside from the different windo it should look like this:

![image](https://user-images.githubusercontent.com/16058242/29790591-a69a3552-8c3a-11e7-981a-585ad0aa68bd.png)

The TradeMacro hotkeys weren't assigned at all.

**Comment by MorteNoir** [comment]
Below is a schot of my TradeMacroInit.ahk file
![image](https://user-images.githubusercontent.com/31398606/29790691-acf8a2d0-8c08-11e7-816b-df8035e66af5.png)

**Comment by Eruyome** [comment]
How about using the dev version? https://github.com/PoE-TradeMacro/POE-TradeMacro/archive/devEru.zip
It's possible that it is not entirely stable since I rewrote some stuff but works fine so far for me.

**Comment by MorteNoir** [comment]
I copied what you sent me and replaced the existing files and it shows the same thing.
![image](https://user-images.githubusercontent.com/31398606/29790927-46d383e8-8c09-11e7-875f-bd25e598a844.png)

**Comment by Eruyome** [comment]
Sry, if you're running the dev version, start the script without editing additionalmacros, right click the system tray icon and choose "show all assigned hotkeys" from the context menu.

**Comment by MorteNoir** [comment]
Just to make sure, below is where i put the list hotkeys command:
![image](https://user-images.githubusercontent.com/31398606/29791072-b3cabcdc-8c09-11e7-8c9e-d1ca41070002.png)

This is what i see from "show all assigned hotkeys":
![image](https://user-images.githubusercontent.com/31398606/29791090-c5a86918-8c09-11e7-9688-c672543c0bb2.png)

Also, I'm getting this message as well:
![image](https://user-images.githubusercontent.com/31398606/29791116-d7d71404-8c09-11e7-9ab7-015311845b2b.png)

**Comment by Eruyome** [comment]
That's all fine. Aside from the missing hotkeys.

**Comment by MorteNoir** [comment]
Ok, so is it an error in the code or are they not assigned properly?

**Comment by Eruyome** [comment]
All hotkeys are set when you open the settings menu? Or are there blank fields?

**Comment by MorteNoir** [comment]
This is what is shown after hitting restore default:
![image](https://user-images.githubusercontent.com/31398606/29791271-5ae3092a-8c0a-11e7-85a8-20b49cb73403.png)

**Comment by Eruyome** [comment]
Are the .ini files placed in the user folder? Or are they missing? In that case those hotkeys would be read from the fallback variables in the code and there could be an issue,

**Comment by MorteNoir** [comment]
They are in the program folders:
![image](https://user-images.githubusercontent.com/31398606/29791436-eea09a6a-8c0a-11e7-9473-f0fd1d6a9611.png)

**Comment by Eruyome** [comment]
go to the context menu again -> open user folder

**Comment by MorteNoir** [comment]
Is this what you are asking for:
![image](https://user-images.githubusercontent.com/31398606/29791535-41362c40-8c0b-11e7-80f1-2d477395b8f3.png)

**Comment by Eruyome** [comment]
![image](https://user-images.githubusercontent.com/16058242/29791654-0304df92-8c3e-11e7-8959-b3f42a9191ec.png)

which should open `%USERPROFILE%\Documents\PoE-TradeMacro`, you can just paste that into your explorer.

**Comment by MorteNoir** [comment]
All these folders are empty:
![image](https://user-images.githubusercontent.com/31398606/29791739-003829c2-8c0c-11e7-80ed-97cdd4181d91.png)

**Comment by Eruyome** [comment]
Did you copy additionalmacros manually into this folder at some point? I believe you mentioned this. Permission issues again? Only manual file copy/write possible?

**Comment by MorteNoir** [comment]
Yes, that is how i stopped the first error message of additionalmacros.ext doesnt exist.

**Comment by Eruyome** [comment]
Now it's getting annoying... I have updated my dev version, it will probably fail for you at start since you don't have the right permissions. This is a huge issue since you won't be able to save the config files, get updates to the config files and additional macros (and all other user files that may come at some time).

**Comment by MorteNoir** [comment]
Seems like this is going to be more trouble than it is worth. Thank you for all your help and time so far, but i dont believe troubleshooting any further will lead to better results.

**Comment by Eruyome** [comment]
If not for you it may for others. Although I don't believe I can solve this on my end, it should be able to be solved on yours.

**Comment by MorteNoir** [comment]
let me try something and see if i can do a work around

**Comment by MorteNoir** [comment]
i fixed it. Im using BitDefender Anti-Vrius that blocks AHk from modifying files, i also disabled file permission inheritance and my "show all assigned hotkeys" looks as followed:
![image](https://user-images.githubusercontent.com/31398606/29793056-7f7393f8-8c10-11e7-89e4-d7d872a5a406.png)

**Comment by Eruyome** [comment]
Hm, is this blocking inherited to windows cmdlets started via AHK? Or does bitdefender also block your windows console?

Anyway, I would have suggested replacing all `A_MyDocuments` in `Run_TradeMacro.ahk` with `A_AppData`, maybe there's a different behaviour, although I doubt that bitdefender cares about this. Or is this possible?

**Comment by MorteNoir** [comment]
Bitdefender stops the AHK files form updating and the cmdlet access via AHK. I jst ran the script again after the two setps mentioned above and every command works perfectly.

**Comment by Eruyome** [comment]
Ok, I've added file write check for the script directory and user folder with an explanation mentioning that antivir software could be blocking ahk from writing/modifying those files.

**Comment by MorteNoir** [comment]
Correct, im glad we solved this issue and i hope no one else has this. In case it does happen again, please be sure to save what was done here to resolve this issue. Again, thank you for all your hard work and patience.

**Comment by Eruyome** [comment]
Oh I'm sure there are others having this issue, or even had them nad not solved it so far.
