### ISSUE TITLE
Invalid installation path 

### ISSUE THREAD

**Issue by koogy** [PoE-TradeMacro/POE-TradeMacro#464]
Hi,
https://github.com/POE-TradeMacro/POE-TradeMacro/releases/tag/v2.4.0
Downloaded from here
"POE-TradeMacro-2.4.0.zip"
Extracted in a folder then running " run_trademacro.ahk"
does this : 

" Executing Poe-TradeMacro from your desktop may cause script errors, please choose a different directory"
then
" Error at line 12753.
Line Text: ²::
Error : Hotkeys/hotstrings are not allowed insides functions
The program will exit."

I didn't edit anything, what's wrong ?

**Comment by Eruyome** [comment]
First of you could follow the advise given in that fisrt sentence, move the folder to someplace else, not your desktop.

**Comment by koogy** [comment]
I did it, still the same
I downloaded an older version which is 2.3.9 instead of 2.4.0 and it works from my desktop 
the script works fine
there is an issue with 2.4.0

**Comment by Eruyome** [comment]
That message was added in 2.4.0 and doesn't cause the issue itself. Can you run 2.4.0 again (not from desktop) and show me a screenshot of the error message?

**Comment by koogy** [comment]
It seems to work fine now even tho there is still the message 
What I did is updating from 2.3.9 to 2.4.0 when the notifcation appeared asking me to update 
but when I downloaded directly the 2.4.0 from https://github.com/POE-TradeMacro/POE-TradeMacro/releases/tag/v2.4.0

there is the message and the script doesn't work
Anyway it's solved now, thanks :) !
