### ISSUE TITLE
Duplicate function definition error

### ISSUE THREAD

**Issue by MerguezNight** [PoE-TradeMacro/POE-TradeMacro#465]
Just setup the new version, starting the macro and here's the error I got :

![error](https://user-images.githubusercontent.com/20791377/29794121-f247e1b4-8c46-11e7-8ced-ef3fa27ba0bc.png)

Don't know what to do honestly

I can't find any duplicate functions in the code itself

Help me out, please ;_;

**Comment by Eruyome** [comment]
Using an older AHK version can cause the weirdest issues, maybe try updating if you have an older version?

**Comment by MerguezNight** [comment]
Nope, I already have the latest version :/

**Comment by Eruyome** [comment]
Hm, maybe purge all TradeMacro files an try the dev version https://github.com/PoE-TradeMacro/POE-TradeMacro/archive/devEru.zip

**Comment by MerguezNight** [comment]
What do you mean by purging ? Deleting all previous versions files ?
The dev version got same error but "13158" instead of "12971" for the line

**Comment by Eruyome** [comment]
Yeah, thats what I mean. 
Just to be sure, whats your AHK version?  You're not using 2.x (which would be wrong)?

**Comment by aRTy42** [comment]
Do you have any personal macros in the /CustomMacros folder?

I've been checking my source code and there is no function "CloseScript" at all, only "CloseScripts", so your issue might be external.

**Comment by Eruyome** [comment]
It's in the run scripts, so it shouldn't be merged into the actual main scripts.

**Comment by MerguezNight** [comment]
AHK is 1.1.26.01
Nothing in the custom macros folder aswell

**Comment by Eruyome** [comment]
Attach your _TradeMacroMain.ahk here, I want to take a look at ti.

**Comment by MerguezNight** [comment]
Here :
[Trade macro.zip](https://github.com/PoE-TradeMacro/POE-TradeMacro/files/1258463/Trade.macro.zip)

**Comment by Eruyome** [comment]
According to the merged file this function here from the run script: 
```
AppendCustomMacros(userDirectory)
{
	If(!InStr(FileExist(userDirectory "\CustomMacros"), "D")) {
		FileCreateDir, %userDirectory%\CustomMacros\
	}
	
	appendedMacros := "`n`n"
	extensions := "txt,ahk"
	Loop %userDirectory%\CustomMacros\*
	{
		If A_LoopFileExt in %extensions% 
		{
			FileRead, tmp, %A_LoopFileFullPath%
			appendedMacros .= "; appended custom macro file: " A_LoopFileName " ---------------------------------------------------"
			appendedMacros .= "`n" tmp "`n`n"
		}
	}
	
	Return appendedMacros
}
```

adds/merges `Run_ItemInfo.ahk` into hte main file. But This should only happen if this file is located in %USERPROFILE%\Documents\PoE-TradeMacro\CustomMacros\`.

**Comment by MerguezNight** [comment]
Welp, i'm a retard...

I was sure to had checked the folder, I was wrong.

Thanks for the help
It is working fine now :D

**Comment by Eruyome** [comment]
You're welcome. And please delete CustomMacros when the next stable version is released, the example file in there is not finished but will never be overwritten by any update.

**Comment by MerguezNight** [comment]
Will do
