### ISSUE TITLE
Doesn't appear Harbringer league on settings

### ISSUE THREAD

**Issue by Ispasnarcis** [PoE-TradeMacro/POE-TradeMacro#466]
Hi guys ,

I want to change the league from standard on Harbringer league but on settings i dont have this league ... Anyone had the same issue to not appear the new league on settings ? What i need to do to make apper Harbringer league ? I downloaded 3 times until now and nothing happend ... Please help

**Comment by dein0s** [comment]
TmpStandart and TmpHardcore for the challenge leagues.

**Comment by Eruyome** [comment]
Correct.
