### ISSUE TITLE
VerstionTrade.txt cannot be opened?

### ISSUE THREAD

**Issue by Sythril2017** [PoE-TradeMacro/POE-TradeMacro#467]
Installed Auto Hotkey
Downloaded PoE trade
Unzipped to C:\Users\Me\Desktop\PoE Trade
Double clicked Run_TradeMacro
Get error: http://tinyurl.com/ycp28ljo

This is within Windows 10, I originally tried running this on my D:\ (game install drive) but after finding a few posts that mentioned ProgramFiles(x86) tried it in there with the same results (as shown in screen).

**Comment by Eruyome** [comment]
Check if your AntiVir software blocks Autohotkey from writing/modifying files.

**Comment by Sythril2017** [comment]
I cannot find any setting for it to specify that as an option, normally I receive popups when something new is occurring (I have it set to notify me on all new occurrences).

**Comment by Eruyome** [comment]
Any chance that you haven't actually extracted the zip archive but simply navigated into it? Windows makes it easy to make that mistake.

**Comment by Eruyome** [comment]
Does the file exist?

**Comment by Sythril2017** [comment]
Definitely not still zipped and yes the file exists.

**Comment by Eruyome** [comment]
Is your AHK up to date? I noticed that the error message mentions
```
", C.\..." 
```
as the name/path of the file to be included. This may just be a weird way to display it or it's an issue with AHK treating this as the actual file path. If you have an older version I wouldn't be surprised if it doesn't recognize the `,` in the command correctly:
```
#Include, %A_ScriptDir%\resources\VersionTrade.txt

**Comment by Sythril2017** [comment]
I have ahk v 2.0 is this not a version I should be using?

**Comment by Eruyome** [comment]
Just some quote:

> AutoHotkey v2 is based on Chris’ plans for AutoHotkey’s future + AutoHotkey_L code. It is developed by Lexikos, too. It cleans up syntax, and introduces many script-breaking changes. You can already use it, although it may have some bugs. But you might have to change your scripts for every new version, and you cannot use a lot of forum scripts. AutoHotkey v2 is Unicode-only.
> It is not (yet) recommended to install this version.

**Comment by Sythril2017** [comment]
that gives me an error http://tinyurl.com/y9frqp54 If version 2 and above is not supported yet, where can i get earlier versions from since that is the latest version avaliable?

**Comment by Sythril2017** [comment]
Ok, downloaded version 1.1.26.041 of AutoHotKey but still returns the same error (I have associated .ahk files with the newly downloaded version).

**Comment by Sythril2017** [comment]
aha, it seems using the AutoHotKeyU64 application does not work (thought that was the x64 version) so am now running ok with the AutoHotKeyU32 application.

I am wondering if its possible to resize the app though, I have a 4K monitor running at 3840*2160 and the popup is tiny >.<

**Comment by Eruyome** [comment]
Hm, not really, I mean maybe but that would be quite a big rework. At least scaling everything up, just the tooltip may not be that much of  change, basically just changing the font size. I guess I'll include a config entry for this for now, I want to make a new release. Then I can work something out a bit later.

**Comment by Eruyome** [comment]
Btw, until then you can set the font size in the settings menu, ItemInfo tab.
