### ISSUE TITLE
getting a error suddenly

### ISSUE THREAD

**Issue by clickbaitzz** [PoE-TradeMacro/POE-TradeMacro#468]
the macro was working fine until now,i'm getting this error
http://imgur.com/a/Ts0n9

**Comment by TheNightWillCome** [comment]
Same on my end. Tried to move the folder in different places didnt work. Download it again didnt work either. Using Windows 10...

**Comment by thaalum** [comment]
Same error here.

**Comment by EmberAmbassador** [comment]
Glad I'm not the only one. Contrary to TheNightWillCome I am using Windows 7, if that is any help.

**Comment by bdg0** [comment]
This is due to poeninja's API being down. I don't think Eruyome can fix this.

**Comment by mrinfiniti** [comment]
I'm getting the same error, the interesting part is that if you use Ctrl + C on an item you can Ctrl + V out of the game, try it

**Comment by TheNightWillCome** [comment]
Working again. Thanks guys, it was the API down

**Comment by thaalum** [comment]
@mrinfiniti that is part of PoE, not TradeMacro

**Comment by DankRafft** [comment]
Still not working for me. Maybe arty is able to add some sort of workaround in case something like that happens again.
