### ISSUE TITLE
Map Warning: Not Stunned won't show up

### ISSUE THREAD

**Issue by BFGGaming** [PoE-TradeMacro/POE-TradeMacro#469]
The "If" clause that contains adding this warning is in the wrong place. Needs to be moved into the "b" section or outside that nested-if all together (since you've already tested for the stun anyways it doesn't need to be in either A or B).

After looking it may not be your issue, might be the base PoE-ItemInfo. I don't know who controls that.

**Comment by aRTy42** [comment]
It's ItemInfo and it should (and will) be moved outside the ifs alltogether. The order of the mods isn't safe to assume, so it could be either a or b.

Thanks for the report.

**Comment by aRTy42** [comment]
Fixed in the new TradeMacro release.
