### ISSUE TITLE
Run_Trademacro.ahk disappears

### ISSUE THREAD

**Issue by SabreCat** [PoE-TradeMacro/POE-TradeMacro#471]
After using the Trade Macro for a couple of sessions, the main Run_Trademacro.ahk file vanishes from its folder. I can run using the hidden _TradeMacroMain.ahk file, but I don't think that's intended!

**Comment by aRTy42** [comment]
Do you have any overzealous malware software that quarantined the file?

**Comment by SabreCat** [comment]
Not that I can tell! Nothing in the logs saying any threats have been detected.

**Comment by aRTy42** [comment]
That's quite odd. And yes, the hidden file isn't meant to be run directly.
I assume you re-downloaded/re-unpacked the file at least once. How often did it vanish?
Which operating system and what kind of malware/antivir programs do you use?

**Comment by SabreCat** [comment]
I redownloaded the last couple of times there was an update, and it went away a session or two after each. I'll try to keep a closer eye on when exactly it happens to provide more detail.

I'm on Windows 10, typically just run Windows Defender for ongoing malware/antivirus. (I have Malwarebytes but haven't scanned with it lately.)

**Comment by Eruyome** [comment]
I can assure you that there is no way that the file is being deleted by TradeMacro itself. Has to come from your windows in some way.

**Comment by SabreCat** [comment]
Prompted by the discussion here, I poked around a bit further, and found two copies of Run_TradeMacro.ahk in the Recycle Bin. 🤔 Could be some bizarre PEBKAC, but to cover all bases, does anything in the script ever send the Delete keystroke?

**Comment by Eruyome** [comment]
Then try using a shortcut to start TradeMacro, not touching the actual run script. Or a batch script.

**Comment by SabreCat** [comment]
OK, I'll try setting up an autostart shortcut and see if that resolves the issue!

**Comment by Eruyome** [comment]
No need for autostart, just make a desktop shortcut and play around with it a bit, you know, restarting the macro and so on.

**Comment by SabreCat** [comment]
This hasn't happened to me in the last few days, so iunno! Closing for now, I can reopen if I figure out what was going on and it turns out to be something this project could fix.
