### ISSUE TITLE
New client: 2.5.1 - doesn't work but loads.

### ISSUE THREAD

**Issue by kinkaito** [PoE-TradeMacro/POE-TradeMacro#475]
Previous versions worked perfect, current download it however starts up, the icon goes to the task manager, however nothing works.

IF i manually load up Fallback.exe the macro does work, but the lines to go between the prices/items however are all misaligned making it hard to read.

**Comment by Eruyome** [comment]
You sure about that? There are some issues here and there where the startup takes a bit because some requests to GGs API, poe.trade, poe.ninja take a while.

**Comment by kinkaito** [comment]
Eruyome - i honestly have no idea. i just started it up (for the 9th time) and it worked.

I did notice something though. in the system tray. the name was "_Path of Exile TradeMacro v2.5.1" when it wasn't working.
when it did work. the name was "Path of Exile TradeMacro v2.5.1"  without the "_"

**Comment by Eruyome** [comment]
Never paid any attention to that...
You can see if the dev version works better for you. There's an unimportant hidden Internet Explorer call at the end of initialization, it should be extremely fast but maybe it takes a while for you. I don't think that this blocks anything though. Anyway, I changed it to be asynchronous.
https://github.com/PoE-TradeMacro/POE-TradeMacro/archive/devEru.zip

**Comment by HMColeman** [comment]
http://i.imgur.com/8GEQKaE.jpg
It looks like it loads then seconds later I get error/crash.

**Comment by Eruyome** [comment]
Sigh... maybe I do have to make another release. @HMColeman I guess this was with the relase version, not the dev version that I linked?

**Comment by HMColeman** [comment]
Release version. I will try the dev version and get back to you.

**Comment by Eruyome** [comment]
I just updated the dev version btw.

**Comment by HMColeman** [comment]
I downloaded from the link after I commented and whatever version that was seems to work for me.

**Comment by Eruyome** [comment]
Can you still try it again to make sure you have the latest version?  You may see an Internet Explorer window opening for you and maybe a window asking you for some permissions. If yes I'd like to know if allowing this once and restarting the script skips all of this after that.

**Comment by HMColeman** [comment]
Downloaded from https://github.com/PoE-TradeMacro/POE-TradeMacro/archive/devEru.zip
Run_TradeMacro
UAC pops up, as is normal iirc
White icon in task bar with "Path of Exile TradeMacro v2.5.1" takes a minute to turn black and then is working as intended. Abnormally long load time, for me, compared to previous versions.

**Comment by Eruyome** [comment]
But no errors anymore and no IE windows popping up on script start?

**Comment by HMColeman** [comment]
No error

**Comment by kinkaito** [comment]
http://imgur.com/a/0U6g7
When this one loads i still have the problem (sorry i went to the store for the miss's so long delay)

tried the "Dev" one and "source code" and zip (in case they was different) don't know why, but when the "_" pops up it doesn't work, but when it isn't their it works, seems to be random o-o

**Comment by Eruyome** [comment]
I don't get whats going on here.
Could you edit `resources\ahk\TradeMacroInit.ahk` last lines and change 
```
	SetTimer, TrackUserCount, 100
```
to
```
	;SetTimer, TrackUserCount, 100
``` 
?

**Comment by Eruyome** [comment]
Did you use 2.5.0 without those issues or 2.4.0?

**Comment by HMColeman** [comment]
;SetTimer, TrackUserCount, 100
made it load faster for me. No other errors.

On my end, all issues are new to this release.

**Comment by Eruyome** [comment]
How much faster? Just a little bit? Is it consistent? Btw, updated again with an added sleep of 2 seconds before actually executing that function.

**Comment by HMColeman** [comment]
It opens in under 10 seconds as opposed to over a minute before.

Ok, just got 2.5.2 and issues seem to be back, possibly worse. The script never fully loads for me now.

**Comment by Eruyome** [comment]
Hm, I may have to deactivate that funtion for now and test a bit more with the help of some people.

**Comment by HMColeman** [comment]
The previous dev version with the one addition of ; actually worked the very best for me.
If I can help at all in a less spam your issue page kinda way let me know.

**Comment by Eruyome** [comment]
Joining the discord server and messaging me. But I guess I'll disable this function in the release that I'm gonna make now and take some time to test/improve this, so no gurry.

**Comment by kinkaito** [comment]
New update fixed the issue ^^ thank you
