### ISSUE TITLE
PoE-TradeMacro doesnt work

### ISSUE THREAD

**Issue by fataleast** [PoE-TradeMacro/POE-TradeMacro#476]
i have this problem since 2.0.0, but now its really impossible to use.
When i start script, after all loadings i get this http://imgur.com/78m8SGk
After that, i can only use Ctrl+C option, any other hotkey doesnt work at all. When i try to manage settings all i can find is this http://imgur.com/m0S2wOL .
Any suggestions? I really miss PoE-trademacro(((
P.S. Sorry for my bad english.

**Comment by dein0s** [comment]
Check this https://github.com/PoE-TradeMacro/POE-TradeMacro/issues/433

**Comment by fataleast** [comment]
Solved! Thank you!
