### ISSUE TITLE
Error upon auto-updating

### ISSUE THREAD

**Issue by chanci** [PoE-TradeMacro/POE-TradeMacro#479]
I have been able to update the macro good for a long time now. Since 2.5.0 when I click update it starts to download the zip and an error message pops up saying "Error downloading file to C:\Users\username\AppData\Local\Temp\POE-TradeMacro\release.zip. The update fails after that.

**Comment by aRTy42** [comment]
2.5.0 introduced an issue with the updater that was fixed again in 2.5.1. Download the latest version (2.5.2) manually and all should be fine.

**Comment by chanci** [comment]
Yes, it is working now, thanks :-)
