### ISSUE TITLE
Keeps bringing up IE upon startup

### ISSUE THREAD

**Issue by DarkDenizen** [PoE-TradeMacro/POE-TradeMacro#480]
Hi,

Upon startup, it keeps bringing up Internet Explorer, eventhough I use Chrome as my default browser.

Thanks

**Comment by aRTy42** [comment]
Is it about some IE setting that the browser wants you to confirm? If so, it shouldn't pop up again once you choose something.

The script uses windows tools to download files which are related to the IE. Just using those might trigger some IE settings even though you don't need to browser actively open.

**Comment by Eruyome** [comment]
That IE launch is intentional, though you seeing it should be because some issue (you seeing ti is a fallback/error handling). As aRTy already asked, are there any windows/popups asking you to confirm/allow something?

**Comment by GoWale** [comment]
It is the same for me IE11 starts every time i lunche PoE-Trade (Since 2.5.2 and with 2.5.3).
In the IE window i don't have any poup/question etc. to confirm something

**Comment by Eruyome** [comment]
I fixed some stuff regarding this. First off after the first successful start I'll write a file to the user folder, if that exists you won't ever use the fallback, which is starting a visible IE instance. It simply tries to start a hidden one. It's not that important anyway.

**Comment by torekk** [comment]
I have this problem as well and reloading the script several times lead to the behaviour that GoWale described: the IE window pops up, but then closes automatically(which didn't happen before). There's no popup asking me for permission though.

If it helps anything, I first "installed" the script into my downloads folder and later copied it into my PoE game folder, then updated it and selected a new folder, so e.g.:
From "E:\Downloads\POE-TradeMacro-2.4.0" to "C:\Path of Exile\POE-TradeMacro"

Not sure if that broke anything. I can't remember if I had anything to confirm the really first time I started the script.

**Comment by Eruyome** [comment]
https://github.com/PoE-TradeMacro/POE-TradeMacro/archive/devEru.zip
Try that.

**Comment by asduibg** [comment]
I have the same issue on 2.5.3. Internet Explorer opens every time, never asks for permissions.
Tried the version you just posted and it no longer does that.

**Comment by OmikronGamma** [comment]
Using 2.5.4, IE keeps poping up each time i start the script.

**Comment by Eruyome** [comment]
Are you letting IE finish loading or do you kill/close it before that?

**Comment by OmikronGamma** [comment]
Yes I am letting IE finish loading.

**Comment by Eruyome** [comment]
It currently works like this, if a successful load of that page with IE was detected, the file `IEComObjectCall.txt` is written to the user folder, if that file exists you won't get the IE window again.

Anyway, edt `lib\IEComObjectTestCall.ahk` and replace its contents with:
```
#SingleInstance, force

userFolderPath = %1%

; don't use the fallback if it was completed successfully once
; 
global Fallback := True
If (FileExist(userFolderPath "\IEComObjectCall.txt")) {
	Fallback := False
}

url := "https://poe-trademacro.github.io/userCount/index.html"
Try {   
	wb1 := ComObjCreate("InternetExplorer.Application")
	wb1.Visible := False
	wb1.Navigate(url)	
	IELoad(wb1, loaded, userFolderPath)
	wb1.quit
} Catch error {
	If (Fallback) {
		Try {
			wb2 := ComObjCreate("InternetExplorer.Application")
			wb2.Visible := True		
			wb2.Navigate(url)
			IELoad(wb2, loaded, userFolderPath)
			wb2.quit
		} Catch e {
			ExitApp
		}	
	}	
}

ExitApp

IELoad(wb, ByRef loaded = false, path = "")	;You need to send the IE handle to the function unless you define it as global.
{
	i := 0
	If !wb    ;If wb is not a valid pointer then quit
		Return False
	Loop
	{
		Sleep,100
		Try {
			loaded := wb.Document.getElementById("loaded").innerHTML = "Loaded." ? true : false
		} catch e {
		
		}
		i++
	}
	Until ((wb.Document.Readystate = "Complete" and loaded or i = 2000))
	msgbox % loaded "`n" wb.Document.Readystate "`n" i
	If (loaded and not FileExist(path "\IEComObjectCall.txt")) {
		FileAppend, true, %path%\IEComObjectCall.txt
		Fallback := False
	}
	
	Return True
}
```

Run the script again, there should be a messagebx that pops up once or twice.

**Comment by OmikronGamma** [comment]
OK, replaced code above, new pop-up window showed up, saying this everytime i loaded the script.

> 1
complete
1

Then i reverted the change, and no IE window and no this new warning at all.

**Comment by Eruyome** [comment]
Ok, I also made a small fix, not just adding a messagebox.
