### ISSUE TITLE
Error on line 4

### ISSUE THREAD

**Issue by DeathCabby** [PoE-TradeMacro/POE-TradeMacro#481]
I unzipped the file and when i try to open i get error on line 4

https://imgur.com/QTmyJRj

**Comment by aRTy42** [comment]
It looks like you have the Run_TradeMacro.ahk **file** on your desktop, not a link to it. You moved it away from all its data and resource files, so it doesn't find what it needs.

Put it back into the main folder with everything else or re-download the zip and unzip it again if you don't know how it was before. Then either start it from that folder or create a shortcut to the Run file. That shortcut can sit on your desktop then.

**Comment by Hitsuu** [comment]
I'm getting this error on a fresh download, haven't moved anything.

**Comment by aRTy42** [comment]
Is the folder on a drive or special system section with read/write protection?

Do you have any anti-malware software that might block unknown files entirely?

**Comment by Hitsuu** [comment]
Nope, just my downloads folder. I have no anti-malware software (don't
judge).

**Comment by aRTy42** [comment]
Did you unzip the folder? Windows lets you browse a zip file like a regular folder, but the zipped state doesn't allow regular file usage.

**Comment by Hitsuu** [comment]
No, thank you I'll try.

**Comment by aRTy42** [comment]
I'll guess it worked, so I'll close this for now. If it still doesn't work please re-open the issue.

**Comment by Hitsuu** [comment]
It did work, thank you.
