### ISSUE TITLE
ctrl + alt + C not workin

### ISSUE THREAD

**Issue by tudezzz** [PoE-TradeMacro/POE-TradeMacro#483]
Hi, 

Just watched Engineerings video and wanted to try out that shotcut but i keep getting error message that i cannot open new tab ? 

Tried to put chrome address into browser path and win10 browser fix but no help there.

**Comment by Eruyome** [comment]
Is that an InternetExplorer error? Is that your default browser? I only ever heard of an issue with it using IE.

**Comment by tudezzz** [comment]
no my default is chrome

**Comment by Eruyome** [comment]
What does this return/show? Save it as an .ahk file and run it.

```
application := AssociatedProgram("html")
msgbox % application
url := "www.google.com"
;Run, "%application%" -new-tab "%Url%"

;-- Function: AssociatedProgram
;-- Description: Returns the full path of the program (if any) associated to
;   a file extension (p_FileExt).
;-- Original author: TheGood
;       http://www.autohotkey.com/forum/viewtopic.php?p=363558#363558
;-- Modified by: Eruyome
;-- Programming note: AssocQueryStringA is never called because it returns
;   invalid results on Windows XP.
AssociatedProgram(p_FileExt) {
    program := ""
    ext     := p_FileExt
    Static ASSOCSTR_EXECUTABLE:=2

    ;-- Workaround for AutoHotkey Basic
    PtrType:=A_PtrSize ? "Ptr":"UInt"

    ;-- File extension
    if SubStr(p_FileExt,1,1)<>"."
        p_FileExt:="." . p_FileExt  ;-- Prepend dot

    ;-- If needed, convert file extension to Unicode
    l_FileExtW:=p_FileExt
    if not A_IsUnicode
        {
        nSize:=StrLen(p_FileExt)+1          ;-- Size in chars including terminating null
        VarSetCapacity(l_FileExtW,nSize*2)  ;-- Size in bytes
        DllCall("MultiByteToWideChar","UInt",0,"UInt",0,PtrType,&p_FileExt,"Int",-1,PtrType,&l_FileExtW,"Int",nSize)
        }

    ;-- Get the full path to the program
    VarSetCapacity(l_EXENameW,65536,0)      ;-- Size allows for 32K characters
    DllCall("shlwapi.dll\AssocQueryStringW"
        ,"UInt",0                           ;-- ASSOCF flags
        ,"UInt",ASSOCSTR_EXECUTABLE         ;-- ASSOCSTR flags
        ,PtrType,&l_FileExtW                ;-- pszAssoc (file extension used)
        ,PtrType,0                          ;-- pszExtra (not used)
        ,PtrType,&l_EXENameW                ;-- pszOut (output string)
        ,PtrType . "*",65536)               ;-- pcchOut (len of the output string)

    ;-- If needed, convert result back to ANSI
    if A_IsUnicode
        program := l_EXENameW
     else {
        nSize:=DllCall("WideCharToMultiByte","UInt",0,"UInt",0,PtrType,&l_EXENameW,"Int",-1,PtrType,0,"Int",0,PtrType,0,PtrType,0)
            ;-- Returns the number of bytes including the terminating null

        VarSetCapacity(l_EXEName,nSize)
        DllCall("WideCharToMultiByte","UInt",0,"UInt",0,PtrType,&l_EXENameW,"Int",-1,PtrType,&l_EXEName,"Int",nSize,PtrType,0,PtrType,0)
        program := l_EXEName
    }

    if (not StrLen(program)) {
        program := AssocQueryApp(ext)
    }
    Return program
}

AssocQueryApp(ext) {
    RegRead, type, HKCR, .%ext%
    RegRead, act , HKCR, %type%\shell
    If ErrorLevel
        act = open
    RegRead, cmd , HKCR, %type%\shell\%act%\command
    app := RegExReplace(cmd, "("".*?"").*","$1")
    Return, app
}
```

**Comment by tudezzz** [comment]
![result](https://user-images.githubusercontent.com/31565082/30001777-bda53606-90a0-11e7-9a81-236d51b81066.JPG)

**Comment by Eruyome** [comment]
Have you seen my edit? It opens the url without specifying the application.

**Comment by tudezzz** [comment]
same result as before. i assume you meant this as edited: 

;Run, "%application%" -new-tab "%Url%" -> Run, "%Url%"

both these give same result.

**Comment by Eruyome** [comment]
The first line was the one that seems to cuase you problems, so I commented/disabled it.
The second should open the browser AHK thinks is your default one but shouldn't cause any error,

Is everything I said correct?
And the first line still causes an error if you would uncomment it?

**Comment by Eruyome** [comment]
Ok, I edited it again, please tell me what happens.

**Comment by tudezzz** [comment]
Hmm not sure if i am doing this right, bit rusty on my programming but when i replaced first line to:

;Run, "%application%" -new-tab "%Url%"

and removed that semicolon on front, i didn't get error same response as last time but this time when i closed that popup window it will open my desktop on a browser

**Comment by Eruyome** [comment]
I had that issue before while playing around with functions that return the associated program and didn't get a response... I guess `Run, "missing application/empty string" -new-tab` just opens the windows explorer.

**Comment by tudezzz** [comment]
yeah it does
tried your edited script (didn't know i had to reload page before it showed) ;) 

same response as last time and opens windows explorer

**Comment by tudezzz** [comment]
![original error](https://user-images.githubusercontent.com/31565082/30001869-a30e4e60-90a3-11e7-9efc-949efe60ffd5.JPG)

This is the error i get when trying ctrl +alt + c item. sadly it's in finnish but rougly translated:

Target -new-tab doesn't found. Make sure you typed name right and try again

**Comment by Eruyome** [comment]
Yeah, the script uses an application that doesn't understand the -new-tab arguments, which should be fixed  by wrapping it in a try catch block. I don't know why that code above opens an explorer window though, have to fix that first....

**Comment by Eruyome** [comment]
Well I was an idiot, that's why. Anyway, copy the entire code block again and test it.

**Comment by tudezzz** [comment]
no shame admitting when you have made error :) 

now it open new tab on chrome

**Comment by Eruyome** [comment]
Nice, seen my question about Edge? ninja edited it again.

**Comment by tudezzz** [comment]
yeah i have it installed and didn't notice it before :)

**Comment by Eruyome** [comment]
I had a user who reported that his `application` variable contains `system32/launchwinapp.exe`, which seems to be Edge. Can you try this code, first with the second line commented, then switch them. I want to know if any of those lines open Edge.
```
application := "system32/launchwinapp.exe"
url := "www.google.com"
Run, "%application%" "%Url%"
;Run microsoft-edge:%Url%
```

**Comment by tudezzz** [comment]
first line not commented returns same error message and does nothing after that and when first line is commented and second is not, i get same error message but it does open edge

**Comment by Eruyome** [comment]
Did you use just the 4 lines I gave you or added that to the big code block?

**Comment by tudezzz** [comment]
added in the big block

**Comment by tudezzz** [comment]
and with just 4 lines you wrote, nothing happens with either one

**Comment by Eruyome** [comment]
use it in a new file, nothing else

**Comment by Eruyome** [comment]
```
application := "system32/launchwinapp.exe"
url := "www.google.com"
Run, "%application%" "%url%"
;Run microsoft-edge:%url%
```

try that

**Comment by tudezzz** [comment]
nothing happens with either of them

**Comment by Eruyome** [comment]
``` 
Run,%windir%\explorer.exe shell:Appsfolder\Microsoft.MicrosoftEdge_8wekyb3d8bbwe!MicrosoftEdge http://www.rainymood.com/
```

This?

**Comment by tudezzz** [comment]
just that line ?

**Comment by Eruyome** [comment]
yes

**Comment by tudezzz** [comment]
opens windows explorer folder files

**Comment by Eruyome** [comment]
Trying to google this, for example
https://www.reddit.com/r/windows/comments/4aac5b/how_do_i_run_edge_browser_with_autohotkey/
https://www.reddit.com/r/AutoHotkey/comments/3kw3li/run_with_microsoftedgeexe/

This here should be able to open Edge 
```
IApplicationActivationManager := ComObjCreate("{45BA127D-10A8-46EA-8AB7-56EA9078943C}", "{2e941141-7f97-4756-ba1d-9decde894a3d}")
    DllCall(NumGet(NumGet(IApplicationActivationManager+0)+3*A_PtrSize), "Ptr", IApplicationActivationManager, "Str", "Microsoft.MicrosoftEdge_8wekyb3d8bbwe!MicrosoftEdge", "Str", 0, "UInt", 0, "IntP", processId)
    ObjRelease(IApplicationActivationManager)
```
But I have no idea how to open a specific url..

**Comment by Eruyome** [comment]
`Run,%A_WinDir%\explorer.exe shell:Appsfolder\Microsoft.MicrosoftEdge_8wekyb3d8bbwe!MicrosoftEdge http://www.rainymood.com/`

I made a mistake. Try this.

**Comment by tudezzz** [comment]
still just opens windows explorer on files

**Comment by Eruyome** [comment]
Edited last post.

**Comment by tudezzz** [comment]
yes now it opens edge without errors

**Comment by Eruyome** [comment]
but it doesn't open any specific url right?

how about this via windows console/cmdlet?

`start microsoft-edge:http://www.google.com`

**Comment by tudezzz** [comment]
yeah without any specific url. that console command also opens google.com on edge

**Comment by Eruyome** [comment]
This via AHK?
`Run, %comspec% /c "chcp 1251 & start microsoft-edge:%Url%"`

**Comment by tudezzz** [comment]
yeah opens edge through command console

**Comment by Eruyome** [comment]
Nice, complicated enough... thanks for your help^^
You can use the dev version for now until I make a new release https://github.com/PoE-TradeMacro/POE-TradeMacro/archive/devEru.zip

**Comment by tudezzz** [comment]
no no, thank you if you were able to solve it with my help :) 

I can live long enough for waiting new release, this was just feature i didn't know before and i think it is amazing feature :) 

Also big thank you for you and team behind this great macro.

**Comment by Eruyome** [comment]
I'm the team :p 
Well, I won't forget about aRTy (ItemInfo maintainer) though^^
