### ISSUE TITLE
Macro not working 

### ISSUE THREAD

**Issue by rasher007** [PoE-TradeMacro/POE-TradeMacro#484]
Please help 
endless reading cookies
![macro](https://user-images.githubusercontent.com/10233321/29995204-9d748846-8fec-11e7-9a18-ddbe731ce52b.png)

**Comment by Eruyome** [comment]
Not sure why it doesn't stop sometime. I guess you can open `%USERPROFILE%\config_trade.ini` with notepad and set `UseManualCookies = 1`.

This should skip that step but you'll have to follow these instructions and add cookies in the settingsmenu https://github.com/PoE-TradeMacro/POE-TradeMacro/wiki/Cookie-retrieval
