### ISSUE TITLE
Invalid Installation Path

### ISSUE THREAD

**Issue by Zahirlan** [PoE-TradeMacro/POE-TradeMacro#487]
Is there a way to remove/ or make this stop appearing. Everytime i try to open Poe.trade This thing always pop up Excuting PoE- TradeMacro from your Desktop ) or any of its subfolders) may cause script error, please choose a different directory. But Poe trade macro seem to work fine is just annoying why it always pop up everytime i try to open the application

**Comment by aRTy42** [comment]
It can cause errors, so there is a warning now. Without the warning, we get lots of people that can't run the script from there and don't know what is wrong.

Put the folder somewhere else and just place a shortcut to the Run_TradeMacro.ahk on your desktop if you want to have it there.
