### ISSUE TITLE
Error: Parameter #2 Invalid.

### ISSUE THREAD

**Issue by In3bitabl3** [PoE-TradeMacro/POE-TradeMacro#488]
"Specifically: Tab 3
  Line#
  792: Tab Names:= ""
  793: Loop,Scripts.Length()
  793:{
  794: name:= Scripts[A_Index]
  795: TabNames .= name"|"
  796: }
  798: StringTrimRight,TabNames,Tabnames, 1
->799: Gui,Add,Tab3,Choose1 h790 x0,%TabNames%

**Comment by Eruyome** [comment]
Never seen that one before, you have that always?

**Comment by LightningDev** [comment]
I have the same problem but I solved it by installing the AutoHotkey version v1.1.26.01, before that I installed the version 1.1.22.07. Hope this help you!
