### ISSUE TITLE
[Fixed?] Error when launching script.

### ISSUE THREAD

**Issue by Matuir** [PoE-TradeMacro/POE-TradeMacro#49]
http://i.imgur.com/EFwqsxC.png
Line 10649 has an error when I try to run "Run_Only_This.ahk"

**Comment by Penetrosity** [comment]
Having same error. Windows 7x64

**Comment by Penetrosity** [comment]
Killed old version of Longan I had running, removed it entirely.
Deleted all files from both downloads
Redownloaded 1.1.3.2
Working as intended now..

**Comment by Eruyome** [comment]
Nice, to be sure just completely wipe your installation before updating. In the future this may not be important but we had quite some huge changes since the old versions.

**Comment by Matuir** [comment]
Still not working, same error.

**Comment by Eruyome** [comment]
The newest release (1.1.3.4) should fix this.

**Comment by Matuir** [comment]
Fixed!
