### ISSUE TITLE
Issue with price checking.

### ISSUE THREAD

**Issue by Xropsha** [PoE-TradeMacro/POE-TradeMacro#491]
Hello. Is any way to use por trade macro if my ISP is blocking poe.trade site? It seems macros cannot connect to poe.trade when i press ctrl+d.

**Comment by Eruyome** [comment]
The macro attempts to read your Internet Explorers cookies/useragent after visiting poe.trade in the background. This may fail. In that case you can also try using manually retrieved cookies and input them in the settings menu. https://github.com/PoE-TradeMacro/POE-TradeMacro/wiki/Cookie-retrieval

If this also fails you will be limited to open searches directly in your browser instead of showing the tooltip.

**Comment by Xropsha** [comment]
Already tried this, but there is no cf_clearance line in my browser. Even Internet Explorer doenst have this line.

**Comment by Eruyome** [comment]
This cookie thing only works if poe.trade is protected by cloudflare and you get a redirect page when visiting poe.trade with deleted cookies. 
If that's not the case, if it's blocked by something else then you can't use cookies to bypass it.

So depending on the actual issue, I'm not sure if you can make it work. You can access poe.trade via browser, are you using any proxy/VPN? But you should at least be able to use the hotkeys that open your searches in your browser.

**Comment by Xropsha** [comment]
Yep, i have to use Firefox with friGate addon to get access to poe.trade.  Item info, wiki item page works well, but when i use ctrl+d to check price it takes few minutes with requesting search results then i get no item found message.

**Comment by Eruyome** [comment]
The macro uses [cURL](https://curl.haxx.se/), specificially `lib\curl.exe` for all requests. So unless you're using a VPN or if there's a way to bypass you're providers block for just that application, then you're not going to make this work. You'll be limited to use ctrl + q ot the "open on poe.trade" button on the advanced search gui.

**Comment by Xropsha** [comment]
Okay, i got it. Thank you for the information! I guess VPN is my way to go.

**Comment by Enigmer** [comment]
Problem with hotkeys, only Ctrl+I and Ctrl+L working, cant check the price with Ctrl+D juts nothing happens. Script is loading and running without any errors
