### ISSUE TITLE
Updater not working

### ISSUE THREAD

**Issue by Vytals** [PoE-TradeMacro/POE-TradeMacro#492]
Whenever I get the message saying there is a new update I am unable to update through the program.  I have to manually install and run it from scratch. 

The auto updater will ask for the path I want to save, work through the extraction, ask permission to run on the computer and then whatever happens after that doesn't finish.

**Comment by pvpshoot** [comment]
hm..., i just download this app and nothing is hipping
I try to CTRL+S and .... nothing,
Can it be associated with last update?
_And i love that u prefer node js =)_

**Comment by aRTy42** [comment]
> I try to CTRL+S and .... nothing

There is not default function with +S, the default price checking would be +D. Or is it a typo here?

**Comment by pvpshoot** [comment]
oh, sorry, yes it was typo
I tried it, and ctrl+L didn't work too =(

**Comment by Krzysiu** [comment]
I had this problem since autoupdate was provided, but the last version was the first one which did it flawlessly. I'm not telling it should work for others. Just it's fine for me.
