### ISSUE TITLE
Error at Line 6

### ISSUE THREAD

**Issue by c2ho2** [PoE-TradeMacro/POE-TradeMacro#494]
![image](https://user-images.githubusercontent.com/16774450/30041315-b6312ee4-921b-11e7-8453-e81557fd4f81.png)

I updated my POE-TradeMacro and downloaded AHK 2.0.
But this error happens.

**Comment by aRTy42** [comment]
Don't use 2.0, that's basically a 2nd project.

Go to https://autohotkey.com/download/ and click the blue/purple button at the top left. It should prompt you to download 1.1.26.01.
