### ISSUE TITLE
Some uniques variable mods are erroneous

### ISSUE THREAD

**Issue by MalakaJones** [PoE-TradeMacro/POE-TradeMacro#495]
If you look at this item variable mods, it sets it to minimum 160% increased physical damage. Although, this item %dmg range is much lower. I've got a similar issue with Cameria's Maul.

![image](https://user-images.githubusercontent.com/15826583/30046614-23ffe862-91da-11e7-9f21-dd05aee79147.png)

**Comment by Eruyome** [comment]
I get this data from the wiki, it may have been updated there rather late and I need to request and update it again.

**Comment by MalakaJones** [comment]
So those values are not hard coded. That's good news.
