### ISSUE TITLE
add please new trademacro hotkey

### ISSUE THREAD

**Issue by zizaran** [PoE-TradeMacro/POE-TradeMacro#496]
I'd like to see new hotkey for currency search with pressing combo of buttons to change currency ю It's so uncomfortably to alt-tab and every time choose new currency to check prices.  Sorry if I posted in a wrong section. This hotkey would be very useful. Thanks for your wonderful soft

**Comment by dein0s** [comment]
I'd assume that your main language is russian, so the following part will be in russian:
Опиши, пожалуйста, на русском - что ты хочешь получить в итоге и какова твоя текущая цепочка действий для достижения этого итога.

**Comment by zizaran** [comment]
[http://i.imgur.com/fmx6ZHy.png](url)

That's what I'd like to see and that would be very useful for everyone

**Comment by aRTy42** [comment]
You can use Ctrl+Q on currency to open the search form on poe.trade and then just switch chaos to something else and press search − that's three clicks.

Switching through a long list with a hotkey does not seem that much easier.

**Comment by Eruyome** [comment]
That's a bad idea, not gonna implement it. That's a list of 49 currencies.

**Comment by dein0s** [comment]
Actually 39 :) But still - that's a really bad idea to cycle through all of them, not worth it.
And you can always implement this for your personal needs via custom macros.
