### ISSUE TITLE
Script not working.

### ISSUE THREAD

**Issue by Nabulsii** [PoE-TradeMacro/POE-TradeMacro#497]
I downloaded it and tried it a few different days all with the same results. I open Run_TradeMacro (also tried to drag into AHK) and it acts like it will start. It gets to "initializing script", stays for a few seconds, and just closes completely. What do.

**Comment by Eruyome** [comment]
Are you sure it really closes instead of just running in the background? I'm not aware of any "crashes" that don't also have any kind of error message.

**Comment by Nabulsii** [comment]
I'm sure. I've gone into my task manager and don't see it in the programs or details.On Sep 6, 2017 00:30, Eruyome <notifications@github.com> wrote:Are you sure it really closes instead of just running in the background? I'm not aware of any "crashes" that don't also have any kind of error message.

**Comment by Eruyome** [comment]
Are you aware that it is simply called "AutoHotkey Uncideo 32-bit" or something like that?

**Comment by Nabulsii** [comment]
Yes. But 64-bit shows up instead of 32.On Sep 6, 2017 06:32, Eruyome <notifications@github.com> wrote:Are you aware that it is simply called "AutoHotkey Uncideo 32-bit" or something like that?

**Comment by Nabulsii** [comment]
Well, I got home from work and tried it again. I changed nothing and did nothing different, but it worked this time. Appreciate the help!

**Comment by Eruyome** [comment]
The best issues solve themselves.
