### ISSUE TITLE
IE window opens on every launch

### ISSUE THREAD

**Issue by Silvergreylion** [PoE-TradeMacro/POE-TradeMacro#500]
I hereby report that I get an IE window on every script start, since it said to report it.
Just updated to 2.5.5, same issue.

Using Windows 7 Ult x64 SP1, Autohotkey 1.1.26.01.
Do you need any other details?

**Comment by MaestroMaelstrom** [comment]
I am having this same issue.

**Comment by OmikronGamma** [comment]
Try solutions in this one
https://github.com/PoE-TradeMacro/POE-TradeMacro/issues/480

**Comment by Silvergreylion** [comment]
Perhaps I should elaborate on this; the IE window does not ask for any permission, this is all it says:

> Tala Moana, Exile.
>
> TradeMacro visits this page to make sure that it can open pages via Internet Explorer which is being used as a fallback in some circumstances. 
> For example, using Internet Explorer via ComObjects is necessary to read your user-agent in case that you need cookies for a CloudFlare bypass. 
>
> You should see the IE instance/window visiting this page only once so that IE can ask you for permission. 
> If this IE window opens every time at script start for you please report it. Loaded. 

I would be fine with this if the window closed automatically after 3-4 secs.

IE version is 11.0.9600.18449.

**Comment by Eruyome** [comment]
@Silvergreylion Replace `lib\IEComObjectTestCall.ahk` with this:

```
#SingleInstance, force

userFolderPath = %1%

; don't use the fallback if it was completed successfully once
; 
global Fallback := True
global wb1 := 
global wb2 :=
If (FileExist(userFolderPath "\IEComObjectCall.txt")) {
	Fallback := False
}

url := "https://poe-trademacro.github.io/userCount/index.html"
Try {   
	wb1 := ComObjCreate("InternetExplorer.Application")
	wb1.Visible := False
	wb1.Navigate(url)	
	IELoad(wb1, loaded, userFolderPath)
} Catch error {
	If (Fallback) {
		Try {
			wb2 := ComObjCreate("InternetExplorer.Application")
			wb2.Visible := True		
			wb2.Navigate(url)
			IELoad(wb2, loaded, userFolderPath)			
		} Catch e {
			CleanIE()
		}	
	}	
}

CleanIE() {
	Try {			
		wb1.Quit
		wb2.Quit	
	} Catch e {
		
	}
	ExitApp
}	

IELoad(wb, ByRef loaded = false, path = "")	;You need to send the IE handle to the function unless you define it as global.
{
	i := 0
	If !wb    ;If wb is not a valid pointer then quit
		Return False
	Loop
	{
		Sleep,100
		Try {
			loaded	:= wb.Document.getElementById("loaded").innerHTML = "Loaded." ? true : false
		} catch e {
			
		}
		Try {
			ready	:= wb.Document.Readystate
		} catch a {
			
		}
		i++
	}
	Until ((ready = "Complete" and loaded or i = 2000))
	
	If (loaded and not FileExist(path "\IEComObjectCall.txt")) {
		FileAppend, true, %path%\IEComObjectCall.txt
		Fallback := False
	}
	
	CleanIE()
	
	Return True
}
```

**Comment by noraj1337** [comment]
Windows Server 2012 Datacenter Edition
ItemInfo 3.0.03
TradeMacro 2.5.5
AutoHotKey 1.1.26.01

**Comment by KRAZY13omber** [comment]
Windows 10 home
TradeMacro 2.5.5
AHK 1.1.26.01

Unsure of the item info but everything is up to date as of a few days ago.
Having the same issue and get this. Only posting as it asks to notify if the issue occurs 
![image](https://user-images.githubusercontent.com/31776056/30223937-ac3cda06-9481-11e7-8984-c6009357096a.png)

**Comment by Eruyome** [comment]
@noraj1337 and @KRAZY13omber , have any of you tried what I suggested in my last comment?

**Comment by Warsteiner88** [comment]
@Eruyome 
I had the same Problem which was fixed with your suggestion. Thanks.

**Comment by Silvergreylion** [comment]
I replaced that file with your suggestion and it seems to have worked, no IE window on launch. Thanks :)

**Comment by noraj1337** [comment]
@Eruyome Yes it works, no IE Window. Can you push it into next release?
