### ISSUE TITLE
Incorrect resistance pseudo mods

### ISSUE THREAD

**Issue by Pyr0Byt3** [PoE-TradeMacro/POE-TradeMacro#501]
The resist pseudo mods for this item are double what they should be in the ctrl-c tooltip.

![image](https://user-images.githubusercontent.com/1373374/30136017-1bbdcafa-932b-11e7-88bf-0716271db675.png)
```
Rarity: Normal
Prismatic Ring
--------
Requirements:
Level: 30
--------
Item Level: 80
--------
+8% to all Elemental Resistances
```
![image](https://user-images.githubusercontent.com/1373374/30136064-49236bbc-932b-11e7-8e28-e3b5aef2189d.png)

**Comment by dein0s** [comment]
Well, same with the two-stone white base:
![two_stone](https://i.imgur.com/CmClefw.png)

Everything looks fine with rare rings tho:
![prismatic_rare](https://i.imgur.com/93PmG5f.png)
![two_stone_rare](https://i.imgur.com/vXKwsy2.png)

@aRTy42 take a look, guess it's cos of iteminfo.

**Comment by aRTy42** [comment]
It's all white items in general, the script expects some kinds of mod, so the implicits gets mistaken for the explicit stats and counted twice.

Eru and I know about this bug, we just didn't prioritise fixing it.

Thanks for the report though.

**Comment by Eruyome** [comment]
Fixed.
