### ISSUE TITLE
Error on Launch

### ISSUE THREAD

**Issue by DrCheech** [PoE-TradeMacro/POE-TradeMacro#509]
When I try to launch with AHK I get "#include file "*i %A_ScriptDir%\resources\VersionTrade.txt" cannot be opened." It's been extracted and I tried with various AHK versions and it just keep giving me the same error.

**Comment by Eruyome** [comment]
Which AHK versions did you try?

The `*i` tells ahk to ignore any read errors of this file, so there's something weird going on here.

**Comment by DrCheech** [comment]
I tried each of the 2 current versions that the VersionTrade said are compatible(1.1.26.00, 1.1.26.01) and also some of the previous versions.

**Comment by DrCheech** [comment]
I tried with both the 2 most recent versions of the macro as well and it still kept happening. Is there a specific folder(i.e. the PoE folder) I have to place it in?

**Comment by DrCheech** [comment]
Nevermind, found the issue. My computer was starting it as a completely different file type for some reason even though it has AHK as the designated program. Thanks for the fast response though.

**Comment by Eruyome** [comment]
If `Run_TradeMacro.ahk` wasn't associated with AHK you would never have gotten that error message anyway. So I don't quite understand what you actually did, what your issue was.

**Comment by DrCheech** [comment]
For whatever reason, my computer was recognizing that it was an AHK file, but it didn't run it as a script. I had to specifically choose to run it as a script in order for it to function(in my case, that's a right click menu).

**Comment by Eruyome** [comment]
Try manually assigning .ahk files to the AHK executable, in fact there are 4 of them int he AHK install folder, I had a user where choosing the Unicode 64 bit version fixed this.

**Comment by Dmichels11** [comment]
I am having the same issue when I attempt to launch Run_TradeMacro.ahk. However, mine is set to run as a script but is still having issues.

**Comment by aRTy42** [comment]
Put the unzip results into a folder and place that folder somewhere on your computer where you usually have programs (for example C:\Program Files\).

The downloads folder might come with permission restrictions.

**Comment by Dmichels11** [comment]
Thank you for the quick response! I went ahead and tried it in a different folder and a different hard drive and am still shown the same error unfortunately. Any other ideas?

**Comment by Eruyome** [comment]
What's your AHK version and which folder/path are you using now?

**Comment by Dmichels11** [comment]
I'm currently running AHK 1.0.00 and I tried running the script from a folder I created here: T:\Path of Exile Trade Macro

**Comment by Eruyome** [comment]
Uninstall AHK, reinstall the newest version.

**Comment by Dmichels11** [comment]
Thank you for the tip! That did the trick!

**Comment by kolenj** [comment]
thx @Eruyome
