### ISSUE TITLE
error messages

### ISSUE THREAD

**Issue by hsmagnet** [PoE-TradeMacro/POE-TradeMacro#510]
still getting errors
![poetrade](https://user-images.githubusercontent.com/31567350/30246007-ad505f14-95ba-11e7-8a6a-ecc792365635.jpg)

**Comment by dein0s** [comment]
Duplicates https://github.com/PoE-TradeMacro/POE-TradeMacro/issues/498

**Comment by aRTy42** [comment]
You seem to have several old folders still lying around. At the top is says something that ends with ".../ahk/POE-TradeMacro-2.5.5" but on the left side below the error dialog there are TradeMacro folders such as data, data_trade, lib etc. next to Fallout New Vegas. Remove old stuff please.

If you got several old folder still around and they are within the file path of the current version, that can cause issues.

**Comment by hsmagnet** [comment]
thank you.

bad housekeeping has bit me before ...
