### ISSUE TITLE
Unclear ItemInfo tooltip

### ISSUE THREAD

**Issue by dukilupp** [PoE-TradeMacro/POE-TradeMacro#511]
![photo](https://user-images.githubusercontent.com/31819666/30248527-08a63fb8-965c-11e7-8503-095f576a125c.png)

I have some problems in description.

a) in the 「+45 to Strength  43-50 (74)  8-55 (82)  T2  S」, what is the meaning of 「(74)」,「 8-55」and「(82)」?

b) what is the meaning of 「(pseudo)」such as 「(pseudo) +55 to maximum Life」?

Thank you

**Comment by dein0s** [comment]
> a) in the 「+45 to Strength 43-50 (74) 8-55 (82) T2 S」, what is the meaning of 「(74)」,「 8-55」and「(82)」?

`74` - current tier of affix (they are divided into tiers by itemlevel), `8-55` - range of all possible rolls for that affix.
Use http://poeaffix.net for more info.

> b) what is the meaning of 「(pseudo)」such as 「(pseudo) +55 to maximum Life」?

Apart from the flat affix `+33 to maximum life`, `pseudo` also taking into account life bonus from strength.
[Every 10 strength grants an additional 5 maximum life.](https://pathofexile.gamepedia.com/Strength)

**Comment by Eruyome** [comment]
I'll think about a way to make this easier to understand, don't want to add multiple lines of descriptions to that tooltip though.
