### ISSUE TITLE
Allow fixed-value mods in advanced pricecheck for unique variants

### ISSUE THREAD

**Issue by philroberts** [PoE-TradeMacro/POE-TradeMacro#512]
It would be nice to be able to search for, e.g., Vessel of Vinktar's fixed lightning pen mod when you have that variant.

**Comment by aRTy42** [comment]
With the bug you pointed out at https://github.com/aRTy42/POE-ItemInfo/issues/99 being fixed, the advanced price search works for Vinktar's, so you can check the mod line if you want that specific variant.

**Comment by philroberts** [comment]
Does it work for all variants though?

**Comment by aRTy42** [comment]
Good point. Testing it with the debug mode suggests it would only work for added damage to spells/attacks variants, because those mods are variable, whereas the other lines are static.

I'm not sure how easy it would be to adjust the style variant uniques in general.

**Comment by Eruyome** [comment]
Variants work in general, only using the mods that are on the actual item but also only if the item mods with variable values.

I don't like making the advanced check available for items that don't have any variable mods. I could think of a way to automatically include the variant mod/mods on a unique item in every search. That way you'd only find the unique that you have, not all variants.
