### ISSUE TITLE
Upon starting the ahk script the program stops completely.

### ISSUE THREAD

**Issue by Svenning123** [PoE-TradeMacro/POE-TradeMacro#513]
Ill try to go through the exact problem.

I start the run_trademacro.ahk script
Asks for permission to run, i press yes.
popup in the middle of the screen "starting and merging scripts".
I start the script, an ahk icon appears, not a poe icon.
No commands work.
After several minutes the "starting and merging scripts" popup appears again, this time it crashes instantly.

Trying to delete the folder fails since a program in it is still being used, this program is the "curl.exe" program.

Reinstalled ahk multiple times, restarted multiple times, redownloaded the zip multiple times.
Tried running from desktop, from inside my hdd and also from inside my sdd.

I feel like im out of options and need some guidance on what to try next.

**Comment by Eruyome** [comment]
Check the `temp\` folder inside the trademacro folder, there should be a file `StartupLog.txt`. cURL is being used to make all the requests to GGGs API, poe.trade, github etc. 
Maybe the request times out but cURL doesn't quit waiting. The mentioned file logs all of those requests, we could at least see if one of them goes through.

**Comment by Clarynaa** [comment]
I have this exact problem, there is nothing in the temp folder, at all.  It worked fine yesterday.

**Comment by Eruyome** [comment]
Just close the script at that point.

**Comment by Clarynaa** [comment]
In my case, I was having DNS issues, and very little was able to resolve.  After restarting my PC to fix my DNS issues it worked fine.

**Comment by Eruyome** [comment]
Nice, I should add a timeout to all curl requests though.

**Comment by Svenning123** [comment]
Adding to this, fixing dns problems fixed my problems, i turned off p2p transfer on windows updates and the program now starts correctly, if anyone with similar problems read this try all methods you can find that fixes dns problems.
