### ISSUE TITLE
Sidhebreath Paua Amulet's explicit range on Shop lookup

### ISSUE THREAD

**Issue by VADemon** [PoE-TradeMacro/POE-TradeMacro#515]
Wiki: https://pathofexile.gamepedia.com/Sidhebreath
The explicit: "(15-10)% reduced Mana Cost of Minion Skills"

Factually, 15 is good and 10 is bad - same logic as with "normal" modifiers despite reversed annotation.
If you do a Ctrl+Q or advanced look up on poe.trade, it will fill the filter as follows: "x% reduced Mana Cost of Minion Skills | min 15 | max 9" and yield [no results](http://poe.trade/search/mahisiitanaret)
However for poe.trade to understand that, the minimal value must be mathematically closer to zero; if you want to use this as a filter you must [enter (min 9 | max 15)](http://poe.trade/search/ounokinomihoho).

I believe this bug affects all other items with reversedly written modifiers.
Both poe.trade and poeapp.com need the mathematical ascending order in order (hehe) to filter correctly.

**Comment by Eruyome** [comment]
So I guess, I just have to reverse the min  and max value if min > max, right? 
@aRTy42 you know of any cases where this would cause issues?

**Comment by Eruyome** [comment]
Fixed.

**Comment by aRTy42** [comment]
No case comes to mind right now.
