### ISSUE TITLE
I'm New and having a DL Error

### ISSUE THREAD

**Issue by Parligaming** [PoE-TradeMacro/POE-TradeMacro#516]
Ok so using the macro is completely new to me.  Everybody makes it sound so simple to install and get running so i thought, what the heck.  However I've been working at this for almost 2 hours so far not understanding what my problem is, but I feel that I at least have a conclusion.  So, I use 7zip, and whenever I go to unzip the file it says that there is a checksum error.  It also says that it cannot open it as a zip archive but as a PE archive instead.  So when I open the folder there is no script to run.  I don't know if I am doing something wrong, but any help would be appreciated.

**Comment by aRTy42** [comment]
Googling the problem suggests the zip download might have been corrupted, try downloading the zip again.

Also you should check whether some kind of anti-virus/malware software is interrupting 7zip midway to scan the files first, which might be solved by manually choosing the scan before unzipping.
