### ISSUE TITLE
Script opens wrong browser and the opened window does not retain settings

### ISSUE THREAD

**Issue by Lame4Fame** [PoE-TradeMacro/POE-TradeMacro#517]
Hey, 
I recently installed the ahk and I think the script works great, I have a small issue though. 
I have both chrome and firefox installed, the former is selected as standard browser (through windows 7, works fine with most other things as far as I can tell). 

However if I use any function that requires a browser, like the item search (ctrl + d) or wiki (ctrl + w) shortcuts it opens in firefox instead of chrome. When I change the path manually to my chrome.exe it uses chrome but opens a new window instead of a tab and it acts like a completely clean browser, without any of my user settings/data (like bookmarks) and chrome also tells me it is currently not my standard browser and asks if I want to configure it as such (does not happen when I use it normally).

It might be an issue with my Windows/browser and not the script but I still thought I'd ask if there was anything I could change to make it work like it's supposed to.

**Comment by Eruyome** [comment]
To be exact, the script has a few functions to determine your default browser (a few fallbacks), in your case the script might take the browser associated to .htm/.html files, which doesn't have to be your systems default browser.

Haven't heard of that second issue before, maybe you have more than one chrome installation/executables on your system?

**Comment by Lame4Fame** [comment]
I might have multiple Installations of chrome but I specified the path to the exe that my usual shortcuts use as well so I don't see how that would cause it. Oh and plugins/addons I use like ad block are missing, too.

As for the default application to open htm(l) that's chrome as well, according to windows.
Pretty weird.

Thanks for responding!

**Comment by Lame4Fame** [comment]
Okay nevermind. I just restarted it and now it works. Not sure what I did wrong but the case is closed. It works without specifying a directory, too!
