### ISSUE TITLE
Config directory typo?

### ISSUE THREAD

**Issue by cbynep** [PoE-TradeMacro/POE-TradeMacro#520]
2.5.5 version stores it's config files and folders in users/x/documents root directory, rather than it's own.
Also it keeps opening IE window every startup, but maybe it's related to my IE settings, so I wouldn't call it a bug and it doesn't bother me enough to test the cause.

**Comment by Eruyome** [comment]
I did find those files in the mentioned directory. but after deleting them they don't reappear there, no matter what I do.

**Comment by dein0s** [comment]
I also found userfiles in documents root several times, but didn't pay much attention to this as I thought it maybe related to my dev/testing activities.
I'll try to remember steps next time I meet such behaviour.

**Comment by Eruyome** [comment]
I find it hard to believe that this is an issue with the current 2.5.5 version since I can't reproduce it. Maybe it's an issue with an older version?

**Comment by dein0s** [comment]
I faced this in 2.5.4/2.5.5 when I started my work on converting keys to key codes. And I can sware that it happened at least once with 2.5.5, but there might be some non-default conditions like debug points/debug message boxes, premature script shutdown and so. Thus my steps/env cannot be taken as a valid steps to reproduce.
Anyway, I'll try to pay more attentiont on it.

**Comment by cbynep** [comment]
Ok, looks like this happens when you use fallback.exe, not ahk file directly. Didn't test much, but it's the same on 2.5.4

**Comment by dein0s** [comment]
Happens when executing compiled version `_TradeMacroMain.ahk`, with and without admin rights.
Can be reproduced with current devEru branch (at commit https://github.com/PoE-TradeMacro/POE-TradeMacro/commit/f774ed4f9065e21795e83f006def7c5da2964032).

**Comment by Eruyome** [comment]
Fixed.
