### ISSUE TITLE
Dual Resistance Summation erroreous

### ISSUE THREAD

**Issue by LyskOnGithub** [PoE-TradeMacro/POE-TradeMacro#522]
As shown below, the summation of dual resistance mods calculates double the actual value.

<img width="395" alt="ttb_resistances" src="https://user-images.githubusercontent.com/24275161/30743172-d800ce92-9f9c-11e7-9ab2-82d4ffd40c41.png">

**Comment by aRTy42** [comment]
It's all white items with implicits in general. It was discussed at #501 and marked as fixed by Eru about a week ago. Should be fine in the next release.
