### ISSUE TITLE
Tried to do a search, now macro stopped working

### ISSUE THREAD

**Issue by Blackrock2318** [PoE-TradeMacro/POE-TradeMacro#523]
did a ctrl+d search on a unique, stuck on searching for results and hung for a while, after a minute i force closed the macro, tried to re open it and it hung on initializing. Deleted all the folders in documents and the macro, redownloaded poe macro and cleared cache/history/cookies etc on chrome. Re opened poe macro fresh and hangs on initializing for 5ish minutes then goes to "reading user agent and cookies from poe.trade, this can take a few seconds if your internet explorer doesn't have the cookies cached." after 5 more minutes it pops up with a nice big error which will be shown below. I also have difficulties with loading up poe.trade, takes a rather long time to load up front page but even then it doesn't fully load it, seems to be connected to the macro not being able to do its thing, everything else loads up fine just not poe.trade.

https://ibb.co/cnuQm5

**Comment by aRTy42** [comment]
poe.trade is having issues at the moment, see [here](https://www.reddit.com/r/pathofexile/comments/71wwph/is_poetrade_down_or_is_it_just_me/) for example.

Consequently the TradeMacro can't use it properly. The macro itself should be fine (so you don't need to reinstall anything), you just need to wait for poe.trade to get back to normal.
