### ISSUE TITLE
initalizing script

### ISSUE THREAD

**Issue by clagger78** [PoE-TradeMacro/POE-TradeMacro#525]
Been running macro fine for a few days now when i run script i only get the message initalizing script.
I can run the trade item info script fine tho.

**Comment by Neph0** [comment]
So, what exactly is the issue?

**Comment by clagger78** [comment]
the poe trade macro wont run just says inialinzing script it was working fine for a week then has now just stopped and i get that message in middle of my screen but like i said the poe item info runs fine but not the tarade macro.

**Comment by Neph0** [comment]
Can you access [poe.trade](poe.trade) without any trouble?

**Comment by clagger78** [comment]
yes i can ill just have to not bother with the marco then.

**Comment by Eruyome** [comment]
Please check if the file `temp\StartupLog.txt` exists and post it contents here.

**Comment by clagger78** [comment]
were ,will i find this as im clueless at this sort of stuff:(

**Comment by Eruyome** [comment]
In your trademacro folder.

**Comment by clagger78** [comment]
Starting up PoE-TradeMacro....

----------------------------------------------------------
2017-09-30T13:55Z
----------------------------------------------------------

Requesting leagues from api.pathofexile.com...

cURL command:
"C:\Users\lee\Desktop\trade\POE-TradeMacro-2.5.6\lib\curl.exe" "http://api.pathofexile.com/leagues?type=main" -ILks -H "Host:api.pathofexile.com" -H "Connection:keep-alive" -H "Cache-Control:max-age=0" -H "Content-type:application/x-www-form-urlencoded; charset=UTF-8" -H "Accept:text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8" -H "User-Agent:Mozilla/5.0 (Windows NT 6.3; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.90 Safari/537.36" --max-time 90 

Answer:
HTTP/1.1 302 Found
Server: nginx/1.8.1
Date: Sat, 30 Sep 2017 13:55:04 GMT
Content-Type: text/html; charset=UTF-8
Connection: keep-alive
Expires: Thu, 19 Nov 1981 08:52:00 GMT
Cache-Control: no-store, no-cache, must-revalidate
Pragma: no-cache
Set-Cookie: POESESSID=149827e597a2c97500502daac9f618aa; path=/; domain=.pathofexile.com; HttpOnly
Location: /login/?redir=%2Fleagues%3Ftype%3Dmain
X-Frame-Options: SAMEORIGIN

HTTP/1.1 404
Server: nginx/1.8.1
Date: Sat, 30 Sep 2017 13:55:04 GMT
Content-Type: text/html; charset=UTF-8
Connection: keep-alive
Expires: Thu, 19 Nov 1981 08:52:00 GMT
Cache-Control: no-store, no-cache, must-revalidate
Pragma: no-cache
Set-Cookie: POESESSID=d475616a671c273b6b150208a81c3128; path=/; domain=.pathofexile.com; HttpOnly



----------------------------------------------------------
2017-09-30T13:55Z
----------------------------------------------------------

Testing CloudFlare bypass, connecting to http://poe.trade...

cURL command:
"C:\Users\lee\Desktop\trade\POE-TradeMacro-2.5.6\lib\curl.exe" "http://poe.trade" -ILks -H "User-Agent:Mozilla/5.0 (Windows NT 6.3; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/59.0.3071.115 Safari/537.36" -H "Accept:text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8" -H "Accept-Encoding:gzip, deflate" -H "Accept-Language:de-DE,de;q=0.8,en-US;q=0.6,en;q=0.4" -H "Connection:keep-alive" -H "Host:poe.trade" -H "Upgrade-Insecure-Requests:1" --max-time 90 

Answer:
HTTP/1.1 200 OK
Date: Sat, 30 Sep 2017 13:55:05 GMT
Content-Type: text/html; charset=utf-8
Connection: keep-alive
Set-Cookie: __cfduid=dc9ae2ba2bf3a3bd76c3cca892da0e7e61506779705; expires=Sun, 30-Sep-18 13:55:05 GMT; path=/; domain=.poe.trade; HttpOnly
X-Frame-Options: DENY
Content-Encoding: gzip
Server: cloudflare-nginx
CF-RAY: 3a67ad89743534a0-LHR

**Comment by Eruyome** [comment]
Please try the newest version and show me the StartupLog again.

**Comment by clagger78** [comment]
Starting up PoE-TradeMacro....

----------------------------------------------------------
2017-10-01T21:52Z
----------------------------------------------------------

Requesting leagues from api.pathofexile.com...

cURL command:
"C:\Users\lee\Desktop\trade\POE-TradeMacro\lib\curl.exe" "http://api.pathofexile.com/leagues?type=main" -ILks -H "Host:api.pathofexile.com" -H "Connection:keep-alive" -H "Cache-Control:max-age=0" -H "Content-type:application/x-www-form-urlencoded; charset=UTF-8" -H "Accept:text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8" -H "User-Agent:Mozilla/5.0 (Windows NT 6.3; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.90 Safari/537.36" --max-time 30 

Answer:
HTTP/1.1 302 Found
Server: nginx/1.8.1
Date: Sun, 01 Oct 2017 21:52:44 GMT
Content-Type: text/html; charset=UTF-8
Connection: keep-alive
Expires: Thu, 19 Nov 1981 08:52:00 GMT
Cache-Control: no-store, no-cache, must-revalidate
Pragma: no-cache
Set-Cookie: POESESSID=d84b8d56f629a85a8dae3b345c8a850a; path=/; domain=.pathofexile.com; HttpOnly
Location: /login/?redir=%2Fleagues%3Ftype%3Dmain
X-Frame-Options: SAMEORIGIN

HTTP/1.1 404
Server: nginx/1.8.1
Date: Sun, 01 Oct 2017 21:52:44 GMT
Content-Type: text/html; charset=UTF-8
Connection: keep-alive
Expires: Thu, 19 Nov 1981 08:52:00 GMT
Cache-Control: no-store, no-cache, must-revalidate
Pragma: no-cache
Set-Cookie: POESESSID=e0d2f5c8dbaaaf02f4be4cb10f14b893; path=/; domain=.pathofexile.com; HttpOnly



----------------------------------------------------------
2017-10-01T21:52Z
----------------------------------------------------------

Testing CloudFlare bypass, connecting to http://poe.trade...

cURL command:
"C:\Users\lee\Desktop\trade\POE-TradeMacro\lib\curl.exe" "http://poe.trade" -ILks -H "User-Agent:Mozilla/5.0 (Windows NT 6.3; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/59.0.3071.115 Safari/537.36" -H "Accept:text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8" -H "Accept-Encoding:gzip, deflate" -H "Accept-Language:de-DE,de;q=0.8,en-US;q=0.6,en;q=0.4" -H "Connection:keep-alive" -H "Host:poe.trade" -H "Upgrade-Insecure-Requests:1" --max-time 30 

Answer:
HTTP/1.1 200 OK
Date: Sun, 01 Oct 2017 21:52:45 GMT
Content-Type: text/html; charset=utf-8
Connection: keep-alive
Set-Cookie: __cfduid=d131432290c5ddd29cc6382116327a4761506894765; expires=Mon, 01-Oct-18 21:52:45 GMT; path=/; domain=.poe.trade; HttpOnly
X-Frame-Options: DENY
Content-Encoding: gzip
Server: cloudflare-nginx
CF-RAY: 3a72a69aa6ba353c-LHR

**Comment by Eruyome** [comment]
for reference https://github.com/PoE-TradeMacro/POE-TradeMacro/issues/537#issuecomment-333407187

**Comment by clagger78** [comment]
The Problem is Sky Broadband ran a Vpn and it works fine
