### ISSUE TITLE
Incorrect initialization if non-latin layout is active

### ISSUE THREAD

**Issue by snqlby** [PoE-TradeMacro/POE-TradeMacro#526]
TradeMacro can't start if english keyboard layout is not active
![trademacro_init](https://user-images.githubusercontent.com/6323370/30903956-1e3652ee-a379-11e7-938f-1bcef29897fc.PNG)

**Comment by dein0s** [comment]
Well known issue, reported multiple times.
Fixed in https://github.com/PoE-TradeMacro/POE-TradeMacro/pull/493 (not yet merged tho).
