### ISSUE TITLE
Improved format for floating point numbers

### ISSUE THREAD

**Issue by snqlby** [PoE-TradeMacro/POE-TradeMacro#527]
There are some consumable items which requires 4 number after the floating point. For example:
![ratio_before](https://user-images.githubusercontent.com/6323370/30904676-542ef71e-a37b-11e7-886a-03708245000c.PNG)
We can see 0.2 rates for all items.

It would be great to improve SetFormat and get something like this in the end:
![ratio_after](https://user-images.githubusercontent.com/6323370/30904760-9240f5de-a37b-11e7-8826-b363c718250f.PNG)

I use `SetFormat, float, 0.4` for myself. Maybe it will be useful for everyone.

**Comment by Eruyome** [comment]
already implemented in the dev version
