### ISSUE TITLE
Can't run script

### ISSUE THREAD

**Issue by Neth3** [PoE-TradeMacro/POE-TradeMacro#529]
![poe-trademacro](https://user-images.githubusercontent.com/32343228/30936315-bb55c0c8-a3d3-11e7-920c-dae5d13612fc.png)

Hi, 
I get this error when trying to run "Run_TradeMacro.ahk". 
I have AutoHotkey installed and running and I unzipped the files.

Thanks for your help,
Neth3

**Comment by Eruyome** [comment]
Which AHK version do you have?

**Comment by Neth3** [comment]
I have version 1.000 (AutoHotkey 1.0.* - also retroactively known as AutoHotkey Basic, Classic, Vanilla, etc.)

**Comment by dein0s** [comment]
TradeMacro requires [1.1.*](https://autohotkey.com/download/1.1/) version (currently the latest one is [1.1.26.01](https://autohotkey.com/download/1.1/AutoHotkey_1.1.26.01_setup.exe))
