### ISSUE TITLE
Ctrl+Alt+D issue 

### ISSUE THREAD

**Issue by Anguskhan82** [PoE-TradeMacro/POE-TradeMacro#533]
Hi guys basically when i do Ctrl+Alt+D the little window comes up but it will not let me add any values into my search boxes i get one or more mods couldn't be found on poe.goods all the boxes have little red ! next to it how do i fix this please 

![untitled](https://user-images.githubusercontent.com/32411873/31044847-66a36942-a5cf-11e7-98e3-b412e68b5ffe.png)

**Comment by Eruyome** [comment]
Can you make sure that this file exists in your TradeMacro folder: `data_trade\mods.json` and that it isn't empty?

**Comment by Anguskhan82** [comment]
yh it is their and no it is not empty

**Comment by Eruyome** [comment]
And your issue persists even after a script restart?

**Comment by Anguskhan82** [comment]
yes my script takes like 5 mins to load as well so i dnt know it if worth just re installing

**Comment by Anguskhan82** [comment]
just re installed it takes least 5 mins to start working i am using windows 10 64bit

**Comment by Eruyome** [comment]
Please show me `<TradeMacroFolder>\temp\StartupLog.txt`.

**Comment by elllissss** [comment]
Hi Eruyome, I am having the exact same problem, here's my startuplog if this helps:


Starting up PoE-TradeMacro....

----------------------------------------------------------
2017-10-01T08:28Z
----------------------------------------------------------

Requesting leagues from api.pathofexile.com...

cURL command:
"C:\Users\Ellis\Downloads\POETRADEMACRO\lib\curl.exe" "http://api.pathofexile.com/leagues?type=main" -ILks -H "Host:api.pathofexile.com" -H "Connection:keep-alive" -H "Cache-Control:max-age=0" -H "Content-type:application/x-www-form-urlencoded; charset=UTF-8" -H "Accept:text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8" -H "User-Agent:Mozilla/5.0 (Windows NT 6.3; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.90 Safari/537.36" --max-time 90 

Answer:
HTTP/1.1 302 Found
Server: nginx/1.8.1
Date: Sun, 01 Oct 2017 08:28:51 GMT
Content-Type: text/html; charset=UTF-8
Connection: keep-alive
Expires: Thu, 19 Nov 1981 08:52:00 GMT
Cache-Control: no-store, no-cache, must-revalidate
Pragma: no-cache
Set-Cookie: POESESSID=1d5d39a91ce4d7a79b0e49ec1e5abe45; path=/; domain=.pathofexile.com; HttpOnly
Location: /login/?redir=%2Fleagues%3Ftype%3Dmain
X-Frame-Options: SAMEORIGIN

HTTP/1.1 404
Server: nginx/1.8.1
Date: Sun, 01 Oct 2017 08:28:51 GMT
Content-Type: text/html; charset=UTF-8
Connection: keep-alive
Expires: Thu, 19 Nov 1981 08:52:00 GMT
Cache-Control: no-store, no-cache, must-revalidate
Pragma: no-cache
Set-Cookie: POESESSID=f8b382d2647940c8cba1a339a5a41b5a; path=/; domain=.pathofexile.com; HttpOnly



----------------------------------------------------------
2017-10-01T08:28Z
----------------------------------------------------------

Testing CloudFlare bypass, connecting to http://poe.trade...

cURL command:
"C:\Users\Ellis\Downloads\POETRADEMACRO\lib\curl.exe" "http://poe.trade" -ILks -H "User-Agent:Mozilla/5.0 (Windows NT 6.3; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/59.0.3071.115 Safari/537.36" -H "Accept:text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8" -H "Accept-Encoding:gzip, deflate" -H "Accept-Language:de-DE,de;q=0.8,en-US;q=0.6,en;q=0.4" -H "Connection:keep-alive" -H "Host:poe.trade" -H "Upgrade-Insecure-Requests:1" --max-time 90 

Answer:
HTTP/1.1 200 OK
Date: Sun, 01 Oct 2017 08:28:52 GMT
Content-Type: text/html; charset=utf-8
Connection: keep-alive
Set-Cookie: __cfduid=d4c33611a84c16f4dd9392cb2065055c81506846531; expires=Mon, 01-Oct-18 08:28:51 GMT; path=/; domain=.poe.trade; HttpOnly
X-Frame-Options: DENY
Content-Encoding: gzip
Server: cloudflare-nginx
CF-RAY: 3a6e0d08b69a34a0-LHR

**Comment by Eruyome** [comment]
@elllissss and @Anguskhan82  while I'd be surprised if the newest version solves your issue, please try it https://github.com/PoE-TradeMacro/POE-TradeMacro/releases

**Comment by TheOlddan** [comment]
These are the same symptoms as the Sky Broadband issue in the other thread (taking 5 minutes to load while sitting on Initializing Script / once loaded red ! next to all affixes in the advanced search)
