### ISSUE TITLE
TradeMacro 2.5.5 weird behavior

### ISSUE THREAD

**Issue by steelbacon** [PoE-TradeMacro/POE-TradeMacro#534]
Version 2.5.5 force PoE client from Windowed Fullscreen to Windowed mode, have to manually change the setting again to get the client back to Windowed Fullscreen. 

While starting the script, cannot do anything but update, which fails to 

" Parsing the currency data (json) from poe.ninja failed.
This should only happen when the servers are down / unavailable.

Using archived data from a fallback file.league: "league".

This can fix itself when the servers are up again and the data gets
updated automatically or if you restart the script at such a time. "

Been like this for 3 days, have not tried to manually install 2.5.6 version yet, 
just wanted report the errors i have received.

Picture of the error in question and my Startup log as follows:

![9a3dd92b1499bfa3e609b005d707ea36](https://user-images.githubusercontent.com/32431379/31053968-f6c43b32-a6b0-11e7-8384-aff44efd4fde.png)

> Starting up PoE-TradeMacro....

----------------------------------------------------------
2017-10-01T10:44Z
----------------------------------------------------------

Requesting leagues from api.pathofexile.com...

cURL command:
"D:\pelikamaa\POE-TradeMacro-2.5.5\lib\curl.exe" "http://api.pathofexile.com/leagues?type=main" -ILks -H "Host:api.pathofexile.com" -H "Connection:keep-alive" -H "Cache-Control:max-age=0" -H "Content-type:application/x-www-form-urlencoded; charset=UTF-8" -H "Accept:text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8" -H "User-Agent:Mozilla/5.0 (Windows NT 6.3; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.90 Safari/537.36" 

Answer:
HTTP/1.1 302 Found
Server: nginx/1.8.1
Date: Sun, 01 Oct 2017 10:44:21 GMT
Content-Type: text/html; charset=UTF-8
Connection: keep-alive
Expires: Thu, 19 Nov 1981 08:52:00 GMT
Cache-Control: no-store, no-cache, must-revalidate
Pragma: no-cache
Set-Cookie: POESESSID=36c9966aad1d83c8070974aa1e6c3df5; path=/; domain=.pathofexile.com; HttpOnly
Location: /login/?redir=%2Fleagues%3Ftype%3Dmain
X-Frame-Options: SAMEORIGIN

HTTP/1.1 404
Server: nginx/1.8.1
Date: Sun, 01 Oct 2017 10:44:21 GMT
Content-Type: text/html; charset=UTF-8
Connection: keep-alive
Expires: Thu, 19 Nov 1981 08:52:00 GMT
Cache-Control: no-store, no-cache, must-revalidate
Pragma: no-cache
Set-Cookie: POESESSID=ac86233db68b8800c5f9243a437bdc4c; path=/; domain=.pathofexile.com; HttpOnly

----------------------------------------------------------
2017-10-01T10:44Z
----------------------------------------------------------

Testing CloudFlare bypass, connecting to http://poe.trade...

cURL command:
"D:\pelikamaa\POE-TradeMacro-2.5.5\lib\curl.exe" "http://poe.trade" -ILks -H "User-Agent:Mozilla/5.0 (Windows NT 6.3; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/59.0.3071.115 Safari/537.36" -H "Accept:text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8" -H "Accept-Encoding:gzip, deflate" -H "Accept-Language:de-DE,de;q=0.8,en-US;q=0.6,en;q=0.4" -H "Connection:keep-alive" -H "Host:poe.trade" -H "Upgrade-Insecure-Requests:1" 

Answer:
HTTP/1.1 200 OK
Date: Sun, 01 Oct 2017 10:44:23 GMT
Content-Type: text/html; charset=utf-8
Connection: keep-alive
Set-Cookie: __cfduid=d20bfe4f9a2bd8c6b81c3bc4b23833a5c1506854663; expires=Mon, 01-Oct-18 10:44:23 GMT; path=/; domain=.poe.trade; HttpOnly
X-Frame-Options: DENY
Content-Encoding: gzip
Server: cloudflare-nginx
CF-RAY: 3a6ed390865d5b1b-HEL

**Comment by LillieSatou** [comment]
Right now, the trade macro can't pull Perma HARDCORE data from ninja. Not a program bug, but a site issue.

**Comment by Raynarth** [comment]
Same here, it's a problem that message or we can ignore?

**Comment by dein0s** [comment]
Well, it looks like something went wrong with the base url `http://poeninja.azureedge.net` (I've faced a problem with resolving dns for it).
You can temporary fix it locally:
- file [`resources/ahk/TradeMacro.ahk`](https://github.com/PoE-TradeMacro/POE-TradeMacro/blob/master/resources/ahk/TradeMacro.ahk) lines [#3784](https://github.com/PoE-TradeMacro/POE-TradeMacro/blob/master/resources/ahk/TradeMacro.ahk#L3784) and [#3797](https://github.com/PoE-TradeMacro/POE-TradeMacro/blob/master/resources/ahk/TradeMacro.ahk#L3797) replace `http://poeninja.azureedge.net` with `http://poe.ninja`
- file [`resources/ahk/POE-ItemInfo.ahk`](https://github.com/PoE-TradeMacro/POE-TradeMacro/blob/master/resources/ahk/POE-ItemInfo.ahk) line [#10547](https://github.com/PoE-TradeMacro/POE-TradeMacro/blob/master/resources/ahk/POE-ItemInfo.ahk#L10547) replace `http://poeninja.azureedge.net` with `http://poe.ninja`

**Comment by steelbacon** [comment]
Changing the url lines from 2 files from poeninja.azureedge.net to poe.ninja/ worked for me, however for some reason, when i start the script it changes my PoE Display Mode from Windowed Fullscreen to Windowed. 

still have no clue why the script forces client Display Mode change

**Comment by dein0s** [comment]
I doubt that the TradeMacro script can do that in anyway.
Maybe you accidentally hitting `Alt-Enter` combination?

**Comment by steelbacon** [comment]
nah, just start the script, click to activate PoE window and it does that, few times froze my PoE completely, had to kill the game, albeit it could be an unrelated problem that just coincidentally happens at the same time, but it's only when i start the TradeMacro

**Comment by artsy23** [comment]
please help im having this error to

**Comment by dein0s** [comment]
@artsy23 there's a solution few comments above.

**Comment by Eruyome** [comment]
Poe.ninja changed the api url, the script falls back to a hardcoded currency data file in that case. Making a release to fix it.

**Comment by steelbacon** [comment]
ah sweet, i'll test it if the update is available tomorrow

**Comment by LillieSatou** [comment]
2.5.7 is unstable.

**Comment by LillieSatou** [comment]
It's a LOT slower now. The previous issue has worsened (about poe.ninja failing to correctly parse data)

**Comment by steelbacon** [comment]
ah, let's hope they fix the problems with the site, thank you for informing us :)

**Comment by LillieSatou** [comment]
This has been fixed.

**Comment by steelbacon** [comment]
yep, it's fixed, didn't realize to check if the thingy still does the display mode change in the client for me tho, but that's a minor inconvenience, thank you for awesome support :)
