### ISSUE TITLE
Error: Failing to parse currency data

### ISSUE THREAD

**Issue by arilev** [PoE-TradeMacro/POE-TradeMacro#535]
Version 2.5.4 was working find up until today, then I kept on getting this error upon running the macro:

![image](https://user-images.githubusercontent.com/1335097/31056215-214b8f5a-a69c-11e7-9850-a25e3e26f4a4.png)

The PoE servers are up and reloading the script doesn't seem to help.

I updated to Version 2.5.6 and I'm still getting that error.  Whatever this error is prevents the macro from working.

AHK version: 1.1.26.01
Windows version: 10.0.15063

**Comment by arilev** [comment]
Didn't notice that the previous issue was the exact same.  I was looking for "parsing" "currency" or "league" in the title.  Not "weird issue" :P

**Comment by Eruyome** [comment]
Poe.ninja changed the api url, the script falls back to a hardcoded currency data file in that case.
