### ISSUE TITLE
Stuck/Error on Initializing Script... - Sky Broadband issue

### ISSUE THREAD

**Issue by shadowhunter2002** [PoE-TradeMacro/POE-TradeMacro#537]
Stuck loading the PoE-TradeMacro on initializing script for a day now, updated to 2.5.7 and have the same issue, someone help??

**Comment by shadowhunter2002** [comment]
Starting up PoE-TradeMacro....

----------------------------------------------------------
2017-10-01T20:02Z
----------------------------------------------------------

Requesting leagues from api.pathofexile.com...

cURL command:
"C:\Users\Christopher\Downloads\POE-TradeMacro-2.5.7\lib\curl.exe" "http://api.pathofexile.com/leagues?type=main" -ILks -H "Host:api.pathofexile.com" -H "Connection:keep-alive" -H "Cache-Control:max-age=0" -H "Content-type:application/x-www-form-urlencoded; charset=UTF-8" -H "Accept:text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8" -H "User-Agent:Mozilla/5.0 (Windows NT 6.3; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.90 Safari/537.36" --max-time 30 

Answer:
HTTP/1.1 302 Found
Server: nginx/1.8.1
Date: Sun, 01 Oct 2017 20:02:20 GMT
Content-Type: text/html; charset=UTF-8
Connection: keep-alive
Expires: Thu, 19 Nov 1981 08:52:00 GMT
Cache-Control: no-store, no-cache, must-revalidate
Pragma: no-cache
Set-Cookie: POESESSID=2ebfabad996aec39060d0f76d86ab979; path=/; domain=.pathofexile.com; HttpOnly
Location: /login/?redir=%2Fleagues%3Ftype%3Dmain
X-Frame-Options: SAMEORIGIN

HTTP/1.1 404
Server: nginx/1.8.1
Date: Sun, 01 Oct 2017 20:02:20 GMT
Content-Type: text/html; charset=UTF-8
Connection: keep-alive
Expires: Thu, 19 Nov 1981 08:52:00 GMT
Cache-Control: no-store, no-cache, must-revalidate
Pragma: no-cache
Set-Cookie: POESESSID=818d232c1e2e03787c5c2da91e3085f0; path=/; domain=.pathofexile.com; HttpOnly



----------------------------------------------------------
2017-10-01T20:02Z
----------------------------------------------------------

Testing CloudFlare bypass, connecting to http://poe.trade...

cURL command:
"C:\Users\Christopher\Downloads\POE-TradeMacro-2.5.7\lib\curl.exe" "http://poe.trade" -ILks -H "User-Agent:Mozilla/5.0 (Windows NT 6.3; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/59.0.3071.115 Safari/537.36" -H "Accept:text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8" -H "Accept-Encoding:gzip, deflate" -H "Accept-Language:de-DE,de;q=0.8,en-US;q=0.6,en;q=0.4" -H "Connection:keep-alive" -H "Host:poe.trade" -H "Upgrade-Insecure-Requests:1" --max-time 30 

Answer:
HTTP/1.1 200 OK
Date: Sun, 01 Oct 2017 20:02:22 GMT
Content-Type: text/html; charset=utf-8
Connection: keep-alive
Set-Cookie: __cfduid=d9969bef0f678c5b681e999366625a6791506888142; expires=Mon, 01-Oct-18 20:02:22 GMT; path=/; domain=.poe.trade; HttpOnly
X-Frame-Options: DENY
Content-Encoding: gzip
Server: cloudflare-nginx
CF-RAY: 3a7204ed12646ba3-LHR

Copied over from my start up log file

**Comment by Eruyome** [comment]
That log doesn't seem to be from teh newest version though, there should be a third log entry.

**Comment by shadowhunter2002** [comment]
Looked back to see if I had missed anything, and that's all I can see in the file... could that be the issue?

**Comment by Eruyome** [comment]
`"C:\Users\Christopher\Downloads\POE-TradeMacro-2.5.7\lib\curl.exe" "https://raw.githubusercontent.com/PoE-TradeMacro/POE-TradeMacro/master/data_trade/mods.json" -ILks `
Could you execute this in any windows console window/cmdlet/terminal?

**Comment by Eruyome** [comment]
There were some reports of the script getting stuck on downloading the data files (which should write the third log entry).

**Comment by shadowhunter2002** [comment]
Nothing will execute, sometime it says curl: try 'curl --help' or 'curl --manual' for more information, 'https:' is not recognized as an internal or external command,
operable program or batch file., or nothing happens

**Comment by Eruyome** [comment]
This is the complete request used by the macro, you can also try this but you have to be in the <TradeMacroFolder>\lib\ directory (in your cmdlet) or add the complete path to the curl.exe file in that folder.
```
"curl.exe" "http://poe.trade" -ILks -H "User-Agent:Mozilla/5.0 (Windows NT 6.3; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/59.0.3071.115 Safari/537.36" -H "Accept:text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8" -H "Accept-Encoding:gzip, deflate" -H "Accept-Language:de-DE,de;q=0.8,en-US;q=0.6,en;q=0.4" -H "Connection:keep-alive" -H "Host:poe.trade" -H "Upgrade-Insecure-Requests:1" --max-time 30 
```

**Comment by Eruyome** [comment]
If there are any errors please show me a screenshot of the console window.

**Comment by shadowhunter2002** [comment]
![image](https://user-images.githubusercontent.com/32439720/31058591-2116fa5e-a6ee-11e7-811f-84ed8cfaebb6.png)

**Comment by Eruyome** [comment]
Ok, so multiple issues:
- You made an error when editing the path to curl.exe
- I posted the wrong request, here's the correct one.

```
"C:\Users\Christopher\Downloads\POE-TradeMacro-2.5.7\lib\curl.exe" "https://raw.githubusercontent.com/POE-TradeMacro/POE-TradeMacro/master/data_trade/boot_enchantment_mods.txt" -ILks --max-time 30 
```

I have edited the path, make sure it exists.

**Comment by shadowhunter2002** [comment]
Side note, is "curl.exe" the same as cmd? Or is it something in the AHK files??

**Comment by Eruyome** [comment]
cURL.exe is a commandline program that can be executed via cmd.

**Comment by shadowhunter2002** [comment]
I run it, nothing happen for about 20 second, then it just 
![image](https://user-images.githubusercontent.com/32439720/31058662-1659b790-a6ef-11e7-93ce-bf99288b4bf4.png)

**Comment by Eruyome** [comment]
Are you sure it's 20 seconds? Not 30 seconds which would be the timeout used in the curl request?
Delete `--max-time 30` and try again. Also Try opening `https://raw.githubusercontent.com/POE-TradeMacro/POE-TradeMacro/master/data_trade/boot_enchantment_mods.txt` in your browser and tell me if there's any issue.

**Comment by shadowhunter2002** [comment]
1) The time was a guess tbh, but was between 20-30 seconds 2)Tried to load https://raw.githubusercontent.com/POE-TradeMacro/POE-TradeMacro/master/data_trade/boot_enchantment_mods.txt and nothing happend, Problem loading page 3) cmd did the same thing as before, even after removing the --max-time 30

**Comment by Eruyome** [comment]
@ 2), you mean that you opened it in your browser? Got a white screen/infinitely loading page?

**Comment by shadowhunter2002** [comment]
Exactly that

**Comment by Eruyome** [comment]
Could you open your developer tools? maybe we can see something there under network or the console.
Most browsers use "F12".

example
![image](https://user-images.githubusercontent.com/16058242/31058763-35bf7066-a6f9-11e7-917a-758b76a28ca7.png)

**Comment by shadowhunter2002** [comment]
![image](https://user-images.githubusercontent.com/32439720/31058773-2be88472-a6f1-11e7-8e0a-c76f21bc7658.png)

**Comment by shadowhunter2002** [comment]
Tried to "F12" the file https://raw.githubusercontent.com/POE-TradeMacro/POE-TradeMacro/master/data_trade/boot_enchantment_mods.txt And nothing shows up...

**Comment by Eruyome** [comment]
Could you try a 
```
tracert raw.githubusercontent.com
```
? Windwos cmd again.

**Comment by shadowhunter2002** [comment]
![image](https://user-images.githubusercontent.com/32439720/31058873-3f478a2a-a6f3-11e7-9b84-7cd264da7a39.png)

**Comment by Eruyome** [comment]
Does the normal page work? https://github.com/PoE-TradeMacro/POE-TradeMacro/blob/master/data_trade/boot_enchantment_mods.txt

**Comment by shadowhunter2002** [comment]
Loaded fine

**Comment by Eruyome** [comment]
And when you click on "raw" it fails again?

**Comment by shadowhunter2002** [comment]
Failed

**Comment by Eruyome** [comment]
When you open/activate the dev tool network panel before navigating to the raw page you should see the request, like this. Maybe this shows a bit more

![image](https://user-images.githubusercontent.com/16058242/31058909-40bea452-a6fc-11e7-90cd-e4dd9c8a4349.png)

**Comment by shadowhunter2002** [comment]
![image](https://user-images.githubusercontent.com/32439720/31058918-12a95c36-a6f4-11e7-9d15-85791178eecd.png)

**Comment by Eruyome** [comment]
You have to select the request and take a look at the Headers, Preview, Response tabs.

**Comment by shadowhunter2002** [comment]
![image](https://user-images.githubusercontent.com/32439720/31058937-7195d382-a6f4-11e7-8f36-84d14e1e44da.png)

**Comment by shadowhunter2002** [comment]
![image](https://user-images.githubusercontent.com/32439720/31058942-80bc5e76-a6f4-11e7-9bb5-07e070782bdb.png)
Response was blank

**Comment by shadowhunter2002** [comment]
![image](https://user-images.githubusercontent.com/32439720/31058952-961966a6-a6f4-11e7-9871-2e621c8021ee.png)
Timings if that helps in any way

**Comment by Calyx-** [comment]
@shadowhunter2002 is your ISP Sky Broadband?
Both places I've tried with issues are on Sky.
While a VPN to a location with a different ISP worked fine.

I've contacted Github support about the URL timeout.

**Comment by shadowhunter2002** [comment]
Yeah I'm on Sky, doesn't help with anything loading, I don't think xD But that makes sense

**Comment by shadowhunter2002** [comment]
By anything I meant the trade macro... sorry for any confusion

**Comment by Eruyome** [comment]
I can't do anything about this domain not being avalailable for you because of Sky Broadband, but you can either use a VPN or as a workaround enable debug output in the settignsmenu/set `Debug =1` in config_trade.ini. In the user folder, ' %Userprofile%\Documents\PoE-TradeMacro`.

**Comment by clagger78** [comment]
ran a vpn and it works the problem is Sky Broadband

**Comment by shadowhunter2002** [comment]
So this whole time its been Sky... not Firefox or Chrome... not PoE or the files... BUT SKY

**Comment by shadowhunter2002** [comment]
Well this is easy to fix at least xD

**Comment by shadowhunter2002** [comment]
Thanks for the help everyone :D and hope this might have helped anyone else with the issue

**Comment by shadowhunter2002** [comment]
Umm VPNs cost money... And I don't have money... anyone know of a free vpn @clagger78 ??

**Comment by Eruyome** [comment]
I don't think VPN's are your solution here, some people reported that it's fixed for them, I can't really check myself if the issue with Sky Broadband is resolved.

**Comment by shadowhunter2002** [comment]
Ok, I did the /set Debug =1 in config_trade.ini. In the user folder, ' %Userprofile%\Documents\PoE-TradeMacro` And got the macros working, so I'll just keep it like this for now, Thanks again for the help

**Comment by dein0s** [comment]
To check if the issue is resolved on ISP side simple `nslookup`/`tracert` is enough:
```
nslookup raw.githubusercontent.com
```
```
tracert raw.githubusercontent.com
```
If the final IP in any of this requests belongs to Sky Broadband - the issue is still persists.

**Comment by shadowhunter2002** [comment]
Yeah my router is Sky, and it shows up as Skyrouter.home in cmd

**Comment by tabs-mc** [comment]
Sky broadband here also same issue. Nice find guys/girls.

**Comment by Eruyome** [comment]
Btw, I'm an idiot, you could also disable this option in the settingsmenu as a workaround...
![image](https://user-images.githubusercontent.com/16058242/31103481-6b2d2c32-a7d7-11e7-89a3-ef7df80b77bd.png)

**Comment by TheOlddan** [comment]
Also on Sky Broadband and been struggling with this issue for a week or so.

Placing
151.101.4.133 raw.githubusercontent.com
into the hosts file worked as a temporary solution for me.

**Comment by djandy** [comment]
i have same issue TheOlddan sorry bit thick but i cant find hosts file

**Comment by dein0s** [comment]
@djandy **Editing this file may harm your internet/lan connections - do it on your own risk and only if you understand what you're doing.**

`%WINDIR%\system32\drivers\etc\hosts`
Note that editing this file is restricted to "Administrators" only and you have to open it with your text editor in appropriate way.

**Comment by djandy** [comment]
ty dein0 but i oviosly have no idea what im doing but i think i will try it tyvm

**Comment by Eruyome** [comment]
https://support.rackspace.com/how-to/modify-your-hosts-file/
Just add the line that TheOlddan posted.

**Comment by TheOlddan** [comment]
Looks like Sky have fixed their issue; the macro (and this site in general) are now working again without any tweaks.
