### ISSUE TITLE
[RESOLVED] Error when launching script

### ISSUE THREAD

**Issue by sampSCS** [PoE-TradeMacro/POE-TradeMacro#54]
http://i.imgur.com/dtK0fxd.png

TradeMacro v1.1.3.2
AutoHotkey v1.1.24.2

Same error even if I run as administrator.

**Comment by Eruyome** [comment]
So far everyone (I know about) could fix this by installing the newest AHK version (or one of the newer ones). I have v1.1.24.01. Your's should be 1.1.24.02?

Btw there's a TradeMacro 1.1.3.4, not that it should make a difference here.

Maybe test https://autohotkey.com/download/1.1/Ahk2Exe112401.zip if nothing else helps.

**Comment by sampSCS** [comment]
I'm posting this for anyone else with this problem.

Using AutoHotkey to EXE utility with the main.ahk of TradeMacro v1.1.3.2 and running the resulting executable, got everything working, but there were some error messages that I think are related to the popup that prompts to download the latest version.

Using AutoHotkey to EXE utility with the main.ahk of TradeMacro v1.1.3.4 (latest version at time of posting) and running the resulting executable, got everything working without any errors or problems.

Thanks for the help!
