### ISSUE TITLE
Error after starting up the macro

### ISSUE THREAD

**Issue by FUGAZISLAYER** [PoE-TradeMacro/POE-TradeMacro#542]
Whenever I start up the macro this message pops up 
![poetrademacroerrormessage](https://user-images.githubusercontent.com/32525970/31197586-72fa104e-a906-11e7-8abf-379bd6b84f71.png)

I'm using both the current Macro and AHK on Windows 10. Any help would be appreciated, Please and Thank you.

**Comment by aRTy42** [comment]
The Fallback.exe is meant as a backup launch method, don't rely on it for regular use. Start the script with the "Run_TradeMacro.ahk" file.

**Comment by FUGAZISLAYER** [comment]
Thank you very much.

**Comment by FUGAZISLAYER** [comment]
After starting it up with the "Run_TradeMacro.ahk" file I get this message pop up 
![poetrademacroerrormessage2](https://user-images.githubusercontent.com/32525970/31199879-a9edad84-a90d-11e7-854a-8a9c4c737961.png)

**Comment by Eruyome** [comment]
Show me the contents of `<TradeMacroFolder>\temp\currencyData.json`.

**Comment by aRTy42** [comment]
Your screenshot shows the old "poeninja.azureedge.net" url that was changed recently. This got fixed with the latest release of the macro: v2.5.7.

Are you sure you got the latest update?

**Comment by FUGAZISLAYER** [comment]
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd"><html><head><meta http-equiv="refresh" content="0;url=http://finder.cox.net/main?ParticipantID=96e687opkbv4scrood8k84drs6gw5duf&FailedURI=http%3A%2F%2Fpoeninja.azureedge.net%2Fapi%2FData%2FGetCurrencyOverview%3Fleague%3DHarbinger&FailureMode=1&Implementation=&AddInType=4&Version=pywr1.0&ClientLocation=us"/><script type="text/javascript">url="http://finder.cox.net/main?ParticipantID=96e687opkbv4scrood8k84drs6gw5duf&FailedURI=http%3A%2F%2Fpoeninja.azureedge.net%2Fapi%2FData%2FGetCurrencyOverview%3Fleague%3DHarbinger&FailureMode=1&Implementation=&AddInType=4&Version=pywr1.0&ClientLocation=us";if(top.location!=location){var w=window,d=document,e=d.documentElement,b=d.body,x=w.innerWidth||e.clientWidth||b.clientWidth,y=w.innerHeight||e.clientHeight||b.clientHeight;url+="&w="+x+"&h="+y;}window.location.replace(url);</script></head><body></body></html>

**Comment by FUGAZISLAYER** [comment]
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd"><html><head><meta http-equiv="refresh" content="0;url=http://finder.cox.net/main?ParticipantID=96e687opkbv4scrood8k84drs6gw5duf&FailedURI=http%3A%2F%2Fpoeninja.azureedge.net%2Fapi%2FData%2FGetCurrencyOverview%3Fleague%3DHarbinger&FailureMode=1&Implementation=&AddInType=4&Version=pywr1.0&ClientLocation=us"/><script type="text/javascript">url="http://finder.cox.net/main?ParticipantID=96e687opkbv4scrood8k84drs6gw5duf&FailedURI=http%3A%2F%2Fpoeninja.azureedge.net%2Fapi%2FData%2FGetCurrencyOverview%3Fleague%3DHarbinger&FailureMode=1&Implementation=&AddInType=4&Version=pywr1.0&ClientLocation=us";if(top.location!=location){var w=window,d=document,e=d.documentElement,b=d.body,x=w.innerWidth||e.clientWidth||b.clientWidth,y=w.innerHeight||e.clientHeight||b.clientHeight;url+="&w="+x+"&h="+y;}window.location.replace(url);</script></head><body></body></html>

**Comment by FUGAZISLAYER** [comment]
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd"><html><head><meta http-equiv="refresh" content="0;url=http://finder.cox.net/main?ParticipantID=96e687opkbv4scrood8k84drs6gw5duf&FailedURI=http%3A%2F%2Fpoeninja.azureedge.net%2Fapi%2FData%2FGetCurrencyOverview%3Fleague%3DHarbinger&FailureMode=1&Implementation=&AddInType=4&Version=pywr1.0&ClientLocation=us"/><script type="text/javascript">url="http://finder.cox.net/main?ParticipantID=96e687opkbv4scrood8k84drs6gw5duf&FailedURI=http%3A%2F%2Fpoeninja.azureedge.net%2Fapi%2FData%2FGetCurrencyOverview%3Fleague%3DHarbinger&FailureMode=1&Implementation=&AddInType=4&Version=pywr1.0&ClientLocation=us";if(top.location!=location){var w=window,d=document,e=d.documentElement,b=d.body,x=w.innerWidth||e.clientWidth||b.clientWidth,y=w.innerHeight||e.clientHeight||b.clientHeight;url+="&w="+x+"&h="+y;}window.location.replace(url);</script></head><body></body></html>

**Comment by FUGAZISLAYER** [comment]
Ya, I update every time it shows a new update

**Comment by Eruyome** [comment]
That certainly doesn't look like the newest version, and you won't get the notification since you can't start the script.
https://github.com/PoE-TradeMacro/POE-TradeMacro/releases/tag/v2.5.7

**Comment by FUGAZISLAYER** [comment]
That's weird...it should be but I went ahead and replaced all the files from the link you provided. I guess I won't update through the Macro anymore and just do it manually from now on.

**Comment by FUGAZISLAYER** [comment]
Thank you for the help, it's most appreciated.

**Comment by aRTy42** [comment]
You can continue to use the auto-updater, it just didn't work this time because this error occurred before the script could fully load.
