### ISSUE TITLE
Leo's "Faster Start of Energy Shield Regen" mod does not show up in iteminfo window.

### ISSUE THREAD

**Issue by LillieSatou** [PoE-TradeMacro/POE-TradeMacro#545]
It does come up within advanced search options, just not within the item info window. It is a suffix.

Image proof: https://i.imgur.com/0Jg8wFi.png

**Comment by aRTy42** [comment]
Mods that are exclusively master crafts for that item type are not all supported yet, they will be added at some point. That one should be a prefix, by the way.

**Comment by Eruyome** [comment]
@aRTy42 is this still relevant?

**Comment by aRTy42** [comment]
This one is still missing, but so are other master mods. You can keep this issue open if you like, but I personally don't need it as a reminder.

**Comment by Eruyome** [comment]
I do^^

**Comment by LillieSatou** [comment]
closing since it's been ~6 months ^^
