### ISSUE TITLE
[Bug] -- This script is illegal

### ISSUE THREAD

**Issue by Dillybob92** [PoE-TradeMacro/POE-TradeMacro#55]
And will be reporting to the GGG authorities right now. Chris Wilson is coming for you.

**Comment by thirdy** [comment]
Here you go,

![capture1](https://cloud.githubusercontent.com/assets/75921/19616653/738c7f96-984b-11e6-8548-06b0d13e30d1.PNG)

**Comment by Dillybob92** [comment]
I don't give a shit about your email, you cannot even tell if someone was trolling or not.
