### ISSUE TITLE
Cookie Problem?

### ISSUE THREAD

**Issue by Jinxtrr** [PoE-TradeMacro/POE-TradeMacro#552]
When loading the script, it hangs and then throws this error.

![ahkpoetrade](https://user-images.githubusercontent.com/32783726/31570560-ffd35126-b052-11e7-85c1-1b2be09a9f18.JPG)

I have tried redownloading the script. Redownloading AHK.

Current AHK version I have.
![ahkv](https://user-images.githubusercontent.com/32783726/31570586-3be66022-b053-11e7-898f-d74651a827a9.JPG)

PC specs:
![what](https://user-images.githubusercontent.com/32783726/31570660-2d8e3ecc-b054-11e7-95ec-df97ea1a80a9.JPG)

Happens every time I try to load the script. This just started happening today. Only other programs I have running are Firefox, Spotify, PoE, Steam, and Discord. Also have Corsair LINK and CUE running for K/M and water cooler.

**Comment by Eruyome** [comment]
While it seems that you have an issue with cookies you shouldn't get such a script error. Normally I'd suspect a wrong AHK version/some issue with AHK itself. The syntax used there is correct. Your AHK version seems to be ok though.

You could try editing the file `config_trade.ini`, setting these values:
```
[Cookies]
UseManualCookies=1
UserAgent=
CfdUid=
CfClearance=
```

retrieving useragent/cfduid/cfclearance according to https://github.com/PoE-TradeMacro/POE-TradeMacro/wiki/Cookie-retrieval.

I'm not sure if that can skip the script error, but it's worth a try.

**Comment by Jinxtrr** [comment]
Ok, so I changed the value to 1.
![cookieini](https://user-images.githubusercontent.com/32783726/31572137-ea08848c-b06c-11e7-926b-69c1e5efc154.JPG)

The script now loads normally and seems to work fine. 

Finding the cookie information has been hard as my version of Firefox appears to be nothing like the one shown in the document. I was able to find the _cfduid cookie but that was it. 

Here is what I can see.

Cookies are under storage for me, and only the _cfduid is available. 
![poecookies](https://user-images.githubusercontent.com/32783726/31572150-1ade59c4-b06d-11e7-9f15-f7cc83fe92d0.JPG)

This is what I get under Network.
![poenetwork](https://user-images.githubusercontent.com/32783726/31572152-35c7d620-b06d-11e7-8d9e-d25e196380cb.JPG)

Other than not finding those items it seems to be working again.

The quick search seems to work fine.
![quick search](https://user-images.githubusercontent.com/32783726/31572179-ba394cea-b06d-11e7-82b9-36d5782fab60.png)

The advanced search comes back normally it seems as well.
![advanced search](https://user-images.githubusercontent.com/32783726/31572185-c8db55b8-b06d-11e7-81a4-05bcdb166729.png)

I guess until something stops working, consider it case closed?

**Comment by Eruyome** [comment]
Aside from the script error, your issues mihgt have been caused by this https://www.reddit.com/r/pathofexile/comments/768lcs/poe_trade_is_down/

**Comment by Jinxtrr** [comment]
I don't think so. When I was having the issue I was able to go to the website. I was able to get those screenshots for you from Poe.Trade while I was still having the issue. Who knows. Seems to be working.
