### ISSUE TITLE
launch bug

### ISSUE THREAD

**Issue by V4LK1** [PoE-TradeMacro/POE-TradeMacro#557]
hello my problem is that I would be installing everything as it says in the guide and I am appearing an error when trying to execute the script someone could help me?
![captura](https://user-images.githubusercontent.com/32866924/31657290-5e58fb70-b304-11e7-8e31-52085f3c908c.PNG)
I have windows 8.1

**Comment by Eruyome** [comment]
Can you confirm your AHK version?

**Comment by V4LK1** [comment]
I downloaded the first one that appeared is 2.5.7

**Comment by Eruyome** [comment]
Not talking about the TradeMacro version but the Autohotkey version.

**Comment by V4LK1** [comment]
sorry I misunderstood I downloaded the file AutoHotkey104414.exe

**Comment by Eruyome** [comment]
That seems weird, how about using AutoHotkey_1.1.26.01_setup.exe from https://autohotkey.com/download/?

**Comment by V4LK1** [comment]
thank you very much, I got executed
