### ISSUE TITLE
[ToDo] Improve implementation of Trade macro corrupted settings

### ISSUE THREAD

**Issue by slowmike** [PoE-TradeMacro/POE-TradeMacro#56]
When I press ctrl+d on a corrupted item, it keeps showing corrupted items but I would rather have it at either.
Also, when i press the [trade] ok button, it bugs out and duplicates the whichever option was selected in the drop down list.

**Comment by Eruyome** [comment]
Regarding the corruption, that's not bugged, it's a choice and we can definitely think about solving this a better way. In any case it should always be the default to use the same corruption state as your item has.
To be honest, there's hardly a reason to having it another way. 

Regarding the Dropdown, I can look into that, but it still works doesn't it?

**Comment by Eruyome** [comment]
This can now be overwritten in the Settings-Menu.
