### ISSUE TITLE
Map mod is not functioning well

### ISSUE THREAD

**Issue by lskku** [PoE-TradeMacro/POE-TradeMacro#561]
_TEMPLATE_ (Remove the explanations here from your post) 

Make sure:
* That you have checked the Wiki/FAQ before creating any issue.
* That poe.trade/GGG's website don't have any issues if loading the script takes too long or failes.

Information to include:
* AHK (including 32/64bit) version if you have any kind of script errors.
* Windows version could be relevant.

Fill out everything that may be relevant and remove everything except these informations below:  

AHK version: 1.1.26.00
Windows version: windows 10

![capture](https://user-images.githubusercontent.com/8382563/31725284-417cb412-b424-11e7-944b-1f953e6fa9fa.PNG)

here as you see, enable map mod warnings marked and temporal chains should be warned
but here

![10-18 16 46 30_li](https://user-images.githubusercontent.com/8382563/31725458-bc981f24-b424-11e7-97b9-37088793ff6a.jpg)

showing none

it happened after i download new version today. please have a look.

**Comment by Eruyome** [comment]
It's known and being fixed, or already fixed, not pushed or released yet though.

**Comment by aRTy42** [comment]
The new .ini files come with [sections] now that need to be specifically named when reading. In this case the "Affixes" was [simply missing](/aRTy42/POE-ItemInfo/commit/13c6a492af5c577728e81dfaaed5446e97640d0a).
