### ISSUE TITLE
Totaly new and dont know what the problem is.

### ISSUE THREAD

**Issue by Kimpanzy** [PoE-TradeMacro/POE-TradeMacro#566]
---------------------------
Merge_TradeMacro.ahk
---------------------------
Error in #include file "C:\Users\kimpe\OneDrive\Dokument\trade macro\lib\PoEScripts_HandleUserSettings.ahk":
     Call to nonexistent function.

Specifically: HashFile(DestinationFolder . "\temp\" . file_name, "SHA")

	Line#
	075: RegExMatch(f_name_no_ext, "i)(_dontOverwrite)", dontOverwrite)  
	076: file_name := RegExReplace(f_name_no_ext, "i)_dontOverwrite", "") . "." . f_ext
	077: FileCopy,%A_LoopFileFullPath%,%DestinationFolder%\temp\%file_name%,1
	078: file := f_dir . "\" . file_name
	079: fileNames.push(file_name)  
	082: if (not StrLen(dontOverwrite))  
	082: {
--->	083: sourceHash := HashFile(DestinationFolder . "\temp\" . file_name, "SHA")
	084: hashes[file_name] := sourceHash  
	085: }
	088: if (PoEScripts_CopyNeeded(file_name, DestinationFolder, sourceHash, hashes_locked, dontOverwrite))  
	088: {
	090: if (FileExist(DestinationFolder "\" file_name))  
	090: {
	091: overwrittenFiles.push(file_name)  

The program will exit.
---------------------------
OK   
---------------------------

**Comment by Eruyome** [comment]
First question on script errors, whats your AHK version?

**Comment by Kimpanzy** [comment]
AutoHotKey v1.1.26.01 (Unicode 64-bit)

**Comment by Kimpanzy** [comment]
First time using the macro so there should not be any old files, extracted it to a new clean map without any contents in it and i just downloaded the lastest version (18days ago)? Since u cant choose what version right?

**Comment by Eruyome** [comment]
You can by going here https://github.com/PoE-TradeMacro/POE-TradeMacro/releases instead of the page showing "latest" releases, since it doesn't show pre-releases.

**Comment by Eruyome** [comment]
Some advice, move the TradeMacro install folder to a different location, not directly in your `Documents` folder, even a subfolder is ok, just nothing called "PoE-TradeMacro" since that folder will be used to store user configurations.

Also, can you do me a favour and run this as a new `.ahk` script?
```
msgbox % A_MyDocuments
```
and show me the result?

**Comment by Kimpanzy** [comment]
Okay i got the beta version and it worked right away, how do i run it as a new .ahk? and i'll post the result.

**Comment by Eruyome** [comment]
Just create a file ending with `.ahk`, save the code as its contents and double click.

**Comment by Kimpanzy** [comment]
---------------------------
New AutoHotkey Script.ahk
---------------------------
C:\Users\kimpe\OneDrive\Dokument
---------------------------
OK   
---------------------------
This pops up then, correct?

**Comment by Eruyome** [comment]
Yeah, thx.
