### ISSUE TITLE
Can't convert other currencies to chaos

### ISSUE THREAD

**Issue by guiniol** [PoE-TradeMacro/POE-TradeMacro#567]
AHK version: 1.1.26.01
Windows version: 10

Updated to the beta tonight, and it seems that it can't convert other currencies to chaos. There's an error message saying so, and if there are no prices in chaos, it will display the average price as 0.0.

**Comment by aRTy42** [comment]
See #560. It's fixed in the beta branch and will be in the next release.

**Comment by guiniol** [comment]
Sorry. I didn't realise those were the same issues.

**Comment by Eruyome** [comment]
Both issues had the same cause, fethcing the currency rates from poe.ninja failing because of some changes that where made on that end.

**Comment by guiniol** [comment]
Ok. In any case, good to know it's fixed ^^
