### ISSUE TITLE
GDI+ window misaligned when not fitting on screen

### ISSUE THREAD

**Issue by Precursorx** [PoE-TradeMacro/POE-TradeMacro#568]
The GDI+ window aligns the bottom edge to the edge of the screen when not fitting on it this is different to the behavior of the normal window (which jumps to the top of the screen instead).
Because of this the window can appear under your cursor and tabs you out when you click.

![poetradereport](https://user-images.githubusercontent.com/11192114/31769534-5f248caa-b4d4-11e7-9d31-0e0c379d71f7.png)

AHK version: 64bit
Windows version: windows 7

**Comment by Eruyome** [comment]
So you're saying that it makes you accidently click the GDI tooltip and therefore making the PoE window lose focus?
In that case the current dev version should fix it, I made the tootlip window clickthrough.
https://github.com/PoE-TradeMacro/POE-TradeMacro/archive/beta.zip

**Comment by Precursorx** [comment]
That's exactly what i meant and the beta fixed it thanks!
