### ISSUE TITLE
Iteminfo of The Tempest Longbow shows The tempest's binding information

### ISSUE THREAD

**Issue by darthbane83** [PoE-TradeMacro/POE-TradeMacro#569]
Iteminfo ctrl+c shows information of the The tempest's binding instead of The Tempest. Item search ctrl+d shows results for the correct item.
using up to date beta version

**Comment by FlorentTornil** [comment]
Got the same problem, here's a screenshot :

![tempest](https://user-images.githubusercontent.com/23338954/31851653-6fcc9c7c-b66a-11e7-8a91-feeddee3037a.PNG)

**Comment by aRTy42** [comment]
Thank you, I've corrected the ItemName matching for Uniques. It should no longer accept partial matches. Should be in the next release.
