### ISSUE TITLE
CTRL+F does not put that item in search anymore, as well as CTRL+Mousewheel doesn't scroll through tabs

### ISSUE THREAD

**Issue by captaincbr** [PoE-TradeMacro/POE-TradeMacro#570]
Fill out everything that may be relevant and remove everything except these informations below:  

AHK version: 64bit
Windows version: 7

As the title states, I didn't have this issue until I updated it to current version 2.6.0-beta

**Comment by aRTy42** [comment]
Does any macro work, for example the hideout travel with F5?

We've standardized the check that ensures macros are not executed while people are not ingame. It might have had side effects in unusual cases.
Is your game client modified or untypical in any way? Did you rename your .exe file? Are you running PoE with some kind of special setting?

**Comment by captaincbr** [comment]
I actually didn't know about the hideout functionality and was excited to try it, but unfortunately the hideout travel with F5 doesn't work. Anything I can do to fix this?

I run my game unmodified. I have not renamed any files. No special setting that I know of, but if you need me to check something in game I can certain ly this.

**Comment by Eruyome** [comment]
Right click the macros system-tray menu -> Show Assigned Hotkeys and show us the window that opens.

**Comment by captaincbr** [comment]
@Eruyome It is blank for me. What do I need to do to make it look like that?

**Comment by aRTy42** [comment]
There is another open issue thread that is also about hotkeys not working, I'd like to point you to my answer there instead of copy-pasting it: [Here](/PoE-TradeMacro/POE-TradeMacro/issues/564#issuecomment-338950203)

**Comment by captaincbr** [comment]
@aRTy42 Thank you Arty. I read that and it prompted me to reinstall AHK. After doing so and running Run_TradeMacro, this function works as it did before.
