### ISSUE TITLE
Corrupted override settings not working for price check

### ISSUE THREAD

**Issue by SpeedZealot** [PoE-TradeMacro/POE-TradeMacro#572]
The "Override" settings is not working well for price check.

![capture](https://user-images.githubusercontent.com/32897737/31875702-8a838088-b7cf-11e7-8937-645079cd9d14.png)

AHK version: 2.6.0-beta.2
Windows version: 10

**Comment by Eruyome** [comment]
Fixed that, will be released soon. Will keep this open for visibility.
