### ISSUE TITLE
Add Pre-fill Current-Values ?

### ISSUE THREAD

**Issue by schmutzlord** [PoE-TradeMacro/POE-TradeMacro#575]
hi to the poe.trademacro makers, i had to get out of my way to make this github account, just cause i was annoyed with 1 thing that's still lacking and was hoping it was an easy thing to add.
it would be cool if you could add a "pre-fil current-values" of an item checkbox.
i can only choose min + maxvalues, but i want to always fill in currentvalues and go form my prices for my sales from there, min values most of the time extremely devalue an item.

hope this is possible and a nice idea.

**Comment by aRTy42** [comment]
You can already adjust the "Mod Range Modifier (%)" for that, by default it's 20 - 20 which is halved for non-uniques.

If you want your exact roll as the minimum you choose 0 for the left box. You can then decide if you want to give the maximum a bit more range or maybe even disable the maximum limit (un-tick "Pre-Fill Max-Values").

**Comment by schmutzlord** [comment]
oh cool didnt know that, thx.
