### ISSUE TITLE
IDK if UPDATE buttom is broken but it doesn't work

### ISSUE THREAD

**Issue by Khuzvhan** [PoE-TradeMacro/POE-TradeMacro#576]
with these tons of beta updates i always get that annoying message informing that there's an update for download, then i click update buttom, it creates a backup, says it's downloading and extracting new stuff. but then when i open the "new" downloaded stuff the update message shows again. did never get it updates from this buttom, everytime there's an update i have to get here in GH then delete my old stuff, and do the rest myself, really annoying.

**Comment by Eruyome** [comment]
Can you tell me if the update was actually installed, for example looking at `<tm folder>\resources\versionTrade.txt` and it just tells you for some reason that it hasn't?
