### ISSUE TITLE
Ctrl + d on currency not working with alternative currency search

### ISSUE THREAD

**Issue by SpeedZealot** [PoE-TradeMacro/POE-TradeMacro#577]
Not working with alternative search, but without it's ok

![capture](https://user-images.githubusercontent.com/32897737/31983361-5124f8e6-b95d-11e7-838e-8205a2def6ee.PNG)
![capture2](https://user-images.githubusercontent.com/32897737/31983362-51482aa0-b95d-11e7-8b97-787a9b680e0c.PNG)

AHK version: 2.6.0-beta.3
Windows version: 10

**Comment by Eruyome** [comment]
Fixed (not yet released).
