### ISSUE TITLE
Ctrl + C shows incorrect damage range on Doomfletch (Prism)

### ISSUE THREAD

**Issue by Simpsonboy77** [PoE-TradeMacro/POE-TradeMacro#579]
AHK version: v1.1.26.01 (Unicode 64)
Windows version: Windows 7 home x64

When I press Ctrl + C on both Doomfletch and Doomfletch Prism, the range shown is 8-16 | 12-20. The wiki says the actual range is (8-12) - (16-20). I would expect the tooltip to say 8-12 | 16-20.

![image](https://user-images.githubusercontent.com/7366389/32086951-9c369944-baa6-11e7-8a07-5354a605acf6.png)

**Comment by aRTy42** [comment]
Thanks! All unique double ranges are currently shown as a-c|b-d, should be fixed soon.
