### ISSUE TITLE
Remove multiple listing from same account not working

### ISSUE THREAD

**Issue by SpeedZealot** [PoE-TradeMacro/POE-TradeMacro#580]
The search is listing multiple time the same account even with "remove multiple... " checked.

![capture](https://user-images.githubusercontent.com/32897737/32134070-49627a40-bbe5-11e7-9126-28a8d25afe97.PNG)

AHK version: 2.6.0-beta.3
Windows version: 10

**Comment by Eruyome** [comment]
Fixed (not yet released).
