### ISSUE TITLE
Settings Window is Too Tall/Inflexible On Some Setups

### ISSUE THREAD

**Issue by dsnvwlmnt** [PoE-TradeMacro/POE-TradeMacro#584]
I have the Windows taskbar always on. Your settings window is always hidden behind the taskbar, making it impossible to click Ok or Cancel. Unless i manually hide/move the taskbar.

In fact, while making this issue, i noticed that i can't see all the options even if i move the taskbar. There's a 3rd textbox in the Manual Cookie Selection section that i can only see the very top of. See attached image.

Suggested solution: make the settings window horizontal rather than vertical.

Resolution: 1366x768
Windows version: 10
AHK version: 1.1.26.01

![image](https://user-images.githubusercontent.com/14173022/32453084-348be178-c2d0-11e7-845b-a00b6aa15f08.png)

**Comment by Eruyome** [comment]
That's more or less planned, but GUIs in AHK are a pain in the ass so it's not simply changed in 5 minutes.

**Comment by dsnvwlmnt** [comment]
Temporary solution: click the 2nd tab, where the OK/Cancel buttons are much higher up.

**Comment by Eruyome** [comment]
fixes
