### ISSUE TITLE
Unset rings show error that mod not on poe.trade

### ISSUE THREAD

**Issue by Seyeght** [PoE-TradeMacro/POE-TradeMacro#585]
as seen below,
![image](https://user-images.githubusercontent.com/20807322/32523417-ce1059d0-c3e0-11e7-84e5-1b3aa616e5da.png)

However on poe.trade there is this option, which does return the mod indicated:
![image](https://user-images.githubusercontent.com/20807322/32523492-1fd64fa4-c3e1-11e7-88e3-7878842013e3.png)

**Comment by Eruyome** [comment]
Fixed (not released yet).
