### ISSUE TITLE
Cant save race league for price search function.

### ISSUE THREAD

**Issue by OmikronGamma** [PoE-TradeMacro/POE-TradeMacro#589]
Hello, i cant save race league (turmoil as of right now) for price search function. It works for current session - i start the script, choose turmoil, it works; but when i restart the script it switches to standard. Also, if i set any other league, it saves fine.

**Comment by dein0s** [comment]
Fixed in https://github.com/PoE-TradeMacro/POE-TradeMacro/pull/586
You have to wait for the new beta release, until then you can manually download trademacro archieve based on this [merge-commit](https://github.com/PoE-TradeMacro/POE-TradeMacro/tree/d366c85ad2e52729a4b387d930eb20a469f3a7b1).

**Comment by OmikronGamma** [comment]
So this is known issue? Ok, I'll wait for the fix.
