### ISSUE TITLE
Error after downloading script

### ISSUE THREAD

**Issue by Daamon0700** [PoE-TradeMacro/POE-TradeMacro#590]
Not sure if this is common to everyone else as well but I am recieving an error after downloading and unzipping the macro, Error states the following:

"Error at line 1 in #include file "D:\lib\CalcChecksum.ahk".

Line Text: HashFile(filePath,hashType=2)
Error:Duplicate function definition.

The Program will now exit."

**Comment by aRTy42** [comment]
Did you unzip the macro directly onto the D:\ drive? Please use a folder, such as "D:\POE-TradeMacro\...", otherwise it can cause all sorts of issues.

**Comment by Daamon0700** [comment]
No, I made a new folder, named in TradeMacro, and unzipped the macro into that

**Comment by aRTy42** [comment]
Is that main macro folder inside your "<Documents>\PoE-TradeMacro" user config folder on D? If so, get it out of there. If not, please post your full macro folder path (you can replace personal names if needed).

**Comment by Daamon0700** [comment]
D:\TradeMacro\POE-TradeMacro-master

**Comment by aRTy42** [comment]
Delete that entirely and download a release from https://github.com/PoE-TradeMacro/POE-TradeMacro/releases (so POE-TradeMacro-2.6.0-beta.4.zip).

The default name for the macro folder that the updater uses is "POE-TradeMacro" so I'd recommend to unzip the download into "D:\POE-TradeMacro" in your case, that way it keeps its name by default.

Please report back if that works.

**Comment by Daamon0700** [comment]
Interesting, so I unzipped it twice, once directly into my D:/ Drive, and once into a folder within my D drive which I named POE-TradeMacro, the copy within the folder gets the same error however the copy installed directly into my D: drive works fine

**Comment by aRTy42** [comment]
If the full path ends up as "D:\POE-TradeMacro\POE-TradeMacro" or something similar that causes issues because the script is no longer able to correctly find or access everything.

**Comment by Daamon0700** [comment]
Nah the full path is D:\POE-TradeMacro

I dont know if its the Zip client I am using or the Zip itself but when I unzip the folder it doesnt unzip a POE-TradeMacro folder it just unzips the files inside and the data folders

**Comment by aRTy42** [comment]
The files are directly in the zip file because thats how GitHub works. Having the extracted macro directly on the D:\ drive is dodgy, it should work fine within a folder. Did you have several copies unzipped when you tried the different paths?

**Comment by Daamon0700** [comment]
No, I tried renaming the folder, that failed, so I deleted everything and unzipped into a new folder which I had named POE-TradeMacro, that failed, so I unzipped straight onto the drive adn it worked

**Comment by aRTy42** [comment]
Odd. Having it directly on the drive will mess up the auto-updater, so it shouldn't stay there. I'm not exactly sure whats causing the issue here, but a few things to check:

Are you launching the script with the "Run_TradeMacro.ahk" file? If you are using the Fallback.exe: Don't.

Could you try having the extracted files within a folder (like before), while doublechecking that no files from previous extractions remain and move/delete the zip. Since you extracted it directly to the drive, I guess the folders are scattered between other folder names, so make sure you get the following five folders (and the few single files): /data, /data_trade, /lib, /resources, /temp

**Comment by Daamon0700** [comment]
Yeah let me take a look at that, Ill delete everything and then scan through my D: drive and make sure there arent any leftovers just to make sure

**Comment by Daamon0700** [comment]
Ok so that seems to have fixed it, I had deleted folders as well as the Main AHK file, but had forgotten about the fallback and internet files scattered over my drive, I deleted those and the unzipped into my POE-TradeMacro folder and it works fine now, thank for the help

**Comment by aRTy42** [comment]
Great. Glad that was it and no wild bug chase is needed.
