### ISSUE TITLE
Auto update does not function

### ISSUE THREAD

**Issue by tiany4** [PoE-TradeMacro/POE-TradeMacro#594]
AHK version: v1.1.26.01
Windows version: Windows 7 Ultimate

Line 62 in PoEScripts_FinishUpdate.ahk:

> Exception thrown while copying new files to %pathname%. Update failed!
>
> Update scripted failed to run.

I have not been able to use autoupdate for the past year or so. I have used different versions of AHK and TradeMacro all with the same result. I have also tried setting different paths or folder names, including Documents and other places on both C and D drives.

**Comment by Eruyome** [comment]
Did it work once?

**Comment by tiany4** [comment]
Nope, not that I remember.

**Comment by Eruyome** [comment]
Is that the original unaltered error message? There shouldn't be a `%pathname%`.

**Comment by tiany4** [comment]
`%pathname%` is just whichever path I try to install the macro in. I replaced it with `%pathname%` so it's easier to read. I read through PoEScripts_FinishUpdate.ahk and it looks like this error is thrown when there's no error code.

**Comment by Eruyome** [comment]
I'll look into it, would be nice seeing your actual path though.

**Comment by tiany4** [comment]
Here are a few paths I just tried with v2.6.0-beta.5
D:\GAMEZ\POETools\POE-TradeMacro
C:\Users\Floorsweeper\Documents\My Games\Path of Exile\POE-TradeMacro
F:\POE-TradeMacro

**Comment by Blekota2k** [comment]
I belive i have the same issue. When i press update when im informed of new version, the program create backup folder, downloads some files and then stops, when i run the program again, i got the update window again and it all cycle.

**Comment by tiany4** [comment]
Aye, 'tis the issue. Do you have the same version of AHK and Windows?

**Comment by Blekota2k** [comment]
AHK is the same (v1.1.26.01), i run Win 10 Pro

**Comment by MaxKruse** [comment]
i think it has to do with the script getting updated on a different partition than where the %temp% folder is located.

**Comment by tiany4** [comment]
I have tried putting the script in C: drive and the same error occurs.

**Comment by Eruyome** [comment]
For me it works on different partitions.

Let's try this quickly before I try to write some complicated debug logger.

Edit `%TM-Folder%\lib\PoeScripts_FinishUpdate.ahk`, line 35:
```
RunWait, "copyUpdate.bat" "%updateScriptPath%" "%installPath%" "%installFolder%" "%installPath%_tempInstall" "%installFolder%_tempInstall", , hide
```
to 
```
MsgBox % updateScriptPath "`n`n" installPath "`n`n" installFolder "`n`n" installPath "_tempInstall" "`n`n" installFolder "_tempInstall"
RunWait, "copyUpdate.bat" "%updateScriptPath%" "%installPath%" "%installFolder%" "%installPath%_tempInstall" "%installFolder%_tempInstall", , 
```

AND 
`%TM-Folder%\lib\copyUpdate.bat`, line 75 (last line):
```
::pause
```
to
```
pause
```
____________________________
You'll get a message box showing all path that will be passed to the batch script that finishes the update and the batch script will be shown (console window) and it will be pause instead of being closed automatically. Maybe we can see some errors there.

**Comment by MaxKruse** [comment]
http://bit.ly/2FpBHph http://bit.ly/2FolW1K http://bit.ly/2Fm6JhD there you go, all the boxes and stuff i got from doing this.

**Comment by Eruyome** [comment]
https://github.com/PoE-TradeMacro/POE-TradeMacro/archive/devEru.zip

I've added some more debug output, you have to enable `Debug output` in the settings though. Just edit `%TM-Folder%\resources\Version_Trade.txt` and lower the version number to simulate updates.

On a first glance I'd say that you some permission issues.

**Comment by MaxKruse** [comment]
http://bit.ly/2CSfm1O updated the owner of the whole partition/harddrive to the user, so there is no way the application doesnt have permission

**Comment by Eruyome** [comment]
I have updated the dev branch and improved the error handling. A successful update should look like this:
 
![image](https://user-images.githubusercontent.com/16058242/34848822-8c0778ca-f720-11e7-9762-e77b192e52b3.png)

I said there may be permission issues because even AHKs FileMoveDir fails while throwing an exception, which is unusual.

**Comment by MaxKruse** [comment]
![cmd_2018-01-11_23-05-08](https://user-images.githubusercontent.com/10248041/34849797-ec8b7324-f723-11e7-801b-a2d25426afd6.png)

what is going on wtf

**Comment by Eruyome** [comment]
So, permission issues...
This seems to happen while executing the second robocopy commands. I have updated the script again, while it solves nothing it prints out the actual robocopy command used, including full filepaths.

**Comment by MaxKruse** [comment]
well thats weird http://bit.ly/2EC73rt

there is no "C:\Users\Max\AppData\Local\Temp\POE-TradeMacro\ext" for me D:

**Comment by Eruyome** [comment]
https://github.com/PoE-TradeMacro/POE-TradeMacro/archive/devEru.zip

Now the script directly stops of that `\ext` folder doesn't exist or is empty. Try it to make sure that the is really missing at the moment of script execution. I'll also try to see why it may be missing.

**Comment by MaxKruse** [comment]
the /ext folder with all its contents is indeed created/extracted/whatever. 

it appears the update now works, altho the temp-folder dont get deleted correctly http://bit.ly/2FzfULN
http://bit.ly/2FxgtWl

**Comment by Eruyome** [comment]
That confuses me a bit... I'll also take look at the cleanup (removing the temp folder).

**Comment by tiany4** [comment]
Just got a chance to get on my computer... Anyway, [https://i.imgur.com/YeTOKWr.png](https://i.imgur.com/YeTOKWr.png) this is what I have.

**Comment by Eruyome** [comment]
https://github.com/PoE-TradeMacro/POE-TradeMacro/archive/devEru.zip

@tiany4 Try this, some commands used in the batch script like robocopy and findstr are not part of cmd.exe but external executables stored in %SystemRoot%\System32. I didn't use full pathnames which can lead to issues if that path is not contained inyour users PATH variable.

**Comment by tiany4** [comment]
So here's what happened.

1. Extracted to C:\POE-TradeMacro-devEru. 
2. Changed VersionTrade.txt from TradeReleaseVersion := "v2.7.5" to TradeReleaseVersion := "v2.7.4"
3. Ran Run_TradeMacro.ahk and updated.
4. The update ran successfully,
5. A new folder, C:\POE-TradeMacro was created with the new version. It is ran automatically. The old script in C:\POE-TradeMacro-devEru was unchanged.
6. In C:\POE-TradeMacro, I changed VersionTrade.txt from TradeReleaseVersion := "v2.7.5" to TradeReleaseVersion := "v2.7.4".
7. Ran Run_TradeMacro.ahk and updated.
8. The folder C:\POE-TradeMacro was deleted, and C:\POE-TradeMacro_tempInstall was created, but this new folder is empty.
9. An error occured saying "Script file not found: C:\POE-TradeMacro\Run_TradeMacro.ahk".
10. In the end, there were the original C:\POE-TradeMacro-devEru and the empty C:\POE-TradeMacro_tempInstall.

**Comment by Eruyome** [comment]
Have you run the update in debug mode? I have suspicions what/where it went wrong but I need to know if there are any issues shown by the batch script.

**Comment by tiany4** [comment]
Sorry, life got busy and I forgot about this issue. I will do some testing
when I get home from work tonight. Would you like me to use the debug build
from earlier or just enable debugging from the latest release?

**Comment by Eruyome** [comment]
The latest release should be ok.

**Comment by tiany4** [comment]
https://i.imgur.com/A54ksS7.png
This is what I have.

**Comment by Eruyome** [comment]
That seems ok, did the  update work or did something fail?

**Comment by tiany4** [comment]
Seems like it works with debug output off.

**Comment by Eruyome** [comment]
With debug output on it should work then also, if you close all debug windows after they appear at least. So, your case is closed then?

**Comment by tiany4** [comment]
I'd say yes. I will let you know if something else comes up.
