### ISSUE TITLE
poor computer user has a problem here.

### ISSUE THREAD

**Issue by FELITH** [PoE-TradeMacro/POE-TradeMacro#595]
Can you make an option to copy the link to Clipboard instead of open on browser for the ctrl+w,q. So I can open it myself with POE's steam browser.
why I want this? because My computer is too slow to open a browser.

**Comment by FELITH** [comment]
and the options window is too big on my 1366x768 resolution.

**Comment by Eruyome** [comment]
Settings dimensions are fixed already.
The option to copy to clipboard instead is also added.
Will be released soon as a new beta release.
