### ISSUE TITLE
Poe.trade provider blocking and curl.exe

### ISSUE THREAD

**Issue by BillyofAstora** [PoE-TradeMacro/POE-TradeMacro#602]
This was already asked in #491, but no actual solution was posted. Apparently poe.trade is blocked in Russia due to either ignorance or stupidity, or both. Several providers are blocking it as of now.

The goal here is to use proxy with curl.exe - but how? I am no expert and I have no idea. I set IE to load poe.trade with a specific proxy, but that doesn't seem to help.

Any advice, please?

**Comment by Eruyome** [comment]
From the top of may head: Use a VPN. 
Regarding proxies with curl, I'll have to look into that.

**Comment by BillyofAstora** [comment]
>>>do you need cloudflare bypass/cookies to access poe.trade with your browser
I simply entered a proxy in IE and now it opens it no problem. The problem is to contact it with trade macro.

https://i.gyazo.com/0207c46e1ad0a62ef02d796b26227844.png

**Comment by Eruyome** [comment]
PLease show me the proxy itself, so that I can find away to use it with curl.

**Comment by BillyofAstora** [comment]
Well, there are lots of different ways to bypass that blockade (for browsers). For example, I pasted this https://antizapret.prostovpn.org/proxy.pac in the proxy url field in IE.
