### ISSUE TITLE
Update Failed, Leaving Garbled Folders. What Now?

### ISSUE THREAD

**Issue by dsnvwlmnt** [PoE-TradeMacro/POE-TradeMacro#604]
[Ignore cports.exe & Path of Exile.ahk, i manually copy them there.]

AHK version: 1.1.26.01
Windows version: 10 Home

![image](https://user-images.githubusercontent.com/14173022/33793590-a138543e-dc6e-11e7-909e-d41c33ea5918.png)

**Comment by aRTy42** [comment]
Delete "POE-TradeMacro" and rename the "..._tempInstall" folder to "POE-TradeMacro". The file dates look like only the final rename failed.

If it does not run properly then (and does not correct itself via update either), you should remove everything except the "_backup" folder and either try to run that one (so an update is executed) or manually download the latest release and unzip it.

**Comment by dsnvwlmnt** [comment]
Seems to have done the trick.
