### ISSUE TITLE
no Abyss league option 

### ISSUE THREAD

**Issue by FFx2** [PoE-TradeMacro/POE-TradeMacro#605]
I can only select standard or hardcore no Abyss league option v2.6.2

**Comment by dominikS007** [comment]
Yup I have the same problem. I receive an error message with the error:

Parsing the currency data (json) from poe.ninja failed.

I have looked for an solution for this but only found that this issue was already once addressed with 
https://github.com/PoE-TradeMacro/POE-TradeMacro/issues/534

It is just this time that I cannot do the changes that "dein0s" says because as they do not exist:

> file resources/ahk/TradeMacro.ahk lines #3784 and #3797 replace http://poeninja.azureedge.net with http://poe.ninja

**Comment by damoochie** [comment]
I also have the Parsing error and another error that appears before that message:

![failed](https://user-images.githubusercontent.com/13886692/33826630-5666ae66-deb1-11e7-986a-4f69a06df6b6.JPG)
I've tried all the different options available but can't get it to work

**Comment by FFx2** [comment]
![image](https://user-images.githubusercontent.com/34435539/33827154-fbcd35f6-de6f-11e7-85d9-665422af7e24.png)

**Comment by damoochie** [comment]
To the OP: "tmpstandard" should be the option for Abyss league now.

**Comment by Eruyome** [comment]
`tmpstandard` = temporary standard league, so at the moment = `abyss`.

@damoochie abd @dominikS007 do you always have those issues or just at times? These things can happen if there are issues with yout connection to these sites/servers, which doesn't mean it's a permanent thing.

**Comment by dominikS007** [comment]
No, this only happened recent that is why I am confused about the error. When the league started its was fine was able to select the option abyss. Then one time my internet dropped and this problem started to happen.

**Comment by wnipper** [comment]
I have tmpstandard selected and it is still searching against standard, not abyss.  

I have an older version (the last update before the fancy new "additional settings" interface) installed on my main PC.  On that version, tmpstandard == abyss league.  On my laptop, I have 2.6.3, downloaded just a few minutes ago.  On this version, tmpstandard == standard.

**Comment by wnipper** [comment]
![image](https://user-images.githubusercontent.com/29803508/33842765-7cabe048-de69-11e7-8649-d3f5285b4e7c.png)

![image](https://user-images.githubusercontent.com/29803508/33842740-6b0cb74a-de69-11e7-8cb9-f265f413dbe2.png)

**Comment by Eruyome** [comment]
https://www.dropbox.com/s/0ylxegir9o78jff/POE-TradeMacro.rar?dl=0

Try this version, it pops up a debug output window, probably 2 times. Most likely both times it has the same contents. Here's a part of it, unless 1 - 5 different I only need to see the output of one of those windows. 
![image](https://user-images.githubusercontent.com/16058242/33868040-e22b6730-df00-11e7-9bec-1e831051d63e.png)

Just copy and paste the text here. Try wrapping it in code blocks (there's a format option for this in this editor here if you don't know how, called "Insert code").

**Comment by HMBK** [comment]
Different person, had the same issue (parsing the currency JSON) crop up these last couple of days. Have tried copying the JSON from PoE's API as someone suggested, running as admin, at C: instead of Users directory etc... No dice.

On **Win7**, by the way - here's the output from your debug version:

`Array
(
    [1] => Array
        (
            [end] => 2018-03-07T21:00:00Z
            [start] => 2017-12-08T20:00:00Z
        )
    [2] => tmpstandard
    [3] => 3845922
    [4] => -9095164078
    [5] => tmpstandard
    [6] => Array
        (
            [1] => Array
                (
                    [description] => #LeagueStandard
                    [endAt] => 
                    [event] => 0
                    [id] => Standard
                    [registerAt] => 
                    [rules] => Array
                        (
                        )
                    [startAt] => 2013-01-23T21:00:00Z
                    [url] => http://pathofexile.com/forum/view-thread/71278
                )
            [2] => Array
                (
                    [description] => #LeagueHardcore
                    [endAt] => 
                    [event] => 0
                    [id] => Hardcore
                    [registerAt] => 
                    [rules] => Array
                        (
                            [1] => Array
                                (
                                    [description] => A character killed in Hardcore is moved to its parent league.
                                    [id] => 4
                                    [name] => Hardcore
                                )
                        )
                    [startAt] => 2013-01-23T21:00:00Z
                    [url] => http://pathofexile.com/forum/view-thread/71276
                )
            [3] => Array
                (
                    [description] => #LeagueStandardSSF
                    [endAt] => 
                    [event] => 0
                    [id] => SSF Standard
                    [registerAt] => 
                    [rules] => Array
                        (
                            [1] => Array
                                (
                                    [description] => You may not party in this league.
                                    [id] => 24
                                    [name] => Solo
                                )
                        )
                    [startAt] => 2013-01-23T21:00:00Z
                    [url] => http://pathofexile.com/forum/view-thread/1841357
                )
            [4] => Array
                (
                    [description] => #LeagueHardcoreSSF
                    [endAt] => 
                    [event] => 0
                    [id] => SSF Hardcore
                    [registerAt] => 
                    [rules] => Array
                        (
                            [1] => Array
                                (
                                    [description] => A character killed in Hardcore is moved to its parent league.
                                    [id] => 4
                                    [name] => Hardcore
                                )
                            [2] => Array
                                (
                                    [description] => You may not party in this league.
                                    [id] => 24
                                    [name] => Solo
                                )
                        )
                    [startAt] => 2013-01-23T21:00:00Z
                    [url] => http://pathofexile.com/forum/view-thread/1841353
                )
            [5] => Array
                (
                    [description] => #LeagueStandardAbyss
                    [endAt] => 2018-03-07T21:00:00Z
                    [event] => 0
                    [id] => Abyss
                    [registerAt] => 2017-12-08T19:30:00Z
                    [rules] => Array
                        (
                        )
                    [startAt] => 2017-12-08T20:00:00Z
                    [url] => http://pathofexile.com/forum/view-thread/2037517
                )
            [6] => Array
                (
                    [description] => #LeagueHardcoreAbyss
                    [endAt] => 2018-03-07T21:00:00Z
                    [event] => 0
                    [id] => Hardcore Abyss
                    [registerAt] => 2017-12-08T19:30:00Z
                    [rules] => Array
                        (
                            [1] => Array
                                (
                                    [description] => A character killed in Hardcore is moved to its parent league.
                                    [id] => 4
                                    [name] => Hardcore
                                )
                        )
                    [startAt] => 2017-12-08T20:00:00Z
                    [url] => http://pathofexile.com/forum/view-thread/2037514
                )
            [7] => Array
                (
                    [description] => #LeagueStandardSSFAbyss
                    [endAt] => 2018-03-07T21:00:00Z
                    [event] => 0
                    [id] => SSF Abyss
                    [registerAt] => 2017-12-08T19:30:00Z
                    [rules] => Array
                        (
                            [1] => Array
                                (
                                    [description] => You may not party in this league.
                                    [id] => 24
                                    [name] => Solo
                                )
                        )
                    [startAt] => 2017-12-08T20:00:00Z
                    [url] => http://pathofexile.com/forum/view-thread/2037510
                )
            [8] => Array
                (
                    [description] => #LeagueHardcoreSSFAbyss
                    [endAt] => 2018-03-07T21:00:00Z
                    [event] => 0
                    [id] => SSF Abyss HC
                    [registerAt] => 2017-12-08T19:30:00Z
                    [rules] => Array
                        (
                            [1] => Array
                                (
                                    [description] => A character killed in Hardcore is moved to its parent league.
                                    [id] => 4
                                    [name] => Hardcore
                                )
                            [2] => Array
                                (
                                    [description] => You may not party in this league.
                                    [id] => 24
                                    [name] => Solo
                                )
                        )
                    [startAt] => 2017-12-08T20:00:00Z
                    [url] => http://pathofexile.com/forum/view-thread/2037508
                )
        )
)`

**Comment by Eruyome** [comment]
And you can confirm that it actually searches on standard (use ctrl + q for example)? I'd expect it does though.

**Comment by HMBK** [comment]
Sorry, had to patch the game - yep, Ctrl-Q searches like you'd expect, but on Standard. Ctrl-D displays results again from Standard.

...Though, setting this debug one to "tmpstandard" looks to have it working for Abyss league queries?

I just went and restored the old 2.6.2 rar, gave it a go and it looks like it's working fine? No JSON error, result tooltips say (Abyss) and poe.trade opens up on Abyss league.

**Comment by Eruyome** [comment]
I don't know why it suddenly works for you, maybe you still used some old files for some reason?

In any case, for any others having this issue:
* Try removing all TradeMacro files and using a fresh install.
* Try using this second debug version that shows some different data. https://www.dropbox.com/s/v82v1ihy0b21wbu/POE-TradeMacro2.rar?dl=0

**Comment by wnipper** [comment]
Okie doke.  I'll do a clean scrub, try again with 2.6.3, and report back.  Thank you for the quick response.

**Comment by wnipper** [comment]
Did it in two steps: first just deleted the poetrade macro folder and restarted.  no change.  

Deleted the macro settings folder in `%user%/documents/PoE-TradeMacro/`, deleted the macro folder again, re-extracted the folder, and launched the macro.  Price checks are now done against abyss.  

Only issue I see now (which is persistent since the last install of 2.6.3) is that every time I use the F4 shortcut, I receive "The target of this operation was not a party member".  I copy and pasted my character name directly from the character list on pathofexile.com and made sure to trim whitespace.

**Comment by damoochie** [comment]
it seems to be loading up and functioning normally for me now most of the time for some reason.... still only getting that .json parsing error now.
