### ISSUE TITLE
Using skipSelection breaks auto-update if the script is stored in %My_Documents%\<anyfoldername>\

### ISSUE THREAD

**Issue by sherlockmatt** [PoE-TradeMacro/POE-TradeMacro#606]
Windows 10, TradeReleaseVersion := "v2.6.1" (I saw the same error message in v2.6.0 as well)

After much poking around to try to find out why it thought I was trying to run the script from the user settings folder, it looks like this piece of code here is mangling the path:

```ahk
defaultFolder := RegExReplace(defaultDir, "i)[^\\]+$", "")
; append '_devUpdate' to the folder if it's a development version (.git folder exists)
defaultFolder := StrLen(isDevVersion) > 0 ? defaultFolder . project . "_devUpdate" : defaultFolder . project
; check for equality but ignore case sensitivity (prefer current script dir)
defaultFolder := (defaultFolder != defaultDir) ? defaultFolder : defaultDir
```
_.\lib\PoEScripts_Update.ahk, function UpdateScript, lines 297-301_

This seems to create the variable `defaultFolder` which is the path to the current parent folder with "PoE-TradeMacro" appended. Further on down the function the `defaultFolder` variable is used for the rest of the update process.

I can't work out why this would be the case. This means that if you want to use skipSelection, you have to store the script in a folder called PoE-TradeMacro, which of course conflicts with the user folder if the parent directory of wherever you had installed it previously is %My_Documents%. This restriction is not imposed if you use the folder selection dialog box instead.

The ideal solution would be to simply use the current location, then append "_devUpdate" or "_backup" to it as necessary. I assume there's a reason it's done the current way, but if this solution is acceptable I can make a pull request to implement it.

The workaround for this problem is to create the folder "PoE-TradeMacro" inside wherever the script was stored, move all the files into that folder, then run it from there. As soon as the parent directory is not %My_Documents%, everything works fine.

**Comment by aRTy42** [comment]
Storing the script in %My_Documents% can cause several issues. This particular case can be fixed I suppose, but it won't solve everything. The better approach would be to tell people not to use %My_Documents%.

**Comment by sherlockmatt** [comment]
To be clear I had it stored in "D:\Users\Matt\Documents\PoE-TradeMacro-Script\", and never had a problem before this one. Just seems weird to force a folder name on the user like that without explanation. Took me a long time to work out why I was getting the "you can't use the user settings directory for the script" error when as far as I was concerned I wasn't... And I'm a programmer as my day job!

**Comment by aRTy42** [comment]
Depending on your windows version, anti-virus settings and general permissions, %My_Documents% also comes with read/write issues.
Putting the main script folder into the user-settings folder, so something like "\Documents\PoE-TradeMacro\PoE-TradeMacro-Script" is also problematic, I've dealt with several reports where this caused various malfunctions. Nesting it the other way around (as you suggested) should work. Eruyome managed the Updater though, so I'll rather let him decide how he wants to handle it.

**Comment by Eruyome** [comment]
I actually forgot about this issue... I'm not sure anymore why things were done as they were, I'll think about this sometime, not for now though unless someone sees this as a critical issue. 

Using any subfolder of MyDocuments was never much of an issue for most people as long as it's not `PoE-TradeMacro`.  I'm doing my entire development in `...Documents\GitHub\POE-TradeMacro` since the first day.
