### ISSUE TITLE
ctrl + alt + d  only show base values for search

### ISSUE THREAD

**Issue by Khuzvhan** [PoE-TradeMacro/POE-TradeMacro#608]
i can't add min values for suffixes and prefixes anymore, can't even see them when i use the advanced search, the only ones shown are total armor/evasion/es stuff.

figured it only happens with elder base rares btw

**Comment by Eruyome** [comment]
What's your macro version? and show me a screenshot pelase, everything works for me.

**Comment by Khuzvhan** [comment]
https://puu.sh/yEbmz/63d3d6bcc7.png - shield
https://puu.sh/yEbnc/dff137e3f7.png    - no mods available in advanced search

just started after the latest update 2.6.2

**Comment by Eruyome** [comment]
Can you send me the item data (press ctrl + c while hovering over it), then paste your clipboard here. Also check if you have this here in the settings selected:

![image](https://user-images.githubusercontent.com/16058242/33867477-3230427c-defd-11e7-8835-2c446f063004.png)

**Comment by Khuzvhan** [comment]
somehow back to normal in 2.6.3  :)    something was prob missing/conflicting in 2.6.2 .  it's  good there was a hotfix update so soon.  thanks.
