### ISSUE TITLE
Ctrl+F on Maps lists map as Unknown

### ISSUE THREAD

**Issue by PlanBe01** [PoE-TradeMacro/POE-TradeMacro#609]
![newmaps not found](https://user-images.githubusercontent.com/34453717/33842979-f5ac5284-de50-11e7-9e20-ac9a32518d91.jpg)

Most of the new maps will not work with the Ctrl + F

AHK version: release 2.6.3
Windows version:Win10

**Comment by Eruyome** [comment]
ItemInfos map list isn't updated yet since the wiki is broken and we usually scrape it instead of hardcoding everything by hand. I hotfixed this for the map search (pricing) but overlooked it here.

**Comment by Eruyome** [comment]
For reference https://github.com/PoE-TradeMacro/POE-TradeMacro/issues/607#issuecomment-350947315
