### ISSUE TITLE
Error: Target lable does not exist. Specifically: CM_ExecuteCustomeMacrosCode_Label

### ISSUE THREAD

**Issue by GanWPR** [PoE-TradeMacro/POE-TradeMacro#612]
Hi Just Started POE, Saw this on a YouTube Vid.
No Personal Editing was done. Just want to get it to work.

AHK version: 1.1.26.01 (edit)
POE Trade Macro: 2.6.3 (edit)
Windows version: Window 10 (64Bit)

![trade macro error message](https://user-images.githubusercontent.com/34544389/33995486-1f055b92-e119-11e7-94b9-c812ddffb0f2.jpg)

Picture Attached.
Kindly assist.

**Comment by zhindetz** [comment]
But readme says "Don't install AutoHotkey v2.x.".
Use 1.1 and it will work.

**Comment by GanWPR** [comment]
Pardon me. Made the changes, i installed AHK 1.1.26.01

**Comment by Eruyome** [comment]
Does it work now?

**Comment by GanWPR** [comment]
by changes i mean, i was always using AHK 1.1.26.01. 
I missunderstood, and typed out that i was using AHK 2.6.3 (however i mean i was using the 2.6.3 POE Trade Macro)

So no, it still does not work.

**Comment by Eruyome** [comment]
Sry, late answers ince I took some time off. The error message refers to a label in the [custom macros file](https://github.com/PoE-TradeMacro/POE-TradeMacro/wiki/Custom-Macros). If that file does not exist for some reason that error would make sense.
