### ISSUE TITLE
Is it possible for the script not to press CapsLock

### ISSUE THREAD

**Issue by OmikronGamma** [PoE-TradeMacro/POE-TradeMacro#615]
Hello,
i have a push-to-talk bind to CapsLock in disord; and whenever CapsLock is on and i press any of Script's hotkeys, push-to-talk is activated (=CapsLock is pressed). 
Is it possible to fix? I know its a very minor issue, but its really annoying.

**Comment by Eruyome** [comment]
CapsLock is never being pressed. Not even shift.

**Comment by OmikronGamma** [comment]
Well, it sure is activates it. Can it be because of how AHK works?

**Comment by Pegoth** [comment]
@OmikronGamma It's because of the SetStoreCapslockMode is On by default, easy fix is to add SetStoreCapslockMode, Off in customMacros_example.txt (Right click PoE TradeMacro icon->Edit files->Custom Macro Example) like this and then restart the script
```AutoHotkey
CM_ExecuteCustomMacrosCode_Label:
	SetStoreCapslockMode, Off
Return
```

**Comment by OmikronGamma** [comment]
DUDE! You are my hero! It worked!
