### ISSUE TITLE
ctrl-d on abyss belt crashed computer.

### ISSUE THREAD

**Issue by sclient** [PoE-TradeMacro/POE-TradeMacro#617]
Required power cycle, could not open task manager.

AHK version: Not sure how to check this, but it is at whatever version your script last forced an update to.
Windows version: 8.1

I checked for the log file in temp, but it didnt exist.

Edit: Attempted to replicate, finally, and no problems. May have been another program that crashed me and was just odd timing.

**Comment by Eruyome** [comment]
Would have been very surprised if the macro would have caused it...
