### ISSUE TITLE
"Show item age" function does not work.

### ISSUE THREAD

**Issue by OmikronGamma** [PoE-TradeMacro/POE-TradeMacro#618]
Hello,
"Show item age" function does not work, instead it tries to predict item price, using poeprices.
i tried to reinstall the script and deleting config files (those located at documents), in case hotkey got messy, but no.
Using latest version (2.7.2).

**Comment by tinyspider** [comment]
2.7.1 seems have the same problem. 2.6.3 works well for me.

**Comment by Hurri04** [comment]
it seems to work on unique items for me but not on items of other rarities.
nevertheless it would be great if this could get fixed ASAP since it's pretty important to know how old items are to update their prices effectively.

**Comment by sclient** [comment]
I have not been able to make it work for at least the last 2 leagues if not longer.

**Comment by Yberamos** [comment]
A temporary fix I've found is to disable predicted item pricing. When that features is disabled, the show age features function without any issue.

**Comment by Eruyome** [comment]
Fixed in the next update. At least the issue with the predicted search. Works fine for me otherwise, please report back after the upcoming update if you still have issues.
