### ISSUE TITLE
Small issue with window placement on dual screens.

### ISSUE THREAD

**Issue by sclient** [PoE-TradeMacro/POE-TradeMacro#619]
So the advanced search will not retain memory of the window position when placed on a second screen on an extended desktop. Hopefully someone involved with this has a second screen they can test on.

AHK version: not sure
Windows version: 8.1

**Comment by sclient** [comment]
Additional info: Im talking about the advanced search window, and as I recall it would remember the position correctly on a previous version when I moved it onto the second screen.

**Comment by Eruyome** [comment]
I'm not sure if that ever was the case, I don't think so at least.
