### ISSUE TITLE
Request to poeprices.info timed out or returned an invalid response!

### ISSUE THREAD

**Issue by Seminko** [PoE-TradeMacro/POE-TradeMacro#620]
AHK version: 1.1.26.01 (according to the help file)
Windows version: W7 SP1

Everytime i run CTRL+D I get this error: "Request to poeprices.info timed out or returned an invalid response!". I tried running the item manually on poeprices.info and it worked.

Also, not sure if this is on my end, I doubt it though, but poeprices check takes a LOT OF TIME to process. At least 45-60s. Not sure if this is the correct way to go for TradeMacro...

**Comment by grufftech** [comment]
I have the same issue

**Comment by dsnvwlmnt** [comment]
Still have this issue 6 days later...

**Comment by Eruyome** [comment]
Sorry, took a week off. 
If the request fails, there should be a file `%A_ScriptDir%\temp\poeprices_log.txt`, post that please.

**Comment by dsnvwlmnt** [comment]
Request and response:
{
    "added": {
        "browserUrl": "https://www.poeprices.info/api?l=Hardcore Abyss&i=UmFyaXR5OiBSYXJlDQpHcmltIEtlZXANClNpbGtlbiBIb29kDQotLS0tLS0tLQ0KRXZhc2lvbiBSYXRpbmc6IDM0Ng0KLS0tLS0tLS0NClJlcXVpcmVtZW50czoNCkxldmVsOiA2MA0KRGV4OiAxMzgNCi0tLS0tLS0tDQpTb2NrZXRzOiBHIEctRyANCi0tLS0tLS0tDQpJdGVtIExldmVsOiA3NA0KLS0tLS0tLS0NCjE1JSBpbmNyZWFzZWQgRHVhbCBTdHJpa2UgQXR0YWNrIFNwZWVkDQotLS0tLS0tLQ0KU29ja2V0ZWQgR2VtcyBhcmUgU3VwcG9ydGVkIGJ5IExldmVsIDE4IFJlbW90ZSBNaW5lDQoyNCUgaW5jcmVhc2VkIE1pbmUgRGFtYWdlDQorMjUgdG8gSW50ZWxsaWdlbmNlDQorNjMgdG8gbWF4aW11bSBMaWZlDQoxNiUgaW5jcmVhc2VkIFN0dW4gYW5kIEJsb2NrIFJlY292ZXJ5DQotLS0tLS0tLQ0KU2hhcGVyIEl0ZW0NCg==&w=1",
        "encodedData": "UmFyaXR5OiBSYXJlDQpHcmltIEtlZXANClNpbGtlbiBIb29kDQotLS0tLS0tLQ0KRXZhc2lvbiBSYXRpbmc6IDM0Ng0KLS0tLS0tLS0NClJlcXVpcmVtZW50czoNCkxldmVsOiA2MA0KRGV4OiAxMzgNCi0tLS0tLS0tDQpTb2NrZXRzOiBHIEctRyANCi0tLS0tLS0tDQpJdGVtIExldmVsOiA3NA0KLS0tLS0tLS0NCjE1JSBpbmNyZWFzZWQgRHVhbCBTdHJpa2UgQXR0YWNrIFNwZWVkDQotLS0tLS0tLQ0KU29ja2V0ZWQgR2VtcyBhcmUgU3VwcG9ydGVkIGJ5IExldmVsIDE4IFJlbW90ZSBNaW5lDQoyNCUgaW5jcmVhc2VkIE1pbmUgRGFtYWdlDQorMjUgdG8gSW50ZWxsaWdlbmNlDQorNjMgdG8gbWF4aW11bSBMaWZlDQoxNiUgaW5jcmVhc2VkIFN0dW4gYW5kIEJsb2NrIFJlY292ZXJ5DQotLS0tLS0tLQ0KU2hhcGVyIEl0ZW0NCg==",
        "league": "Hardcore Abyss",
        "requestUrl": "https://www.poeprices.info/api?l=Hardcore Abyss&i=UmFyaXR5OiBSYXJlDQpHcmltIEtlZXANClNpbGtlbiBIb29kDQotLS0tLS0tLQ0KRXZhc2lvbiBSYXRpbmc6IDM0Ng0KLS0tLS0tLS0NClJlcXVpcmVtZW50czoNCkxldmVsOiA2MA0KRGV4OiAxMzgNCi0tLS0tLS0tDQpTb2NrZXRzOiBHIEctRyANCi0tLS0tLS0tDQpJdGVtIExldmVsOiA3NA0KLS0tLS0tLS0NCjE1JSBpbmNyZWFzZWQgRHVhbCBTdHJpa2UgQXR0YWNrIFNwZWVkDQotLS0tLS0tLQ0KU29ja2V0ZWQgR2VtcyBhcmUgU3VwcG9ydGVkIGJ5IExldmVsIDE4IFJlbW90ZSBNaW5lDQoyNCUgaW5jcmVhc2VkIE1pbmUgRGFtYWdlDQorMjUgdG8gSW50ZWxsaWdlbmNlDQorNjMgdG8gbWF4aW11bSBMaWZlDQoxNiUgaW5jcmVhc2VkIFN0dW4gYW5kIEJsb2NrIFJlY292ZXJ5DQotLS0tLS0tLQ0KU2hhcGVyIEl0ZW0NCg=="
    },
    "failed": "ERROR: Parsing response failed, invalid JSON! "
}

**Comment by Eruyome** [comment]
Thx, found the issue.

**Comment by Seminko** [comment]
I will take a look tomorrow. Thanks for getting back to us.

**Comment by Seminko** [comment]
Updated just now, tried and get the same error:
`Request and response:
{
    "added": {
        "browserUrl": "https://www.poeprices.info/api?l=Hardcore Abyss&i=UmFyaXR5OiBSYXJlDQpFbnRyb3B5IEVkZ2UNCkltYnVlZCBXYW5kDQotLS0tLS0tLQ0KV2FuZA0KUGh5c2ljYWwgRGFtYWdlOiAyNC00NA0KQ3JpdGljYWwgU3RyaWtlIENoYW5jZTogNy4wMCUNCkF0dGFja3MgcGVyIFNlY29uZDogMS41MA0KLS0tLS0tLS0NClJlcXVpcmVtZW50czoNCkxldmVsOiA1OQ0KSW50OiAxODgNCi0tLS0tLS0tDQpTb2NrZXRzOiBCLUIgRyANCi0tLS0tLS0tDQpJdGVtIExldmVsOiA2Mg0KLS0tLS0tLS0NCjM3JSBpbmNyZWFzZWQgU3BlbGwgRGFtYWdlDQotLS0tLS0tLQ0KMTclIGluY3JlYXNlZCBTcGVsbCBEYW1hZ2UNCkFkZHMgMzYgdG8gNjcgRmlyZSBEYW1hZ2UgdG8gU3BlbGxzDQoxOCUgaW5jcmVhc2VkIENyaXRpY2FsIFN0cmlrZSBDaGFuY2UgZm9yIFNwZWxscw0KKzI3JSB0byBHbG9iYWwgQ3JpdGljYWwgU3RyaWtlIE11bHRpcGxpZXINCisxNiB0byBtYXhpbXVtIE1hbmENCg==&w=1",
        "encodedData": "UmFyaXR5OiBSYXJlDQpFbnRyb3B5IEVkZ2UNCkltYnVlZCBXYW5kDQotLS0tLS0tLQ0KV2FuZA0KUGh5c2ljYWwgRGFtYWdlOiAyNC00NA0KQ3JpdGljYWwgU3RyaWtlIENoYW5jZTogNy4wMCUNCkF0dGFja3MgcGVyIFNlY29uZDogMS41MA0KLS0tLS0tLS0NClJlcXVpcmVtZW50czoNCkxldmVsOiA1OQ0KSW50OiAxODgNCi0tLS0tLS0tDQpTb2NrZXRzOiBCLUIgRyANCi0tLS0tLS0tDQpJdGVtIExldmVsOiA2Mg0KLS0tLS0tLS0NCjM3JSBpbmNyZWFzZWQgU3BlbGwgRGFtYWdlDQotLS0tLS0tLQ0KMTclIGluY3JlYXNlZCBTcGVsbCBEYW1hZ2UNCkFkZHMgMzYgdG8gNjcgRmlyZSBEYW1hZ2UgdG8gU3BlbGxzDQoxOCUgaW5jcmVhc2VkIENyaXRpY2FsIFN0cmlrZSBDaGFuY2UgZm9yIFNwZWxscw0KKzI3JSB0byBHbG9iYWwgQ3JpdGljYWwgU3RyaWtlIE11bHRpcGxpZXINCisxNiB0byBtYXhpbXVtIE1hbmENCg==",
        "league": "Hardcore Abyss",
        "requestUrl": "https://www.poeprices.info/api?l=Hardcore Abyss&i=UmFyaXR5OiBSYXJlDQpFbnRyb3B5IEVkZ2UNCkltYnVlZCBXYW5kDQotLS0tLS0tLQ0KV2FuZA0KUGh5c2ljYWwgRGFtYWdlOiAyNC00NA0KQ3JpdGljYWwgU3RyaWtlIENoYW5jZTogNy4wMCUNCkF0dGFja3MgcGVyIFNlY29uZDogMS41MA0KLS0tLS0tLS0NClJlcXVpcmVtZW50czoNCkxldmVsOiA1OQ0KSW50OiAxODgNCi0tLS0tLS0tDQpTb2NrZXRzOiBCLUIgRyANCi0tLS0tLS0tDQpJdGVtIExldmVsOiA2Mg0KLS0tLS0tLS0NCjM3JSBpbmNyZWFzZWQgU3BlbGwgRGFtYWdlDQotLS0tLS0tLQ0KMTclIGluY3JlYXNlZCBTcGVsbCBEYW1hZ2UNCkFkZHMgMzYgdG8gNjcgRmlyZSBEYW1hZ2UgdG8gU3BlbGxzDQoxOCUgaW5jcmVhc2VkIENyaXRpY2FsIFN0cmlrZSBDaGFuY2UgZm9yIFNwZWxscw0KKzI3JSB0byBHbG9iYWwgQ3JpdGljYWwgU3RyaWtlIE11bHRpcGxpZXINCisxNiB0byBtYXhpbXVtIE1hbmENCg=="
    },
    "failed": "ERROR: Parsing response failed, invalid JSON! "
}`

**Comment by Eruyome** [comment]
FYI I forgot to [URL encode](https://www.w3schools.com/tags/ref_urlencode.asp) the leaguename in the URL, which is an issue if there are spaces, like in `hardcore abyss`...

**Comment by Seminko** [comment]
Totally forgot to get back to you. It works perfectly now, thanks.

**Comment by zombodotcom** [comment]
Issue just popped back up


#####
### Please post this log file to https://www.pathofexile.com/forum/view-thread/1216141/.
#####

Request and response:
{
    "added": {
        "browserUrl": "https://www.poeprices.info/api?l=Incursion&i=UmFyaXR5OiBSYXJlDQpQYW5kZW1vbml1bSBCYXR0ZXINCkNyaW1zb24gSmV3ZWwNCi0tLS0tLS0tDQpJdGVtIExldmVsOiA3OA0KLS0tLS0tLS0NCjE0JSBpbmNyZWFzZWQgUGh5c2ljYWwgRGFtYWdlIHdpdGggTWFjZXMNCjE3JSBpbmNyZWFzZWQgQ3JpdGljYWwgU3RyaWtlIENoYW5jZSB3aXRoIE9uZSBIYW5kZWQgTWVsZWUgV2VhcG9ucw0KMTIlIGluY3JlYXNlZCBBcmVhIERhbWFnZQ0KLS0tLS0tLS0NClBsYWNlIGludG8gYW4gYWxsb2NhdGVkIEpld2VsIFNvY2tldCBvbiB0aGUgUGFzc2l2ZSBTa2lsbCBUcmVlLiBSaWdodCBjbGljayB0byByZW1vdmUgZnJvbSB0aGUgU29ja2V0Lg0K&w=1",
        "encodedData": "UmFyaXR5OiBSYXJlDQpQYW5kZW1vbml1bSBCYXR0ZXINCkNyaW1zb24gSmV3ZWwNCi0tLS0tLS0tDQpJdGVtIExldmVsOiA3OA0KLS0tLS0tLS0NCjE0JSBpbmNyZWFzZWQgUGh5c2ljYWwgRGFtYWdlIHdpdGggTWFjZXMNCjE3JSBpbmNyZWFzZWQgQ3JpdGljYWwgU3RyaWtlIENoYW5jZSB3aXRoIE9uZSBIYW5kZWQgTWVsZWUgV2VhcG9ucw0KMTIlIGluY3JlYXNlZCBBcmVhIERhbWFnZQ0KLS0tLS0tLS0NClBsYWNlIGludG8gYW4gYWxsb2NhdGVkIEpld2VsIFNvY2tldCBvbiB0aGUgUGFzc2l2ZSBTa2lsbCBUcmVlLiBSaWdodCBjbGljayB0byByZW1vdmUgZnJvbSB0aGUgU29ja2V0Lg0K",
        "league": "Incursion",
        "requestUrl": "https://www.poeprices.info/api?l=Incursion&i=UmFyaXR5OiBSYXJlDQpQYW5kZW1vbml1bSBCYXR0ZXINCkNyaW1zb24gSmV3ZWwNCi0tLS0tLS0tDQpJdGVtIExldmVsOiA3OA0KLS0tLS0tLS0NCjE0JSBpbmNyZWFzZWQgUGh5c2ljYWwgRGFtYWdlIHdpdGggTWFjZXMNCjE3JSBpbmNyZWFzZWQgQ3JpdGljYWwgU3RyaWtlIENoYW5jZSB3aXRoIE9uZSBIYW5kZWQgTWVsZWUgV2VhcG9ucw0KMTIlIGluY3JlYXNlZCBBcmVhIERhbWFnZQ0KLS0tLS0tLS0NClBsYWNlIGludG8gYW4gYWxsb2NhdGVkIEpld2VsIFNvY2tldCBvbiB0aGUgUGFzc2l2ZSBTa2lsbCBUcmVlLiBSaWdodCBjbGljayB0byByZW1vdmUgZnJvbSB0aGUgU29ja2V0Lg0K"
    },
    "failed": "ERROR: Parsing response failed, empty response! "
}

**Comment by Eruyome** [comment]
Fixed by peoprpices.info, their API had issues.

**Comment by russpoe** [comment]
Have been unable to use trade macro for past 3-4 weeks (very annoying).  Based on this link, which is referenced in various forums regarding this problem https://www.pathofexile.com/forum/view-thread/1216141/ , show that I am not alone with this bug.  Please refer to my post listed in the forum for more information.  Thank you.

**Comment by trystan45** [comment]
Have an issue with "use predicted pricing" beeing on. this error. Error: Request to poeprice.info returned HTTP.error 504. Please take a look a look at the file "temp poeprices_log txt.

**Comment by zeoloth** [comment]
same error since yesterday

**Comment by JeroenKeijzer** [comment]
Same error. Log:

#####
### Please post this log file below to https://www.pathofexile.com/forum/view-thread/1216141/.
### Try not to "spam" their thread if a few other reports with the same error description were posted in the last hours.
#####

Request and response:
{
    "added": {
        "browserUrl": "https://www.poeprices.info/api?l=Legion&i=UmFyaXR5OiBSYXJlDQpHcmltIEVkZ2UNCkV4cXVpc2l0ZSBCbGFkZQ0KLS0tLS0tLS0NClR3byBIYW5kZWQgU3dvcmQNClBoeXNpY2FsIERhbWFnZTogOTUtMTYwIChhdWdtZW50ZWQpDQpFbGVtZW50YWwgRGFtYWdlOiA4MC0xNDMgKGF1Z21lbnRlZCkNCkNyaXRpY2FsIFN0cmlrZSBDaGFuY2U6IDYuMDAlDQpBdHRhY2tzIHBlciBTZWNvbmQ6IDEuMzUNCldlYXBvbiBSYW5nZTogMTMNCi0tLS0tLS0tDQpSZXF1aXJlbWVudHM6DQpMZXZlbDogNzANClN0cjogMTE5DQpEZXg6IDEzMQ0KLS0tLS0tLS0NClNvY2tldHM6IEcgRyBHIA0KLS0tLS0tLS0NCkl0ZW0gTGV2ZWw6IDgwDQotLS0tLS0tLQ0KKzYwJSB0byBHbG9iYWwgQ3JpdGljYWwgU3RyaWtlIE11bHRpcGxpZXINCi0tLS0tLS0tDQo3MCUgaW5jcmVhc2VkIFBoeXNpY2FsIERhbWFnZQ0KQWRkcyA4MCB0byAxNDMgRmlyZSBEYW1hZ2UNCjIzJSBpbmNyZWFzZWQgRGFtYWdlIHdpdGggQmxlZWRpbmcNCjglIGluY3JlYXNlZCBQb2lzb24gRHVyYXRpb24NCg==&w=1",
        "encodedData": "UmFyaXR5OiBSYXJlDQpHcmltIEVkZ2UNCkV4cXVpc2l0ZSBCbGFkZQ0KLS0tLS0tLS0NClR3byBIYW5kZWQgU3dvcmQNClBoeXNpY2FsIERhbWFnZTogOTUtMTYwIChhdWdtZW50ZWQpDQpFbGVtZW50YWwgRGFtYWdlOiA4MC0xNDMgKGF1Z21lbnRlZCkNCkNyaXRpY2FsIFN0cmlrZSBDaGFuY2U6IDYuMDAlDQpBdHRhY2tzIHBlciBTZWNvbmQ6IDEuMzUNCldlYXBvbiBSYW5nZTogMTMNCi0tLS0tLS0tDQpSZXF1aXJlbWVudHM6DQpMZXZlbDogNzANClN0cjogMTE5DQpEZXg6IDEzMQ0KLS0tLS0tLS0NClNvY2tldHM6IEcgRyBHIA0KLS0tLS0tLS0NCkl0ZW0gTGV2ZWw6IDgwDQotLS0tLS0tLQ0KKzYwJSB0byBHbG9iYWwgQ3JpdGljYWwgU3RyaWtlIE11bHRpcGxpZXINCi0tLS0tLS0tDQo3MCUgaW5jcmVhc2VkIFBoeXNpY2FsIERhbWFnZQ0KQWRkcyA4MCB0byAxNDMgRmlyZSBEYW1hZ2UNCjIzJSBpbmNyZWFzZWQgRGFtYWdlIHdpdGggQmxlZWRpbmcNCjglIGluY3JlYXNlZCBQb2lzb24gRHVyYXRpb24NCg==",
        "encodingError": "",
        "league": "Legion",
        "requestUrl": "https://www.poeprices.info/api?l=Legion&i=UmFyaXR5OiBSYXJlDQpHcmltIEVkZ2UNCkV4cXVpc2l0ZSBCbGFkZQ0KLS0tLS0tLS0NClR3byBIYW5kZWQgU3dvcmQNClBoeXNpY2FsIERhbWFnZTogOTUtMTYwIChhdWdtZW50ZWQpDQpFbGVtZW50YWwgRGFtYWdlOiA4MC0xNDMgKGF1Z21lbnRlZCkNCkNyaXRpY2FsIFN0cmlrZSBDaGFuY2U6IDYuMDAlDQpBdHRhY2tzIHBlciBTZWNvbmQ6IDEuMzUNCldlYXBvbiBSYW5nZTogMTMNCi0tLS0tLS0tDQpSZXF1aXJlbWVudHM6DQpMZXZlbDogNzANClN0cjogMTE5DQpEZXg6IDEzMQ0KLS0tLS0tLS0NClNvY2tldHM6IEcgRyBHIA0KLS0tLS0tLS0NCkl0ZW0gTGV2ZWw6IDgwDQotLS0tLS0tLQ0KKzYwJSB0byBHbG9iYWwgQ3JpdGljYWwgU3RyaWtlIE11bHRpcGxpZXINCi0tLS0tLS0tDQo3MCUgaW5jcmVhc2VkIFBoeXNpY2FsIERhbWFnZQ0KQWRkcyA4MCB0byAxNDMgRmlyZSBEYW1hZ2UNCjIzJSBpbmNyZWFzZWQgRGFtYWdlIHdpdGggQmxlZWRpbmcNCjglIGluY3JlYXNlZCBQb2lzb24gRHVyYXRpb24NCg==",
        "retHeader": "504",
        "timeoutParam": 25
    }
}

**Comment by Eruyome** [comment]
The poeprices.info server is currently down and the guy behind that project is away on a trip and can't fix it for probably 2 days.
