### ISSUE TITLE
Improvement: Allow alternative currency search on another hotkey?

### ISSUE THREAD

**Issue by feddddd** [PoE-TradeMacro/POE-TradeMacro#621]
Hey. I tried searching for an answer to this and asked on reddit but found no answer.

The alternative currency search is very useful, but I also want to see which trades are currently on poe.trade. Toggling the "alternative currency search" in the options replaces the regular search function on the Ctrl+D hotkey.

Would it be possible to use both of them side by side on different hotkeys? I tried looking into the script (_TradeMacroMain.ahk) and I think I found the corresponding lines (ctrl+f for TradeFunc_ParseAlternativeCurrencySearch) but I can't quite figure out how to bind this on a custom hotkey. Any help would be appreciated.

Thank you for this fantastic tool!

**Comment by Eruyome** [comment]
While there's merit to doing this I'm very hesitant to implement it. Hotkeys are a kind of resource, considering how many this macro already has (including AdditionalMacros).

Take a look at custom macros https://github.com/PoE-TradeMacro/POE-TradeMacro/wiki/Custom-Macros.
Something like this should work (untested).
Basically it's a copy of the normal price check hotkey that sets the AlternativeSearch option temporarely to true.

```
CM_ExecuteCustomMacrosCode_Label:
	Hotkey, ^!v, CM_MyHotkey_Label	; ctrl + alt + v
Return

CM_MyHotkey_Label:
	IfWinActive, ahk_group PoEWindowGrp
	{
		_tempOption := TradeOpts.AlternativeSearch
		TradeOpts.AlternativeSearch := 1
		TradeFunc_PriceCheckHotkey()
		TradeOpts.AlternativeSearch := _tempOption
	}	
Return
```

**Comment by George9x9** [comment]
There are also some other good tools in this article. I recommend reading this: [https://uberant.com/article/846823-path-of-exile-addons-best-supportive-tools-for-poe/](https://uberant.com/article/846823-path-of-exile-addons-best-supportive-tools-for-poe)/ This article helped me a lot.
