### ISSUE TITLE
Search GUIs should have default buttons

### ISSUE THREAD

**Issue by Pegoth** [PoE-TradeMacro/POE-TradeMacro#622]
Custom Search and Advanced search windows should have the "Search" button as the GUI default button, so pressing enter would click it, helping to quick search for something: ctrl+i->"some item"->enter and done instead of clicking search button.

**Comment by Eruyome** [comment]
I have fixed this in the upcoming update, it's a bit "tricky" though. I can focus the control (button) but it's not sufficient to activate it via enter, so I have to send Arrow keys to correctly select the next control and the button again... I hope this doesn't lead to other issues.

	ControlFocus, , ahk_id %CSearchBtnHwnd%
	SendInput, {Right}
	SendInput, {Left}

**Comment by Eruyome** [comment]
Actually my solution was dumb. It only works when you don't interact with the GUI beforehand.
Using `enter` to submit the GUI (searching) should work in the upcoming release.
