### ISSUE TITLE
"Getting price prediction..." just disappears after a while without showing an actual price prediction

### ISSUE THREAD

**Issue by Hurri04** [PoE-TradeMacro/POE-TradeMacro#623]
From what I've seen it mostly happens on rare items when using the detailed search (CTRL+Alt+X).

If the reason is that the script is not able to find a reasonable price prediction it might be nice to know instead of the tooltip just disappearing.

Although sometimes I've seen it work after 2-3 tries. No idea why, since I'm not doing anything different. And having to check the mods I want to search multiple times per items gets old really fast.

Using AHK v1.1.26.1 (no idea whether 32 or 64 bit is selected since I just run the tool by clicking the "Run_TradeMacro.ahk" file) on Windows 7 64 bit.

**Comment by Eruyome** [comment]
The advanced search should not use this search, that is an issue in itself and will be fixed in the upcoming update. Please report back then if you still experience such an issue.
