### ISSUE TITLE
Error at line 17313 after first start

### ISSUE THREAD

**Issue by Loghaire1st** [PoE-TradeMacro/POE-TradeMacro#626]
Hello,
started yesterday i think, first time after unrar script starts and works fine, after closing and starting again I'm getting  _TradeMacroMain.ahk Error at lne 17313
Line text: Globals
Error: Duplicate class definition

AHK version: 2.7.2
Windows version: win10 x64

**Comment by aRTy42** [comment]
Please post a screenshot of the error message.

**Comment by Loghaire1st** [comment]
![poe_trade_err](https://user-images.githubusercontent.com/34153691/34298037-52032ad6-e724-11e7-88b2-8b3b5252ea56.png)

**Comment by aRTy42** [comment]
My _TradeMacroMain.ahk stops at 17284 lines, so I guess in your case something is included differently. Could you rightclick->edit the "_TradeMacroMain" please and post the code chunk around line 17313, something like 20-30 lines depending on where functions seem to start and end.

**Comment by Loghaire1st** [comment]
Funny, I've opened main file and it had same as yours ~17280 lines. After trying to start script i get the same error but the file has 2x lines. After 17280 it starts again "
; Path of Exile ItemInfo
;
; Script is currently maintained by various people and kept up to date by aRTy42 / IGN: Erinyen
; Forum thread: https://www.pathofexile.com/forum/view-thread/1678678
; GitHub: https://github.com/aRTy42/POE-ItemInfo

#SingleInstance force
"
and it has 33 075 lines. It looks like starting Run_TradeMacro doesn't check for existance of Main.ahk and just appends to the bottom.

**Comment by aRTy42** [comment]
That might be a write permission issue with the <Documents> folder. Could you move the whole script folder to somewhere else (also not on the Desktop). Something like "C:\Program Files\..." or wherever you like to install programs.

**Comment by Loghaire1st** [comment]
Yep, permissions. Other directory works like a charm. Thanks for your work.
