### ISSUE TITLE
poe trade macro not work when i update new version

### ISSUE THREAD

**Issue by bluelove1111** [PoE-TradeMacro/POE-TradeMacro#627]
![1231231231](https://user-images.githubusercontent.com/34766149/34291194-ab8e0414-e72d-11e7-9674-4ff1f37907f1.png)

**Comment by aRTy42** [comment]
Well, like the error says the script could not connect to poe.ninja at that time. This should only affect the Ctrl+C function for currency and likely is not a permanent problem.

**Comment by bluelove1111** [comment]
@aRTy42 how can i fix it ?2 days ago, i still use it I normally

**Comment by aRTy42** [comment]
Please check in your settings menu if the league is correctly set, it seems an earlier version might have broken the selection (so your selection might be empty at the moment). For Abyss it should be "tmpstandard".

**Comment by Eruyome** [comment]
@bluelove1111 Does it work  now?

**Comment by Alerand** [comment]
For me this is happening bc when trademacro initializing and trying to connect to poe.ninja he just stuck on cloudflare captcha all the time(in my case)
So the *currencyData.json* contents is content of cloudflare page.
So he cant deal with this bc he not to be here

sry for my bad english

**Comment by Alerand** [comment]
And the error [https://i.gyazo.com/4e00dc15a963f916a97b5408fbeacb11.png](url)

**Comment by Eruyome** [comment]
I hotfixed this for the next release, it's not a complete fix since it seems that cloudflare cookies need to be used in your case to connect to poe.ninja but the script should run without any breaking errors.
