### ISSUE TITLE
Pricecheck doesn`t work (No mapping for the Unicode character exists in the target multi-byte code page)

### ISSUE THREAD

**Issue by Xalention** [PoE-TradeMacro/POE-TradeMacro#63]
I followed the install instruction (downloaded AHK, downloaded the script, started it with the "Run_Only_This.ahk") and everything works fine exept the price check. I can open poe.trade with the script, go to the wiki but when i try to check the price ingame, the "menu" is empty and the next time i get an error messange (pictures below). Perhaps i just missed something or failed at some point - would be nice if someone could help me.

![poe2](https://cloud.githubusercontent.com/assets/23040933/19664743/1ed22b1a-9a42-11e6-882d-1f4c79e54449.PNG)

![poe1](https://cloud.githubusercontent.com/assets/23040933/19664742/1ec0ba88-9a42-11e6-9a3e-24c87e7f87d7.PNG)

**Comment by Eruyome** [comment]
No, I don't think you did something wrong. https://github.com/PoE-TradeMacro/POE-TradeMacro/issues/13 had this some time ago, you're only the second person reporting such a problem and it's hard for me to try solving it without being able to reproduce it. I don't even know if its simply coincidence that both errors are reported from german windows installations (have one, too though). 

Please try to give me information about your Operating System. Do you have any programming knowledge and/or think you could play around with WinHTTP Request options/settings?

**Comment by Eruyome** [comment]
You can join me on Discord or gitter, maybe i can help you then. In any case you could try editing `trade_data\TradeMacro.ahk` and find the function `FunctionDoPostRequest()`, then the lines:       

    HttpObj.Send(payload)     
    HttpObj.WaitForResponse()

and add this after them:     

    if A_LastError
		MsgBox % A_LastError   

and show me the message/error number.

**Comment by Eruyome** [comment]
Next thing to try would be replacing the entire function with this: 

```
FunctionDoPostRequest(payload, openSearchInBrowser = false)
{	
	ComObjError(0)
	Encoding := "utf-8"
    ; Reference in making POST requests - http://stackoverflow.com/questions/158633/how-can-i-send-an-http-post-request-to-a-server-from-excel-using-vba
    HttpObj := ComObjCreate("WinHttp.WinHttpRequest.5.1")
	if (openSearchInBrowser) {
		HttpObj.Option(6) := False ;
	}    
    HttpObj.Open("POST","http://poe.trade/search")
    HttpObj.SetRequestHeader("Host","poe.trade")
    HttpObj.SetRequestHeader("Connection","keep-alive")
    HttpObj.SetRequestHeader("Content-Length",StrLen(payload))
    HttpObj.SetRequestHeader("Cache-Control","max-age=0")
    HttpObj.SetRequestHeader("Origin","http://poe.trade")
    HttpObj.SetRequestHeader("Upgrade-Insecure-Requests","1")
    HttpObj.SetRequestHeader("User-Agent","Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2785.116 Safari/537.36")
    HttpObj.SetRequestHeader("Content-type","application/x-www-form-urlencoded")
    HttpObj.SetRequestHeader("Accept","text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8")
    HttpObj.SetRequestHeader("Referer","http://poe.trade/")
    ;HttpObj.SetRequestHeader("Accept-Encoding","gzip;q=0,deflate;q=0") ; disables compression
    ;HttpObj.SetRequestHeader("Accept-Encoding","gzip, deflate")
    ;HttpObj.SetRequestHeader("Accept-Language","en-US,en;q=0.8")	
    HttpObj.Send(payload)
    HttpObj.WaitForResponse()
	
	If Encoding {
		oADO          := ComObjCreate("adodb.stream")
		oADO.Type     := 1
		oADO.Mode     := 3
		oADO.Open()
		oADO.Write( HttpObj.ResponseBody )
		oADO.Position := 0
		oADO.Type     := 2
		oADO.Charset  := Encoding
		return oADO.ReadText(), oADO.Close()
	}
	
	if A_LastError
		MsgBox % A_LastError	

    ;MsgBox % HttpObj.StatusText . HttpObj.GetAllResponseHeaders()
    ;MsgBox % HttpObj.ResponseText
    ; Dear GGG, it would be nice if you can provide an API like http://pathofexile.com/trade/search?name=Veil+of+the+night&links=4
    ; Pete's indexer is open sourced here - https://github.com/trackpete/exiletools-indexer you can use this to provide this api
    
    Return, HttpObj.ResponseText
}
```

**Comment by Xalention** [comment]
Well the problem solved itself. I came home, started my pc, installed Internet Explorer (because i thought perhaps it´s relevant) and then when i tried again to start the Macro, it told me to download the new version and now it works just like it´s supposed to! Thank you for the update!

**Comment by thirdy** [comment]
the macro relies on a windows specific api for making HTTP request. so the IE thing might be related

**Comment by Eruyome** [comment]
Yeah, that's not impossible, but I hope it was the update. At least in that one forum thread it was the solution someone found for that problem.

**Comment by Eruyome** [comment]
Well, I'm just gonna close both issues and hope nobody will open them again.
