### ISSUE TITLE
Gem exp

### ISSUE THREAD

**Issue by EThaNol2005** [PoE-TradeMacro/POE-TradeMacro#630]
Hey, first at all you do a great job :)

Is it possible to disable the automatic search for Gemexp? Because it partly distorts the prices.
Example:
A Quality: 20 Level: 19 GemExp: 77 "Elemental Damage with Attacks Support"
Is numbered with 30 Choas. But one with 0 exp for 15 chaos.
But a 20/20 with 0 exp starts at 30 chaos.
I can't see the lowered exp gems and there prices, so i 'cant price with ctrl+d good enough.
I think it's not good, that is automatically searched for the gemexp.

greetings
etha

**Comment by Eruyome** [comment]
Except an option to disable this behaviour, do you have a solution to this?
Like ignoring gem XP under condition X and condition Y?

**Comment by EThaNol2005** [comment]
I think a check box (auto off) should work.
Maybe gems at least lvl 18+ are relevant enough to start with, exception Enlighten, Empower and Enhance. 
30%,60%,90% or 50%+ sounds ok in point of view.

greetings

**Comment by Eruyome** [comment]
Added an option (released in 2.7.4
