### ISSUE TITLE
After running Run_TradeMacro, AHK stops working and crashes. 

### ISSUE THREAD

**Issue by Enzgar** [PoE-TradeMacro/POE-TradeMacro#633]
AHK version: Latest version from website
Windows version: Windows 10 Home

Not sure what other information you need. I did a fresh install of both, have tried restarting and trying again, and nothing. I start the script and it tries initializing or something and after about 1 second it just says, 

"AutoHotKey Unicode 64-bit has stopped working. A problem caused the program to stop working correctly. Windows will close the program and notify you if a solution is available." 

With a button that says "close program"

**Comment by raltasha** [comment]
I get the exact same Error. Windows 8 64bit.

**Comment by Enzgar** [comment]
What sucks is there isn't like any error code or anything so I'm doubting it's easy to find the fix.

**Comment by JoelStorklubba** [comment]
Had the same issue and when installing older ahk version it worked for me

**Comment by SavageAsFudge** [comment]
Same here, on Windows7
I had a really old version of poe trade macro, about one year old which worked absolutely fine. Today I thought I'd update it because some uniques weren't supported. Update worked fine but when I try to run it tells me that I have the wrong autohotkey version and I need v 1.1.26 or later. So i download the latest version and get the same crash/error message as OP.

I downgraded to PoeTrade Macro 2.3.6 and that works the same as before.

**Comment by Eruyome** [comment]
Can you tell me the exact AHK version that don't work for you?

Here are all version btw https://autohotkey.com/download/1.1/

**Comment by SavageAsFudge** [comment]
well thats a bit complicated:
no ahk version works with the **latest** PoeTrade Macro. I tried v1.1.27 , v 1.1.26 and v1.1.23 and 24 although with the last ones I don't get a crash/error message from ahk but an error message from PoeTrade Macro telling me that I need 1.1.26 or later.

also, every ahk version works with PoeTrade Macro 2.3.6. (I chose that version randomly)

**Comment by Eruyome** [comment]
Then please try other TM versions and find the highest version that works. I have my doubts but maybe I can see something that could cause these issues.

**Comment by SavageAsFudge** [comment]
TM version 2.5.7 seems to be the last one that does work.
V2.6.0-beta.1, 2 and 3 as well as V2.6.0 all crash. didn't try any later versions

**Comment by evilbond** [comment]
Latest ahk version causes crash however:

AutoHotkey_1.1.26.01_setup.exe

Works fine.

**Comment by rathmourn** [comment]
I'm having the same issue, and just like evilbond, 2.5.7 was the last functional version for me.

**Comment by JoelStorklubba** [comment]
For me ahk v1.1.27.01 - December 31, 2017 didn't work with the latest trade macro but  v 1.1.26 worked

**Comment by Eruyome** [comment]
Guess I'll have to make a PSA with the next update.

**Comment by Eruyome** [comment]
This should be fixed with the newest AHK version.
