### ISSUE TITLE
The only shortcut working is Ctrl + c

### ISSUE THREAD

**Issue by brilvio** [PoE-TradeMacro/POE-TradeMacro#634]
AHK version: 1.1.26.01
Windows version: 10

Hi ctrl + w, ctrl + d, ctrl +alt +d is not working I am using the version 3.1.00

**Comment by Eruyome** [comment]
Are you using ItemInfo only? THat has the version number 3.1.00.
TradeMacro has a different version number.

**Comment by brilvio** [comment]
Maybe that is the problem, I will see when I am at home. Thanks.
