### ISSUE TITLE
Unique Items not appearing on Advanced Search

### ISSUE THREAD

**Issue by AkashSkySingh** [PoE-TradeMacro/POE-TradeMacro#635]
Advanced search does not allow the search of unique items. I was able to search the prices of Goldwrym's with a +16% QoI roll over the weekend. Updated today and couldn't search Goldwyrm's at all. Tried the advanced search with a BoR as well.

Prompt states the following: 
'Advanced search not available for this item. No variable mods'

Tried swapping between V.2.7.2 and V.2.7.3.

Not sure if the support for the feature was removed, or I corrupted my files by accepting an update via the prompt when loading the script. Help would be appreciated.

AHK version: 2.7.3
Windows version: Wins7 SP1

**Comment by AkashSkySingh** [comment]
Additional note: I have only experienced the error for uniques as of yet. Goldwyrms being a base case as the searched worked previously last week.

**Comment by Eruyome** [comment]
Haven't had the time to test the specific uniques that you mentioned but in general the advanced search works for uniques. Have you tested a fresh macro installation?

**Comment by AkashSkySingh** [comment]
Just tried a fresh macro install.

I figured out the issue. I believe the macro isn't able to pick up on some item mods despite them being available on POE.Trade. Not sure what changed for some of the mods for some uniques, like Carnage Heart, Goldwyrm, and Bringer Of Rain. 

Maybe  the way the mods are parsed, or how item mods are read for uniques was changed? Or something changed on  POE.trade's side, but that seem's to be the issue on my end, despite doing a clean install.

**Comment by AkashSkySingh** [comment]
Uniques, such as Divinarius and Atziri's Step still work with advanced search, it's just some mods  for other uniques do not match to the ones for them on POE.Trade.

**Comment by Eruyome** [comment]
The advanced search uses data from the wiki, at least to determine if there are variable mods and what range those mods can have. If anythin is wrong than it's likely that data, which is quite possible since the wiki is still partly broken and can't reliably be parsed/scraped at the moment.

**Comment by AkashSkySingh** [comment]
Makes absolute sense then. Assume someone adjusted things on the wiki and it broke the recognition of mods. Seeing as how even older versions of the script do not work when they did in the past.

**Comment by AkashSkySingh** [comment]
Going to close this issue then.
