### ISSUE TITLE
Crashes on AHK v1.1.27.01

### ISSUE THREAD

**Issue by lemasato** [PoE-TradeMacro/POE-TradeMacro#640]
AHK version: 1.1.27.01
Windows version: W10 x64 1709 

Just a heads up: the latest AHK update  \([1.1.27.01](https://autohotkey.com/docs/AHKL_ChangeLog.htm#v1.1.27.01)\) crashes the script on startup.
Same crash occurs on W7 x64. It's most-likely best to avoid this update.

PoEScripts_HandleUserSettings.ahk
Line 71, calling class_EasyIni() causes the crash:
`OldConfigObj := PoEScripts_TrimEndingSpacesInKeys(class_EasyIni(destDir "\" fileFullName))`

**Comment by lemasato** [comment]
All good, fixed with ([1.1.27.02](https://autohotkey.com/docs/AHKL_ChangeLog.htm#v1.1.27.02)), false alarm :p

**Comment by Eruyome** [comment]
Thx for the heads up
I knew of the issue but not of the fix.
