### ISSUE TITLE
Implicit in unidentified items

### ISSUE THREAD

**Issue by gmanrainy** [PoE-TradeMacro/POE-TradeMacro#641]
AHK version:2.7.4
Windows version:Windows 10

Hello, someone who can create pull request or change code of TradeMacro directly, please add this code to project:
POE-ItenInfo.ahk

> If (Item.hasImplicit and not Item.IsUnique) {
> 		ImplicitTooltip := ""
> 		ItemNameForCheck := ""
> 		If(Item.IsUnidentified = True)
> 		{
> 			ItemNameForCheck := Item.Name
> 		}
> 		Else
> 		{
> 			ItemNameForCheck := Item.BaseName
> 		}
> 		
> 		ImplicitValueArray := LookupImplicitValue(ItemNameForCheck)
> 		maxIndex 	:= Item.Implicit.MaxIndex()
> 		TextLineWidth := ImplicitValueArray.MaxIndex() and StrLen(ImplicitValueArray[1]) ? 20 : 50
> 		Ellipsis := Opts.AffixTextEllipsis
> 		
> 		Loop, % maxIndex {
> 			ImplicitText := Item.Implicit[A_Index]
> 			If(StrLen(ImplicitText) > TextLineWidth)
> 				{
> 					ImplicitText := SubStr(ImplicitText, 1, TextLineWidth - StrLen(Ellipsis))  Ellipsis
> 				}
> 				Else
> 				{
> 					ImplicitText := StrPad(ImplicitText, TextLineWidth)
> 				}
> 			ImplicitTooltip .= "`n" ImplicitText "  " StrPad(ImplicitValueArray[A_Index], 5, "left")
> 		}
> 		TT = %TT%`n--------%ImplicitTooltip%
> 	}

Preview looks bad because code contains special symbols.
Okay, that code need for view item implicit diapasons without identification
if item unidentified Item.BaseName is empty, but in latest version in every case uses Item.BaseName.
Sorry for my perfect English and bad code.

**Screenshot of what I'm talking about**
[https://ibb.co/emrcCG](https://ibb.co/emrcCG)

**Comment by Eruyome** [comment]
was added, forgot to close this
