### ISSUE TITLE
Reading user..

### ISSUE THREAD

**Issue by fluxhell** [PoE-TradeMacro/POE-TradeMacro#647]
It is just stuck at "Reading user-agent and cookies from poe.trade, this can take a few seconds..." I wait for 10 mins and still there. I don't know what to do.
AHK version: AutoHotkey_1.1.27.03
Windows version: Windows 10 Version 1607

**Comment by Eruyome** [comment]
That may be annoying to solve unless you'll edit the macros code yourself. Nothing fancy.

`%TM-Folder\resources\ahk\TradeMacroInit.ahk%` beginning at line 990:

```
TradeFunc_ReadCookieData() {
   .... some code here
}
```

The second line of taht function shows the mentioned splashscreen and the script should be stuck somewhere inside this function. Now, simply copy this line to different lines inside this function:

```
MsgBox % "Step 1" 
```
to find the last line before the script stops.

**Comment by GabeValentine** [comment]
I have this issue. I have tried creating a general exception for the entire /POE-TradeMacro-2.12.3/* folder in my AV as well as specific exceptions for getCookieData.exe and curl.exe in my AV and a specific exception for curl.exe in my firewall.

I have added the message boxes as you suggest. This is where the script is getting stuck (function begins at line 1131 in v2.12.3).

`					Try {
						wb := ComObjCreate("InternetExplorer.Application")
						wb.Visible := False
						wb.Navigate(url)
						TradeFunc_IELoad(wb)
						ua := wb.document.getElementById("rawUa").innerHTML
						;ua := RegExReplace(ua, "i)[^:]*:\s?+", "")
						ua := Trim(RegExReplace(ua, "i)rawUa:", ""))
						wb.quit
					} Catch e {

					}`

AHK then loops forever:

`1130: MsgBox,"Step 4" (0.63)
1131: Try
1132: wb := ComObjCreate("InternetExplorer.Application") (0.19)
1133: wb.Visible := False  
1134: wb.Navigate(url)  
1135: TradeFunc_IELoad(wb)  
1318: Try
1319: if !wb  
1322: Loop
1323: Sleep,500 (0.50)
1324: Until,(wb.busy)
1323: Sleep,500 (0.50)
1324: Until,(wb.busy)
1323: Sleep,500 (0.50)
1324: Until,(wb.busy)
1323: Sleep,500 (0.05)
20474: Try
20475: WinKill,"ahk_pid " cdePID
20476: }
20479: SetTimer,Kill_CookieDataExe,Off
20480: Return (0.45)
1324: Until,(wb.busy)
1323: Sleep,500 (0.50)
1324: Until,(wb.busy)
1323: Sleep,500 (0.50)
1324: Until,(wb.busy)
1323: Sleep,500 (0.50)
1324: Until,(wb.busy)
1323: Sleep,500 (0.50)
1324: Until,(wb.busy)
1323: Sleep,500 (0.50)
1324: Until,(wb.busy)
1323: Sleep,500 (0.50)
1324: Until,(wb.busy)
1323: Sleep,500 (0.45)`

**Comment by Eruyome** [comment]
Try manually updating to the new version

**Comment by GabeValentine** [comment]
I've tried deleting all files of the script and AHK and reinstalling the latest release. Still stuck in the same spot.

**Comment by Eruyome** [comment]
Try opening a windows cmd/terminal and paste -> execute this
```
"D:\Trade\lib\curl.exe" "http://poe.trade" -ILks -w '%{http_code}' -A "Mozilla/5.0 (Windows NT 6.3; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/59.0.3071.115 Safari/537.36" --max-time 20
```

Where you'll have to edit the first part.
```
"D:\Trade\lib\curl.exe" 
```
should point to the `curl.exe` file in your TradeMacros `lib` subfolder.

Then post the result

**Comment by GabeValentine** [comment]
```
C:\WINDOWS\system32>"D:\PoE Utilities\POE-TradeMacro-2.12.3\lib\curl.exe" "http://poe.trade" -ILks -w '%{http_code}' -A "Mozilla/5.0 (Windows NT 6.3; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/59.0.3071.115 Safari/537.36" --max-time 20
HTTP/1.1 200 OK
Server: nginx
Date: Sat, 12 Jan 2019 02:38:59 GMT
Content-Type: text/html; charset=utf-8
Connection: keep-alive
X-Frame-Options: DENY
Content-Encoding: gzip

'200'
```

**Comment by Eruyome** [comment]
Does the script work sometimes for you?

Currently poe.trade is overloaded which can cause the request to timeout.
Which causes TM to believe there may be some issue that can be solved by using cookies.
Which, for whatever reason, doesn't work for you, causing an endless loop although this process should be killed after a while.

**Comment by GabeValentine** [comment]
It has always worked up until today. I've tried launching it about a dozen times over the past 4 hours, hasn't worked any try. My friend just got on and says his is doing the same thing (gets stuck at "reading user-agent and cookies").

**Comment by cameron-r** [comment]
Having the same issue (tried a whole bunch of times as well). Once while I was waiting for it to finish the "reading user-agent and cookies.." step, my internet explorer opened on https://www.whatsmyua.info/ .

Not sure if it's related, but I installed a windows update since the last time TradeMacro was able to open without getting stuck

**Comment by Eruyome** [comment]
Opening that site with IE is intended. It shows your browsers user agent which the macro wants to read.

**Comment by Eruyome** [comment]
Does this version work for you?
https://github.com/PoE-TradeMacro/POE-TradeMacro/archive/dev.zip

**Comment by cameron-r** [comment]
Yes, that version works. Thank you!

**Comment by GabeValentine** [comment]
Yes, that works! Thank you.

**Comment by Eruyome** [comment]
Do you get a messagebox saying something about a timed out request to poe.trade?

**Comment by cameron-r** [comment]
I exited and restarted the script a few times, didn't see anything with that message

**Comment by Eruyome** [comment]
So I guess it's basically fixed because your poe.trade request doesn't time out anymore, not because I did something.

**Comment by cameron-r** [comment]
I think there's _something_ that changed between what I was running and your `dev` version, because even now if try running the original one, it still hangs every time I try.

My VersionTrade.txt is:
```TradeReleaseVersion := "v2.12.2"
TradeAHKVersionRequired := "1.1.26.00"
```

So maybe the issue was fixed in another change you made that I hadn't downloaded yet

**Comment by GabeValentine** [comment]
> even now if try running the original one, it still hangs every time I try.

Can confirm. Just tried to run 2.12.3 and it still is getting stuck in its infinite loop: https://i.imgur.com/CLOVQwF.png

Weird.
