### ISSUE TITLE
Not searching correctly

### ISSUE THREAD

**Issue by Belwas** [PoE-TradeMacro/POE-TradeMacro#648]
Running latest Trade Macro and AHK, on Windows 7 64 bit.

When doing ctrl alt D on rare items, it doesn't do a correct search. When i open the search up in poe.trade it says that the search was too generic, so all items show up as worth 1 alt?

**Comment by Eruyome** [comment]
Can you show mem an example of this search or of those searches?

**Comment by decayedCell** [comment]
You are pressing Ctrl+Q instead of Ctrl+Alt+D. 

Ctrl+Q is completely useless and it shows random items, it takes max 1 property from the item into the search. I'm not sure if that's how it is supposed to work

**Comment by Eruyome** [comment]
Ctrl +D (non-rare items) and Ctrl + Q simply search by name and in some cases using stuff like iLvl, the item base (good crafting bases), corrupted status etc, that's intended. 
For rare items the predicted search is used, works only with ctrl + D.
