### ISSUE TITLE
Times out on rare items

### ISSUE THREAD

**Issue by Brusevolddalen** [PoE-TradeMacro/POE-TradeMacro#649]
I keep getting "request to poe prices timed out" or no error message at all when using ctrl+d on rares. It works great on currency and uniques.

poeprices_log.txt contains:
```
Request and response:
{
    "added": {
        "browserUrl": "https://www.poeprices.info/api?l=Abyss&i=UmFyaXR5OiBSYXJlDQpGYXRlIFJvZA0KU3Bpa2UtUG9pbnQgQXJyb3cgUXVpdmVyDQotLS0tLS0tLQ0KUmVxdWlyZW1lbnRzOg0KTGV2ZWw6IDQ1DQotLS0tLS0tLQ0KSXRlbSBMZXZlbDogNzANCi0tLS0tLS0tDQozMCUgaW5jcmVhc2VkIEdsb2JhbCBDcml0aWNhbCBTdHJpa2UgQ2hhbmNlDQotLS0tLS0tLQ0KKzE1NSB0byBBY2N1cmFjeSBSYXRpbmcNCis4MyB0byBtYXhpbXVtIExpZmUNCisyOCUgdG8gQ29sZCBSZXNpc3RhbmNlDQozMSUgaW5jcmVhc2VkIFByb2plY3RpbGUgU3BlZWQNCg==&w=1",
        "encodedData": "UmFyaXR5OiBSYXJlDQpGYXRlIFJvZA0KU3Bpa2UtUG9pbnQgQXJyb3cgUXVpdmVyDQotLS0tLS0tLQ0KUmVxdWlyZW1lbnRzOg0KTGV2ZWw6IDQ1DQotLS0tLS0tLQ0KSXRlbSBMZXZlbDogNzANCi0tLS0tLS0tDQozMCUgaW5jcmVhc2VkIEdsb2JhbCBDcml0aWNhbCBTdHJpa2UgQ2hhbmNlDQotLS0tLS0tLQ0KKzE1NSB0byBBY2N1cmFjeSBSYXRpbmcNCis4MyB0byBtYXhpbXVtIExpZmUNCisyOCUgdG8gQ29sZCBSZXNpc3RhbmNlDQozMSUgaW5jcmVhc2VkIFByb2plY3RpbGUgU3BlZWQNCg==",
        "league": "Abyss",
        "requestUrl": "https://www.poeprices.info/api?l=Abyss&i=UmFyaXR5OiBSYXJlDQpGYXRlIFJvZA0KU3Bpa2UtUG9pbnQgQXJyb3cgUXVpdmVyDQotLS0tLS0tLQ0KUmVxdWlyZW1lbnRzOg0KTGV2ZWw6IDQ1DQotLS0tLS0tLQ0KSXRlbSBMZXZlbDogNzANCi0tLS0tLS0tDQozMCUgaW5jcmVhc2VkIEdsb2JhbCBDcml0aWNhbCBTdHJpa2UgQ2hhbmNlDQotLS0tLS0tLQ0KKzE1NSB0byBBY2N1cmFjeSBSYXRpbmcNCis4MyB0byBtYXhpbXVtIExpZmUNCisyOCUgdG8gQ29sZCBSZXNpc3RhbmNlDQozMSUgaW5jcmVhc2VkIFByb2plY3RpbGUgU3BlZWQNCg=="
    },
    "failed": "ERROR: Parsing response failed, empty response! "
}
```
AHK version: 1.1.27.02
Windows version: 7 Ultimate 64Bit

**Comment by Kurumah** [comment]
I'm currently having the same issue.

**Comment by MrSapient** [comment]
Having the same problem on and off over the last few days.

**Comment by Elixiia** [comment]
Same problem for me too and for several days.

**Comment by Eruyome** [comment]
May be an issue on poeprices.infos side, I'll check with them.

**Comment by xeroh1** [comment]
still happening all items but rares works fine

**Comment by aRTy42** [comment]
You can disable the predictive price search function (using poeprices.info) in the settings menu for the time being. You should remember though that you disabled it and consider checking back on it after a while, because future script releases will likely not overwrite your setting again (meaning it would stay disabled).

**Comment by Cassiana18** [comment]
I keep getting the same issue. When I try price checking any rares I get  "request to poe prices timed out". It works fine for uniques though.

**Comment by xeroh1** [comment]
seems to be working again :)

**Comment by Eruyome** [comment]
When that happens jsut check whether the poeprices.info site works, or at least the item pricing on their site, it may just be that their server has an issue/is down.

**Comment by thejase** [comment]
@Eruyome pricing on the site always seems to work (with a longer-than-usual delay).  Using POE Trade Macro always times out.

**Comment by Eruyome** [comment]
There's this issue https://github.com/PoE-TradeMacro/POE-TradeMacro/issues/637.
Is the `encodedData` also missing for you?

**Comment by thejase** [comment]
I have the `encodedData`.  Funny though, after opening that file, prediction is working very quickly now.

**Comment by Eruyome** [comment]
That confuses me.

Anyway, I have added some debug output to this version here, try it.

You'll get a windows console window showing whether the certutil command was successful and an AHK console window showing the certutil commands (fullpath and relative path) and the encodedData length at some places in the code. You'll have to enable `Debug output`in the settings though.

https://github.com/PoE-TradeMacro/POE-TradeMacro/archive/encodeDataDebug.zip

**Comment by russpoe** [comment]
Still having same issue referenced above request to poeprices.info timed out.  Ctrl - Alt - D also does not work.  Nothing about the trade macro has been useful for me past 3-4 weeks https://www.pathofexile.com/forum/view-thread/1216141/
