### ISSUE TITLE
Memory limit reached

### ISSUE THREAD

**Issue by Camayy** [PoE-TradeMacro/POE-TradeMacro#650]
AHK version: 1.1.26.01
Windows version: 7 

After using ctrl + d on a item, sometimes it gets stuck at 'Requesting search results...' and am unable to check the prices for any items. After about 30mins or so I receive a error claiming memory limit has been reached
![autohotkey_2018-01-09_22-23-47](https://user-images.githubusercontent.com/8885122/34746796-4e7baf2e-f58d-11e7-9ddd-8c28dd642ccf.png)

Once this message has appeared I can use ctrl + d again.

(This error only started occurring when I switched internet and changed to wireless so that might have something to do with it) 

Cheers.

**Comment by Eruyome** [comment]
Extremeley late answer, but I couldn't make sense of it. Please open it again if it's still an issue.
