### ISSUE TITLE
Tooltip reopen randomly

### ISSUE THREAD

**Issue by nartaki** [PoE-TradeMacro/POE-TradeMacro#651]
AHK version: 1.1.27.04
Windows version: 7 premium

After a while of the macro being open and the game running i started seeing my last ctrl+d tooltip randomly on the screen and quite often so the mouse was not hovernig an item nor were button being pressed! Using latest build downloaded today...

**Comment by Eruyome** [comment]
You probably have some application that changes the clipboard. The macro watches for clipboard changes, which will be changed someday, but for now any change to the clipbaord triggers it, even if the contents stay the same.

**Comment by nartaki** [comment]
I have Ditto yes,which totally watches clipboard and saves a record of it...

**Comment by Survap** [comment]
But why does this issue started on new updates? It was really fine at 2.7.2 and now it comes to a point where I need to disable it to trade properly or I'll get the tooltip spamming all day.

**Comment by Eruyome** [comment]
This changed behaviour shouldn't be related to TradeMacro, nothing changed for months that could be related to this.
