### ISSUE TITLE
Poe trade macro wont start up

### ISSUE THREAD

**Issue by nicnic489** [PoE-TradeMacro/POE-TradeMacro#652]
AHK version: v1.1.27.04
Windows version: 10

Initially the macro was working as intended however one day without changing anything, every hotkey would take me to my hideout by putting "/hideout" in chat as if all hotkeys were bound to that paste option. Even tried copying something else and it would revert back to "/hideout"
Tried messing around with files and then... I try to run the macro and I always get a message: https://gyazo.com/86671690a31852d945c6b127cbcb52d9

I've tried reinstalling several times to no avail. Maybe im not reinstalling properly idk
Help will be appreciated as this was an excellent tool while it was working.
Thanks

**Comment by Eruyome** [comment]
Are you really using the latest TradeMacro version (2.7.5 as of right now)?

What language (more specifically which keyboardlayout) are you using?
