### ISSUE TITLE
Requesting search  results lasts a long time

### ISSUE THREAD

**Issue by tenslidetails** [PoE-TradeMacro/POE-TradeMacro#653]
AHK version: 2.7.5
Windows version: 10 64bit
Requesting search  results lasts a long time https://imgur.com/a/kWGVT , in seconds 30 it shows prices, other functions work well

**Comment by Eruyome** [comment]
Is that always the case or just at times?

**Comment by tenslidetails** [comment]
@Eruyome always

**Comment by tenslidetails** [comment]
The program does not respond and then shows

**Comment by Eruyome** [comment]
There should be a file `%TM-Folder%\temp\poeprices_log.txt`, please show me its contents.

**Comment by tenslidetails** [comment]
here only 3 files : currencyData.json, currentLeagues.json, StartupLog.txt

**Comment by Eruyome** [comment]
A scipt restart removes all files in that folder, have you made a request/price check again?

**Comment by tenslidetails** [comment]
i did every shortcut but he did not appear

**Comment by tenslidetails** [comment]
@Eruyome  I think the problem is the same as in issue #291 But all the advice did not help me
