### ISSUE TITLE
Search Opal Ring with ilvl by default

### ISSUE THREAD

**Issue by C485** [PoE-TradeMacro/POE-TradeMacro#654]
Ctrl+D shows wrong price for Opal Ring, ilvl: 84 shows price around 15 chaos with should be 35chaos +-
Imho script should check price directly on poe.trade not in poeprice

Version: 2.7.3

**Comment by aRTy42** [comment]
If it's just about not using poeprice, then you can disable predictive pricing in the settings menu.

**Comment by C485** [comment]
Ok, but it will disable it globally, the problem is only with this specific item, also a lot of new players have no idea that price of this specific item depends on ilvl.
It is possible to add a option to disable poeprice for specific item names?
Or just hardcode it but i think it's a bad idea.

**Comment by aRTy42** [comment]
Well, the whole point about poeprice's machine learning is that you don't put in rules like iLvl and special bases yourself. You can help training the algorithm by submitting an opinion about the price result it gives (too low/too high).

Rules about special bases such as opal rings and ilvl thresholds such as 84 are used for poe.trade queries.

**Comment by Eruyome** [comment]
Use the advanced search. Or scour the item, predicted search won't be used then :p
