### ISSUE TITLE
Buyout only not work

### ISSUE THREAD

**Issue by fragfaq** [PoE-TradeMacro/POE-TradeMacro#656]
For a long time the "Buyout only" function does not work. Poe.trade produces the results "Has buyout: either" instead of "Has buyout: Yes". In the search settings there is a tick on Buyout only, I tried to disable this setting, save and re-enable it, but this does not have an effect. I did not find solve the problem in the Wiki / FAQ, and in autohotkey I'm not very strong, your code is too complex for me. This is not too serious a problem, I thought it was a bug that would disappear with time, but new versions are coming out, and Buyout still does not work. Sry for my bad english, i hope i can explain the problem.

* AHK version: 1.1.27.03 - January 6, 2018
* Windows version: Win7 x64, SP1

**Comment by Eruyome** [comment]
Should be some stupid little bug that nobody noticed/reported. I'll look into it in the next days.

**Comment by fragfaq** [comment]
It would be wonderful, a special thanks for such a quick reaction. Now I'm faced with another problem with GDI. Later I will be able to give the beat a detailed feedback if I do not find a solution in the FAQ and past issues. Thx again for u work ^_^

**Comment by Dibro89** [comment]
@Eruyome I have related issue with median price (sometimes it can be lower than the first one):

![image](https://user-images.githubusercontent.com/16293890/35400621-f05a018c-01ff-11e8-90e3-4c6f634d2740.png)

I will try to fix it by myself on the weekends.

**Comment by Eruyome** [comment]
The buyout only works again (dev version), will be released in time for Bestiary League.
