### ISSUE TITLE
Exact currency search option?

### ISSUE THREAD

**Issue by Zeronthe** [PoE-TradeMacro/POE-TradeMacro#657]
More of a suggestion than an issue,  would it be possible to be able have an option so the Ctrl+D/Q search utilize the new exact currency feature that was added recently?

i.e i only want to see results in chaos, so ctrl D only shows chaos listings. I'm not a huge fan of the odd averages "show all trades as chaos equivalent" produces, so seeing just the actual chaos trades would be great since everyone and their mother apparently is trying to cheat the listings on ASC.

At the moment i have to Ctrl+Q something then select chaos/exact to see all the actual chaos listings.

**Comment by Eruyome** [comment]
I'll think about it, not a bad idea, depending on the implementation, for some searches it may not be the best way to only search for a specific currency and always having to open the settings menu to change that could be inconvenient.
Won't be implemented intime for Bestiary league though.

**Comment by Eruyome** [comment]
Added in my dev version as an option, I'll close this, will be released soon.
