### ISSUE TITLE
Spacebar being recognized as Shift when running the POE trademacro

### ISSUE THREAD

**Issue by Poonbilly** [PoE-TradeMacro/POE-TradeMacro#659]
AHK version:2.7.5
Windows version: 10

**Comment by aRTy42** [comment]
In what kind of context? What exactly happens that makes you think it works like shift?

**Comment by Poonbilly** [comment]
I used space as a hotkey in POE to stand in place and attack. When using the POE trade macro, when I use space it acts like the shift command. Additionally, if I try to use space as another input or hotkey it says shift instead of spaceber.


Sent from my Verizon, Samsung Galaxy smartphone
-------- Original message --------From: aRTy42 <notifications@github.com> Date: 1/26/18  7:46 AM  (GMT-06:00) To: PoE-TradeMacro/POE-TradeMacro <POE-TradeMacro@noreply.github.com> Cc: Poonbilly <hein.benjamin@gmail.com>, Author <author@noreply.github.com> Subject: Re: [PoE-TradeMacro/POE-TradeMacro] Spacebar being recognized as Shift when running the POE trademacro (#659) 
In what kind of context? What exactly happens that makes you think it works like shift?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/PoE-TradeMacro/POE-TradeMacro","title":"PoE-TradeMacro/POE-TradeMacro","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/PoE-TradeMacro/POE-TradeMacro"}},"updates":{"snippets":[{"icon":"PERSON","message":"@aRTy42 in #659: In what kind of context? What exactly happens that makes you think it works like shift?"}],"action":{"name":"View Issue","url":"https://github.com/PoE-TradeMacro/POE-TradeMacro/issues/659#issuecomment-360788516"}}}

**Comment by Poonbilly** [comment]
Hey aRTy42,

Think we can disregard.  Looks like a simple hard restart set me straight.
Thanks for taking a look!
