### ISSUE TITLE
Can't launch the script

### ISSUE THREAD

**Issue by Nyvlem** [PoE-TradeMacro/POE-TradeMacro#660]
As soon as i try to launch the script i get this message :

v2.7.5 
Cookie file not found. 
Retrieving cookies failed. 
Windows Version: 10.0.16299 (10.0.16299), 64bit. 
Compiling 'getCookieData' script failed. 
Net Framework used for compiling: v4 
Internet Explorer: v11.192.16299.0

AHK version: latest v2.7.5
Windows version: 10

Do you have any idea how to solve this problem ?

**Comment by thanh125643** [comment]
Run file as admin

**Comment by Nyvlem** [comment]
Still doesn't work same error
