### ISSUE TITLE
Can not run Run _TradeMacro.ahk. - comand line parameters

### ISSUE THREAD

**Issue by JONOGA3** [PoE-TradeMacro/POE-TradeMacro#662]
When trying to open Run _TradeMacro.ahk. I am getting -

Command Line parameters:
Ahk2Exe.exe /in infile.ahk [/out.outfile.exe] [/icon iconfile.ico] [/binautohotkeysc.bin] [/mpress 1 (true) or 0 (false)] [/cp codepage]

If someone could tell me what I am doing wrong that would be greatly appreciated.
Thanks
AHK version: AutoHotkey_1.1.26.01
Windows version: 10 home

**Comment by aRTy42** [comment]
"Open" means left mouse button double click, right?

The Ahk2exe part sounds like you are not running the script, but attempting to compile it into an exe file. Please try rightclick -> "run script" and see if that works.

**Comment by JONOGA3** [comment]
Thanks for your reply.

Yes I was as there is no run script option.

**Comment by JONOGA3** [comment]
I figured it out. I opened with AutoHotkeyU64 instead of ahk2exe and it works
