### ISSUE TITLE
Trade Macro now minimizes POE

### ISSUE THREAD

**Issue by GunthorNC** [PoE-TradeMacro/POE-TradeMacro#664]
Everything that I can find online about Trade Macro says that it cannot and never will be able to be used in full screen mode, Take it those comment's are old. I am 99% certain that I've used it full screen for the Ctrl-D feature without issues for over a long while now. I am 99% certain that I have not been running POE as a border less window. I did a windows update yesterday, (window's 10) Updated my graphic's driver's (GTX 1070) and updated my headphone driver's (Logitech g933) I did those all in 1 batch, So I've added a fair number of variables to the mix. However, immediately afterward's I can no longer use the Ctrl-D feature of Trade Macro without it minimizing POE. Is there an option that I could check that would restore this functionality? Did this functionality ever exist in the first place? 99% sure that it did, but 1% is 1%. Was there a new update for trade macro that it automatically updated to? and if so is it possible to roll back?

Thank's in advance for your feedback.

**Comment by aRTy42** [comment]
To my knowledge there is absolutely no way to use it in actual full screen mode, so I'm pretty sure you are mistaken. Is there a reason for you to not use borderless for PoE?

**Comment by Eruyome** [comment]
I'm still convinced that you have to use windowed mode. Anyway, I'll close this for now, feel free to open it again if there's anything further to discuss.
