### ISSUE TITLE
Show count for duplicate item listings

### ISSUE THREAD

**Issue by aRTy42** [PoE-TradeMacro/POE-TradeMacro#665]
From [ItemInfo issues](https://github.com/aRTy42/POE-ItemInfo/issues/95):
> I think it would be nice if in the search feature popup it would show (if any) who has duplicate posts and how many of them they have. This would be helpful for a quick way to tell if the prices are being fixed. That way we could easily figure out if we should check poe.trade for more information.

As a reminder, because the request was meant for this project.

**Comment by Eruyome** [comment]
I'll implement this sometime later, meaning not in time for the Bestiary League.
