### ISSUE TITLE
Searching for shaped maps always find no result

### ISSUE THREAD

**Issue by chinhodado** [PoE-TradeMacro/POE-TradeMacro#667]
Searching for shaped maps always find no result. Normal maps work fine.

**Comment by Eruyome** [comment]
I don't have this issue. Is this still the case for you? Is it the case for every shaped map or just specific ones?

**Comment by Eruyome** [comment]
Was the case for shaped vault since it was missing as base option on poe.trade, this is fixed for all shaped maps now.
