### ISSUE TITLE
Trade macro won't launch (script error)

### ISSUE THREAD

**Issue by KasparasK** [PoE-TradeMacro/POE-TradeMacro#670]
AHK version: 1. 1. 26. 01
Windows version: Win10 64bit

Doesnt matter which version of macro I use, get the same error

![error](https://user-images.githubusercontent.com/22654917/36933237-3eb32124-1ede-11e8-86cf-e27eb7c1082d.PNG)

**Comment by Eruyome** [comment]
Does the file `%userprofile%\Documents\PoE-TradeMacro\dev_master\CustomMacros\PoE-TradeMacro\dev_master\CustomMacros\customMacros_example.txt`? If yes have you edited it/is it empty?

**Comment by KasparasK** [comment]
the path to the document in my pc is different:
%userprofile%\Documents\PoE-TradeMacro\CustomMacros\customMacros_example.txt
And it is empty, I did not edit it.

**Comment by Eruyome** [comment]
That shouldn't be the case (empty), anyway, the file also exists in `POE-TradeMacro\resources\default_UserFiles\CustomMacros`, copy it over and try again.

**Comment by KasparasK** [comment]
ITS ALIVE! Thank you!
