### ISSUE TITLE
cant check prices of Dive cards in div tab

### ISSUE THREAD

**Issue by devio3000** [PoE-TradeMacro/POE-TradeMacro#673]
didnt know if this was a thing u noticed but i could do it last league but cant after update

**Comment by Eruyome** [comment]
Never tried that before. Anyway, parsing and searching items only works ic ctrl + c when hovering oder them copies the item data to the clipboard. This is a default feature of PoE but it does not seem to work in the div tab.

**Comment by devio3000** [comment]
yes last league and before that u could check prices by hovering over div card and press ctrl + d like u would to check prices in div card tab u can no longer do that

**Comment by zxczxc322** [comment]
Same problem
In older version its work fine.

**Comment by Eruyome** [comment]
Oh? it still works in older versions? Have to try that later.

**Comment by razerguy90** [comment]
Hi there!
After 2.7.6 update now we cant check prices in Divination card stash tab! Can u fixed it asap please?!

**Comment by Eruyome** [comment]
No, I can't, GGG changed that. I can't retrieve the item data from the div tab anymore.
