### ISSUE TITLE
Totem ele resist on jewels is mistaken for player ele resist

### ISSUE THREAD

**Issue by thescyphozoa** [PoE-TradeMacro/POE-TradeMacro#675]
https://i.imgur.com/NOVBiwL.png

Checking the boxes and searching on poe.trade leads to a search with "elemental resist" (for players) instead of "totem elemental resist". It should use this poe.trade mod instead: https://i.imgur.com/49fjN7P.png

**Comment by Eruyome** [comment]
Thx for the report, will try to fix this in the next days.

**Comment by SirKori** [comment]
same for minion ele resist also.

**Comment by Eruyome** [comment]
fixed
