### ISSUE TITLE
Error on start up

### ISSUE THREAD

**Issue by DeOrthodox** [PoE-TradeMacro/POE-TradeMacro#676]
AHK version: 64 bit
Windows version: 10

 ok idk why but with the new version i get some weird error... 3.7.5 is fine but i get this https://gyazo.com/8df569023c4e68705644074928dcbede from the 3.7.6 version

**Comment by Eruyome** [comment]
Have you completely removed all files from your TradeMacro folder and made a fresh install?

**Comment by DeOrthodox** [comment]
ive deleted the folder multiple times

**Comment by Eruyome** [comment]
Can you try not to extract the macro directly in your `d:` drive root?

**Comment by DeOrthodox** [comment]
how do you mean?

**Comment by aRTy42** [comment]
The script thinks you drive "D:\" is the main script "folder", at least thats what is visible in the error message. Either you extracted the script directly onto D:\ (which you should not do) or there is another issue with your script folder.

Where are your files located?

Please also check that you do not have remnants of another install directly on D:\, meaning there should be no files like "Run_TradeMacro.ahk" on D:\ and the five folders \data, \data_trade, \lib, \resources and \temp should not be there either (check their content if its not clear if they are from the trademacro).

**Comment by DeOrthodox** [comment]
thank you! fixed it now! seems like i had a rogue Lib map in there <.< im blind lol to many folders haha thaks tho!
