### ISSUE TITLE
Price prediction dont work anymore.

### ISSUE THREAD

**Issue by CroDanZ** [PoE-TradeMacro/POE-TradeMacro#678]
When I try to price predict items (CTRL + D) I get the error massage:

"ERROR: Request to poeprices.info timed out or returned a invalid response!"

It always worked well so far but with 2.7.6 it dont work anymore.

Windows 10, 64 Bit.

Removed all folders and fresh installed it multiple times (even with PC restart)...didnt solve the problem.

**Comment by Eruyome** [comment]
Works again, their server broke down for a few hours.
