### ISSUE TITLE
Error on reinstallation

### ISSUE THREAD

**Issue by dwperry** [PoE-TradeMacro/POE-TradeMacro#680]
AHK version: 1.1.26.01
Windows version: Windows 10

I get this message whenever I try to open the script. This persists even when I delete the entire folder, including data, data_trade, lib, resources, temp, Run_TradeMacro.ahk and replace them with freshly downloaded files.

https://imgur.com/6N7skbh

**Comment by aRTy42** [comment]
Your custom macro file in the user folder is messed up. By default it should look like this:
```
/*
	Custom macro main file. Don't delete it. Using and including this file is important. If you don't want to edit the 
	technical AdditionalMacro.txt file, you need this file and the already defined hotkey label. 
	Epsecially if you want to execute any personal code outside of hotkey labels.
	
	**TLDR**:
		You can add your own code below, use the existing Label.
		View a formatted description/how to here -> https://github.com/PoE-TradeMacro/POE-TradeMacro/wiki/Custom-Macros.
*/

CM_ExecuteCustomMacrosCode_Label:	
	
Return
```
In your case the opening of the comment section ( /* ) seems to be missing.

**Comment by dwperry** [comment]
This is the file I see in the resources>default_Userfiles>CustomMacros folder every time I download the latest release, and the error persists, even if I delete the file entirely.

https://imgur.com/AXMWtqs

**Comment by aRTy42** [comment]
The file in \resources\... is the default file the macro brings along to create a user file from it. You are not supposed to edit that one or delete it.
Your user files are in <Documents>\PoE-TradeMacro. Check the "CustomMacros" subfolder and look at the file. Either fix the code with what I posted or delete the file to have it recreated from the default file (that you do not delete please).

**Comment by dwperry** [comment]
Ahhhhh I didnt realize it created another folder for user settings in a completely different place than the install location. Found the user folder in Documents, deleted it, then reinstalled everything and now it works. Thanks for the help!

**Comment by aRTy42** [comment]
The user folder is there so that personal configuration does not get overwritten with every update, since the main folder is replaced.
