### ISSUE TITLE
Change @ Hotkey

### ISSUE THREAD

**Issue by Slatyo** [PoE-TradeMacro/POE-TradeMacro#681]
Hey,

is it possible to change the poeapp-search function (on @) to an other keybind?
The @ symbol is used to contact someone in poe (whisper function).

**Comment by aRTy42** [comment]
You can change it in the settings menu. Maybe the default will be changed, but until then you can adapt it to your personal liking.

**Comment by Slatyo** [comment]
Yea I know that it can be changed but it shouldn't take the @ as default, i guess.

**Comment by Eruyome** [comment]
No it shouldn't, the issue being that I missed that alt + q is being used on some layouts to type the @, i will change the default in the next release.

**Comment by Eruyome** [comment]
It was changed btw.
