### ISSUE TITLE
TradeMacro dont start, dont know how to fix that..

### ISSUE THREAD

**Issue by Verothx** [PoE-TradeMacro/POE-TradeMacro#682]
hey i have the newest ahk and trade macro version. everytime when i want to start the script the following error message occurs:

https://gyazo.com/e7f8d129bb5dab1e598918670b83f032

how can i fix that?

**Comment by aRTy42** [comment]
You should get a warning that the desktop and its subfolders can cause issues when you start the script. Try putting the folder at some location typical for programs, such as "C:\Program Files\PoE-TradeMacro\" or something similar that fits your needs. If you then want to start the script from the desktop you can create a link to the "Run_TradeMacro.ahk" file.

**Comment by Verothx** [comment]
restartet the pc, everything works now. thank you! :)
