### ISSUE TITLE
Bestiary League

### ISSUE THREAD

**Issue by Nrevi** [PoE-TradeMacro/POE-TradeMacro#683]
Hello,

I'm playing on bestiary league and I don't seem to see a league supported by it? So all trade prices are irrelevant to me. That's the only reason i downloaded trade macro lol

https://i.imgur.com/7noukTQ.png

**Comment by aRTy42** [comment]
Since the three month league name changes every time, the name isn't hardcoded there. "tmpstandard" is the three month temporary SC league (Bestiary) and accordingly "tmphardcore" is Bestiary HC.
