### ISSUE TITLE
Critical permission error

### ISSUE THREAD

**Issue by Fone-Bone** [PoE-TradeMacro/POE-TradeMacro#685]
Hi
I get this message when i try to use youre great program:

![image](https://user-images.githubusercontent.com/30850087/37247621-24e17fe4-24be-11e8-89d1-005487dd035e.png)

al permission is given in Bitdefender. I have tryid to start it as administrator but all give the same messages.

hope you can help. I have used your program before with no problem.

_TEMPLATE_ (Remove the explanations here from your post) 

Make sure:
* That you have checked the Wiki/FAQ before creating any issue.
* That poe.trade/GGG's website don't have any issues if loading the script takes too long or failes.

Information to include:
* AHK (including 32/64bit) version if you have any kind of script errors.
* Windows version could be relevant.

Fill out everything that may be relevant and remove everything except these informations below:  

AHK version:
Windows version:

**Comment by Eruyome** [comment]
Is this still an issue for you? If yes, when did it occur, after upgrading to a specific version? Does an older version still work?

**Comment by Cano-G** [comment]
Hi, 
SOLUTION for ABOVE and BITDEFENDER users (and similar solution for other system security software)

I have the exact same error. I also have Bitdefender. I tried to install POE-TradeMacro-2.7.7 on windows 10.0.16299
The install creates directory successfully: C:\Users\<user>\Documents\PoE-TradeMacro\CustomMacros 

I opened bitdefender and I see now it is blocked by bitdefender:
![image](https://user-images.githubusercontent.com/37453842/37566526-b2bcd190-2aba-11e8-9293-0a28c8c2dda9.png)

I clicked on "Learn More"
![image](https://user-images.githubusercontent.com/37453842/37566539-d372d18c-2aba-11e8-8ff0-fde9be434438.png)

Then I clicked "Allow" for program AutoHotkey
