### ISSUE TITLE
Explicit & implicit stat merged when using CTRL+ALT+D (Advanced item search)

### ISSUE THREAD

**Issue by vincent-clipet** [PoE-TradeMacro/POE-TradeMacro#686]
Hello !

Small issue I encountered when using _advanced item search_ on a bow : 
* CTRL+C of the bow : 
https://gist.github.com/vincent-clipet/b7800456154876fc5de85fc6c2c5660b

It has 2 **increased Critical Strike Chance** stats : 1 implicit, 1 explicit.

When opening it in the advanced search, it looks like this : 
![1](https://user-images.githubusercontent.com/6408027/37261274-886f0ce2-259b-11e8-8867-7e0a86c61a98.png)

Both **increased Critical Strike Chance** from implicit & explicit are merged into one stat.
When opening this search on poe.trade, the merging of these 2 stats is searched as implicit _(which leads to no results, because the value is much higher than max implicit crit chance possible)_ : 
http://poe.trade/search/atugitamasiota

These 2 stats should remain independant in the _advanced search_.

______________________________

AHK version: 1.1.26.01
Windows version: 8.1

**Comment by Eruyome** [comment]
You're right, I'll look into a solution to this soon.
