### ISSUE TITLE
Text Box Misaligned

### ISSUE THREAD

**Issue by SoraNet** [PoE-TradeMacro/POE-TradeMacro#687]
Cntrl + D / C

https://cdn.discordapp.com/attachments/403858104187617280/422763572209385472/unknown.png

https://cdn.discordapp.com/attachments/403858104187617280/422763441053499392/unknown.png

Is there a fix? Is it my monitor? D:

**Comment by SoraNet** [comment]
It has been like this for 2 leagues haha, thought it was normal until a friend pointed it out. Restarting does not help.

I'm using windows 10 pro? Edition. 

1920x1080 27" screen
Borderless window
As for language, I'm using Dutch (system), with either UK/USA english keyboard layout depending on what I need.

I can supply more info if you need, just let me know! 

And thanks for such quick help!

**Comment by Eruyome** [comment]
Have you tested the GDI+ tooltip? You can enable it in the settings, ItemInfo tab.

**Comment by aRTy42** [comment]
Furthermore, since it is the source for errors way too often: Where do you have your script folder? Is it on the desktop?

**Comment by SoraNet** [comment]
The GDI tooltip, will try it out. I think I used it for a short time but didn't like.

It's on my D:/ahk/poetrade...- 

Does it have to be in C:/? I know some programs don't function well when placed in places other than program files or whatever :[

**Comment by aRTy42** [comment]
"D:\something" should be fine. It's just a common problem that people put the folder right on the desktop and then get permission issues from windows. They also tend to ignore the popup message they get about not putting it on the desktop, because they can continue with ok and "everything seemed to be working" − except for the problem they contact us about.

**Comment by SoraNet** [comment]
Hmm, it's suddenly fixed?

![image](https://user-images.githubusercontent.com/37301108/37377328-90458fe2-2729-11e8-833c-6a99b6aa1785.png)

From your end? Or.. double slit experiment haha, the bug knows it's being watched so it fixed itself o.o

Anyway, I'll update if it breaks again!

**Comment by aRTy42** [comment]
Not from our end. Here's to hoping that it stays fine.
