### ISSUE TITLE
Wrong prices

### ISSUE THREAD

**Issue by GoldFisz** [PoE-TradeMacro/POE-TradeMacro#689]
AHK version: latest I just reinstalled
Windows version: win 10 pro

So I did find out that the macro shows wrong prices sometimes.  For example, Enlighten Support costs around 10 to 15 c while I search it manually but when I  used ctrl+d it showed me that it costs between 2 and 3c. Even I used the ctrl+q to show me the poe trade and there are actually people that sell it for 2 or 3 c but when I search it manually the prices start from 10c. Is it my fault? I did not change the settings except settings the price to chaos

**Comment by GoldFisz** [comment]
Alright, I am retarded. It shows all the prices even in offline while in poe trade I looked only on online prices

**Comment by Eruyome** [comment]
![image](https://user-images.githubusercontent.com/16058242/37416123-488e1d84-27ad-11e8-9b72-9131877340b5.png)

Is "online only" enalbed in your settings? If it is and still shows offline results there is an issue, it works fine for me though.

**Comment by GoldFisz** [comment]
Yes it works correctly. My fault was that I checked offline prices and there was 10 people on front who sold for ridiculous low price but they were afk for few days while online people sold it for much more. So it is all on me macro works fine
