### ISSUE TITLE
[Fixed?] Search defaulting to Race League?

### ISSUE THREAD

**Issue by texaswalkeranger** [PoE-TradeMacro/POE-TradeMacro#69]
Haven't personally changed any settings, downloaded latest update and no data is being shown when I search for any item or currency as it has the modifier (Cutthroat (ERW003)) next to the name of the item I'm searching for. Is this an issue with pulling from the poe.trade database?

**Comment by Eruyome** [comment]
Did you post this after my hotfix release?

**Comment by texaswalkeranger** [comment]
Nope, hotfix should hopefully fix it, downloading now. Thanks!
