### ISSUE TITLE
Can't launch ahk

### ISSUE THREAD

**Issue by Sidusol** [PoE-TradeMacro/POE-TradeMacro#693]
When trying to open Run _TradeMacro.ahk. I am getting -

Command Line parameters:
Ahk2Exe.exe /in infile.ahk [/out.outfile.exe] [/icon iconfile.ico] [/binautohotkeysc.bin] [/mpress 1 (true) or 0 (false)] [/cp codepage]

Yestarday everything was working, now I can't launch it. There is no option to "run script" ahk is not launching too when I try to launch its exe file. Just a help window.

**Comment by aRTy42** [comment]
Did you reinstall autohotkey or something that might have reassigned file extensions? The Ahk2exe is not what you use to execute script, it lets you convert them into .exe files.

Right click the Run_TradeMacro.ahk and select properties. At "open with" you should be able to select "AutoHotkey Unicode 64-bit" or something similar, depending on what you installed.

**Comment by Sidusol** [comment]
oh okey! The 2nd solution works! Thanks!
