### ISSUE TITLE
Prefill ilvl values behavior

### ISSUE THREAD

**Issue by dona3000** [PoE-TradeMacro/POE-TradeMacro#698]
Hi,

Wouldn't it be nice to include an option to always prefill the ilvl value but not preselect the checkmark in advanced search? In addition to the current option that prefills AND preselects the ilvl for the search.

It would be pretty useful to me (and other people I'm sure) not having to always check and enter shaper/elder item etc. ilvls but not also having the ilvl always being selected for searches where it doesn't matter. In my opinion this should just be the default behavior no reason not to.

Hope these kind of requests are allowed.
In any case, thanks for this great tool :)

**Comment by Eruyome** [comment]
Was annoyed by that this league, too. Will add it.
