### ISSUE TITLE
shaper amulet quantity mod disinformation

### ISSUE THREAD

**Issue by asmonsz** [PoE-TradeMacro/POE-TradeMacro#699]
https://imgur.com/a/La8iY

my 85 lvl shaped amulet have 10% quantity. This is the real maximum for it. But script showing that it can be 9-12%. I guess it is the old legacy quantity parameter. But can it be fixed somehow?

**Comment by Eruyome** [comment]
The script doesn't know the min/max values since it doesn't has access to the advanced mod info on the item and it's a pain in the ass to get that information for every mod and item type otherwise. It simply calculates a value to fill something in (+/- 10%/20% of the current value).

**Comment by aRTy42** [comment]
That is already pending for the next release.

I'm currently not planning to support all shaper/elder mods in the current state because I'd rather wait for GGG to get the advanced mod breakdown also into the clipboard (so that tools can use it), but I noticed this specific issue aswell fixed it.

**Comment by aRTy42** [comment]
Fixed for a while now, forgot to close this.
