### ISSUE TITLE
[Fixed on dev branch] Search for unique maps isn't working anymore

### ISSUE THREAD

**Issue by AliBabo** [PoE-TradeMacro/POE-TradeMacro#70]
Instead it searches for the basetype of the map. For example if I check my Whakawairua map it only shows the prices for Strand maps.

**Comment by Eruyome** [comment]
Thx for the report, seems I also broke that recently while refactoring some code.. fixed on development  branch. New Release shouldn't take longer than a day, maybe I'll wait and see if I can finish the first advanced search version for normal/magic/rare items.
