### ISSUE TITLE
TradeMacro hotkeys stop working out of the blue.

### ISSUE THREAD

**Issue by zug0** [PoE-TradeMacro/POE-TradeMacro#700]
I'm currently having a issue that all the hotkeys beside Ctrl+C stop working. I open the script and I'm in game and everything works fine, suddenly ctrl+d and other hotkeys don't work, sometimes it takes 5 seconds, other it takes half hour, i don't know what triggers it, nothing popups on screen, I get no errors even on debug mode. Tried a clean install of the trademacro and AHK but it continues. I didn't have this issue on last version. Only way to fix is to reload do script or close and open the macro. Restarting game doesn't help.

AHK version: 1.1.28.01
Windows version: Windows 10 Pro

**Comment by aRTy42** [comment]
It might be a connection or routing issue to poe.trade and other sites. For me today it was slower than usual aswell, which meant the usual near instant popup took 5 seconds or so.

**Comment by zug0** [comment]
I can test the conection on debug mode and everything is fine. The issue seems to be that the hotkeys stops being recognized. I don't even get the requesting search results on the screen.

**Comment by Eruyome** [comment]
Sorry for the late answer, took some time off.
Is this still an issue?

**Comment by zug0** [comment]
Hi, sorry. It started happening again today but it only happens when I have MercuryTrade opened at the same time. Everything stops working besides control+C. Contrl+d and Ctrl+Alt+D stops completely. As soon as I close mercury trade everything goes back to normal. I can usually run a couple ctrl+d/ctrl+alt+D, but then it suddenly stops.

Also the additional macros stop working (hideout and kick from party) the ones that I use.

**Comment by Eruyome** [comment]
Wow, ok, that's weird. I really don't know what to look here for exactly... Have you tried using [PoE-TradesCompanion](https://github.com/lemasato/POE-Trades-Companion) instead? Have you any other Java applications that run in the background or that you can have opened for a while? I don't want to say that that just having such an app running causes those issues but I don't know what else to check.

**Comment by Eruyome** [comment]
I asked about other applications to see whether it has something to do with Java in general or mercury trade specifically. 

I repeat myself, I really don't have a clue on what to look for/test on TradeMacros side.
Btw, ItemIndos `ctrl + c` feature doesn't use a hotkey at the moment. The script watches for clipboard changes. Everything else on the other hand uses a real hotkey.

So it seems that for some reasons all hotkeys are blocked.

You could run a script like this:
```
#SingleInstance, Force

^!p::test()

test() {
	IfWinActive, Path of Exile ahk_class POEWindowClass 
	{
		msgbox yo, it works.
	}
	Return
}
Return
```
Pressing `ctrl + alt + p` when PoE is active shows a message box. If this most basic AHK script also stops working then it's not a TradeMacro issue for sure.

**Comment by Eruyome** [comment]
What if you use this script:
```
#SingleInstance, Force

Hotkey, ^!p, test, On

test:
	IfWinActive, Path of Exile ahk_class POEWindowClass 
	{
		msgbox yo, it works.
	}
Return
```
Different way to assign the hotkeys, not sure if it makes a difference,

**Comment by zug0** [comment]
Ok, After the update last night,  today it took A LONG time to happen. But it ended up happening... The above script also works. Right now I also don't what else to do...

**Comment by Eruyome** [comment]
I'll continue to think about it but I can't promise much and there are a lot of other things to fix an implement too.

**Comment by zug0** [comment]
No problem man. thanks for your time and for this.
