### ISSUE TITLE
Suggestion: prohecy tab support

### ISSUE THREAD

**Issue by Luckyn1604** [PoE-TradeMacro/POE-TradeMacro#703]
Hi,

I just have a suggestion regarding the search for prophecy. As a newby I'm still looking at wiki / poe.trade to have an idea of the value of a prophecy or how to solve it.
But the ctrl+d / ctrl+w are only working on the item, so you have to manually search or unseal to use the macro.
I think it could be great if we could use it directly on the prohecy tab :)

Regards,

**Comment by aRTy42** [comment]
We would like that aswell, but the game does not support it. The game client gives out the item info in text based form when you use ctrl+c on an item, that is what the macro uses. This does not work on the prophecy tab though, so we can't do anything there.
