### ISSUE TITLE
Suggestion : add more socket/link support to ctrl+d

### ISSUE THREAD

**Issue by romainbebert** [PoE-TradeMacro/POE-TradeMacro#705]
Hi,

not gonna lie, this suggestion comes from getting totally bamboozled an hour ago over a lightpoacher. Standard search (ctrl+d) doesn't really take in account sockets or some other secondary yet important pricing characteristics like links.  Maybe something similar could be taken in account for some other items where sockets are a big deal for pricing (like the 2 AS tombfist or lightpoacher) which may be easily forgotten when not knowing the item enough. Kind of an egoist and users' fault coming suggestion, but had to ask anyway.

Love this macro and thanks for your hard work !

**Comment by Quantisaveri** [comment]
There is always ctrl+alt+d for these purposes. good luck.

**Comment by Eruyome** [comment]
I don't really like adding too complex automated search queries for specific items. It creates a lot of manual maintenance and easily leads to mistakes. I can see your point but that's what the advanced search is for (ctrl + alt +d).
Poeprices predicted search should also help here, I haven't tested lightpoacher/tombfist but I'd expect their machine learning approach to evaluate sockets/links for these items.
