### ISSUE TITLE
My trade macro stops responding out of the blue!

### ISSUE THREAD

**Issue by inlagdgurka** [PoE-TradeMacro/POE-TradeMacro#709]
Information to include:
AHK version: 1.1.28.02
Windows version: Windows 10 Pro 64-bit

My poe trade macro stops responding when trying to ctrl+d an rare item, it works fine on uniques and it did work on rares like 1 h ago, but now all of a sudden it stopped working.
Tried reinstalling AHK and redownloading the macro, also tried the Dev version. no improvements... 
maybe its my side or something and if so i need help. 

Fill out everything that may be relevant and remove everything except these informations below:  

AHK version: 1.1.28.02
Windows version: Windows 10 Pro 64-bit

Kind Regards, inlagdgurka

**Comment by Eruyome** [comment]
Are you using the predicted search (peoprices) which is default for the ctrl + d search unless you disable it in the settings menu? In that case it may be aserver issue on their side.
Well, the macro shouldn't stop completely in that case but timeout after a while though.

**Comment by HarvardYard** [comment]
I can also confirm this issue. Doesn't kill the script just times it out for roughly 20 seconds. Unchecking Predicted Pricing fixes the Ctrl + D issue and everything else works just fine.

**Comment by Eruyome** [comment]
There's not really much that I can do about this. Either the poeprices request is fast and doesn't time out (which I have no influence over) or the macro will stop responding for a bit. AHK doesn't really work asynchronously.
