### ISSUE TITLE
Long unique price searching

### ISSUE THREAD

**Issue by Yoozi2k** [PoE-TradeMacro/POE-TradeMacro#71]
I waiting 10-20sec until macro search the price.. Any suggestions? (Im using Ctrl+D + updated script and ahk)

**Comment by Eruyome** [comment]
The search time depends on your internet connection. So maybe it's just that? I don't have this problem. Does it take that long on every search, not only advanced unique search?

**Comment by Yoozi2k** [comment]
Every search.. Searching by Ctrl+Q is 5 times faster
@Eruyome

**Comment by Eruyome** [comment]
I'm not too familiar with how those WinHTTP Requests to download the page work, but it seems its always slower than just opening poe.trade via ctrl + q. I have to play around with gzip compression though.

**Comment by Eruyome** [comment]
https://github.com/PoE-TradeMacro/POE-TradeMacro/issues/85
