### ISSUE TITLE
[Suggestion] Option for using poe.ninja when searching a unique

### ISSUE THREAD

**Issue by Pegoth** [PoE-TradeMacro/POE-TradeMacro#713]
Basically the same as "Alternative currency search", but for unique items.

**Comment by Eruyome** [comment]
I have talked to the poe.ninja dev about this and it seems fine to implement it, it shouldn't put too much stress on the site.

Having said that, it might take a bit to implement because I have some other things that I want to get in before that.

**Comment by Pegoth** [comment]
@Eruyome Wondering if this feature will be in for 3.3?

**Comment by Eruyome** [comment]
No, if it were just a hotkey to open the item on poeninja than that could be done, but more than that will take longer.
Maybe I'll add an option to open unique items/div cards/maps/essences on poe.ninja when using ctrl + q instead of opening it on poe.trade, so a compromise for the time being.

**Comment by Pegoth** [comment]
Okay, that's fair enough, thank you!

**Comment by Eruyome** [comment]
Partial support (open on poe.ninja) is now added.
