### ISSUE TITLE
cant change control + c 

### ISSUE THREAD

**Issue by methodicalpoe** [PoE-TradeMacro/POE-TradeMacro#714]
i cannot edit control c.  i can change everything else but not that one.
i see someone else posted earlier about it and read the reply.
however i have a friend that has the option of changing his on newer version.  i made sure i had the current script and still dont have the option.  
currently my "c" key does not work at all and i need to change it.

**Comment by aRTy42** [comment]
I'm pretty sure your friend is mistaken or is talking about something else.

You can assign a key though to send the Ctrl+C command, which is almost the same and likely what you want. Open the settings menu and go to the "Additional Macros" tab. Tick the box at "SendCtrlC" and set a key combination you like with the edit button.
