### ISSUE TITLE
Can't Change Hotkeys for Hideout

### ISSUE THREAD

**Issue by pibacc** [PoE-TradeMacro/POE-TradeMacro#715]
Can you please, PLEASE give an actual answer on how to change hotkeys?

Under the poe item info tab or w/e you call it, hideout and /remaining aren't options to change. Cool.

If I go "edit files" "additional macros" I change it there but then when I save it and reload the script it has now created duplicates for all 3 of the files and the changes don't work.

Nothing works.

I just want hideout to be F3 and remaining to be F2.

Is this possible or no?

I finally had them changed on version 2.5.5 but I was basically forced to update so that I wasn't spammed with the stupid "YOU CAN UPDATE!!!!!!!!!!!" pop-up every time I load it.

**Comment by Eruyome** [comment]
First of, the instructions are pretty clear and sufficient. You go here to change it:

![image](https://user-images.githubusercontent.com/16058242/40148595-14b8c484-596f-11e8-8031-64361ef7b37a.png)

Secondly, If you'd have taken a good look at the options and disabled "Update: Show Notifications", you could have prevented this annoyance.

Thirdly, the attidute you're showing here doesn't really motivate anyone to invest much time in helping you.

**Comment by pibacc** [comment]
Well my apologies I looked at that menu for like 10 minutes and for some reason I could not see it.
