### ISSUE TITLE
Support for Windows/high contrast themes

### ISSUE THREAD

**Issue by sajber** [PoE-TradeMacro/POE-TradeMacro#717]
Great script, can't thank you enough for all the time it saves!

I am using Windows with high contrast or custom contrast theme and this creates an issue with the "Windows" that are populated with menues.
The regular price-check black box is viewed just fine.

Example Image when I press Win+R on an item:
![image](https://user-images.githubusercontent.com/6634243/40329395-b93935b0-5d49-11e8-8db9-d68dd7d6b48a.png)

Would it be possible to add support for high contrast or possibly other skins to select for these kind of windows?

Thanks in advance!

AHK version: 1.1.26.01
POE-TradeMacro: v2.9.0 (but this has been an issue for me as long as I can recall in earlier versions)
Windows version: Windows 10 Enterprise 1803 (OS Build 17134.48)

**Comment by Eruyome** [comment]
Try this version, made some very simple changes to the curerncy ratio window, I believe it should work, except those buttons since I can't manipulate them. And maybe the dropdown also.


https://github.com/PoE-TradeMacro/POE-TradeMacro/archive/devEru.zip

**Comment by Eruyome** [comment]
Manually fixing everything, not only the currency ratio UI, is a bit more complicated, in the sense of finding all the places where something has to be changed.
A new update would overwrite everything that you changed locally. I suggest that you simply wait a bit, shouldn't be that much work to fix everything so it may be done in time for 3.3.0.

**Comment by sajber** [comment]
Thank you so much for looking into it so fast, no hurries or worries.

**Comment by Eruyome** [comment]
All Gui windows should be fine now. If you find no issues I'll close this (or you can do it).

**Comment by sajber** [comment]
Thanks =)
