### ISSUE TITLE
Using Without AutoHotkey?

### ISSUE THREAD

**Issue by ibrahimkirmizi** [PoE-TradeMacro/POE-TradeMacro#718]
Hello. I just saw this program and it's super helpful and useful. But i have a problem.

I'm playing Black Desert Online same time while playing Path of Exile. Black Desert Online Guard system is blocking AutoHotkey. So if i open AutoHotkey BDO closed automactly. And this is bad because i also wanna use this program.

Does is there anyway to use this program without using AutoHotkey? 

Thanks and have a nice day.

**Comment by Eruyome** [comment]
Well that's why I suggested using a virtual machine, if your PC can handle it you can run BDO in that machine instead, it wouldn't have any way to communicate with your actual pc and detect or block AHK.
