### ISSUE TITLE
Issue with the last Ver 2.10.1

### ISSUE THREAD

**Issue by thedot80** [PoE-TradeMacro/POE-TradeMacro#723]
Every time I start the poe trade macro I am getting this message first:

https://imgur.com/eswWSpN

Ingame, every time I start a request with Ctrl+D, first of all, the message from above appears and after I click OK the data showed up. 

https://youtu.be/WjUJ_THNsLg

The previous version worked without any issues... 

AHK version: 1.1.29 (64bit) latest version
Windows version: WIN 10 latest updates and patches.

**Comment by Eruyome** [comment]
You're running `Fallback.exe`, right? Use `Run_TradeMacro.ahk` instead. I forgot to remove that debug code before compiling the fallback exe, it's removed in the actual ahk files.

**Comment by thedot80** [comment]
Perfect, working as intended now :) Thanks
