### ISSUE TITLE
Giant Warning Popup About Cookies While Loading Script

### ISSUE THREAD

**Issue by dsnvwlmnt** [PoE-TradeMacro/POE-TradeMacro#724]
Suddenly i'm getting 2 popups when loading PoE-TradeMacro. Everything was fine last time i ran it, a day or so ago. Updated to 2.10.1 a couple days ago, everything was fine, no popups.

The first popup is just annoying as it overlays my screen for 5-10 seconds (on a very fast computer). Then i get a giant window with tons of information and buttons. It says to check the FAQ for cURL. There is no reference to cURL in the FAQ.

1- If i click "Open cookie file", this is what's in it:
**useragent=Mozilla/4.0 (compatible; MSIE 7.0; Windows NT 6.2; Win64; x64; Trident/7.0; .NET4.0C; .NET4.0E)**
2- I tried clicking "continue". Script seems to work but next time i load it i get the same 2 annoying popups.
3- I tried clicking "Delete cookies". Script seems to work but next time i load it i get the same 2 annoying popups.
4- I tried setting **UseManualCookies=1** in config_trade.ini. No change.

AHK 1.1.28.02
Windows 10 LTSB

![image](https://user-images.githubusercontent.com/14173022/40755758-98c63818-6434-11e8-9c38-2ad785e01da8.png)

![image](https://user-images.githubusercontent.com/14173022/40755760-9bec1026-6434-11e8-89b2-03a98d545141.png)

**Comment by Eruyome** [comment]
Did anything change with your internet connection? Provider/ISP change?

**Comment by simpala** [comment]
same issue only i never get pass the first "reading your user-agent and cookies"
no isp change or any changes to internet. 
FWIW I do not use Internet Explorer or Edge, usually just Chrome

**Comment by Eruyome** [comment]
IE is used to read cookies (after opening a hidden IE instance), because it's way too hard to read cookies from those other browsers.

If you don't get any kind of cloudflare page redirect in your browser of choice after deleting it's poe.trade cookies, then you don't need them and there's a different issue.

Btw, after changing `UseManualCookies=1` you also have to open the settings menu and manually add those cookies (if poe.trade actually creates them).

There should be a file `temp\StartUpLog.txt`, post that here please.

**Comment by dsnvwlmnt** [comment]
Forgot to post that the problem went away for me.

I don't think i did anything relevant after my post... Opened the settings window and poked around looking for cookies-related settings, checked and unchecked something unrelated ("Update: Skip folder selection"), then clicked OK. Usually i would Cancel since i didn't change anything but i clicked OK. Can't remember if things went back to working normally immediately on the next run but i think so.

Internet changes... maybe. We reset the router Monday due to Fancy Bear hack. Same day as the trademacro update, which i likely did before the router reset. And today _might_ have been the first time i ran PoE since then.

**Comment by simpala** [comment]
Tried it again it worked without any problems, I did not do anything different but the user-agent/cookies message did not pop up this time, maybe there was a network issue at the time that i was not aware of.
