### ISSUE TITLE
TradeMacro hotkeys break ingame shortcuts

### ISSUE THREAD

**Issue by niklaas-0rbit** [PoE-TradeMacro/POE-TradeMacro#725]
So after updating to the latest version I realised that the assigned hotkeys for the currency ratio (Ctrl-R) & league change (Ctrl-L) are breaking the set ingame shortcuts for rotating the hideout decorations. Deactivating or changing the shortcut in the settings actually changes nothing about that behaviour.

**Comment by Eruyome** [comment]
Rebinding in the settings and reloading the script works perfectly. Not sure how I missed that, I like building hideouts myself...

**Comment by niklaas-0rbit** [comment]
Interesting, now I stopped AHK and restarted the script. Now it works with my set keybindings (just used Ctrl-Alt-R & Ctrl-Alt-L instead). I probably made a mistake with reloading I guess... thanks for answering.

**Comment by Eruyome** [comment]
I'll probably gonna change the default hotkey for that. Not sure yet whether to use ctrl + alt + r or just alt + r.
