### ISSUE TITLE
Minor Issue: Premium Tab Currency Popup (Ctrl+R) - ESC doesn't work

### ISSUE THREAD

**Issue by dsnvwlmnt** [PoE-TradeMacro/POE-TradeMacro#726]
ESC works for all the other windows in PoETradeMacro, but not this newer one.

![image](https://user-images.githubusercontent.com/14173022/40818474-fe858406-650b-11e8-964b-9eac0c73df50.png)

**Comment by Eruyome** [comment]
Yeah, how easy it is to forget stuff liek that...

**Comment by Eruyome** [comment]
Fixed on my dev branch.
