### ISSUE TITLE
[ToDo] Custom Input Search dialog can appear off screen

### ISSUE THREAD

**Issue by poeuser** [PoE-TradeMacro/POE-TradeMacro#73]
Custom Input Search (Ctrl-I) opens the dialog box near the mouse cursor. If the cursor is near the edge of the screen, the dialog box may appear partially off the screen.

Here my cursor was over the top-left card in my stash when I pressed Ctrl-I:
![example](https://cloud.githubusercontent.com/assets/22657713/19749422/6b7e6052-9c1b-11e6-9495-8b183e5ad0ae.PNG)

Since the dialog is context-free (not related to the current item unlike the Price Check Hotkey), it does not need to follow the cursor. I suggest a fixed position slightly to the right of the middle of the screen (so it does not block the character, stash, or inventory).

**Comment by Eruyome** [comment]
Thx, will implement it.

**Comment by Eruyome** [comment]
fixed on dev-branch
