### ISSUE TITLE
Searches on Incursion league even with SearchLeague=standard set.

### ISSUE THREAD

**Issue by Eliont** [PoE-TradeMacro/POE-TradeMacro#730]
Hello and good time of day.
Trade macro searches on Incursion league even with **SearchLeague=standard** set.

AHK version: 1.26
Windows version: Seven Prof

**Comment by Eruyome** [comment]
It does not for me. Have you cycled through the leagues/changed them around in the settings to see if anything gets fixed by that?

**Comment by Eliont** [comment]
Working now.
Problem is - settings set in ini file was ignored.
Option window works.

And idk why - several first launches of the script did not bring option (bold - http://puu.sh/AyJEF/74f5fd448e.png) variant to menu.

**Comment by Eruyome** [comment]
If the macro doesn't finish launching completely it only has a small menu, you can see that when looking at it while it initialises.

**Comment by Eruyome** [comment]
Still an issue? Could there be file permission problems when writing the in ifile?
