### ISSUE TITLE
Can't Alt+Tab out of the gameanymore

### ISSUE THREAD

**Issue by AiluroPanda31** [PoE-TradeMacro/POE-TradeMacro#731]
Hello there, first thanks for your work :D.
I have a problem since a little bit of time : 
After lauching POE Trade Macro, i can't ALT+TAB out of the game.
If i suspend hotkeys it's working again.
I tried disabling all hotkey with an alt or tab but didnt work.

Versions :  
- AHK U64 ->1.26.01
- POE Trade ->2.10.2
- Windows -> 10

Thanks for the help.

**Comment by Eruyome** [comment]
Have you changed any of the default hotkeys?

Could you right click the system tray icon and select `Show all assigned hotkeys` and show me the windows that appears?

**Comment by AiluroPanda31** [comment]
Got ya : 
![screenshot_1](https://user-images.githubusercontent.com/33065647/41482305-74b5b2ac-70d5-11e8-925d-b13bd959b354.png)

**Comment by Eruyome** [comment]
Still an issue? I don't know what's going on here.
