### ISSUE TITLE
Exception Thrown(download)!

### ISSUE THREAD

**Issue by Blackbol** [PoE-TradeMacro/POE-TradeMacro#733]
Information to include:
* AHK (64bit) last build (04/06/2018)
* Windows 10

Fill out everything that may be relevant and remove everything except these informations below:  

AHK version: last build (04/06/2018
Windows version: last build (04/06/2018)

Hi, my friends have it and i want test but i have error
![error](https://user-images.githubusercontent.com/21270889/40926780-60fec8c2-681d-11e8-8d2f-6030f9fe6d42.png)
![error 2](https://user-images.githubusercontent.com/21270889/40926783-61897af8-681d-11e8-8cb2-4ec49ed92850.png)

**Comment by aRTy42** [comment]
The official site and API were down for a bit, it should work now.

**Comment by arkanis78320** [comment]
is that fix, i have the same problem atm

**Comment by Eruyome** [comment]
Please report back if there's still an issue, I'll close this for now.
