### ISSUE TITLE
Same issue as before (PoE Trade macro times out)

### ISSUE THREAD

**Issue by SirKori** [PoE-TradeMacro/POE-TradeMacro#735]
AHK version: Latest
Windows version: Windows 7

I posted this last league I believe, but basically the CTRL D/C search function seems to time out after a short while of playing. In order to fix it I have to just launch internet explorer which immediately fixes the issue. I would however wish this wasn't a necessity to tab out every 5-10minutes.

I could not find a solution for this last league and still can't seem to find one now. It seems it's trying to find the information, but fails and brings up the usual box of say X unique item but gives no information as if there's none for sale/to compare to.

Hopefully you're smarter and can finally figure out what's going on. Perplexed that instantly starting Internet Explorer fixes the problem temporarily until it inevitably fails again.

**Comment by Eruyome** [comment]
Did the latest version change/fix anything?
