### ISSUE TITLE
Vial of the Ritual Price Check Not Working For Me

### ISSUE THREAD

**Issue by dsnvwlmnt** [PoE-TradeMacro/POE-TradeMacro#737]
It seems to work the way it should for my buddy, but with my settings nothing shows up.

AHK version: 1.1.28.02
Windows version: 10 LTSB

My popup Ctrl+D:
![image](https://user-images.githubusercontent.com/14173022/41113551-d159401e-6a36-11e8-9cae-f548c4308b07.png)

My popup Ctrl+C:
![image](https://user-images.githubusercontent.com/14173022/41113595-f45d5dd4-6a36-11e8-9e34-d76282bcec3e.png)

Friend's popup:
![image](https://user-images.githubusercontent.com/14173022/41113462-8e62e864-6a36-11e8-876c-3412a27c8d6d.png)

My settings:
![image](https://user-images.githubusercontent.com/14173022/41113387-57b520a2-6a36-11e8-9e8c-455b5ccc731f.png)

**Comment by aRTy42** [comment]
You have "Alternative currency search" checked. Third option from the bottom in the upper middle section.

**Comment by aRTy42** [comment]
The vials are currency but not on poe.ninja at the moment. The function does not get data for it, so it can't display anything.
