### ISSUE TITLE
pathofexile.com/trade support

### ISSUE THREAD

**Issue by Noshei** [PoE-TradeMacro/POE-TradeMacro#739]
I'm just wondering if support for pathofexile.com/trade will be added.  This league I've noticed that poe.trade has been much worse than pathofexile.com/trade and would like to only be using pathofexile.com/trade if possible.

**Comment by Eruyome** [comment]
Here's my most recent answer to that https://github.com/PoE-TradeMacro/POE-TradeMacro/issues/429#issuecomment-395694752

TLDR: I want to add it, but it's just a shit ton of work, so I haven't even started and have no ETA.
