### ISSUE TITLE
Predicted search has encountered an unknown error 

### ISSUE THREAD

**Issue by SpecOpz** [PoE-TradeMacro/POE-TradeMacro#742]
I keep getting this error when i try to price check any rare item. Ive made sure to run everything as admin and tried reinstalling ahk and the script a few times and havent been able to figure out what is causing this error. Any help would be greatly appreciated.

AHK version:1.1.29.01
Windows version: win 10 64bit

**Comment by Eruyome** [comment]
It's a known issue for ings and armours, will be fixed soon.

**Comment by SpecOpz** [comment]
ok thanks alot
