### ISSUE TITLE
Failed attempt to launch program

### ISSUE THREAD

**Issue by ABoehm4** [PoE-TradeMacro/POE-TradeMacro#746]
AHK version: v2.10.4 (newest)
Windows version: Windows 10

Hello,
My trade macro was working flawlessly before this most recent update. Now, whenever I try to custom search (Control + alt + D) and click "Open on poe.trade", this error pops up https://gyazo.com/43c7c0dbba62221fb9cbcb21f192ebfa

If I use just the "Search" function, it seems to work okay, but it won't launch a new window in Chrome like it did before this update.

**Comment by Eruyome** [comment]
Does reverting back to the previous version change anything?

**Comment by ABoehm4** [comment]
Reverting to the previous version did not fix the problem. Editing the file path, however, did seem to fix it. Thank you for your help.

**Comment by Eruyome** [comment]
The macro tries to find your default browser (which is not as easy as it sounds) but it seems it fails to do so, manually adding a path to your browser works in that case.
