### ISSUE TITLE
Ability to choose between GGG's trade site and poe.trade

### ISSUE THREAD

**Issue by nut-3** [PoE-TradeMacro/POE-TradeMacro#747]
Hello!
Recently GGG has released their own trade platform - https://www.pathofexile.com/trade/. It copies the functionality of poe.trade, just does it in it's own way. The pros of using GGG's site is it works more reliable than poe.trade. I think it's because of slow public stash api, which is not poe.trade's fault, but for end users the reason is not so important.
I think if there's an option in you macro to choose between these two sites, it would be great!
Thanks in advance.

**Comment by aRTy42** [comment]
Surprisingly we already know that site exists. It's just not that easy to swap.

See Eru's most recent answer [here](https://github.com/PoE-TradeMacro/POE-TradeMacro/issues/429#issuecomment-395694752) or simply see the exact same suggestion by someone else a few issues down list [here](https://github.com/PoE-TradeMacro/POE-TradeMacro/issues/739).
