### ISSUE TITLE
Disable CTRL+C overlay

### ISSUE THREAD

**Issue by brunocassol** [PoE-TradeMacro/POE-TradeMacro#748]
First of all, TradeMacro is an amazing tool! Thank you!

How can I disable CTRL+C item overlay? I'm developing a tool which needs to send CTRL+C to detect what item is under the cursor but TradeMacro's overlay causes unnecessary delay and inconsistencies. I still want to use TradeMacro for price check, but not the item information. Thanks

**Comment by aRTy42** [comment]
You can't disable Ctrl+C permanently at the moment, but you should be able to disable ItemInfo each session by pressing the "Pause" button. You can set/change that key in the Settings -> Additional Macros if you want to.

**Comment by brunocassol** [comment]
That's good enough for me 👍
