### ISSUE TITLE
 Full Stash Pricing/Export Stash item Prices to CSV or other format 

### ISSUE THREAD

**Issue by zombodotcom** [PoE-TradeMacro/POE-TradeMacro#749]
Is there a way to get the price of every item in a stash, and export it to a csv or something?

**Comment by Eruyome** [comment]
No and you won't ever get it with this macro (at least not in the foreseeable future).
If you want to price an entire stash (having anything besides maps, currency, div cards, essences, fragments) try using this site https://www.poeprices.info/.

If you want to price an entire stash only having the mentioned item types use https://www.pathofexile.com/forum/view-thread/1989935.

**Comment by zombodotcom** [comment]
found https://www.poeprices.info/ yesterday, seems like the best option
