### ISSUE TITLE
Getting a download error

### ISSUE THREAD

**Issue by xereau69** [PoE-TradeMacro/POE-TradeMacro#750]
AHK version: POE-TradeMacro-2.10.4
Windows version: Windows 10

Just started today.  

Exception thrown (download)!

Error while downloading
<http://api.pathofexile.com/leagues?type=main> using
URLDownloadToFile (DownloadFallBack)

When you try to search for an item in Incursion, it is giving prices and searching for items in Standard.

Maybe just the api site is down?

Thought you'd want to know either way.

**Comment by Eruyome** [comment]
The API is down/lagging hard all the time at the moment.

**Comment by xereau69** [comment]
Still buggered 24hrs later.

**Comment by Eruyome** [comment]
Still an issue?

**Comment by xereau69** [comment]
Yes, still not working.  Control D brings up Standard pricing only.  Control Q brings up Standard search query only.  I tried downloading again and trying from a fresh install folder.  Same issue.

**Comment by xereau69** [comment]
Bit of history in case you want to come up with a fix.  When the API went down, the default league to check prices on became Standard (without me changing any settings).  When the API settled down, and I was still in Incursion, doing price checks from Incursion, the control D and control Q results were still only giving me Standard league results.  I had to manually change back to tmpleague in the settings options.  Any way to make this setting automatic when any search is made from the league you are in?

**Comment by Eruyome** [comment]
No, since I can't read the league that you're currently in. That's the whole reason for automatically falling back to the permanent leagues if no other active league can be found.
