### ISSUE TITLE
Error: Predicted search has encountered an unknown error on items linked in chat

### ISSUE THREAD

**Issue by Atmosquake** [PoE-TradeMacro/POE-TradeMacro#751]
It seemed to working fine earlier but all of a sudden it started not working. Help would be appreciated! 

I took the liberty of posting the poeprices_log.txt because it seemed important. Let me know what else to post!

AHK version: 2.10.4
Windows version: Windows 10

Request and response:
{
    "added": {
        "browserUrl": "https://www.poeprices.info/api?l=Incursion&i=UmFyaXR5OiBSYXJlDQo8PHNldDpNUz4+PDxzZXQ6TT4+PDxzZXQ6Uz4+TG9hdGggTG9jaw0KU3R5Z2lhbiBWaXNlDQotLS0tLS0tLQ0KUmVxdWlyZW1lbnRzOg0KTGV2ZWw6IDQ4DQotLS0tLS0tLQ0KU29ja2V0czogQSANCi0tLS0tLS0tDQpJdGVtIExldmVsOiA4NQ0KLS0tLS0tLS0NCkhhcyAxIEFieXNzYWwgU29ja2V0DQotLS0tLS0tLQ0KKzY4IHRvIEFybW91cg0KKzY3IHRvIG1heGltdW0gTGlmZQ0KKzMyJSB0byBGaXJlIFJlc2lzdGFuY2UNCiszOSUgdG8gTGlnaHRuaW5nIFJlc2lzdGFuY2UNClJlZmxlY3RzIDIgUGh5c2ljYWwgRGFtYWdlIHRvIE1lbGVlIEF0dGFja2Vycw0KKzI0JSB0byBDb2xkIFJlc2lzdGFuY2UNCg==&w=1",
        "encodedData": "UmFyaXR5OiBSYXJlDQo8PHNldDpNUz4+PDxzZXQ6TT4+PDxzZXQ6Uz4+TG9hdGggTG9jaw0KU3R5Z2lhbiBWaXNlDQotLS0tLS0tLQ0KUmVxdWlyZW1lbnRzOg0KTGV2ZWw6IDQ4DQotLS0tLS0tLQ0KU29ja2V0czogQSANCi0tLS0tLS0tDQpJdGVtIExldmVsOiA4NQ0KLS0tLS0tLS0NCkhhcyAxIEFieXNzYWwgU29ja2V0DQotLS0tLS0tLQ0KKzY4IHRvIEFybW91cg0KKzY3IHRvIG1heGltdW0gTGlmZQ0KKzMyJSB0byBGaXJlIFJlc2lzdGFuY2UNCiszOSUgdG8gTGlnaHRuaW5nIFJlc2lzdGFuY2UNClJlZmxlY3RzIDIgUGh5c2ljYWwgRGFtYWdlIHRvIE1lbGVlIEF0dGFja2Vycw0KKzI0JSB0byBDb2xkIFJlc2lzdGFuY2UNCg==",
        "league": "Incursion",
        "requestUrl": "https://www.poeprices.info/api?l=Incursion&i=UmFyaXR5OiBSYXJlDQo8PHNldDpNUz4+PDxzZXQ6TT4+PDxzZXQ6Uz4+TG9hdGggTG9jaw0KU3R5Z2lhbiBWaXNlDQotLS0tLS0tLQ0KUmVxdWlyZW1lbnRzOg0KTGV2ZWw6IDQ4DQotLS0tLS0tLQ0KU29ja2V0czogQSANCi0tLS0tLS0tDQpJdGVtIExldmVsOiA4NQ0KLS0tLS0tLS0NCkhhcyAxIEFieXNzYWwgU29ja2V0DQotLS0tLS0tLQ0KKzY4IHRvIEFybW91cg0KKzY3IHRvIG1heGltdW0gTGlmZQ0KKzMyJSB0byBGaXJlIFJlc2lzdGFuY2UNCiszOSUgdG8gTGlnaHRuaW5nIFJlc2lzdGFuY2UNClJlZmxlY3RzIDIgUGh5c2ljYWwgRGFtYWdlIHRvIE1lbGVlIEF0dGFja2Vycw0KKzI0JSB0byBDb2xkIFJlc2lzdGFuY2UNCg=="
    },
    "data": {},
    "error": 2,
    "status": 200
}

**Comment by Atmosquake** [comment]
I should add that it works if it's an equipped item or in an inventory (either my own or a stash)

**Comment by aRTy42** [comment]
I'm pretty sure the issue comes from localisation stuff that gets added to the clipboard info if you get the info from chat items.

Chat:
```
Rarity: Rare
<<set:MS>><<set:M>><<set:S>>Whispering Bane
Searching Eye Jewel
```

Otherwise:
```
Rarity: Rare
Whispering Bane
Searching Eye Jewel
```

will talk with Eruyome about it.

**Comment by Eruyome** [comment]
I can probably fix that locally but I told slug about it (my poeprices contatct) and he'll also look into it on his end since it could also effect the website in general.

**Comment by Eruyome** [comment]
Fixed
