### ISSUE TITLE
Using program to check price opens a new window and forces me out of game, even when in windowed fullscreen

### ISSUE THREAD

**Issue by Thickpickle** [PoE-TradeMacro/POE-TradeMacro#752]
_TEMPLATE_ (Remove the explanations here from your post) 

Make sure:
* That you have checked the Wiki/FAQ before creating any issue.
* That poe.trade/GGG's website don't have any issues if loading the script takes too long or failes.

Information to include:
* AHK (including 32/64bit) version if you have any kind of script errors.
* Windows version could be relevant.

Fill out everything that may be relevant and remove everything except these informations below:  

AHK version:
Windows version:

**Comment by Eruyome** [comment]
You can remove the template stuff, it only makes it take longer to see what your issue is about. You haven't even included the information that was asked for.

Please describe this issue in further detail. What window, maybe show it? Is it the peoprices window (ctrl + d) on rares? You can disable this window in the settings.

**Comment by Thickpickle** [comment]
When I use (ctrl+d) in game it should open a small window over the item showing the pricing details. However, for me it takes me out of game and shows a much larger window. It doesn't seem to want to work in game, but rather out of it.

**Comment by Thickpickle** [comment]
windows 10 64 bit. sorry for that, guess i missed that info earlier

**Comment by Eruyome** [comment]
Screenshot.

**Comment by methodicalpoe** [comment]
same issue here
just started 20 minutes ago.
i can either press control c to check the items mods, control d to price check and it minimizes path of exile with no return.
a screen shot wont show anything.  if i press ctrl d or ctrl c it minimizes path of exile. opens no window.

**Comment by Eruyome** [comment]
Still an issue? If yes please provide some more information (screenshot for example).

**Comment by backtink** [comment]
i have the same problem. WHen Control D it forces the game to windows desktop, and i have to close, and reenter game. Someone had the same experience ?

**Comment by Eruyome** [comment]
I have still no idea what to do or even test here. Do you guys still have these issues? Anything you tried to fix it or did you find any solution?
