### ISSUE TITLE
Issue adding new affixes to Map Mod Warnings

### ISSUE THREAD

**Issue by lonitref** [PoE-TradeMacro/POE-TradeMacro#754]
Trying to include more affixes to map mod warnings. Edited MapModWarnings.ini file accordingly and restarted the script. But new affixes are not appearing in the warnings section when they are present on a map.

AHK version: 1.1.26.01
Windows version: Windows 10

**Comment by aRTy42** [comment]
The MapModWarnings.ini is just a config file. Unless you edited the script's main ItemInfo.ahk file aswell, adding new lines to the config file won't have any effect.

What did you want to add?
