### ISSUE TITLE
Price prediction of rares not working anymore?

### ISSUE THREAD

**Issue by madvirtu** [PoE-TradeMacro/POE-TradeMacro#755]
So when using the CTRL+D Feature on rares in my Inventory, i get this little message "Getting price prediction..." and nothing else happens.

I have Windows 7, and use the 64 bit version of AHK

**Comment by Awesomtologist** [comment]
I'm having the same issue this morning.  It was working last night just fine. Ctrl+D doesnt work for me, Ctrl+C works. Windows 10 64-bit. TradeMacro v2.10.4

**Comment by TheOne320** [comment]
It gets the prediction from https://www.poeprices.info/ , so if that site is not reachable, then you will not get results.

**Comment by madvirtu** [comment]
@TheOne320 Yes i know, and i checked beforehand if the poeprices.info is working fine on its own, which is indeed working fine when i copy+pasta an item directly into the Website

**Comment by zombodotcom** [comment]
I have been having the same issue... Posted about it in another thread and on discord.

**Comment by luchen5** [comment]
I'm having same issues over here

**Comment by turtle328** [comment]
Same issue, the poeprices site works fine and the predicted search was working fine last night. I suspect that poeprices change something in their site that is breaking poetrademacro considering poetrademacro hasn't been updated lately.

**Comment by Eruyome** [comment]
Fixed by peoprpices.info, their API had issues.
