### ISSUE TITLE
CTRL + D not working but CTRL + ALT + D works.

### ISSUE THREAD

**Issue by dalollypop** [PoE-TradeMacro/POE-TradeMacro#756]
Just a thing that started happening. Ctrl + D doesn't work for rare items only unique and currency etc. 
It seems like the hotkey itself hangs and I can't scroll through stash tabs while its hanging looking for price check. But when I use advanced price check it works. Just a thing.

**Comment by zombodotcom** [comment]
same

**Comment by Eruyome** [comment]
Fixed by peoprpices.info, their API had issues.
