### ISSUE TITLE
[Fixed on Dev branch] ]Unique Map Lookups

### ISSUE THREAD

**Issue by Smooshface** [PoE-TradeMacro/POE-TradeMacro#76]
Noticed that the Pricing for Maelstrom of Chaos seemed a bit low, when searching an ID'd unique map, it just searches the price for the base, so it was showing Atoll map prices, not Maelstrom map prices.

**Comment by Eruyome** [comment]
https://github.com/PoE-TradeMacro/POE-TradeMacro/commit/f2697896c0ff00ee779bbb085e3833c62cec26c6

Yeah sry, fixed on dev branch, will try to make a new release in a few hours

**Comment by Smooshface** [comment]
No worries at all, just trying to make sure you know!
