### ISSUE TITLE
Trade Macro Error

### ISSUE THREAD

**Issue by BonChan8** [PoE-TradeMacro/POE-TradeMacro#760]
AHK version: 1.1.29.01
Windows version: 10 Home 64 bit

![poemacro](https://user-images.githubusercontent.com/40407434/41623894-fcd5cb40-73c8-11e8-810a-8aa7f0a3380c.jpg)

Please help :(

**Comment by lucifronsun** [comment]
Same thing has been happening to me for a day or two now, the poe ninja site appears to be working just fine however, so I'm not sure what the problem is.

**Comment by BonChan8** [comment]
Yeah, at first I thought it wasn't only me, but then I asked a friend who uses it as well and it worked fine for him.

**Comment by Dan-E2** [comment]
I'm having the same issue. I switched the league to standard in my settings and now it's not even trying to load incursion. I've uninsatlled and reinstalled and still not even giving me the option to change the league to incursion in the settings.

**Comment by Eruyome** [comment]
Please post your `temp\StartUpLog.txt` here. If you directly post the contents do me a favour and warp it in code tags  ("insert code" in the formatting menu). Or upload the file.

**Comment by Eruyome** [comment]
You can also try using this version https://github.com/PoE-TradeMacro/POE-TradeMacro/archive/dev.zip

I rewrote some of that currency data download and loggging stuff.

**Comment by BonChan8** [comment]
Tried your other version and didn't work either, here the file for the normal macro.

[StartupLog.txt](https://github.com/PoE-TradeMacro/POE-TradeMacro/files/2121146/StartupLog.txt)

**Comment by Dan-E2** [comment]
[StartupLog.txt](https://github.com/PoE-TradeMacro/POE-TradeMacro/files/2121346/StartupLog.txt)

startup log above

**Comment by Eruyome** [comment]
Download it again.
The script now creates some files in `temp\`:
![image](https://user-images.githubusercontent.com/16058242/41690823-a8115130-74f7-11e8-8f15-68feba612d32.png)

Here's an example of how a "good" file looks like:
[currencyHistory_tmpstandard.txt](https://github.com/PoE-TradeMacro/POE-TradeMacro/files/2121563/currencyHistory_tmpstandard.txt)

I'ts basically what you can see when opening this http://poe.ninja/api/Data/GetCurrencyOverview?league=tmpstandard

It's normal if the one's with "event" in the name are empty. Tell me which of the others look "fine" (examples above) and which ones have different contents/are empty.

**Comment by Dan-E2** [comment]
re-downloaded and still stuck in standard with no incursion option to switch to in settings.

same as Bon; my `temp` has `currencyData.json` `currentLeagues.json` `StartupLog`

here is the `search` section of my `config_trade.ini`

```
[Search]
AlternativeSearch=0
AccountName=
SearchLeague=tmpstandard
; Defaults to "standard" or "tmpstandard" if there is a Temp-League active at the time of script execution.
; "tmpstandard" and "tmphardcore" are automatically replaced with their permanent counterparts if no Temp-League is active.
; Possible values:
; 	"tmpstandard" (current SC Temp-League)
;	"tmphardcore" (current HC Temp-League)
;	"standard",
;	"hardcore"
```

**Comment by Dan-E2** [comment]
so, in my `config_trade.ini` I changed the `SearchLeague` section to incursion and got the same original error message that we were getting.

**Comment by Dan-E2** [comment]
and the last update. fixed the issue. in the `config_trade.ini` file I chaged the `SearchLeague` to `tmpstandard`.

Problem resolved.

**Comment by BonChan8** [comment]
Oh wow it worked, thanks so much.
