### ISSUE TITLE
Consider Using Recommended Price Rather than Machine Learning Prediction

### ISSUE THREAD

**Issue by turtle328** [PoE-TradeMacro/POE-TradeMacro#761]
I've been toying on poeprices.info and I've noticed their prices are much more accurate with the "Recommended Price" rather than "Machine Learning Prediction". Here's an example: https://gyazo.com/e3a1a214cb7a71b02571b1344b0ecd40

This ring is certainly worth at least 15c, so the Recommended Price correclty lists 15c, however the Machine Learning Price is way undervaluing this ring.

**Comment by slugspanker** [comment]
API is having some unknown errors for certain item types and leagues. The symptom is that the prediction may ignore all the mods on a rare item.

This affects the ML prediction both on the website and the TradeMacro function.
Recommended price on the website is not affected.

We are currently investigating the cause, which may take a day or two.

**Comment by Eruyome** [comment]
Btw, I'm pretty sure that I posted a reply here, maybe I forgot to hit the "comment" button...
The mentioned issue may be related to what slug just posted (he messed something up) but in general to answer the original question I wanted to quote slug, after talking about this again with him.

> It is case by case in my opinion. Many times recommended price could end up with nothing or too few items to match the queried item. Overall, ML should be better. To generate recommended price, one or few queries will be issued to DB, which takes much longer time( just like when u use the website). I don’t think my server can handle the volume (we can try in a careful way). I would say encourage to use the link you have in the UI to get the recommended price or give us feedback, when the price is way off.

**Comment by turtle328** [comment]
I'd like to thank both of you for clearing things up, I'm glad it's just an API issue and not a genuine price the ML algorithm came up with!
