### ISSUE TITLE
Trade tooltip misalignment

### ISSUE THREAD

**Issue by NativeFail** [PoE-TradeMacro/POE-TradeMacro#762]
* AHK version: 1.1.29.01.
* Windows 10

I tried 32bits(Legacy and Unicode) and 64bits of AHK

![poetrademacromissalign](https://user-images.githubusercontent.com/21171611/41683968-7701e886-74dc-11e8-9285-d48e305e527e.PNG)

**Comment by aRTy42** [comment]
The monospace font was not loaded properly. Was this the result right after starting the macro? It happens to me too if I try to use hotkeys already while the macro is loading its last bits.

**Comment by NativeFail** [comment]
It look like this all the time since months for me :/

**Comment by NativeFail** [comment]
Ohh !! I just read https://github.com/PoE-TradeMacro/POE-TradeMacro#usage--instructions again !
And the solution is:

**4. Run Run_TradeMacro.ahk.**

I always used Fallback.exe before.
