### ISSUE TITLE
Accessing PoE.trade using curl failed!

### ISSUE THREAD

**Issue by quaye12** [PoE-TradeMacro/POE-TradeMacro#765]
![image](https://user-images.githubusercontent.com/40598482/41907365-8a119880-7938-11e8-9098-d9362e820560.png)

Can anyone help me with this issue? Loaded up macro today when it was fine for months and getting this.

**Comment by aRTy42** [comment]
Make sure your antivir/firewall didn't block curl.exe (location: <scriptfolder>\lib\curl.exe). There was another user recently where avast quarantined the file.

**Comment by aRTy42** [comment]
Didn't have any other idea, but I just realised that you just wrote disabled, nothing specific about quarantine. Please check if `<script folder>\lib\curl.exe` is still there and if that exe is missing, look for your antivir quarantine functionality.

**Comment by Eruyome** [comment]
So, @quaye12, did you try artys suggestion?
