### ISSUE TITLE
Acessing poe.trade using cURL failed

### ISSUE THREAD

**Issue by sighichinoez** [PoE-TradeMacro/POE-TradeMacro#767]
I just played PoE like normally and noticed the poe trade macro stopped working. I'm 99% sure I didn't do or change anything but when it stopped working I just tried to redownload it and downloaded the newer version. I got this error and I don't know how to fix it.

[https://gyazo.com/8b02bcd71da620ebcbf85aeaff360397](url)

I tried to remove cookies and a bunch of the steps in the FAQ. And I have disabled firewalls and everything but it didn't seem to work. I never realized how much I depended on this program untill it stopped working like this :|

AHK version:  v1.1.29.01
Windows 10

**Comment by aRTy42** [comment]
Please check if your antivir/firewall blocked or quarantined curl.exe (false positive). In particular please check if `<script folder>\lib\curl.exe` is still there.

**Comment by sighichinoez** [comment]
I have antivirus/firewall both disabled atm so it shouldn't affect it right? and the curl.exe is still there in the lib folder

I'm lost to what's wrong :(

**Comment by Eruyome** [comment]
Is this still an issue? Can you post `temp\StartUpLog.txt`?
