### ISSUE TITLE
Predicted search has encountered an unknown error 

### ISSUE THREAD

**Issue by Kecupko** [PoE-TradeMacro/POE-TradeMacro#768]
Hello,
predicted search encounter an unknown error, when I want to know price of rare items (TradeMacro works fine with unique items, etc.). At same moment my friends has no problem, macro is working fine for them (tried price prediction on same item).
I found some topics about this, but they are already closed  and fixed (solution: poeprices.info API error).

temp\poeprice_log output:

Request and response:
{
    "added": {
        "browserUrl": "https://www.poeprices.info/api?l=Incursion&i=&w=1",
        "encodedData": "",
        "league": "Incursion",
        "requestUrl": "https://www.poeprices.info/api?l=Incursion&i="
    },
    "data": {},
    "error": 2,
    "status": 200
}

AHK version: 1.1.29.01
Windows version: Win 8.1

**Comment by Eruyome** [comment]
Sorry for the wait, took some time off.

There's information missing from the created URL, causing it not to work. Does this happen with every rare item?

**Comment by Eruyome** [comment]
https://github.com/PoE-TradeMacro/POE-TradeMacro/archive/dev.zip

This version writes a second debug log `poe_prices_debug_log.txt`. Please post it, I'll probably have to work on it but it's a start.

**Comment by Kecupko** [comment]
Yea, this happen with every rare item.

temp\poe_prices_debug_log.txt output:

Request and response:
{
    "EncodedItemata": "",
    "League": "Incursion",
    "RawItemData": "Rarity: Rare\r\nPlague Hold\r\nConjurer Gloves\r\n--------\r\nQuality: +20% (augmented)\r\nEnergy Shield: 49 (augmented)\r\n--------\r\nRequirements:\r\nLevel: 66\r\nStr: 105\r\nInt: 83\r\n--------\r\nSockets: R-R-R-B \r\n--------\r\nItem Level: 80\r\n--------\r\n+6 to maximum Energy Shield\r\n+87 to maximum Life\r\n3.2 Life Regenerated per second\r\n+63 to maximum Mana\r\n+45% to Fire Resistance\r\n+43% to Lightning Resistance\r\n"
}

**Comment by Eruyome** [comment]
- Make a search (rare item), then show me `temp\itemText.txt` (should contain the items data).
- Open a [windows console in the TradeMacro  main folder](https://superuser.com/questions/339997/how-to-open-a-terminal-quickly-from-a-file-explorer-at-a-folder-in-windows-7).
- Paste this to the console window and execute it `certutil -encode -f "%cd%\temp\itemText.txt" "%cd%\temp\base64ItemText.txt" & type "%cd%\temp\base64ItemText.txt"`

**Comment by Kecupko** [comment]
temp\itemText.txt output:

Rarity: Rare
Plague Hold
Conjurer Gloves
--------
Quality: +20% (augmented)
Energy Shield: 49 (augmented)
--------
Requirements:
Level: 66
Str: 105
Int: 83
--------
Sockets: R-R-R-B 
--------
Item Level: 80
--------
+6 to maximum Energy Shield
+87 to maximum Life
3.2 Life Regenerated per second
+63 to maximum Mana
+45% to Fire Resistance
+43% to Lightning Resistance

So I put that to the console window and executed it... Looks like I miss that command-line program
![vystrizek](https://user-images.githubusercontent.com/40704283/42421599-69188784-82d8-11e8-9b40-70765f73fd73.PNG)

Is it part of some microsoft's service package?

**Comment by Eruyome** [comment]
Please check whether `C:\Windows\System32\certutil.exe` exists.

**Comment by Kecupko** [comment]
Oh, so you just fixed my problem...It was just my own mess :)
Predicted search is working after adding C:\Windows\System32\  into PATH system variable.
Thanks for your help!

**Comment by Eruyome** [comment]
I'm surprised that it wasn't there to begin with...
