### ISSUE TITLE
TradeMacro doesn't see Incursion league

### ISSUE THREAD

**Issue by McDough** [PoE-TradeMacro/POE-TradeMacro#769]
Hi. I can't find Incursion league in the Settings suddenly. It looks like this 
![number1](https://user-images.githubusercontent.com/40870774/42345854-00f6e5d0-80a1-11e8-8a6a-7d35e2d1b47a.jpg)
It worked fine firstly when I downloaded it but now it shows only standard leagues. 

AHK version: 1.1.29.01
Windows version: 10

**Comment by aRTy42** [comment]
It is supposed to look like this, if you saw Incursion there you cought the macro at an odd time where the league transition/startup happened. "tmpstandard" is the generic name for the current 3 month league, in this case Incursion.

**Comment by McDough** [comment]
Oh, ok. Thank you.
