### ISSUE TITLE
1H mace vs sceptre

### ISSUE THREAD

**Issue by bobev18** [PoE-TradeMacro/POE-TradeMacro#770]
AHK version: 1.1.27.03 64bit version
Windows version: Win10 1803

When performing detailed search (Ctrl-Alt-D) on one handed maces like this
![det_srch](https://user-images.githubusercontent.com/321099/42408023-5038c800-81cf-11e8-8260-63f147fd405d.png)

returns no results. Apparently the some maces are listed as scepters on poe.trade. Opening the site, and manually switching the type does return results.

It will be nice if the search filter can pick on that and automatically adjust the type.

Thanks.

**Comment by aRTy42** [comment]
Something similar was fixed in v2.10.5 (18 days ago), after we also noticed that issue. We'll probably have to adjust the item class depending on the base name (meaning looking for "Sceptre", "Sekhem" and "Grinning Fetish")

**Comment by Eruyome** [comment]
That should have been fixed, I actually made a mistake (typo) though, causing not not to work.

**Comment by bobev18** [comment]
thanks
