### ISSUE TITLE
Trademacro giving false data

### ISSUE THREAD

**Issue by MacheteDontText** [PoE-TradeMacro/POE-TradeMacro#771]
Hi, 

Ever since Incursion started I m getting false data from trademacro, completely bogus prices and false results.

Just did a quick test on my brightbeak:

https://imgur.com/a/Q0VcAd4

I m running the latest version of both ahk, and trademacro, just reinstalled everything including PoE. I use Win 10 Pro 64, never had this problem before Incursion.

AHK version:1.1.29.01
Windows version: Win 10 Pro (1803)

**Comment by aRTy42** [comment]
It says in the very first line that you are searching "Hardcore", the permanent one.

Go to the settings menu and change the league setting to what you are actually playing. "tmpstandard" and "tmphardcore" are the generic names for the current league, so Incursion SC and Incursion HC.

**Comment by MacheteDontText** [comment]
Jeez, thanks a lot, I didnt have to do this with the former league, I didnt even know there was a settings :)
