### ISSUE TITLE
500 Internal Server Error on currency search

### ISSUE THREAD

**Issue by zealmanur** [PoE-TradeMacro/POE-TradeMacro#772]
When using any currency search request, getting following url content:

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">
<title>500 Internal Server Error</title>
<h1>Internal Server Error</h1>
<p>The server encountered an internal error and was unable to complete your request.  Either the server is overloaded or there is an error in the application.</p>

autohotkey: v1.1.29.01
Windows 7 x64

**Comment by zealmanur** [comment]
figured that need to be added &stock=& in search url to have results again

**Comment by nJoyAl** [comment]
How did you do that?

**Comment by Eruyome** [comment]
Fixed it locally, will release an update soon.

**Comment by Eruyome** [comment]
Update released.
