### ISSUE TITLE
Cant open Trade macro exe on Windwos 10

### ISSUE THREAD

**Issue by Eyke66** [PoE-TradeMacro/POE-TradeMacro#776]
Hello i install PoE on a new pc with windows 10 and when i try to open Trade Macro i cant click the exe it opens in word instead of exe
![untitled](https://user-images.githubusercontent.com/42174598/43772867-51137f1e-9a4c-11e8-8f64-f9c439699ae4.png)

please help me fix this

**Comment by aRTy42** [comment]
Make sure you have [autohotkey](https://autohotkey.com/) installed.

If you have that and it is still not working, right click Run_TradeMacro and select properties. In the first tab "General" it should say "Opens with:" almost at the top. The selection should be your autohotkey installation, in my case "AutoHotkey Unicode 64-bit". Fix that selection.

**Comment by Eyke66** [comment]
hat fixed my problem i reinstalled AutoHotkey 64 bit and it worked , thank you very much
