### ISSUE TITLE
Cant start trademacro

### ISSUE THREAD

**Issue by Exentraa** [PoE-TradeMacro/POE-TradeMacro#777]
get this 
![isss](https://user-images.githubusercontent.com/42556847/44369107-e4e8f480-a4dd-11e8-9fac-1351d3d5010c.png) 
already installed the latest versions

**Comment by aRTy42** [comment]
Did you unzip the whole download into a folder and keep the files together? If you only extracted some files or moved only the Run_TradeMacro file afterwards, the script won't find all its parts.

**Comment by Exentraa** [comment]
nope i unzipped all of them into one folder

**Comment by aRTy42** [comment]
Where is that folder located? Might there be an issue with file read access permissions? In particular the desktop and the `\Documents\` folder are candidates for trouble.

**Comment by Eruyome** [comment]
still an issue?

**Comment by AlexSchindler1** [comment]
Having same issue here no matter where i put it.

**Comment by Eruyome** [comment]
Do you guys have AHK 1.0.* installed?

```
AutoHotkey 1.1.* - previously known as AutoHotkey_L.
AutoHotkey 1.0.* - also retroactively known as AutoHotkey Basic, Classic, Vanilla, etc.
```

1.1.* and 1.0.* are fundamentally different and the version check seems to break when using the very old 1.0.* version.

**Comment by AlexSchindler1** [comment]
yea that worked thank you for the fast response ! :D
