### ISSUE TITLE
Can't Run Trade Macro

### ISSUE THREAD

**Issue by rbedsole** [PoE-TradeMacro/POE-TradeMacro#779]
When I click Run_TradeMacro.ahk I get this error window.
![capture](https://user-images.githubusercontent.com/39732557/44462054-daf7ec00-a5d8-11e8-8148-915f333dbfa8.PNG)

AHK version: v1.1.30.00
Windows version: Windows 10

**Comment by aRTy42** [comment]
For future reference, from discord:
> rbedsole:
> I figured it out it seems the issue was that it couldn't access some of the files in those folders since the default documents folder is in onedrive and it wasn't syncing

closing issue.
