### ISSUE TITLE
I'm trying to install this right now with the AHK, however, the script isn't running. It doesn't show on the tray. I tried running as admin doesn't work. I have windows 10.

### ISSUE THREAD

**Issue by ZainD31** [PoE-TradeMacro/POE-TradeMacro#781]

**Comment by ZainD31** [comment]
I downloaded the zip file and extracted everything to a different folder. I ran the new ahk program with the compiler. And then it created the Run_TradeMacro.exe. Still it doesn't show on the system tray.

**Comment by aRTy42** [comment]
Don't compile it into an exe, you should be able to run the Run_TradeMacro.ahk file when you have autohotkey installed. Double click should be enough if you checked an option during installation to link the .ahk ending to autohotkey. If not, right click the Run_TradeMacro.ahk file, select properties and set the program to run it with.

**Comment by ZainD31** [comment]
Nice! That worked! Thanks!!!
