### ISSUE TITLE
When launching Macro, claims it's launching from desktop when it isn't.

### ISSUE THREAD

**Issue by Z0MBIE2** [PoE-TradeMacro/POE-TradeMacro#784]
AHK version: Version 1.1.29.01
Windows version: Windows 10

When I launch the macro from my downloads folder, it gives me this error:
![image](https://user-images.githubusercontent.com/34387311/44948712-90ece280-adf0-11e8-8b76-a2f64e12f9c0.png)

Despite the fact it's located in D:\Users\User\New folder - Copy (2)\POE-TradeMacro

**Comment by Eruyome** [comment]
I'll look into it, for now try using some other folder.

**Comment by Eruyome** [comment]
Is this still an issue?

**Comment by Z0MBIE2** [comment]
Vers 2.10.9, no longer launches with the message. No issue, thanks!
