### ISSUE TITLE
CTRL + D not working because of missing files

### ISSUE THREAD

**Issue by nguyendang4242** [PoE-TradeMacro/POE-TradeMacro#786]
Whenever I try to use CTRL + D to price rare items, the following error pops up.

![image](https://user-images.githubusercontent.com/25260800/44959010-0e6e2c80-ae9d-11e8-836c-780c7dce955e.png)

I checked earlier threads, and it seems that the temp/ folder is missing some files. Here's a picture of my temp folder: 

![image](https://user-images.githubusercontent.com/25260800/44959054-93f1dc80-ae9d-11e8-9c3a-32366b2ab868.png)

AHK version: 1.1.130
Windows version: 10

**Comment by Eruyome** [comment]
This happend while using the "certuil" console command. I remembered an issue with that from a while ago, related to permission issues. https://github.com/PoE-TradeMacro/POE-TradeMacro/issues/637#issuecomment-357330503

I'm not sure whether that could be related here.

Try this:
Make a price check (rare item).
Open a windows console in the TM directory.
Paste this line into it:
```
chcp 1251 /f >nul 2>&1 & certutil -encode -f "%cd%\temp\itemText.txt" "%cd%\temp\base64ItemText.txt" & type "%cd%\temp\base64ItemText.txt" > temp\encodeToBase64.txt
```
Execute it and tell/show me what happens.

**Comment by nguyendang4242** [comment]
Here's what I get when I execute the command

![image](https://user-images.githubusercontent.com/25260800/45004926-67c18300-afa5-11e8-8f3c-8384f01dcdca.png)

**Comment by Eruyome** [comment]
So that works, do you always get that error/exception when using the macro?
I'm not sure yet why there would be an exception thrown...

**Comment by Eruyome** [comment]
Still an issue? I don't really know what else tho check atm.
