### ISSUE TITLE
[HUGE] Advanced search doesn't work with uniques (jewels?)

### ISSUE THREAD

**Issue by Aerinx** [PoE-TradeMacro/POE-TradeMacro#787]
When using advanced search with a unique it does not fill the unique's name, searching instead for items that have the checked properties with the same base item. I don't know what uniques are affected, tried it with three unique jewels, might only happen with jewels, worked right with a helmet. The bug could be exclusive to jewels. I already lost more chaos than I have because of this T_T

AHK version: 2.10.8
Windows version: Windows 10

**Comment by Eruyome** [comment]
Please tell me which jewels you tested.

**Comment by Aerinx** [comment]
Might and Influence, Growing Agony and Self-Flagellation.

**Comment by Aerinx** [comment]
Might and Influence, Growing Agony and Self-Flagellation.

**Comment by Eruyome** [comment]
Fixed. Update coming soon.

**Comment by Aerinx** [comment]
Great work, thank you.

**Comment by Eruyome** [comment]
Yeah should be closed then.
