### ISSUE TITLE
Trade Macro wont' launch

### ISSUE THREAD

**Issue by tuday2** [PoE-TradeMacro/POE-TradeMacro#788]
Gives error message when launching

![image](https://user-images.githubusercontent.com/27604078/45067453-f22ee300-b088-11e8-8e46-2e3259c6a822.png)

AHK version: 1.1.27.07
Windows version: Windows 10 PRO 1803 (17134.228)

**Comment by Eruyome** [comment]
As told in teh error meesage, there's a "StartUpLog.txt" file, post it here please.

**Comment by mauricioparaujo** [comment]
i am having this same issue, here is my "StartUpLog.txt". Thank you very much!

[StartupLog.txt](https://github.com/PoE-TradeMacro/POE-TradeMacro/files/2353618/StartupLog.txt)

**Comment by Eruyome** [comment]
The league parameter is missing from the url.
Can you check whether there's a league selected in the settings?
![image](https://user-images.githubusercontent.com/16058242/45210748-b7979700-b290-11e8-8129-9e38a3c6759e.png)

Also take a look at `%userprofile%\Documents\PoE-TradeMacro\config_trade.ini` and tell me what value the `SearchLeague` has.

**Comment by mauricioparaujo** [comment]
![1](https://user-images.githubusercontent.com/27684476/45218657-caa16b80-b27e-11e8-9161-7838f0007cd3.jpg)
![2](https://user-images.githubusercontent.com/27684476/45218658-caa16b80-b27e-11e8-9770-83e73ccbbc0f.jpg)

**Comment by faraddox** [comment]
Got same error today, can't start macro. Getting this error everytime i start trade macro after a few minutes.

**Comment by Eruyome** [comment]
Sorry for neglecting this for while.
Anyway @faraddox could you also post your startuplog.txt?
