### ISSUE TITLE
Toggle checkbox to clear all min/max values before searching in poe.trade

### ISSUE THREAD

**Issue by rhazor** [PoE-TradeMacro/POE-TradeMacro#791]
On CTRL+ALT+D add a checkbox to remove all min/max values for all mods before searching in poe.trade

Just like the toggle checkbox to tick/untick all mod boxes 'Check normal mods'.

**Comment by Eruyome** [comment]
There are options for that 
![image](https://user-images.githubusercontent.com/16058242/48318573-1a940a00-e603-11e8-9617-72d31a8a1be2.png)

Are these too limited for you because you want this functionality only situational?
