### ISSUE TITLE
[False Positive] Fallback.exe detected as Trojan:Win32/Ludicrouz.Q

### ISSUE THREAD

**Issue by RandomStuffAndCode** [PoE-TradeMacro/POE-TradeMacro#792]
PoE-TradeMacro version: 2.10.9
Windows version: Windows 10 1803

Fallback.exe is detected as Trojan:Win32/Ludicrouz.Q by windows defender

**Comment by aRTy42** [comment]
[False positive](https://www.virustotal.com/#/file/5f17c9bd520809c81525633b00600821a6c90ec477c61dc02523faf1396a3c31/detection).

If you feel more comfortable though you can simply delete the exe if you don't have issues with the regular Run_TradeMacro launch.

**Comment by Eruyome** [comment]
There's not really anything that I can do about that.
I have edited the title and will keep the issue open for a while.

As aRTy42 mentioned already, if anyone doesn't trust the file simply delete it/don't use it. As the name suggests it's an optional file.
