### ISSUE TITLE
Info window doesn't open in fullscreen mode and takes a few tries in windowed fullscreen

### ISSUE THREAD

**Issue by nikolaydyankov** [PoE-TradeMacro/POE-TradeMacro#796]
The last league I played was incursion and the following issues weren't happening:

- Fullscreen mode - info window doesn't open when pressing CTRL+C
- Windowed Fullscreen mode - info window sometimes opens blank, sometimes you can see only shadow, sometimes doesn't open at all. It can take 2-3 tries until it shows properly with the info inside it. It might also not show with the correct monospace font and as a result, the formatting can be a bit messy.

Windows 10 Pro
10.0.17134 Build 17134

AHK 1.1.26.00

**Comment by Eruyome** [comment]
- It can't work in fullscreen, that's normal.
- Please make a screenshot of those issues.

**Comment by darkwiz666** [comment]
I think he means something like this, since this is the issue I'm having. 
![Image of Issue](https://i.imgur.com/wRbDp1w.jpg)

**Comment by aRTy42** [comment]
Is this always the result, or only sometimes? If always, please check the options menu and take a look at the "ItemInfo" tab. Confirm in the GDI+ section that the values there make sense. If you have opacity 0 for the font for example, it will be completely transparent.

**Comment by darkwiz666** [comment]
Sorry for taking so long to reply, haven't been into PoE lately.
GDI+ section is at defaults (90% opacity | 10% transparent), ran the script as Admin just in-case it was something to do with access to system files or something : still 100% nothing in the window.

Mind you before I even started poking around with the in-game menu I wasn't having issues with the other menu that comes up with the feedback.

**Comment by Eruyome** [comment]
Please don't use the GDI tooltip, I'm working on a new tooltip solution, it still has it's issues but I'd rather not try solving anything GDI related for now since it may be replaced anyway.
