### ISSUE TITLE
Predicted search has encountered an unknown error

### ISSUE THREAD

**Issue by MarciLilac** [PoE-TradeMacro/POE-TradeMacro#797]
Anytime I try to look up a rare item I get this error, I've checked other threads for solutions but they didn't help me any

uniques work perfectly fine, just rares don't work at all

the output of my poeprices_log.txt is

Request and response:
{
    "added": {
        "browserUrl": "https://www.poeprices.info/api?l=Delve&i=&w=1",
        "encodedData": "",
        "league": "Delve",
        "requestUrl": "https://www.poeprices.info/api?l=Delve&i="
    },
    "data": {},
    "error": 2,
    "status": 200
}

AHK is at version 1.1.30.00
Win 10 Home

**Comment by Eruyome** [comment]
Have you also checked this thread here?
https://github.com/PoE-TradeMacro/POE-TradeMacro/issues/786

**Comment by MarciLilac** [comment]
I did not see that one, but it did help me figure out the issue, had nothing to do with the macro itself and all to do with a miner messing up cmd.exe

thanks, you helped me not just get the macro working but also get rid of a miner

**Comment by Eruyome** [comment]
You had an unintended/unknown miner on your system? Or something you used and forgot about?
