### ISSUE TITLE
Delve items randomly using currency popup window?

### ISSUE THREAD

**Issue by syd-h** [PoE-TradeMacro/POE-TradeMacro#800]
Up till yesterday I believe it was, the Delve fossils and resonators were using the unique item popup. Now they seem to be using the currency trading popup? Is this something we can force back to use the item search or is this something that poe.trade has changed and that got pushed to us? Having the item average price, trimmed mean, and median price was really damn helpful. 

Thanks as always.

**Comment by Eruyome** [comment]
Well, it is labeld as a currency, therefore Tm uses currency search and I believe that's fine.

I guess I could add something like average/median etc for currency also.
