### ISSUE TITLE
Explorer / Interface Freeze with TM

### ISSUE THREAD

**Issue by invoxone** [PoE-TradeMacro/POE-TradeMacro#801]
Hello together,

i have a new system since few weeks and installed POE with the TradeMacro.
My issue is that after some time (some price checks), the window from TM just freeze.
System is still working, Game running and all klickable, but my whole windows explorer does not respond to mouseclicks.

Only the alt+ctrl + del -> Taskmanager option works, after Taskmanager is open, trade macro works again. Tried older versions and newer versions. Windows is uptodate, System ist few weeks old and all hardwareparts tested (prime,crystalmark etc). Framework newest version and SystemFileCheck from windows with 0 errors.

AHK version: 2.10.8 / 2.10.9 (same issue)
Windows version: win 10 pro 64x

System:

Gigabyte Z370 Gaming 7 - op
I7-8570k
16GB - 3000mhz Vengance
500GB m2 Samsung 970 EVO
GForce GTX-970 
Software: only Razer Synapse and Steam ist running)

While these "interface freeze" there are no spikes at CPU/GPU/SSD/RAM. All with low to 0 utilization.

I am clueless and think of reinstalling the whole system - but jeah...dont really think this will help?

best ragards,

invox

**Comment by Eruyome** [comment]
I don't really know what to do or test here also... is it still an issue?

**Comment by invoxone** [comment]
Hey, not really - it was an issue with my windows10 installation. works fine again!

**Comment by invoxone** [comment]
Sadly i had to reinstall whole windows. Reinstall POE/Autohotkey/Drivers etc. wont help. I think maybe corrupted win10 installation or drivers, cause the system was freshly installed on the system.
