### ISSUE TITLE
"Buyout only" option

### ISSUE THREAD

**Issue by jusk64** [PoE-TradeMacro/POE-TradeMacro#82]
Seems like searches using Ctrl-Q have "buyout only" set to on by default.

IMO the default should be off. poe.trade itself defaults to off, and many players use the `~b/o` syntax regardless of their intention to accept haggling or not. Defaulting to on means hiding a lot of potential search results, which the user might not even know is happening if they don't check the search form after the fact.

I'd like to add a setting to the GUI. Is this something you might be working on already, or would you take a PR?

**Comment by Eruyome** [comment]
since I already have an other option to add I'll jsut do it myself.

**Comment by Eruyome** [comment]
Added on dev branch, will close this issue.
