### ISSUE TITLE
The following variable contains an illegal character: "cm-"

### ISSUE THREAD

**Issue by hitman718** [PoE-TradeMacro/POE-TradeMacro#821]
Worked great for years but recently got this error. Using latest release of macro and ahk 1.1 on w10. Did reinstall ahk.
The seperate item info part works but the trade part does not.

![poetrademacroerror](https://user-images.githubusercontent.com/45155982/48682732-cf847480-eb77-11e8-9bf5-29073fc9efcc.png)

**Comment by Eruyome** [comment]
Try deleting `%userprofile%\Documents\PoE-TradeMacro\CustomMacros`.

**Comment by hitman718** [comment]
Thank you very much! That worked.
