### ISSUE TITLE
Exception thrown {download}!

### ISSUE THREAD

**Issue by ThrillDaedra96** [PoE-TradeMacro/POE-TradeMacro#824]
I have been offline for a few days and when I got on today, I saw there was an update for the macro. I updated it and every time I start the macro, it brings up this error after some time.

![error](https://user-images.githubusercontent.com/26694386/48790347-20ea4c00-ecbd-11e8-8bcd-4861f6e8b08d.png)

It never did that to me before and I've never had to change the settings for the macro before.

AHK version: 2.11.1
Windows version: Windows 10 Home Build 17134.407

**Comment by Eruyome** [comment]
pathofexile.com and all of it's API are down. Will work again when that is up again.

**Comment by ErebusEtherie** [comment]
Can be closed, problems ended.
