### ISSUE TITLE
Cant find currency data

### ISSUE THREAD

**Issue by MrScavenger** [PoE-TradeMacro/POE-TradeMacro#825]
----------------------------------------------------------
2018-11-22T16:21Z
----------------------------------------------------------

Requesting currency data from poe.ninja...

cURL command:
"F:\Downloads\POE TRADE\lib\curl.exe" "https://poe.ninja/api/Data/GetCurrencyOverview?league=" -ILks --max-time 20 

Answer: HTTP/2 204 
date: Thu, 22 Nov 2018 16:20:58 GMT
set-cookie: __cfduid=d8634032ea3f0305c7695f3d89a1b1a311542903658; expires=Fri, 22-Nov-19 16:20:58 GMT; path=/; domain=.poe.ninja; HttpOnly; Secure
cache-control: public, max-age=900
expires: Thu, 22 Nov 2018 16:21:15 GMT
cf-cache-status: HIT
expect-ct: max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"
server: cloudflare
cf-ray: 47dcb9f9198fb635-TLL

The log.

I have the latest version of trade macro with windows 10 64bit

https://imgur.com/a/IPngfHl

**Comment by karantesh** [comment]
[StartupLog.txt](https://github.com/PoE-TradeMacro/POE-TradeMacro/files/2609058/StartupLog.txt)
Havin the same issue here, has been happening since yestarday, I think it is since I have changed league to delve

**Comment by MrScavenger** [comment]
Sold changed the drop down menu in "leauge" too "tmpstandard" and now it works

**Comment by Eruyome** [comment]
Yeah, change your league again (tmpstandard)

**Comment by miaXcova** [comment]
So tmpstandard is the new Delve league?

Delve is no longer in the list of available leagues:
![image](https://user-images.githubusercontent.com/13664277/48924403-aae51100-ee85-11e8-9cf2-6d28ac9c420d.png)
