### ISSUE TITLE
Include File Cant start script

### ISSUE THREAD

**Issue by FearethGaming** [PoE-TradeMacro/POE-TradeMacro#828]
![githubhelpreportimg](https://user-images.githubusercontent.com/45284694/48962329-70927700-ef4c-11e8-9161-85246b820dcb.PNG)

This is the second time ive downloaded this and i have this error showing up so i gave up. Honestly not sure which ahk i have downloaded currently i believe i started with one of the 1.0s and then tried 2.0s and i still get this error I'm assuming it's a fault on the download or something? Or if im just doing something wrong would definitely like some help in this issue.

**Comment by FearethGaming** [comment]
Update current ahk is 1.1.30.01 
Windows version is win 10

**Comment by Eruyome** [comment]
The version must be 1.1.*
Not 1.0.* and not 2.0.*

Normally that looks like a version issue but you're saying that you have the correct one.
How did you check your version though? Probably not by running a script like this here:

```
#SingleInstance, force
MsgBox % A_AhkVersion "`n" A_AhkPath
```

I'm asking because it's possible that you have multiple or "broken" AHK installations, executing the script by a different AutoHotkey.exe than you think.

The above script shows the correct version and executable path to make sure of it.

**Comment by FearethGaming** [comment]
Oh also no i did not run that script that you listed mainly because i have no idea how to.

**Comment by Eruyome** [comment]
Paste it into an .ahk file and just double click that.
Also, try moving your macro folder to somewhere else than your desktop.

**Comment by FearethGaming** [comment]
![autohotkey error](https://user-images.githubusercontent.com/45284694/48964376-d9d9b080-ef73-11e8-9e3a-4add9e488ad9.PNG)

Also moved the folder back to the downloads folder and it still comes up with the same error.

**Comment by Eruyome** [comment]
Are you sure that you copied that code correctly? It certainly works for me.

The `n is linebreak that is being added to the displayed message, instead it seems that your copied code breaks the line at that point? Breaking the one line into two?

You could use something like this avoiding the linebreak

```
#SingleInstance, force
MsgBox % A_AhkVersion "  -  " A_AhkPath

```

**Comment by FearethGaming** [comment]
Would it be weird to say that its still failing to read that same script you posted? Just copying it and pasting it into a script file and its not running it. Could this end up being a faulty ahk download?
