### ISSUE TITLE
Script causes all input to lag

### ISSUE THREAD

**Issue by ottodeluxe** [PoE-TradeMacro/POE-TradeMacro#832]
I have the same problems other users experienced, where the macro becomes unresponsive for up to several minutes, and in my case all input gets unresponsive as well. I cannot even kill AHK from the task manager, as alt + tab, ctrl + esc and others won't work for sometimes up to three minutes, either. I am using

AHK version: 1.1.30.00 64 bit
Windows version: Windows 10 Pro 10.0.17134 build 17134

At first I thought it might be related to my monitor setup and Windows DPI scaling (which is cause for grief in 80% of cases), but this time it seems to be something else. The dev build that fixed the issue for many people is in stable now, from what I've read. I also tried the DNS and IPv6 fixes from the FAQ to no avail.

I already has this problem in Delve, before Delve I never had any problems.
I have tried both the script and the exe, I have tried to run it with and without elevation, I'm at a loss.

edit: the curl test runs just fine and pretty much instantly. The problem starts after merging, when the script is initializing.

edit2: When I opened the script, it ran AHK.exe as it's supposed to, created up to three processes and did something, and finally killed its child processes and was marked as "suspended" in the task manager. After that, my cursor moves roughly 20 px per second and all input (most notably mouse input) is delayed by 10-20s until I manage to kill AHK.exe

**Comment by Eruyome** [comment]
Huh, that's really weird. 

I'd guess it's some issue with your AHK installation and windows, I can try to think of ways to debug this but I don't expect that anything substantial will happen soon.

I'd like to say try reinstalling windows but that's a lot to ask for... I do know of cases, maybe not when having this exact issue where a reinstall was the solution.

**Comment by ottodeluxe** [comment]
I've been tinkering around in the mean time, and I have found out a handful of things:
1. While it is this script that's affected, and other scripts run just fine, I think it is probably related to other programs/tools that are run during init.
2. After some trial and error, I managed to find a convoluted way to get it to work: I've known before that you can resume suspended tasks via the resource monitor. However, this would only close/crash the script for me. If I am fast enough to resume it, however, it does run normally afterwards. So I have to have everything ready and in place as soon as I run the trade macro.

So yeah, I agree it's my windows, in some weird fashion. A lot of people are affected by Windows randomly suspending tasks. I just wonder what caused it in the first place, must have been a borked Wnidows update, which can't get fixed by DISM.

I'm going to close this issue, since the problem is not directly script related, but rather lies somewhere else and just manifests here.
