### ISSUE TITLE
PoePrices.info Not Opening!

### ISSUE THREAD

**Issue by potasium56** [PoE-TradeMacro/POE-TradeMacro#838]
Not sure why this is happening, but when using CTRL - D and clicking open in poeprices.info it opens the windows in new tab but it doesn't search the item the webpage is just white blank.....Just wanted to let you know

**Comment by AdditionalTesting** [comment]
Getting the same thing. Maybe something wrong with the API request to poeprices.info

**Comment by potasium56** [comment]
You guys are probably right....

**Comment by Eruyome** [comment]
They had to upgrade their servers, expecting double the bill for that this month. Too many players/users.
