### ISSUE TITLE
Error launching

### ISSUE THREAD

**Issue by Remo888** [PoE-TradeMacro/POE-TradeMacro#839]
i have tried deleting both auto hotkey and poe trade macro, then downloaded latest version but still receiving errors. please help
![capture](https://user-images.githubusercontent.com/45729618/49712987-dc464500-fcab-11e8-9cc9-7a3638c20edb.PNG)

**Comment by Eruyome** [comment]
Properly extract the zip archive and don't run it from anywhere in that folder from the message.

**Comment by Eruyome** [comment]
Please reply if this is still an issue. Closed until then.
