### ISSUE TITLE
CTRL + C on map is not accurate

### ISSUE THREAD

**Issue by captaincbr** [PoE-TradeMacro/POE-TradeMacro#842]
The information for map upgrades is inaccurate. It is still using patch 3.4 atlas data. Map produced by, upgrades to, and divination card needs to be updated.

Fill out everything that may be relevant and remove everything except these informations below:  

AHK version: 2.12.2
Windows version: 10

**Comment by Eruyome** [comment]
Yeah, I know, will have to fix that soon.
