### ISSUE TITLE
Keep getting server api error

### ISSUE THREAD

**Issue by crysty1810** [PoE-TradeMacro/POE-TradeMacro#843]
![aaaaaaa](https://user-images.githubusercontent.com/45845307/49928976-0b3a0200-feca-11e8-96a0-800194fde00b.PNG)
I keep getting this error from the start of the league, i have windows 10 and the latest version of trademacro.

**Comment by Eruyome** [comment]
Please upload the file `<trademacro folder>\temp\StartupLog.txt`.
