### ISSUE TITLE
Anti-virus is having a complaint

### ISSUE THREAD

**Issue by Lward53** [PoE-TradeMacro/POE-TradeMacro#845]
AHK version: 1.1.30.01
Windows version: 10 (latest update.)

My antivirus has decided it doesn't like a new file. Gen:Suspicious.Cloud.4.2D0@aGtXNLoi 
Fallback.exe.

However everything seems to be working okay despite it blocking the file entirely.

**Comment by Eruyome** [comment]
https://github.com/PoE-TradeMacro/POE-TradeMacro/issues/819
