### ISSUE TITLE
Run_TradeMacro.ahk fail to launch

### ISSUE THREAD

**Issue by Xalorous** [PoE-TradeMacro/POE-TradeMacro#847]
AutoHotkey v1.1.26.01
Windows 10
POE-TradeMacro was latest master as of 12-16-2018

    Error at line 2110.
    #include file "D:\POE-TradeMacro\data\MapList.txt" cannot be opened.
    The program will exit.

I unzipped the archive.  
Then ran the Run_PoeTradeMacro.ahk file.
The macro creates a new folder called backup, then throws that error.
During the creation of the backup folder it "eats" the data folder.
I copied the data folder in again and repeated.  Same result.
Same result when I reextracted to a different location.
Same result when I reextracted to another location and set permissions to Full for authenticated users.

**Comment by Eruyome** [comment]
Are you talking about the `<TM foldername>_backup` folder?

I know of a `<TM foldername>\backup` folder but that one gets created by my IDE, not the script itself so a normal users shouldn't have that.
And I don't know why the script would "eat" the data folder. Doesn't make sense in any way.
Is your system interfering here in some way? A drive that is being synched or some security suite shenanigens?

**Comment by Xalorous** [comment]
If I unzip in the downloads folder, as is, resulting in the files being
created in `<profile>\Downloads\POE-Trade-Master\Poe-Trade\`, then the
macro runs successfully, creating the backup folder in the same folder as
the data folder.  Trying to unzip the archive into any other location
results in the behavior I listed.  Regardless of security.  Interestingly
enough, my profile is redirected to a NAS, and the location I want the
folder to be is on a local drive (D:\).

Two things I'd recommend you look into.  From my experience as a systems
engineer/systems administrator, this type of behavior is result of either:

1. Some sort of explicit path in the part of the script that backs up the
data.  Or,
2. The data folder being removed implies a folder deletion as part of the
backup.  This is a "Bad Idea".

**Comment by Eruyome** [comment]
There shoudn't be any backup of anything unless you're updating the script through the update function. 
This update would make a copy of the current TM folder before it deletes it's contents and copies the new files over (those are being extracted to windows temp folder beforehand).

There are enough checks in place to make sure nothing goes wrong here and I haven't had any complaints in ages.

I'm still confused about the backup folder that you're talking about. Please show me: 

- This backup folders full path
- The macros folders full path.
