### ISSUE TITLE
Remaining hotkey types in the wrong command

### ISSUE THREAD

**Issue by SigPog** [PoE-TradeMacro/POE-TradeMacro#848]
Using the additional macros tab,  and turning on the hotkey for "Remaining" inputs &remaining instead of /remaining to the in-game chat.

AHK version: Most recent as of 18. December 2018
Windows version: Most recent as of 18. December 2018

**Comment by Eruyome** [comment]
What keyboard layout do you have (language)?

**Comment by SigPog** [comment]
I have a Norwegian keyboard layout, meaning qwerty + æøå. This wasn’t an
issue before

**Comment by Eruyome** [comment]
Could you also test the hotkeys `WhoisLastWhisper`,`JoinChannel`,`KickYourself`?

**Comment by Eruyome** [comment]
Please reply if you still have an issue, I can't debug this by myself. Closed until then.
