### ISSUE TITLE
"Parsing the league data (Json) from path of Exile API Failed

### ISSUE THREAD

**Issue by KMSKyle** [PoE-TradeMacro/POE-TradeMacro#851]
Hello, I've spent 6 hours searching similar issues and absolutely NONE of the solutions I found worked for my situation. 

It seems to be that POE.Trade or Pathofexile.com is running cloud-flare now and the captcha is blocking my macro from connecting? 

It was working fine yesterday and absolutely nothing has changed on my end. 

I've tried asking in the Path of Exile community chats and nobody else seems to have this issue. 

"Parsing the League data (json) from the Path of Exile API failed. This should only happen when the servers are down fo rmaintenance. The Script execution will be stopped, please try again at a later time". 

I have no experience at editing these sorts of files either so editing them in word doesn't seem like it's the correct approach. 

I've tried clearing all of my cookies on both internet explorer AND chrome - I've tried disabling adblocker, disabling my fire-wall, disabling my virus software, adding poe.trade/poe.ninja/pathofexile.com all to safe sites.. Nothing has worked.

I appreciate your time!

Thank you for your help.

AHK version: Current as of Dec 19 2018
Windows version: Windows 10 64x

**Comment by Eruyome** [comment]
Upload `<TM folder>\temp\currentLeagues.json` here and then delete it. Restart the macro.

**Comment by Eruyome** [comment]
Please reply if you still have any issue. Closed until then.

**Comment by pandaroc** [comment]
Got the same problem since yesterday. DEleting the json didn't work. Any idea?

[currentLeagues.txt](https://github.com/PoE-TradeMacro/POE-TradeMacro/files/2974188/currentLeagues.txt)
