### ISSUE TITLE
Search on official site over poe.trade

### ISSUE THREAD

**Issue by d07RiV** [PoE-TradeMacro/POE-TradeMacro#852]
Is it possible to use official site instead of poe.trade for item search, or at least for Alt+Q? I think a lot of people prefer its design, and especially performance over the last few days.

**Comment by TheSixStringSamurai** [comment]
I would love this feature as well to either use official or poe app as defaults instead of poe trade. Sadly poe trade has become mostly obsolete at this point, doesn't maintain mods/features enough.

**Comment by aRTy42** [comment]
This gets requested a lot and we would like to switch to the official site, but that requires to rewrite a lot of code. Even though the sites offer basically the same options, there are many small differences in the details. We can't just switch out the URL.
