### ISSUE TITLE
Windows Defender Flagging Fallback.exe as Trojan:Win32/Zpevdo.B

### ISSUE THREAD

**Issue by Heekzy** [PoE-TradeMacro/POE-TradeMacro#855]
Just opened the trademacro today and was immediately met with a windows defender alert flagging it for having a trojan.
Should I be worried?

Documents\POE-TradeMacro-2.12.2\Fallback.exe
is flagged as "Trojan:Win32/Zpevdo.B" 

Windows 10

**Comment by aRTy42** [comment]
No, the false-positive with AHK and the .exe file in particular is often an issue. You can delete the fallback.exe if you want (it is only there for people who can't launch the macro with the regular "Run_TradeMacro.ahk" file). Alternatively you can also download the "noExe" zip variant, where the exe file is not included to begin with.

**Comment by Eruyome** [comment]
https://github.com/PoE-TradeMacro/POE-TradeMacro/issues/854#issuecomment-450368608
