### ISSUE TITLE
TradeMacroMain.ahk

### ISSUE THREAD

**Issue by rzp94** [PoE-TradeMacro/POE-TradeMacro#856]
Everything was fine to this date.
When I turned on computer today, I am getting error while trying to launch script.
![macro error](https://user-images.githubusercontent.com/45788333/50426875-2a0ca100-0899-11e9-8ab0-e350024c6a6d.png)

it seems to be problem with this:
![macro error 2](https://user-images.githubusercontent.com/45788333/50426884-63451100-0899-11e9-9c5c-47a0002253c1.png)

Tried deleting it, but it appears again after trying to launch a script.

Would be very grateful for your help and response.

**Comment by rzp94** [comment]
I closed the thread because script started working, but today same problem occurred.

**Comment by Eruyome** [comment]
It should appear again, but I'm not sure why it's broken.

Is there aynthing weird about the file? Some encoding issues, weird characters, missing text?

**Comment by n1emad** [comment]
I've been getting this error also, I have attached the file you requested. 



[_TradeMacroMain.zip](https://github.com/PoE-TradeMacro/POE-TradeMacro/files/2718106/_TradeMacroMain.zip)

**Comment by Eruyome** [comment]
@n1emad Can you also show me your `%userprofile%\PoE-TradeMacro\CustomMacros\customMacros_example.txt`?

**Comment by n1emad** [comment]
Here is the requested file

[customMacros_example.zip](https://github.com/PoE-TradeMacro/POE-TradeMacro/files/2719255/customMacros_example.zip)

**Comment by Eruyome** [comment]
I couldn't really solve the issue in the sense that I can detect and fix a broken file (or one with invalid code) but I have improved error handling when the script crashes/can't launch.

The new error feedback window suggests a few solutions, for example deleting the custom macros file.
https://cdn.discordapp.com/attachments/286188925998071809/531922859912593409/unknown.png
