### ISSUE TITLE
Cant type @ ingame when Trademacro is running

### ISSUE THREAD

**Issue by BrockRiefenstahl** [PoE-TradeMacro/POE-TradeMacro#858]
I cant type (german layout) ALT GR (should be right alt key on US layout)  + Q (that is @ sign).
When I close the  Macro it works fine again! Is there a fix for this?

AHK version: V2.12.2
Windows version: Win 7 Ultimate

**Comment by aRTy42** [comment]
That was a short-term issue for a week, from 2nd March to 10th March ([notes](https://github.com/PoE-TradeMacro/POE-TradeMacro/releases/tag/v2.7.7)):

> Changed the default hotkey for the function to open items on peoapp to "ctrl + shift + q" since using "ctrl + alt + q" prevented typing the @ character on some keyboard layouts. You have to manually change your hotkey in the settings though if you have that issue currently.

Launch your macro and open the options menu (double click the black trademacro icon once the macro is fully loaded). On the first tab on the right hand side there should be several hotkeys listed and "Search (poeapp.com)" is probably still set to "ctrl + alt + q" for you, which effectively blocks the @ sign. Click into that field and press Ctrl+Shift+Q to rebind that function.

**Comment by BrockRiefenstahl** [comment]
Ahh **_thanks a lot_**. If I would have checked longer, I could have find that myself. Dumb me :D
