### ISSUE TITLE
Critical permission error with firewall disabled

### ISSUE THREAD

**Issue by dikketante** [PoE-TradeMacro/POE-TradeMacro#860]
Hi i read the wiki and FAQ i've tried multiple thing such as fully disabling my windows defender firewall, the fallback program works but i'd rather use autohotkey. I have exactly the same issue as Fone-Bone (who posted about it on 23th of may), however adding an exeption to my firewall does not seem to solve the issue.

**Comment by Eruyome** [comment]
I'm sorry but I'm not sure which issue you are referecning, do you have a link for me?

**Comment by dikketante** [comment]
https://github.com/PoE-TradeMacro/POE-TradeMacro/issues/685 This thread

**Comment by Eruyome** [comment]
I'm still confused, a firewall only monitors network traffic which shouldn't be an issue with TM. So far security suite issues where related to them blocking AHK/fallback.exe/curl.exe because of potential risks related to trojans/viruses/keyloggers. We are not talking about any firewall here, straight up antivir/anti malware software.

I've never seen a network traffic blocking issue before.

**Comment by dikketante** [comment]
Maybe this will help? i'm pretty sure i'm explaining it wrong, but these are the errors i get. Firstly i get the CM_executecustommacroscode_label error and then when i make a PoE-trademacro folder and copy the custommacros folder from the resources folder and paste it into the poe-trademacro folder i get the critical permission error.



![trademacro error](https://user-images.githubusercontent.com/46243576/50612667-0ec61500-0edb-11e9-85ee-fd539024a0bd.png)
![critical permission error](https://user-images.githubusercontent.com/46243576/50612670-138ac900-0edb-11e9-88a3-a6186b3c5905.png)

**Comment by Eruyome** [comment]
Yeah, your firewall wouldn't be involved here. Please tell me what security software you ahve. You must have more than just windows defender, like BitDefender, Avira Antivir, McAffee etc..

**Comment by dikketante** [comment]
Nope no other anti-virus software is enabled. I only use windows defender and a vpn, but it was disabled when installing the macro files and auto hotkey. i did use avira over a year back but i'm pretty sure i formated both drives and reinstalled windows since.

**Comment by Eruyome** [comment]
Did you find anything?

Btw, your path `G:\Documents\` seems weird. Shouldn't it be `G:\Users\%username%\Documents`?
I know that you can move some system folders to different locations/drives but I never tried only moving one of the subfolders with the user folder. Not sure whether that can be the cause of any issues.

AHK seems to identify the documents folder correctly by reading system variables.
