### ISSUE TITLE
Assertion Failure: ParseMapTier: couldn't parse item data chunk

### ISSUE THREAD

**Issue by bwood0** [PoE-TradeMacro/POE-TradeMacro#861]
**General Information**
* AutoHotkey Version 1.1.30.01 (64 bit)
* Windows 10

**Bug details**
When using Price Check (CTRL+D) on the item below I get an Assertion Failure, ParseMapTier: couldn't parse item data chunk, and the macro crashes. I then need to run the .ahk file again to start the macro back up. I linked the item in general chat, and other people confirmed that it was crashing their macro as well. CTRL+C crashes the macro as well.

**Item information**
```
Rarity: Magic
Jagged Maple Round Shield of Mist
--------
Chance to Block: 23%
Armour: 88
Evasion Rating: 88
--------
Requirements:
Level: 39
Str: 52
Dex: 52
--------
Sockets: R-G-B 
--------
Item Level: 81
--------
180% increased Block Recovery
--------
2% chance to Dodge Attack Hits
Reflects 28 Physical Damage to Melee Attackers
```

**Outro**
I'll stash the item for awhile in case anyone needs it for testing purposes, just in case.

**Comment by Eruyome** [comment]
Fixed locally, will be released soon.
