### ISSUE TITLE
Why does this box keep showing up?

### ISSUE THREAD

**Issue by rushtothesun** [PoE-TradeMacro/POE-TradeMacro#863]
https://puu.sh/Cpp8o/6863c699f9.png

Pressing CTRL + ALT + D on a Steel Ring and only checking ilvl and item base. When it searches that's what shows up. Happens with a lot of other items too. It either goes away when I Ctrl + C something or it crashes.

```
Rarity: Normal
Steel Ring
--------
Requirements:
Level: 80
--------
Item Level: 83
--------
Adds 4 to 12 Physical Damage to Attacks
```

**Comment by Eruyome** [comment]
Go into your settings and disable "GDI+ tooltip". That's a bug that I haven't figured out yet and maybe never will. I'm looking into other better tooltip solutions.

**Comment by rushtothesun** [comment]
> 
> 
> Go into your settings and disable "GDI+ tooltip". That's a bug that I haven't figured out yet and maybe never will. I'm looking into other better tooltip solutions.

I'll just deal with it. I like the coloring theme too much to give it up.
