### ISSUE TITLE
Map Mod Warnings, failure to identify affixes correctly. 

### ISSUE THREAD

**Issue by HiPoEGH** [PoE-TradeMacro/POE-TradeMacro#864]
AHKx64: 1.1.26.01
Windows 7 x64
Script Version: v2.12.1 noExe

Script fails to find certain mods like elemental weakness, player less recovery, extra damage, vulnerability, minus max resistances.

I'm assuming it's because of this line #4582:
`If (Count_DmgMod >= 1.5)`

I can manually change it but I'd rather not. Perhaps allow users to configure a threshold in the future?

MapMod User config file:
`[Affixes]
; To disable/enable the entire MapModWarnings functionality use the ItemInfo Settings menu.
MultiDmgWarning=1
EleReflect=1
PhysReflect=1
NoLeech=1
NoRegen=1
LessRecovery=1
TempChains=1
Vulnerability=1
Enfeeble=0
EleWeakness=1
Beyond=0
ManyTotems=0
BurningGround=0
ChilledGround=0
DesecratedGround=1
ShockingGround=1
PlayerDodgeMonstAccu=0
PlayerEleEquilibrium=0
PlayerLessAoE=0
PlayerPointBlank=0
PlayerReducedBlockLessArmour=0
PlayerReducedFlaskCharge=0
PlayerReducedMaxRes=1
BossDmgAtkCastSpeed=1
BossLifeAoE=0
BossTwinned=1
MonstAvoidElementalAilments=0
MonstAvoidPoisonBlindBleed=0
MonstCauseElementalAilments=0
MonstChaosEleRes=0
MonstCritChanceMult=1
MonstExtraEleDmg=1
MonstHexproof=0
MonstHitsIgnite=1
MonstHitsPoison=1
MonstIncrAoE=0
MonstIncrDmg=1
MonstLessCurse=0
MonstMagicBloodlines=0
MonstMoreLife=0
MonstMoveAtkCastSpeed=0
MonstNotSlowedTaunted=0
MonstNotStunned=0
MonstPhysDmgReduction=0
MonstRareNemesis=0
MonstSkillsChain=1
MonstTakeReducedCritDmg=0
MonstTwoAdditionalProj=1`

**Comment by aRTy42** [comment]
The line with `If (Count_DmgMod >= 1.5)` is only about adding another warning when lots of damage mods appear together, it should not interfere with selected mods at all.

Do you have the whole functionality enabled (Options -> "ItemInfo" tab -> top left area)?

That user file is the one from `\Documents\POE-TradeMacro\`, not from `\<Main Script Folder>\resources\default_UserFiles`, right?

In case you just enabled certain mods in the file, did you save it and restart the script?

**Comment by Eruyome** [comment]
Please reply if there is still an issue, until then I'll close it.
