### ISSUE TITLE
Problem Installing POE trade macro

### ISSUE THREAD

**Issue by Chadtrute** [PoE-TradeMacro/POE-TradeMacro#865]
_TEMPLATE_ (Remove the explanations here from your post) 

Make sure:
* That you have checked the Wiki/FAQ before creating any issue.
* That poe.trade/GGG's website don't have any issues if loading the script takes too long or failes.

Information to include:
* AHK (including 32/64bit) version if you have any kind of script errors.
* Windows version could be relevant.

Fill out everything that may be relevant and remove everything except these informations below:  

AHK version:
Windows version:

**Comment by Chadtrute** [comment]
I installed Auto Hotkey. (it's not showing up in my system tray)
then I download the zip file for Poe Trade macro it auto unzipped into my download folder.
I tried clicking on the  run trademacro.ahk file (symbol of internet explore before .ahk file doesn't' seem right)
then a box pops up for (View and track your downloads) asking me to open or save I do either and it does nothing.

1. how do I know if my auto hotkey program is running or installed?
2. can someone PLEASE HELP been trying for a couple of days now to figure out why it's not working. and followed all the steps given.

**Comment by Eruyome** [comment]
You don't have the .ahk file associated with autohotkey, meaning you probably didn't correctly install AHK. 

Maybe you just have to [manually associate](https://www.digitaltrends.com/computing/how-to-change-file-associations/) the correct application (the autohotkey.exe in the autohotkey installation folder).

**Comment by Eruyome** [comment]
Please reply if this is still an issue, until then I'll close it.
