### ISSUE TITLE
"Update" button doesn't work.

### ISSUE THREAD

**Issue by Asday** [PoE-TradeMacro/POE-TradeMacro#866]
Make sure:
* [x] That you have checked the Wiki/FAQ before creating any issue.
* [x] That poe.trade/GGG's website don't have any issues if loading the script takes too long or fails.

Fill out everything that may be relevant and remove everything except these informations below:  

AHK version: 1.1.30.00 x64
Windows version: 10

-----

The macro runs on system startup, and checks for an update.  It finds one, I click "Update", a window saying "downloading zip" appears, then I get a UAC dialog to allow the program to make changes to my computer.  I allow it, the macro closes, and does not reopen.  `_TradeMacroMain.ahk` is modified, (along with possibly the contents of `temp\`), but running the trade macro again shows me the update dialog again, saying I'm on 2.12.1, and 2.12.2 is available.

My macro is installed at `C:\Users\Asday\PoE Trade Macro\`.

The issue is """resolved""" by deleting and redownloading PoE Trade Macro.  (Obviously, because it's the new version).  When a new version is released, however, the issue resurfaces.

**Comment by Pegoth** [comment]
I have the same problem, tried to remove the settings from the documents and downloaded an older version and extracted it to a new folder to see if a "fresh install" fixes it, but it doesn't. Also tried to disable anti virus to see if that's the culprit, but nope.

When I click update it just crashes after a few seconds, this is the error message: https://i.imgur.com/DPzjLHc.png

**Comment by Trisscar05** [comment]
Same issue, stuck on 2.5.4 ( yes I know I haven't played in a while so sue me XD ), keeps asking to update to 2.13.1, appears to be successful, runs after, but once I start it up again it again asks.
Click on it, goes through "Uninstalling battle.net" sequence (lel), brings up a window saying MapModwarnings, config_trade, and config.ini were changed. Hit close, everything seems to work if being a bit slow.
Rightclicking on the icon in taskbar and saying "About" causes an error of "Invalid or nonexistant owner or parent window. Specifically: owner1" Also "Current thread will exit".
Check for Updates appears to be nonfunctional.
Show Update notes seems to be up to date with 2.13.1

Haven't tried wipe/redl yet, will do so soon.

**Comment by Eruyome** [comment]
Do that please, just remove all files and download the release zip manually.
