### ISSUE TITLE
Can't disable "Get currency ratio note" hotkey permanently.

### ISSUE THREAD

**Issue by Asday** [PoE-TradeMacro/POE-TradeMacro#867]
Make sure:
* [x] That you have checked the Wiki/FAQ before creating any issue.
* [x] That poe.trade/GGG's website don't have any issues if loading the script takes too long or failes.

Fill out everything that may be relevant and remove everything except these informations below:  

AHK version: 1.1.30.00 x64
Windows version: 10

-----------------

Get currency ratio note, bound to Alt+R by default, forgets that I've disabled it every time I restart the macro.  This has messed me up a few times, as I place my main skill on R, and occasionally hold Alt to see stuff on the ground I've missed.

**Comment by Eruyome** [comment]
Are any other settings also affected?

**Comment by Asday** [comment]
Nope, hence filing this as the same issue.

I don't believe there to be any permissions issues, as the directory I've installed to is owned by my account.  I did that because the macro refused to run without elevation when installed to `Program Files`...  😕

**Comment by dsnvwlmnt** [comment]
I have this issue as well. All other settings are correctly remembered and bug-free.
v2.14.1
ahk v1.1.28.02

![image](https://user-images.githubusercontent.com/14173022/55036169-001d6480-4fd7-11e9-90aa-48433a8a2ae0.png)
![image](https://user-images.githubusercontent.com/14173022/55036177-04498200-4fd7-11e9-9476-7916d8280207.png)

**Comment by Eruyome** [comment]
Closed because the issue is so old. Feel free to message again if the issues still persist.

**Comment by dsnvwlmnt** [comment]
Seems good now.
