### ISSUE TITLE
Price Checking rares

### ISSUE THREAD

**Issue by ghost** [PoE-TradeMacro/POE-TradeMacro#868]
Started out fine price checking rares and then this error came up.

Request and response:
{
    "added": {
        "browserUrl": "https://www.poeprices.info/api?l=Betrayal&i=UmFyaXR5OiBSYXJlDQpNaXJhY2xlIEJpbmQNClN0eWdpYW4gVmlzZQ0KLS0tLS0tLS0NClJlcXVpcmVtZW50czoNCkxldmVsOiA2NA0KLS0tLS0tLS0NClNvY2tldHM6IEEgDQotLS0tLS0tLQ0KSXRlbSBMZXZlbDogODYNCi0tLS0tLS0tDQpIYXMgMSBBYnlzc2FsIFNvY2tldA0KLS0tLS0tLS0NCjI3JSBpbmNyZWFzZWQgRmlyZSBEYW1hZ2UNCisyOCB0byBtYXhpbXVtIExpZmUNCisxMiUgdG8gRmlyZSBSZXNpc3RhbmNlDQorMzQlIHRvIENoYW9zIFJlc2lzdGFuY2UNCjI3JSBpbmNyZWFzZWQgRWxlbWVudGFsIERhbWFnZQ0KMzYlIGluY3JlYXNlZCBFbGVtZW50YWwgRGFtYWdlIHdpdGggQXR0YWNrIFNraWxscw0K&w=1",
        "encodedData": "UmFyaXR5OiBSYXJlDQpNaXJhY2xlIEJpbmQNClN0eWdpYW4gVmlzZQ0KLS0tLS0tLS0NClJlcXVpcmVtZW50czoNCkxldmVsOiA2NA0KLS0tLS0tLS0NClNvY2tldHM6IEEgDQotLS0tLS0tLQ0KSXRlbSBMZXZlbDogODYNCi0tLS0tLS0tDQpIYXMgMSBBYnlzc2FsIFNvY2tldA0KLS0tLS0tLS0NCjI3JSBpbmNyZWFzZWQgRmlyZSBEYW1hZ2UNCisyOCB0byBtYXhpbXVtIExpZmUNCisxMiUgdG8gRmlyZSBSZXNpc3RhbmNlDQorMzQlIHRvIENoYW9zIFJlc2lzdGFuY2UNCjI3JSBpbmNyZWFzZWQgRWxlbWVudGFsIERhbWFnZQ0KMzYlIGluY3JlYXNlZCBFbGVtZW50YWwgRGFtYWdlIHdpdGggQXR0YWNrIFNraWxscw0K",
        "encodingError": "",
        "league": "Betrayal",
        "requestUrl": "https://www.poeprices.info/api?l=Betrayal&i=UmFyaXR5OiBSYXJlDQpNaXJhY2xlIEJpbmQNClN0eWdpYW4gVmlzZQ0KLS0tLS0tLS0NClJlcXVpcmVtZW50czoNCkxldmVsOiA2NA0KLS0tLS0tLS0NClNvY2tldHM6IEEgDQotLS0tLS0tLQ0KSXRlbSBMZXZlbDogODYNCi0tLS0tLS0tDQpIYXMgMSBBYnlzc2FsIFNvY2tldA0KLS0tLS0tLS0NCjI3JSBpbmNyZWFzZWQgRmlyZSBEYW1hZ2UNCisyOCB0byBtYXhpbXVtIExpZmUNCisxMiUgdG8gRmlyZSBSZXNpc3RhbmNlDQorMzQlIHRvIENoYW9zIFJlc2lzdGFuY2UNCjI3JSBpbmNyZWFzZWQgRWxlbWVudGFsIERhbWFnZQ0KMzYlIGluY3JlYXNlZCBFbGVtZW50YWwgRGFtYWdlIHdpdGggQXR0YWNrIFNraWxscw0K"
    },
    "failed": "ERROR: Parsing response failed, invalid JSON! "
}

**Comment by Darthelmet** [comment]
Getting the same problem. It worked for a while, then this started happening. Once it started happening the only fix was to restart computer, but it very quickly went back to having the problem, so this clearly isn't a good fix.

**Comment by Eruyome** [comment]
https://github.com/PoE-TradeMacro/POE-TradeMacro/issues/872

See this.
