### ISSUE TITLE
Price prediction not working since yesterday

### ISSUE THREAD

**Issue by Slider2019** [PoE-TradeMacro/POE-TradeMacro#870]
When I try to predict an item price on web and i click on "Open on poeprices.info" a chrome tab opens with the following error message: "Access Denied, you dont have permission to view this page. HTTP Error 403". This happened to me since yesterday. Im using the latest release v2.12.2.

**Comment by Eruyome** [comment]
https://github.com/PoE-TradeMacro/POE-TradeMacro/issues/872

See this.
