### ISSUE TITLE
Zip folder empty when i download it.

### ISSUE THREAD

**Issue by fuhqoff** [PoE-TradeMacro/POE-TradeMacro#871]
When I download the macro from Github, and attempt to extract files with 7zip, the zip file is empty. Therefore nothing to extract. I am downloading the top line.

POE-TradeMacro-2.12.2.zip
3.42 MB
Empty every single time i download it. Also, when i attempt to run AHK installer, my computer asks me if I'd like to run it with notepad... Am i missing some sort of software that would ordinarily run the installer?

**Comment by aRTy42** [comment]
Try the "POE-TradeMacro-2.12.2_noExe.zip"

The AHK installation should be from [here](https://www.autohotkey.com/download/), the light blue download button. That should give you a file named "AutoHotkey_1.1.30.01_setup.exe". I'd hope that your computer doesn't open .exe files with notepad.

**Comment by fuhqoff** [comment]
"Try the "POE-TradeMacro-2.12.2_noExe.zip""  Ok if i download the no EXE, how will i execute the program?

And the only option my computer is giving me to open the ahk installer is literally notepad. What does your computer open it with?

**Comment by aRTy42** [comment]
.exe files are usually not opened with another program but with windows itself. The notepad problem seems to have happened to a lot of people though, when they clicked or ticked something they shouldn't have. Try this solution ([source](https://www.reddit.com/r/techsupport/comments/1aekzf/i_accidentally_changed_all_exe_files_to_open_with/)):
> open up the Control Panel and navigate to: **Control Panel\Programs\Default Programs\Set Default Programs**, or do a search for Default and click on the results until you get to Set Default Programs. Then you should see Notepad on the left. Once you select it, you should see Choose defaults for this program and then you can untick .exe and hit Save.

If that doesn't work, then there are explanations for other ways to fix it in the linked reddit thread and you also can pick from [these](https://www.google.de/search?&q=exe+opens+in+notepad) google results.

Once Autohotkey is installed, you use the "Run_TradeMacro.ahk" file to run the script (which is opened with autohotkey).
