### ISSUE TITLE
"Access to www.poeprices.info was denied" error 

### ISSUE THREAD

**Issue by ioan321** [PoE-TradeMacro/POE-TradeMacro#872]
When I click "open on poeprices.info" button on ur UI, I get the access denied. What is the problem?

Fill out everything that may be relevant and remove everything except these informations below:  

AHK version: newest
Windows version: win 10

**Comment by Slider2019** [comment]
Same here since 3 days

**Comment by AgathoN** [comment]
"Open on poeprices.info" leads to 
[https://www.poeprices.info/api?l=Betrayal&i=UmFyaXR5OiBSYXJlDQpWZW5nZWFuY2UgU3Rhcg0KVXJzaW5lIFBlbHQNCi0tLS0tLS0tDQpRdWFsaXR5OiArMjAlIChhdWdtZW50ZWQpDQpFdmFzaW9uIFJhdGluZzogNDMxIChhdWdtZW50ZWQpDQotLS0tLS0tLQ0KUmVxdWlyZW1lbnRzOg0KTGV2ZWw6IDYwDQpEZXg6IDExNA0KLS0tLS0tLS0NClNvY2tldHM6IEctUiANCi0tLS0tLS0tDQpJdGVtIExldmVsOiA3NA0KLS0tLS0tLS0NCis4NSB0byBtYXhpbXVtIExpZmUNCis0MiUgdG8gRmlyZSBSZXNpc3RhbmNlDQorNDUlIHRvIExpZ2h0bmluZyBSZXNpc3RhbmNlDQorMjIlIHRvIENoYW9zIFJlc2lzdGFuY2UNCjM2JSBpbmNyZWFzZWQgRXZhc2lvbiBSYXRpbmcNCisyNyB0byBtYXhpbXVtIExpZmUNCg==&w=1](link)
a blank page that sometimes displays the text:
"{"status": 403, "data": {}, "error_msg": "Over rate limit", "error": 4} "

I dont want to sound urgent, but please please please fix it. Couldnt use the macro now properly for 3 or 4 days and my POE experience highly depends on it.

Thank you

**Comment by Rulqu** [comment]
This isn't POE-TradeMacro problem though. It's problem at poeprices.info.

**Comment by Eruyome** [comment]
This was caused bei their recently introduced rate limiting and "bad" feedback/response. The site should now show a proper error page and the responses in general now return detailed error messages in a lot of cases which will be displayed by TradeMacro in the upcoming update.

**Comment by SanjeninNagi** [comment]
i found that issue
delete temp/poepricelog
complete

**Comment by Eruyome** [comment]
For future reference, deleting that file doesn't work. The error was caused by their load balancer since they had issues with too much traffic. It just wasn't properly reported/commincated by their site or TradeMacro.
