### ISSUE TITLE
Attach the AHK Script to a different .exe name?

### ISSUE THREAD

**Issue by Vociferate** [PoE-TradeMacro/POE-TradeMacro#875]
Is it possible to have the AHK Script attach to a different named .exe? I use a seperate program to launch and close my games to get better performance from my old as dirt PC. It changes the names of all programs it launches in order to launch them  through a portal of sorts.

**Comment by Eruyome** [comment]
I'm not entirely sure what you're asking.
Which software are you using? Something written by yourself?

**Comment by aRTy42** [comment]
You can modify one of the source scripts. The file will be updated with every TradeMacro version update, so you'll need to make the modification every time you download a new version.

At `\<Script Folder>\resources\ahk\` you find the file `POE-ItemInfo.ahk`. Rightclick and choose "Edit Script". In lines 13-17 you find the following code:
```
;Define window criteria for the regular and steam version, for later use at the very end of the script. This needs to be done early, in the "auto-execute section".
GroupAdd, PoEWindowGrp, Path of Exile ahk_class POEWindowClass ahk_exe PathOfExile.exe
GroupAdd, PoEWindowGrp, Path of Exile ahk_class POEWindowClass ahk_exe PathOfExileSteam.exe
GroupAdd, PoEWindowGrp, Path of Exile ahk_class POEWindowClass ahk_exe PathOfExile_x64.exe
GroupAdd, PoEWindowGrp, Path of Exile ahk_class POEWindowClass ahk_exe PathOfExile_x64Steam.exe
```

To get all the information about your special program window (you only need to do this once), you'll want to use a program that comes with Autohotkey. It's in the Autohotkey folder and has the name `AU3_Spy.exe`, you can also use the start menu file search and look for "window spy" which should give you `AutoIt3 WindowSpy`. Launch that program and leave it open, it should stay in the foreground. Launch Path of Exile through your special program and click into the game window. The window spy should now tell you lots of stuff, in particular there should be a section at the top named "Window Title, Class and Process". Copy the content of that section with Ctrl+C and paste it somewhere, for example in notepad, so you can work with that info.

You want to add this information to the code I quoted earlier. Use the following format and replace `<title>`, `<class>` and `<exe>` with the information you got from your window spy.
```
GroupAdd, PoEWindowGrp, <title> ahk_class <class> ahk_exe <exe>
```
I would recommend that you simply add this line below the four existing ones. Save the file and test the script. If it works, save that line somewhere so it won't get lost on the next update and you can copy+paste it into the script again.

**Comment by Vociferate** [comment]
> I'm not entirely sure what you're asking.
> Which software are you using? Something written by yourself?
It is a modified version of Razer's software that closes all non essential process'. It is something we made in University that I have kept for years. :)

I ended up getting it too work, had to mess with a couple things on my end. But it is working with the directions that Arty gave me from below. 


> You can modify one of the source scripts. The file will be updated with every TradeMacro version update, so you'll need to make the modification every time you download a new version.
> 
> At `\<Script Folder>\resources\ahk\` you find the file `POE-ItemInfo.ahk`. Rightclick and choose "Edit Script". In lines 13-17 you find the following code:
> 
> ```
> ;Define window criteria for the regular and steam version, for later use at the very end of the script. This needs to be done early, in the "auto-execute section".
> GroupAdd, PoEWindowGrp, Path of Exile ahk_class POEWindowClass ahk_exe PathOfExile.exe
> GroupAdd, PoEWindowGrp, Path of Exile ahk_class POEWindowClass ahk_exe PathOfExileSteam.exe
> GroupAdd, PoEWindowGrp, Path of Exile ahk_class POEWindowClass ahk_exe PathOfExile_x64.exe
> GroupAdd, PoEWindowGrp, Path of Exile ahk_class POEWindowClass ahk_exe PathOfExile_x64Steam.exe
> ```
> To get all the information about your special program window (you only need to do this once), you'll want to use a program that comes with Autohotkey. It's in the Autohotkey folder and has the name `AU3_Spy.exe`, you can also use the start menu file search and look for "window spy" which should give you `AutoIt3 WindowSpy`. Launch that program and leave it open, it should stay in the foreground. Launch Path of Exile through your special program and click into the game window. The window spy should now tell you lots of stuff, in particular there should be a section at the top named "Window Title, Class and Process". Copy the content of that section with Ctrl+C and paste it somewhere, for example in notepad, so you can work with that info.
> 
> You want to add this information to the code I quoted earlier. Use the following format and replace `<title>`, `<class>` and `<exe>` with the information you got from your window spy.
> 
> ```
> GroupAdd, PoEWindowGrp, <title> ahk_class <class> ahk_exe <exe>
> ```
> I would recommend that you simply add this line below the four existing ones. Save the file and test the script. If it works, save that line somewhere so it won't get lost on the next update and you can copy+paste it into the script again.

Thank you! That worked perfectly.
