### ISSUE TITLE
Cant price check rares with ctrl+D

### ISSUE THREAD

**Issue by Moshruum** [PoE-TradeMacro/POE-TradeMacro#877]
{
    "added": {
        "browserUrl": "https://www.poeprices.info/api?l=Betrayal&i=UmFyaXR5OiBSYXJlDQpCbG9vZCBDb3JvbmENCkV0ZXJuYWwgQnVyZ29uZXQNCi0tLS0tLS0tDQpRdWFsaXR5OiArMjAlIChhdWdtZW50ZWQpDQpBcm1vdXI6IDUzNCAoYXVnbWVudGVkKQ0KLS0tLS0tLS0NClJlcXVpcmVtZW50czoNCkxldmVsOiA2OQ0KU3RyOiAxNDgNCkRleDogNDgNCkludDogMTA2DQotLS0tLS0tLQ0KU29ja2V0czogUi1CLVItUiANCi0tLS0tLS0tDQpJdGVtIExldmVsOiA3Mw0KLS0tLS0tLS0NClN1bW1vbmVkIEhvbHkgUmVsaWNzIGhhdmUgNzUlIGluY3JlYXNlZCBCdWZmIEVmZmVjdA0KLS0tLS0tLS0NCis3MiB0byBBcm1vdXINCisyOSB0byBtYXhpbXVtIExpZmUNCjkuOCBMaWZlIFJlZ2VuZXJhdGVkIHBlciBzZWNvbmQNCis0NSUgdG8gQ29sZCBSZXNpc3RhbmNlDQorMzUlIHRvIExpZ2h0bmluZyBSZXNpc3RhbmNlDQorNTggdG8gbWF4aW11bSBMaWZlDQo=&w=1",
        "encodedData": "UmFyaXR5OiBSYXJlDQpCbG9vZCBDb3JvbmENCkV0ZXJuYWwgQnVyZ29uZXQNCi0tLS0tLS0tDQpRdWFsaXR5OiArMjAlIChhdWdtZW50ZWQpDQpBcm1vdXI6IDUzNCAoYXVnbWVudGVkKQ0KLS0tLS0tLS0NClJlcXVpcmVtZW50czoNCkxldmVsOiA2OQ0KU3RyOiAxNDgNCkRleDogNDgNCkludDogMTA2DQotLS0tLS0tLQ0KU29ja2V0czogUi1CLVItUiANCi0tLS0tLS0tDQpJdGVtIExldmVsOiA3Mw0KLS0tLS0tLS0NClN1bW1vbmVkIEhvbHkgUmVsaWNzIGhhdmUgNzUlIGluY3JlYXNlZCBCdWZmIEVmZmVjdA0KLS0tLS0tLS0NCis3MiB0byBBcm1vdXINCisyOSB0byBtYXhpbXVtIExpZmUNCjkuOCBMaWZlIFJlZ2VuZXJhdGVkIHBlciBzZWNvbmQNCis0NSUgdG8gQ29sZCBSZXNpc3RhbmNlDQorMzUlIHRvIExpZ2h0bmluZyBSZXNpc3RhbmNlDQorNTggdG8gbWF4aW11bSBMaWZlDQo=",
        "encodingError": "",
        "league": "Betrayal",
        "requestUrl": "https://www.poeprices.info/api?l=Betrayal&i=UmFyaXR5OiBSYXJlDQpCbG9vZCBDb3JvbmENCkV0ZXJuYWwgQnVyZ29uZXQNCi0tLS0tLS0tDQpRdWFsaXR5OiArMjAlIChhdWdtZW50ZWQpDQpBcm1vdXI6IDUzNCAoYXVnbWVudGVkKQ0KLS0tLS0tLS0NClJlcXVpcmVtZW50czoNCkxldmVsOiA2OQ0KU3RyOiAxNDgNCkRleDogNDgNCkludDogMTA2DQotLS0tLS0tLQ0KU29ja2V0czogUi1CLVItUiANCi0tLS0tLS0tDQpJdGVtIExldmVsOiA3Mw0KLS0tLS0tLS0NClN1bW1vbmVkIEhvbHkgUmVsaWNzIGhhdmUgNzUlIGluY3JlYXNlZCBCdWZmIEVmZmVjdA0KLS0tLS0tLS0NCis3MiB0byBBcm1vdXINCisyOSB0byBtYXhpbXVtIExpZmUNCjkuOCBMaWZlIFJlZ2VuZXJhdGVkIHBlciBzZWNvbmQNCis0NSUgdG8gQ29sZCBSZXNpc3RhbmNlDQorMzUlIHRvIExpZ2h0bmluZyBSZXNpc3RhbmNlDQorNTggdG8gbWF4aW11bSBMaWZlDQo=",
        "retHeader": "000"
    }
}

V. 2.12.3
Windows 10
Checking with ctrl+alt+D works

**Comment by SanjeninNagi** [comment]
i found that issue
delete temp/poepricelog
complete

**Comment by Eruyome** [comment]
Deleting that file does nothing. Their servers have issues, sometimes a request will work, sometimes it won't.

**Comment by Eruyome** [comment]
The `"retHeader": "000"` in the logfile suggests this issue
```
Client disconnected before completing the request to poeprices.info because of the timeout parameter (10s).
```

This error wasn't properly reported back to users so far, but will be more clear in the future.

**Comment by Kerannon** [comment]
im having the same issue now and ive litteraly tried everything people suggested in all the comments, i cant price check rares anymore out of nowherer and it says i need to check my temp file which links me to the PoE website thread. what do i have to do to fix this?
