### ISSUE TITLE
ctrl-alt-enter (whioslastwhisper) additional macro does not work by default

### ISSUE THREAD

**Issue by jnitis** [PoE-TradeMacro/POE-TradeMacro#878]
I fixed this in the last two versions by changing this line in TradeMacroMain (line #14729 in the latest version):
`SendInput {Enter}{Home}{Del}/whois{Space}{Enter}`
to this:
`SendInput ^{Enter}{Home}{Del}/whois{Space}{Enter}`

Cheers.

**Comment by aRTy42** [comment]
It works when you didn't change the chat or deleted the `@name` that comes up by default after a whisper. But you are right, the variant with Ctrl covers more cases, I'll discuss this with Eruyome.

**Comment by Eruyome** [comment]
Added/changed.
