### ISSUE TITLE
Unique jewel not including base type

### ISSUE THREAD

**Issue by boolean0101** [PoE-TradeMacro/POE-TradeMacro#88]
I noticed that when I search for a unique jewel , the jewel type is not used in the search, resulting in much lower prices being returned than it actually has. For example, if I use CTRL+D on my 'Grand Spectrum Viridian Jewel', it only searches for "Grand Spectrum", which mixes it with results of the Cobalt and Crimson jewels (which are worth a lot less). 

Perhaps I'm missing a setting and this is by design, but it seems like it should be searching for the jewel name plus the base type.

**Comment by Eruyome** [comment]
No, this is just a bug/oversight. Will fix it.

**Comment by Eruyome** [comment]
Fixed on dev-version, will be released soon. Thx.
