### ISSUE TITLE
PLEASE HELP PoE Trade Macro Won't Start

### ISSUE THREAD

**Issue by WiZRDMiKE** [PoE-TradeMacro/POE-TradeMacro#880]
Getting this message when clicking Run_TradeMacro.ahk:

**_"Error at line 1 #include file "D:\lib\CalcChecksum.ahk".
Line Text: HashFile(filePath,hashType=2)
Error:Duplicate function definition.

The program will exit"_**

AHK version: v1.1.30.01
Windows version: Vista

**Comment by aRTy42** [comment]
The path `D:\lib\CalcChecksum.ahk` looks like you unzipped the macro files directly on the D:\ partition without a folder. Put the files into a folder. The default folder name is "POE-TradeMacro".

**Comment by Eruyome** [comment]
1. First time installation or update?
2 If update, manual or with the scripts updater?
3. Please remove all files, properly extract them and make sure not to use any shortcut to some old TM installation. 
4. Don't use any drive root as your macros folder, which seems to be the case according to this `"D:\lib\CalcChecksum.ahk"`.
