### ISSUE TITLE
after an update this app dosent works 

### ISSUE THREAD

**Issue by fislysandi** [PoE-TradeMacro/POE-TradeMacro#881]
after i updated this it worked for some time then it stopped working like wtf
v2.12.3 
Cookie file found. 
Retrieving cookies failed. 
Windows Version: 10.0.16299 (10.0.16299), 64bit. 
Compiling 'getCookieData' script successful. 
Net Framework used for compiling: v4 
Internet Explorer: v11.547.16299.0

**Comment by DemandingDeath** [comment]
I'm having same problem no cookies so price checking no work.

**Comment by Vociferate** [comment]
+1 - I think something had a hiccup.

**Comment by noelle1520** [comment]
+1

**Comment by RaDeleon** [comment]
now even my old one wont work

**Comment by gatheringtoy** [comment]
not work! (failed cookie , failed cURL) after update, and after uninstalling and setup old version still not working!

**Comment by Genuvien** [comment]
Same issue, just started doing this. Also this issue is being posted on the poe forums. Hope you have time to fix soon. :)

https://www.pathofexile.com/forum/view-thread/1757730/page/66#p16146447

**Comment by SsapS** [comment]
same =(

**Comment by turtle328** [comment]
+1 looks like everyone is having the same issue.

**Comment by Dravick06** [comment]
Same issue, tried moving file location, fresh download, nothing so far.

**Comment by Imaybestoned** [comment]
Same here
![error](https://user-images.githubusercontent.com/46614215/51066869-16707280-15db-11e9-9ef9-abc2e0d68942.JPG)

**Comment by stu177** [comment]
Just checked the Discord, @Eruyome is aware of the issue and working on it at the moment.

**Comment by martintato17** [comment]
I started using this today in the morning, went to work, and when I came back: BOOM! wont work anymore.
I was going to cry, but now I know it's not me. Love you all, great work

**Comment by gatheringtoy** [comment]
fixed 2.12.4

**Comment by Eruyome** [comment]
Fixed.
