### ISSUE TITLE
Getting 403 Forbidden in curl.exe output

### ISSUE THREAD

**Issue by turtle328** [PoE-TradeMacro/POE-TradeMacro#882]
There seems to be a problem with cookie reading from poe.trade.

The poe.trade site works perfectly. I double checked my IE settings they all look fine. I've disabled my antivirus. And I am definitely not on a mobile connection. Regardless of what I do or what other people have said on here, the forums, or the FAQ I keep getting this same output:

C:\Users\Alex\Documents\PoE-Trade-Macro\lib>curl.exe -I poe.trade
HTTP/1.1 403 Forbidden
Server: nginx
Date: Sat, 12 Jan 2019 00:07:29 GMT
Content-Type: text/html
Content-Length: 162
Connection: keep-alive

AHK version: 1.1.30.01
Windows version: Windows 10 Version 1803

**Comment by bwoods89** [comment]
I get the same issue
```
PS D:\Users\Brad\Documents\PoE Scripts\POE-TradeMacro-2.12.3\lib> .\curl.exe -ILk poe.trade
HTTP/1.1 403 Forbidden
Server: nginx
Date: Sat, 12 Jan 2019 00:34:03 GMT
Content-Type: text/html
Content-Length: 162
Connection: keep-alive
```

**Comment by iceberg3366** [comment]
Visiting poe.trade, I do not see any cloudflare cookies.

**Comment by MidasOP** [comment]
The cookie format seems to have changed. I confirmed that the price checking feature does not work, so poe.trade did not just remove cloudflare, So they either changed the cookie format, or they switched to a different service. The cookies now look like

_ga=GA1.2.121616800.1547253325; _gid=GA1.2.340367092.1547253325; __gads=ID=83c0f3e1b8ea88af:T=1547253313:S=ALNI_MaUM5dw1IUuFwU-PhSRMPYWBslsog

**Comment by stu177** [comment]
Same issue as #881 and #883?

**Comment by MidasOP** [comment]
> Same issue as #881 and #883?
 
Yes. This thread is more descriptive though.

**Comment by iceberg3366** [comment]
> The cookie format seems to have changed. I confirmed that the price checking feature does not work, so poe.trade did not just remove cloudflare, So they either changed the cookie format, or they switched to a different service. The cookies now look like
> 
> _ga=XXXXXXXXXXXX; _gid=XXXXXXXXXXXXXXXXX; __gads=ID=XXXXXXXXXXXXX:T=XXXXXXXXXXX:S=XXXX_XXXXXXXXXXXXX-XXXXXXXXX

These are Google Analytics cookies.

**Comment by Eruyome** [comment]
Fixed.
