### ISSUE TITLE
Stuck launching on this screen

### ISSUE THREAD

**Issue by ClickyOSU** [PoE-TradeMacro/POE-TradeMacro#886]
After a recent update to ur macro its been stuck on this forever.
![image](https://user-images.githubusercontent.com/42359579/51068118-98ff2f00-15e7-11e9-9fbc-ab6984beb855.png)

**Comment by potasium56** [comment]
same thing happening to me

**Comment by zullee122** [comment]
Same after updating it takes along time to load and when it does and i price check something it said no items found. i updated to v2.12.4

**Comment by potasium56** [comment]
Update to 2.12.4 and install the files in your ssd or hdd and then run the autohotkey within the directory and not from your desktop and it should work

**Comment by KinokoSama** [comment]
I got past that error by manually updating, but still not getting any results returned. I'm thinking this is due to slowness with trade api. Manual searches are taking quite long on poe.trade, so the macro may be timing out.

**Comment by potasium56** [comment]
Im able to use the macro but your are right poe.trade is slow af

**Comment by DarkLord1610** [comment]
I had the same problem and I got it solved.
first, it started with failing to use POETM in-game, then after re-launching it and updating, I had a cookie read error, following that I re-installed the macro to find the same error window you posted followed by a crush.
How To Solve:
I downloaded all fresh files, POETM and AHK
I moved my Trade Macro folder from my desktop (where I used to have it with the past releases) into one of my partitions (D:/PoE Trade Macro/POE-TradeMacro-2.12.4)
I re-installed AHK (just in case), then restarted my PC.
it works fine now.
try it.

**Comment by potasium56** [comment]
@DarkLord1610 I also mentioned this above - "Update to 2.12.4 and install the files in your ssd or hdd and then run the autohotkey within the directory and not from your desktop and it should work" but i didn't have to reinstall AHK or Restart my system....

**Comment by Eruyome** [comment]
poe.trade still has some issues, being overloaded.

This can cause your requests to timeout which wasn't properly reported back so far. This can either lead to search requests telling you that no item was found or showing this cookie error. TradeMacro thinks that there's an issue that could be prevented by using cookies.

**Comment by AgathoN** [comment]
v2.10.9 
Cookie file found. 
Retrieving cookies failed. 
Windows Version: 10.0.17134 (10.0.17134), 64bit. 
Compiling 'getCookieData' script successful. 
Net Framework used for compiling: v4 
Internet Explorer: v11.523.17134.0

I am kinda getting tired of this - the "Delete cookies" button doesnt do jack. Deleteting everything in the temp folder the "cookie" file is in doesnt do anything.

**Comment by Soerj** [comment]
Hey guys! I just installed new version into ANOTHER random location and it works fine now! No need to reboot or reinstall AHK.

**Comment by Eruyome** [comment]
@AgathoN Press continue and update or update manually https://github.com/PoE-TradeMacro/POE-TradeMacro/releases

**Comment by AgathoN** [comment]
@Eryome I reinstalled AHK and the macro in a different location from new rar files. Same issue.

**Comment by Eruyome** [comment]
Closed because the issue is so old. Feel free to message again if the issues still persist.
