### ISSUE TITLE
2.12.4 won't load?

### ISSUE THREAD

**Issue by DemandingDeath** [PoE-TradeMacro/POE-TradeMacro#887]
I keep getting an invalid installation path
I did a fesh install of 2.12.4 same error and i download the one that had cookie problem and update to 2.12.4 from 2.12.3 even older version 2.12.1 same error i posted a screenshot
![658b0766a5b75ad6128499bc47069614](https://user-images.githubusercontent.com/46613571/51068190-85a09380-15e8-11e9-9ee9-897cefa11c20.png)

**Comment by DemandingDeath** [comment]
Probably just me being stupid

**Comment by potasium56** [comment]
I had the cookie error so i reinstalled to the newest release and it works fine....think you have to run the file when its inside your storage not from the desktop

**Comment by DemandingDeath** [comment]
Thx fixed it big help
