### ISSUE TITLE
SOLUTION for the Cookie screen, Failing to start people having lately.

### ISSUE THREAD

**Issue by DarkLord1610** [PoE-TradeMacro/POE-TradeMacro#889]
I had the problem many people posted the past hour and I got it solved.
first, it started with failing to use POETM in-game, then after re-launching it and updating, I had a cookie read error, following that I re-installed the macro to find an error window followed by a crush.
How To Solve:
I downloaded all fresh files, POETM and AHK
I moved my Trade Macro folder from my desktop (where I used to have it with the past releases) into one of my partitions (D:/PoE Trade Macro/POE-TradeMacro-2.12.4)
I re-installed AHK (just in case), then restarted my PC.
it works fine now.
try it.

**Comment by fooey** [comment]
Downloading and reinstalling POETM from scratch worked for me as well

I did open IE and go to poe.trade too just to make sure first, but I  don't know if that did any good.
