### ISSUE TITLE
Windows Defender Flagging Fallback.exe as Trojan:Win32/Tiggre!plock

### ISSUE THREAD

**Issue by DoctorVanGogh** [PoE-TradeMacro/POE-TradeMacro#890]
Fallback.exe is _still_ classified as a Trojan.

Yes, I'm aware virustotal says it's clean.

I strongly suggest you use https://www.microsoft.com/en-us/wdsi/filesubmission and use the "Software developer" option to get it whitelisted.

**Comment by aRTy42** [comment]
The fallback.exe isn't in the regular release anymore, so it won't bother most people. The very few who really need and want it should be aware of the false-positive flagging issue. Handing it in to get it whitelisted seems pointless since the file will change with every release.

**Comment by DoctorVanGogh** [comment]
Also... why the f*** is there a binary exe embedded? I distinctly remember way back in #149 advocating for some on demand local build ;)

**Comment by Eruyome** [comment]
Which is useless because that would compile using the users local AHK installation. But if that works then they won't need the fallback.exe at all.

Anyway, I removed the file from releases and from the repo itself. I may include a second zip file in my releases that still has it.

**Comment by DoctorVanGogh** [comment]
Hint: It's not removed from the repo :D

It's merely no longer in the *current* state. A lookup/checkout of a previous history will happily grab the old version.
Which - since those files are now historical - could be submitted to MS for elimination of the false positives.

**Comment by Eruyome** [comment]
Yeah ok, that's certainly true.

**Comment by DoctorVanGogh** [comment]
And things may have changed a bit since that original implementation, but "way back" there was a C# script which did the magic. *That* could have been compiled locally against a locally installed .NET version. I just found my old comments regarding the stuff. 😁 

My point is more like: If you distribute *any* non widely used executable you're (at least) exposing yourself to false positives.
With 2M downloads (from a lot of casual users) this repository is a prime target for some security vulnerability injections.

`curl.exe` is certainly fine (assuming it's unchanged)

**Comment by Eruyome** [comment]
That script was for reading cookies from IE.
To compile ahk script to a standalone .exe you need a working AHK installation. But fallback.exe is a fallback/solution for not having that working AHK installation.
