### ISSUE TITLE
Since new update tool doesn't work. 

### ISSUE THREAD

**Issue by Hlxx** [PoE-TradeMacro/POE-TradeMacro#891]
v2.12.4 
Cookie file found. 
Retrieving cookies failed. 
Windows Version: 10.0.17763 (10.0.17763), 64bit. 
Compiling 'getCookieData' script successful. 
Net Framework used for compiling: v4 
Internet Explorer: v11.253.17763.0

**Comment by Eruyome** [comment]
Click continue and use TradeMacro.
Your requests are very likely timing out because poe.trade is too slow atm. Some of your search requests may work.

**Comment by funkerx** [comment]
Its happening for me too. It was okay since last week.

**Comment by dcoriat** [comment]
Hello,

Same issue here, don't think it has to do with poe.trade being slow.

Here's what curl returns :

"Documents\My Games\POE-TradeMacro\lib\curl.exe" -ILk poe.trade
HTTP/1.1 403 Forbidden
Server: nginx
Date: Sat, 12 Jan 2019 10:35:25 GMT
Content-Type: text/html
Content-Length: 162
Connection: keep-alive

Thanks!

**Comment by Arcturus100** [comment]
Same problem here. Poe trade being slow has nothing to do with this, as the issue began right after the last update. Tried many things already, nothing works. It is likely just a bug in the latest version.

**Comment by aRTy42** [comment]
Please try reinstalling the macro: Delete the main macro folder and download the latest version 2.12.4 from the [release page](https://github.com/PoE-TradeMacro/POE-TradeMacro/releases).

The new version was made specifically because there were changes to poe.trade that broke requests.

**Comment by Arcturus100** [comment]
I completely deleted everything macro related and reinstalled the latest version 3 times already. Problem still there.

**Comment by aRTy42** [comment]
> I completely deleted everything macro related and reinstalled the latest version 3 times already. Problem still there.

>Ok, tried reinstalling again and it works now, thanks.

Did you do anything different on the last reinstall? It would help narrow the problem down.

**Comment by topcheese13** [comment]
@aRTy42 

For me I tried downloading and unzipping versions 2.12.2 & 2.12.3 multiple times yesterday , nothing worked. Version 2.12.4 worked right away. Thought you might want to know. Thanks for the tool mate!

**Comment by aRTy42** [comment]
About 15 hours ago there were changes to poe.trade, that's the main content and reason for version 2.12.4. Using the old versions 2.12.2 or 2.12.3 won't "make it work just like before" or whatever people are asking since then.

**Comment by derek-adair** [comment]
Users when you tell them they have to update:

![image](https://user-images.githubusercontent.com/847236/51074922-38e9a680-1642-11e9-9dbd-e090bbca933f.png)

**Comment by derek-adair** [comment]
Can confirm, updating... SHOCKINGLY... fixes this.  Thanks for the hard work dudes.

**Comment by Hlxx** [comment]
> Click continue and use TradeMacro.
> Your requests are very likely timing out because poe.trade is too slow atm. Some of your search requests may work.

Deleteing folder in c:documents fixed the problem. But for some people dont.

**Comment by derek-adair** [comment]
Step 1) Remove 100% of the files you downloaded and unzipped.  ALL OF THEM
Step 2) Re-install the macro
Step 3) Wait for trading api to not fucking suck
step 4) Profit.

**Comment by derek-adair** [comment]
I suspect anyone who isn't able to get this working w/ a fresh install isn't actually freshly installing it.
