### ISSUE TITLE
Allocation Error's since using 2.12.3

### ISSUE THREAD

**Issue by fuhqoff** [PoE-TradeMacro/POE-TradeMacro#895]
Allocation Errors are crashing PoE every half hour. Hundreds of error windows pop. I have to hold escape for about 40 seconds to get through them all. Related to Trade Macro? Also the updater does not seem to be working.

**Comment by Eruyome** [comment]
1. No, not related.
2. How exactly is it not working?

**Comment by turtle328** [comment]
Does PoE run into these allocation errors only when PoE-TradeMacro is running? That seems quite strange.

**Comment by Eruyome** [comment]
Closed because the issue is so old. Feel free to message again if the issues still persist.
