### ISSUE TITLE
new CheckInvalidScriptFolder behavior

### ISSUE THREAD

**Issue by Lothrik** [PoE-TradeMacro/POE-TradeMacro#897]
This commit: https://github.com/PoE-TradeMacro/POE-TradeMacro/commit/f9710a9e950fb3aaa6d1dd2e9587f366e211bac3

Changed the startup behavior here: https://github.com/PoE-TradeMacro/POE-TradeMacro/blob/f9710a9e950fb3aaa6d1dd2e9587f366e211bac3/resources/ahk/Merge_TradeMacro.ahk#L56

Now instead of simply warning the user that they're starting PoE-TradeMacro from their desktop, the script aborts entirely if it detects this.

It might make sense to abort the script under these conditions if the user does not have admin rights (A_IsAdmin is the easiest way to check this AFAIK), but no such check is currently performed -- the script just assumes it won't work and gives up.

**Comment by aRTy42** [comment]
This was already changed in the dev version: https://github.com/PoE-TradeMacro/POE-TradeMacro/commit/567fec5e4de96915f626b000cc4ed15f0de6d635#diff-e5f2da39234f75431403e62fccd118faR1

The issues with the desktop and a few other locations don't seem to be strictly bound to admin/non-admin though, at least the reports I remember seemed quite various to me.

**Comment by Eruyome** [comment]
That was an oversight, didn't intend to completely not allow it.
