### ISSUE TITLE
error at line 5

### ISSUE THREAD

**Issue by insomniak99** [PoE-TradeMacro/POE-TradeMacro#898]
line text: versionfilepath := A_ScriptDir "\resources\versiontrade.txt"
error: this line does not contain a recognised action.

I couldn't update so I deleted the file downloaded new one now I get this error message 
I'm not computer savvy so have no idea what to do

**Comment by aRTy42** [comment]
Download the latest version of [autohotkey](https://www.autohotkey.com/download/) (blue button, purple text).

Delete the entire TradeMacro folder, the one with the "Run_TradeMacro.ahk". Download the latest zip from the [releases](https://github.com/PoE-TradeMacro/POE-TradeMacro/releases). Unzip the files it into a folder, put the folder somewhere where you usually have programs (don't put it on the desktop for example, that can cause permission issues).

Launch the script with the "Run_TradeMacro.ahk".

**Comment by insomniak99** [comment]
tried doing all that about 12 times now still same error everytime

**Comment by aRTy42** [comment]
Screenshot of the error please

**Comment by insomniak99** [comment]
I got it now ran it as administrator and it worked

**Comment by Eruyome** [comment]
Can you confirm that you did nothing else besides running the script as administrator to solve this?

**Comment by insomniak99** [comment]
Yeah I tried deleting and re downloading multiple times. Ran as administrator worked straight away

**Comment by aRTy42** [comment]
Could you run it as non-admin again and see if the error actually comes up again? Because with the error that came up, it makes no sense here.

**Comment by insomniak99** [comment]
Will do when I get home

**Comment by insomniak99** [comment]
Yeah still get the error. Fine if I run it as administrator

**Comment by insomniak99** [comment]
Now it says error at line 6 instead

**Comment by Eruyome** [comment]
This line I guess?
```
SetWorkingDir, %A_ScriptDir%
```

**Comment by insomniak99** [comment]
sorry yeah should of put that part

**Comment by insomniak99** [comment]
1.1.26.01 as it recommends

**Comment by Eruyome** [comment]
I don't get this at all, doesn't make any sense to me and the people I have spoken to.

You can upgrade AHK if you want, 1.1.26.01 is just the minimum requirement because I know that everything works fine with it.

**Comment by insomniak99** [comment]
well it works as it is now so ill leave it as 1.1.26.01 just have to run as administrator everytime
