### ISSUE TITLE
Issues opening Macro

### ISSUE THREAD

**Issue by ccloudff7** [PoE-TradeMacro/POE-TradeMacro#900]
![macro issue](https://user-images.githubusercontent.com/46654076/51088995-6878db80-1734-11e9-9080-40a1422945f9.png)
So I can run the script ok but I'm not sure what's going on because it's not opening properly. When I run the Macro the box pops up and the text is cut off, the box seems too small to display. When it finishes, I've seen in videos that a new box is supposed to pop up with info and I guess settings you can change, but this box never pops up for me. The script seems to be running because I can use the Ctrl commands but I can't access the settings at all. I'm running on Windows 10. I am getting no errrors, the box just doesn't display. I also don't see any scripts icon in my system tray either.

Ive found the ability to use the shortcuts (Ctrl + L) to change leagues but then an error pops up, this happens for any league I change to: 
![change league error](https://user-images.githubusercontent.com/46654076/51089816-7c770a00-1741-11e9-9400-02edf4f7acf4.png)

**Comment by ccloudff7** [comment]
So I can run the script ok but I'm not sure what's going on because it's not opening properly. When I run the Macro the box pops up and the text is cut off, the box seems too small to display. When it finishes, I've seen in videos that a new box is supposed to pop up with info and I guess settings you can change, but this box never pops up for me. The script seems to be running because I can use the Ctrl commands but I can't access the settings at all. I'm running on Windows 10.

**Comment by Eruyome** [comment]
Settings are being accessed by double clicking the system try icon or right clicking it and selecting the correct option.

Can you
1. Tell me if v2.12.4 works for you.
2. Upload me your `temp\Startuplogt.txt` which is being asked of you in the error message.

**Comment by Eruyome** [comment]
Startuplog looks fine. The update window appearing makes sense since 2.12.4 isn't the newest version while .5 is.

Do you still get the parsing currency data error?
If so go to `temp\` and upload all files startiing with `currency_` if they exist.
