### ISSUE TITLE
Critical error, Tradeversion.txt

### ISSUE THREAD

**Issue by Ophighdro** [PoE-TradeMacro/POE-TradeMacro#903]
AHK version:64
Windows version:10

Hello, i have been getting this for the last week since the new updates. I have fresh installed everything multiple times and it still doesn't register this file, any help is appreciated. Thank you.
![2019-01-15](https://user-images.githubusercontent.com/46734582/51223388-6fe7e280-18f6-11e9-8763-eb445a890f93.png)

**Comment by Ophighdro** [comment]
I did not make a folder for it as this happens when its in its own folder or not, thank you much again

**Comment by aRTy42** [comment]
As long as it is in a zip file, it can't work. Unzip it into a folder and put that folder somewhere where you usually have programs, such as `C:\Program Files\PoE-TradeMacro\`.

**Comment by aRTy42** [comment]
The path in the error is messed up. The \RUN\ should not be there. You are using the "Run_TradeMacro.ahk" file to start the macro, correct?

**Comment by Ophighdro** [comment]
Yes i am using the Run_TradeMacro.ahk. Thank you for replying i really appreciate it, ill look into the \run\ right now

**Comment by Ophighdro** [comment]
Hello, so i went and looked at the tradeversion.txt and saw it needed an older version of AHK, so i went and downloaded that and then moved the "Run_TradeMacro.ahk"  out of the run folder and it seems to work. Thank you for replying again :)

**Comment by aRTy42** [comment]
You don't need an old AHK version. The current version v1.1.30.01 should work fine. There is another autohotkey project called Autohotkey v2, aimed at reworking certain aspects of the language, which is in alpha status. You don't want that one.

About the \Run\ folder: That one should not be there to begin with. I have no idea why that existed for you. The TradeMacro download you GitHub should only require you to unzip it, moving single files around is not intended.
