### ISSUE TITLE
Hotkey Changes not Firing

### ISSUE THREAD

**Issue by Vociferate** [PoE-TradeMacro/POE-TradeMacro#904]
AHK version: **11.30.00 64x**
Windows version: **Windows 10**
![stuff](https://user-images.githubusercontent.com/10530013/51260922-2930d180-1964-11e9-8091-41f3cdf0917c.jpg)

Right - so I have changed the hotkeys for Hideout and Kick myself:

After I change them, I close POETrade Macro and restart the program.

Control + H - Hideout
Control + K - Kick Myself (Name is updated to Pickled_Tickler

I always run the program in administrator.

I cannot get any of these custom (altered hotkeys) to work.

Checking the settings in POETradeMacroMaster, they have updated correctly.

Thank you for your time. :)

**Comment by Vociferate** [comment]
You change the settings, you save using the buttons on the right.
You close the script.
You open %userprofile%\PoE-TradeMacro\AdditionalMacros.ini (you can right click the system tray icon -> edit files -> additional macros settings).
**Correct**
![image](https://user-images.githubusercontent.com/10530013/51330933-6f059c80-1a2d-11e9-8eb4-14f680a60e94.png)

The changes that you made are saved to this file?
You run the macro again.
The changed settings are correctly displayed in the menu? Or incorrectly?
All are displayed correctly in the newly reopened trade macro.


The new hotkeys don't work though?
Do the old ones still work in that case?

And nothing works. Old or new Hotkeys.

**Comment by Eruyome** [comment]
Closed because the issue is so old. Feel free to message again if the issues still persist.
