### ISSUE TITLE
Error at line 14827 (regardless of where i install it)

### ISSUE THREAD

**Issue by Dalbs** [PoE-TradeMacro/POE-TradeMacro#906]
![image](https://user-images.githubusercontent.com/46768868/51291422-1bfffb00-19d5-11e9-8b3f-8170a944bc03.png)

Information to include:
*POE Trade macro V 2.12.5
*attempted installing in Program files X86, program files, C drive, path of exile folder, etc.

Fill out everything that may be relevant and remove everything except these informations below:  

AHK version:  1.1.30.01
Windows version: windows 10 64 bit

**Comment by Eruyome** [comment]
Confirming that dialog should show you a window with some links and advice on how to solve some issues.

For example deleting `%userprofile%\PoE-TradeMacro\CustomMacros\customMacros_example.txt`.

**Comment by Dalbs** [comment]
Resolved!  I had to disable/uninstall onedrive, then completely uninstall all previous versions of POE trade macro.  Apparently, an imprint of POE Trade Macro from 7 months ago was linked to my "cloud" onedrive account, and i couldn't uninstall it without disabling Onedrive.  I did that, all set!  Thank you.

**Comment by Eruyome** [comment]
Hm, any chance that the mentioned file was causing that issue nonetheless? Did you remove it by chance?
