### ISSUE TITLE
Issues with checking Map Mods

### ISSUE THREAD

**Issue by WBWebDesigns** [PoE-TradeMacro/POE-TradeMacro#908]
When Control + C over maps, just white box appears. If I try a few times, it eventually lists mods, but takes a while. Video clip here (https://www.youtube.com/watch?v=cQLh-jFgGQk)

I've tried 2 different AHK builds (currently using 64bit 1.1.26.01 - also had same issues with 1.1.30.01). Windows 10 Home.

(Pricing items seem to work fine, it's just the map info part that is buggy)

**Comment by Eruyome** [comment]
For reference

https://youtu.be/ppbahSuEXcI
https://youtu.be/_Lmb6UQVtTc

A seperate script with a simple ToolTip works fine.

**Comment by Eruyome** [comment]
Closed because the issue is so old. Feel free to message again if the issues still persist.
