### ISSUE TITLE
CTRL - D Not working on rare items all of the sudden

### ISSUE THREAD

**Issue by Calipsio** [PoE-TradeMacro/POE-TradeMacro#910]
Im getting "ERROR: Request to poeprice 504"
Suddenly happened while playing while checking random rare items

Been uninstalling. Given poetrade full access. Deleted cookies. Tried to check other threads from you guys but nothing worked. Probably just an easy fix. Everything else works fine with the macro

Thanks

**Comment by 1nHuman** [comment]
Same, but my poe trade say: "Getting price Prediction" and crash or after some time "Request to poeprice.info returned HTTP ERROR 504 ()"

**Comment by Eruyome** [comment]
Servers are fine again.

**Comment by mosquito1114** [comment]
Hello, first of all forgive me for my English, I only speak Spanish and I'm using translators.
I get error 504 and I do not know how to fix it, could someone help me?

**Comment by russpoe** [comment]
Same, getting error 504

**Comment by g0dspeedx12** [comment]
Also getting this error ctrl + D on rares...
#####
### Please post this log file below to https://www.pathofexile.com/forum/view-thread/1216141/.
### Try not to "spam" their thread if a few other reports with the same error description were posted in the last hours.
#####

Request and response:
{
    "added": {
        "browserUrl": "https://www.poeprices.info/api?l=Legion&i=UmFyaXR5OiBSYXJlDQpTb3VsIENsdXRjaGVzDQpTcGlrZWQgR2xvdmVzDQotLS0tLS0tLQ0KQXJtb3VyOiAyNDIgKGF1Z21lbnRlZCkNCi0tLS0tLS0tDQpSZXF1aXJlbWVudHM6DQpMZXZlbDogNzANClN0cjogMTQwDQpEZXg6IDEwMg0KLS0tLS0tLS0NClNvY2tldHM6IFItUi1HLVIgDQotLS0tLS0tLQ0KSXRlbSBMZXZlbDogNzENCi0tLS0tLS0tDQpUcmlnZ2VyIENvbW1hbmRtZW50IG9mIFNwaXRlIHdoZW4gSGl0DQotLS0tLS0tLQ0KMjAlIGluY3JlYXNlZCBNZWxlZSBEYW1hZ2UNCi0tLS0tLS0tDQorMzggdG8gRGV4dGVyaXR5DQpBZGRzIDIgdG8gNSBQaHlzaWNhbCBEYW1hZ2UgdG8gQXR0YWNrcw0KKzIyMSB0byBBY2N1cmFjeSBSYXRpbmcNCisyMiB0byBBcm1vdXINCisxMDUgdG8gbWF4aW11bSBMaWZlDQorMzklIHRvIExpZ2h0bmluZyBSZXNpc3RhbmNlDQo=&w=1",
        "encodedData": "UmFyaXR5OiBSYXJlDQpTb3VsIENsdXRjaGVzDQpTcGlrZWQgR2xvdmVzDQotLS0tLS0tLQ0KQXJtb3VyOiAyNDIgKGF1Z21lbnRlZCkNCi0tLS0tLS0tDQpSZXF1aXJlbWVudHM6DQpMZXZlbDogNzANClN0cjogMTQwDQpEZXg6IDEwMg0KLS0tLS0tLS0NClNvY2tldHM6IFItUi1HLVIgDQotLS0tLS0tLQ0KSXRlbSBMZXZlbDogNzENCi0tLS0tLS0tDQpUcmlnZ2VyIENvbW1hbmRtZW50IG9mIFNwaXRlIHdoZW4gSGl0DQotLS0tLS0tLQ0KMjAlIGluY3JlYXNlZCBNZWxlZSBEYW1hZ2UNCi0tLS0tLS0tDQorMzggdG8gRGV4dGVyaXR5DQpBZGRzIDIgdG8gNSBQaHlzaWNhbCBEYW1hZ2UgdG8gQXR0YWNrcw0KKzIyMSB0byBBY2N1cmFjeSBSYXRpbmcNCisyMiB0byBBcm1vdXINCisxMDUgdG8gbWF4aW11bSBMaWZlDQorMzklIHRvIExpZ2h0bmluZyBSZXNpc3RhbmNlDQo=",
        "encodingError": "",
        "league": "Legion",
        "requestUrl": "https://www.poeprices.info/api?l=Legion&i=UmFyaXR5OiBSYXJlDQpTb3VsIENsdXRjaGVzDQpTcGlrZWQgR2xvdmVzDQotLS0tLS0tLQ0KQXJtb3VyOiAyNDIgKGF1Z21lbnRlZCkNCi0tLS0tLS0tDQpSZXF1aXJlbWVudHM6DQpMZXZlbDogNzANClN0cjogMTQwDQpEZXg6IDEwMg0KLS0tLS0tLS0NClNvY2tldHM6IFItUi1HLVIgDQotLS0tLS0tLQ0KSXRlbSBMZXZlbDogNzENCi0tLS0tLS0tDQpUcmlnZ2VyIENvbW1hbmRtZW50IG9mIFNwaXRlIHdoZW4gSGl0DQotLS0tLS0tLQ0KMjAlIGluY3JlYXNlZCBNZWxlZSBEYW1hZ2UNCi0tLS0tLS0tDQorMzggdG8gRGV4dGVyaXR5DQpBZGRzIDIgdG8gNSBQaHlzaWNhbCBEYW1hZ2UgdG8gQXR0YWNrcw0KKzIyMSB0byBBY2N1cmFjeSBSYXRpbmcNCisyMiB0byBBcm1vdXINCisxMDUgdG8gbWF4aW11bSBMaWZlDQorMzklIHRvIExpZ2h0bmluZyBSZXNpc3RhbmNlDQo=",
        "retHeader": "504",
        "timeoutParam": 25
    }
}
