### ISSUE TITLE
Macro Crashing on Atlas Searching. 

### ISSUE THREAD

**Issue by Grimmjow91** [PoE-TradeMacro/POE-TradeMacro#911]
Hello,

I am running AHK 64 bit. I am running windows 10 home 64 bit. Intel I7-7700HQ 2.80 GHZ, Nividia Geforce GTA 1050. 

There seems to be an issue when searching the atlas. I have had this happen to me 4+ times now so I think I have narrowed down what causes it I hope. When I am searching the Atlas to see if I have completed a map( using the search bar at the top) the macro seems to crash when I do this 4 ish times or more times in a row. This is with exiting the atlas and bring it back up again in a short amount of time to search again. This is the only time it crash so I think it has something to do with the atlas. I do not think this happens with the scripted paused but I have not tried it yet. I will try to see if it continues to crash when the script is paused and report back.

**Comment by Eruyome** [comment]
Can you describe what you're doing exactly in more detail?

Pressing `ctrl + f` -> typing something -> repeat?

**Comment by Grimmjow91** [comment]
Sure, I am looking at maps in my stash, as in highlighting them to see the name, opening up the atlas with G, clicking the search box and typing in the name, highlighting the blinking area to see if I have completed a map and then closing the atlas and starting over again. It seems that when you do this more than 4 times it causes the macro to crash. I have not had the issue since pausing the macro before each search.

**Comment by Grimmjow91** [comment]
Correction it seems to happen regardless of how much time has pasted between searched in the atlas. I have to pause the script anytime I search the atlas or it will crash after about the 4th search.

**Comment by Eruyome** [comment]
I can't really reproduce this.

Try the newest release, just in case.
I'd like to see a video of this if that's possible for you.

**Comment by Grimmjow91** [comment]
I can no longer reproduce the issue myself either. It seems to have been fixed. Thank you. I will close this issue.
