### ISSUE TITLE
GDI+ Rendering broken in newest patch

### ISSUE THREAD

**Issue by kxc0re** [PoE-TradeMacro/POE-TradeMacro#914]
Since the last Patch GDI+ Tooltips are not working for anymore.

AHK version: 1.1.29.1
Windows version: Win 10 64-bit

P.S.: just saw that GDI+ issues are labled wontfix, feel free to close this

**Comment by Eruyome** [comment]
If you're absolutely sure that your issue was caused by the last release then I may look into it regardless since there's a difference between having bugs that I don't have a clue on how to solve and accidentally breaking something that worked before.

**Comment by Eruyome** [comment]
Yeah, seems to be broken, just switch to the normal tooltip unitl I have time to look at what is broken.
