### ISSUE TITLE
Suggestion for a feature. 

### ISSUE THREAD

**Issue by Bennietgoed** [PoE-TradeMacro/POE-TradeMacro#916]
I was wondering, if it hasn't been suggested before, if it would be possible to add a tier option to the ctrl-alt-d pricecheck for rares, instead of the min/max values which work fine for uniques. It's really nice to check rares and come up with a market value that way. I didn't know where else to post this suggestion, so I hope it was alright to do it here. Thnx eitherway. 

Regards,

B.

**Comment by Eruyome** [comment]
Trade sites don't really support mod tiers. Besides, since TM still doesn't have access to the advanced mod descriptions the macro still has to guess with mods/hybrid mods the item has and what tier it is.

So I wouldn't really know of solution to implement this.
