### ISSUE TITLE
Error when opening Run_Trademacro

### ISSUE THREAD

**Issue by Rastakoko** [PoE-TradeMacro/POE-TradeMacro#917]
Got AHS installed. 

When i try to open Run_Trademacro give me this error:

`; #####################################################################################################################
; # This script checks if the right AHK version is installed and runs the TradeMacro merge script.
; #####################################################################################################################
#SingleInstance, Force
#NoEnv
SetWorkingDir, %A_ScriptDir%

versionFilePath := A_ScriptDir "\resources\VersionTrade.txt"
FileRead, versionFile, %versionFilePath%
error := ErrorLevel

If (not StrLen(versionFile) or error) {
    If (RegExMatch(A_ScriptDir, "i).zip$")) {
        MsgBox, 16, PoE-TradeMacro - Critical error, % "You are trying to run PoE-TradeMacro from inside a zip-archive, please unzip the whole folder. nnClosing script..."
        ExitApp
    } Else {
        If (FileExist(versionFilePath)) {
Critical error, % "Script couldn't read/access the file """ A_ScriptDir "\resources\VersionTrade.txt"". nnClosing script..."
        }
        ExitApp
    }
}
Else {
    RegExMatch(versionFile, "i)TradeReleaseVersion.?:=.?""(.?)""", relV)
    TradeReleaseVersion := relV1
    RegExMatch(versionFile, "i)TradeAHKVersionRequired.?:=.?""(.?)""", reqV)
    TradeAHKVersionRequired := reqV1
}

TradeMsgWrongAHKVersion := "AutoHotkey v" . TradeAHKVersionRequired . " or later is needed to run this script. It is important not to run version 2.x. or 1.0. nnYou are using AutoHotkey v" . A_AhkVersion . " (installed at: " . A_AhkPath . ")nnPlease go to http://ahkscript.org/ to download the most recent version."
If (A_AhkVersion < TradeAHKVersionRequired or A_AhkVersion >= "2.0.00.00" or A_AhkVersion < "1.1.00.00")
{
    MsgBox, 16, Wrong AutoHotkey Version, % TradeMsgWrongAHKVersion
    ExitApp
}

arguments := ""
Loop, %0%  ; For each parameter
{
    arguments .= " " %A_Index%
}

Run "%A_AhkPath%" "%A_ScriptDir%\resources\ahk\Merge_TradeMacro.ahk" "%A_ScriptDir%" %arguments%
ExitApp`

The Run_Trademacro appears me like a notebloc icon.

Can you help me? 

Thank You

**Comment by aRTy42** [comment]
That's not an error, you are opening the script file into notepad and see the code of the launcher.

Right click the .ahk file and select properties. Then at "Open with" change that to the exe of your autohotkey installation. For me that is "AutoHotkeyU64.exe" which then appears as "Auto Hotkey Unicode 64-bit" once selected.

**Comment by Rastakoko** [comment]
Solved thanks a lot :)
