### ISSUE TITLE
not working on unique items.

### ISSUE THREAD

**Issue by Whatea** [PoE-TradeMacro/POE-TradeMacro#920]
AHK version: latest 1.1.30.01 - have tried on 1.1.26 - still not working.
Windows version: 10 - 64 bit

price check on unique items is not working on lastest update .
item info is not working aswell.

**Comment by Valerate** [comment]
Did you figure this out since you closed it? I have the same issue

**Comment by Whatea** [comment]
I deleted the sub folders in documents/poe-trademacro and it worked fine afterwards.
