### ISSUE TITLE
error

### ISSUE THREAD

**Issue by noukosgr** [PoE-TradeMacro/POE-TradeMacro#921]
error request to poe price.info timed out or returned an invalid responed

please take a look at the file temp /poeprices

what must to do for fix the issues

**Comment by dyloner** [comment]
same issue for past 8 ish hours
here is my poeprices log txt:
Request and response:
{
    "added": {
        "browserUrl": "https://www.poeprices.info/api?l=Betrayal&i=UmFyaXR5OiBSYXJlDQpEaXJlIFdhcmQNClNvbGFyaXMgQ2lyY2xldA0KLS0tLS0tLS0NCkVuZXJneSBTaGllbGQ6IDgzIChhdWdtZW50ZWQpDQotLS0tLS0tLQ0KUmVxdWlyZW1lbnRzOg0KTGV2ZWw6IDY3DQpJbnQ6IDEyMg0KLS0tLS0tLS0NClNvY2tldHM6IEItQi1CIEIgDQotLS0tLS0tLQ0KSXRlbSBMZXZlbDogODUNCi0tLS0tLS0tDQo0NSUgaW5jcmVhc2VkIEVuZXJneSBTaGllbGQNCis1MiB0byBtYXhpbXVtIExpZmUNCis2OSB0byBtYXhpbXVtIE1hbmENCis0NyUgdG8gRmlyZSBSZXNpc3RhbmNlDQoyNiUgaW5jcmVhc2VkIFN0dW4gYW5kIEJsb2NrIFJlY292ZXJ5DQo=&w=1",
        "encodedData": "UmFyaXR5OiBSYXJlDQpEaXJlIFdhcmQNClNvbGFyaXMgQ2lyY2xldA0KLS0tLS0tLS0NCkVuZXJneSBTaGllbGQ6IDgzIChhdWdtZW50ZWQpDQotLS0tLS0tLQ0KUmVxdWlyZW1lbnRzOg0KTGV2ZWw6IDY3DQpJbnQ6IDEyMg0KLS0tLS0tLS0NClNvY2tldHM6IEItQi1CIEIgDQotLS0tLS0tLQ0KSXRlbSBMZXZlbDogODUNCi0tLS0tLS0tDQo0NSUgaW5jcmVhc2VkIEVuZXJneSBTaGllbGQNCis1MiB0byBtYXhpbXVtIExpZmUNCis2OSB0byBtYXhpbXVtIE1hbmENCis0NyUgdG8gRmlyZSBSZXNpc3RhbmNlDQoyNiUgaW5jcmVhc2VkIFN0dW4gYW5kIEJsb2NrIFJlY292ZXJ5DQo=",
        "encodingError": "",
        "league": "Betrayal",
        "requestUrl": "https://www.poeprices.info/api?l=Betrayal&i=UmFyaXR5OiBSYXJlDQpEaXJlIFdhcmQNClNvbGFyaXMgQ2lyY2xldA0KLS0tLS0tLS0NCkVuZXJneSBTaGllbGQ6IDgzIChhdWdtZW50ZWQpDQotLS0tLS0tLQ0KUmVxdWlyZW1lbnRzOg0KTGV2ZWw6IDY3DQpJbnQ6IDEyMg0KLS0tLS0tLS0NClNvY2tldHM6IEItQi1CIEIgDQotLS0tLS0tLQ0KSXRlbSBMZXZlbDogODUNCi0tLS0tLS0tDQo0NSUgaW5jcmVhc2VkIEVuZXJneSBTaGllbGQNCis1MiB0byBtYXhpbXVtIExpZmUNCis2OSB0byBtYXhpbXVtIE1hbmENCis0NyUgdG8gRmlyZSBSZXNpc3RhbmNlDQoyNiUgaW5jcmVhc2VkIFN0dW4gYW5kIEJsb2NrIFJlY292ZXJ5DQo=",
        "retHeader": "502",
        "timeoutParam": 25
    }
}

please fix :( i love using this macro

**Comment by deusmelody** [comment]
same here all day
here is my poeprices log txt:
Request and response:
{
    "added": {
        "browserUrl": "https://www.poeprices.info/api?l=Betrayal&i=UmFyaXR5OiBSYXJlDQpUb3JtZW50IFN0YXINCkxpb24gUGVsdA0KLS0tLS0tLS0NCkV2YXNpb24gUmF0aW5nOiA0NzUgKGF1Z21lbnRlZCkNCi0tLS0tLS0tDQpSZXF1aXJlbWVudHM6DQpMZXZlbDogNzANCkRleDogMTUwICh1bm1ldCkNCi0tLS0tLS0tDQpTb2NrZXRzOiBHLUcgRyANCi0tLS0tLS0tDQpJdGVtIExldmVsOiA3NQ0KLS0tLS0tLS0NCisyIHRvIExldmVsIG9mIFNvY2tldGVkIE1pbmlvbiBHZW1zDQoyNSUgaW5jcmVhc2VkIEV2YXNpb24gUmF0aW5nDQorODcgdG8gbWF4aW11bSBMaWZlDQo4LjcgTGlmZSBSZWdlbmVyYXRlZCBwZXIgc2Vjb25kDQorMzAlIHRvIExpZ2h0bmluZyBSZXNpc3RhbmNlDQoxMCUgaW5jcmVhc2VkIFN0dW4gYW5kIEJsb2NrIFJlY292ZXJ5DQo=&w=1",
        "encodedData": "UmFyaXR5OiBSYXJlDQpUb3JtZW50IFN0YXINCkxpb24gUGVsdA0KLS0tLS0tLS0NCkV2YXNpb24gUmF0aW5nOiA0NzUgKGF1Z21lbnRlZCkNCi0tLS0tLS0tDQpSZXF1aXJlbWVudHM6DQpMZXZlbDogNzANCkRleDogMTUwICh1bm1ldCkNCi0tLS0tLS0tDQpTb2NrZXRzOiBHLUcgRyANCi0tLS0tLS0tDQpJdGVtIExldmVsOiA3NQ0KLS0tLS0tLS0NCisyIHRvIExldmVsIG9mIFNvY2tldGVkIE1pbmlvbiBHZW1zDQoyNSUgaW5jcmVhc2VkIEV2YXNpb24gUmF0aW5nDQorODcgdG8gbWF4aW11bSBMaWZlDQo4LjcgTGlmZSBSZWdlbmVyYXRlZCBwZXIgc2Vjb25kDQorMzAlIHRvIExpZ2h0bmluZyBSZXNpc3RhbmNlDQoxMCUgaW5jcmVhc2VkIFN0dW4gYW5kIEJsb2NrIFJlY292ZXJ5DQo=",
        "encodingError": "",
        "league": "Betrayal",
        "requestUrl": "https://www.poeprices.info/api?l=Betrayal&i=UmFyaXR5OiBSYXJlDQpUb3JtZW50IFN0YXINCkxpb24gUGVsdA0KLS0tLS0tLS0NCkV2YXNpb24gUmF0aW5nOiA0NzUgKGF1Z21lbnRlZCkNCi0tLS0tLS0tDQpSZXF1aXJlbWVudHM6DQpMZXZlbDogNzANCkRleDogMTUwICh1bm1ldCkNCi0tLS0tLS0tDQpTb2NrZXRzOiBHLUcgRyANCi0tLS0tLS0tDQpJdGVtIExldmVsOiA3NQ0KLS0tLS0tLS0NCisyIHRvIExldmVsIG9mIFNvY2tldGVkIE1pbmlvbiBHZW1zDQoyNSUgaW5jcmVhc2VkIEV2YXNpb24gUmF0aW5nDQorODcgdG8gbWF4aW11bSBMaWZlDQo4LjcgTGlmZSBSZWdlbmVyYXRlZCBwZXIgc2Vjb25kDQorMzAlIHRvIExpZ2h0bmluZyBSZXNpc3RhbmNlDQoxMCUgaW5jcmVhc2VkIFN0dW4gYW5kIEJsb2NrIFJlY292ZXJ5DQo=",
        "retHeader": "502",
        "timeoutParam": 25
plz fix this macro

**Comment by deusmelody** [comment]
https://www.pathofexile.com/forum/view-thread/1216141/.
### Try not to "spam" their thread if a few other reports with the same error description were posted in the last hours.
#####

Request and response:
{
    "added": {
        "browserUrl": "https://www.poeprices.info/api?l=Betrayal&i=UmFyaXR5OiBSYXJlDQpNaXJhY2xlIEh1bmdlcg0KVmFhbCBCbGFkZQ0KLS0tLS0tLS0NCk9uZSBIYW5kZWQgU3dvcmQNClBoeXNpY2FsIERhbWFnZTogNjgtMTI3IChhdWdtZW50ZWQpDQpFbGVtZW50YWwgRGFtYWdlOiA0NS04NSAoYXVnbWVudGVkKQ0KQ3JpdGljYWwgU3RyaWtlIENoYW5jZTogNS4wMCUNCkF0dGFja3MgcGVyIFNlY29uZDogMS4zMA0KV2VhcG9uIFJhbmdlOiA5DQotLS0tLS0tLQ0KUmVxdWlyZW1lbnRzOg0KTGV2ZWw6IDY0DQpTdHI6IDExMw0KRGV4OiAxMTMNCi0tLS0tLS0tDQpTb2NrZXRzOiBSLUctQiANCi0tLS0tLS0tDQpJdGVtIExldmVsOiA3Ng0KLS0tLS0tLS0NCis0NjAgdG8gQWNjdXJhY3kgUmF0aW5nDQotLS0tLS0tLQ0KNDglIGluY3JlYXNlZCBQaHlzaWNhbCBEYW1hZ2UNCkFkZHMgNDUgdG8gODUgRmlyZSBEYW1hZ2UNCiszNyUgdG8gR2xvYmFsIENyaXRpY2FsIFN0cmlrZSBNdWx0aXBsaWVyDQorMzklIHRvIExpZ2h0bmluZyBSZXNpc3RhbmNlDQorMTUgdG8gQWNjdXJhY3kgUmF0aW5nDQo=&w=1",
        "encodedData": "UmFyaXR5OiBSYXJlDQpNaXJhY2xlIEh1bmdlcg0KVmFhbCBCbGFkZQ0KLS0tLS0tLS0NCk9uZSBIYW5kZWQgU3dvcmQNClBoeXNpY2FsIERhbWFnZTogNjgtMTI3IChhdWdtZW50ZWQpDQpFbGVtZW50YWwgRGFtYWdlOiA0NS04NSAoYXVnbWVudGVkKQ0KQ3JpdGljYWwgU3RyaWtlIENoYW5jZTogNS4wMCUNCkF0dGFja3MgcGVyIFNlY29uZDogMS4zMA0KV2VhcG9uIFJhbmdlOiA5DQotLS0tLS0tLQ0KUmVxdWlyZW1lbnRzOg0KTGV2ZWw6IDY0DQpTdHI6IDExMw0KRGV4OiAxMTMNCi0tLS0tLS0tDQpTb2NrZXRzOiBSLUctQiANCi0tLS0tLS0tDQpJdGVtIExldmVsOiA3Ng0KLS0tLS0tLS0NCis0NjAgdG8gQWNjdXJhY3kgUmF0aW5nDQotLS0tLS0tLQ0KNDglIGluY3JlYXNlZCBQaHlzaWNhbCBEYW1hZ2UNCkFkZHMgNDUgdG8gODUgRmlyZSBEYW1hZ2UNCiszNyUgdG8gR2xvYmFsIENyaXRpY2FsIFN0cmlrZSBNdWx0aXBsaWVyDQorMzklIHRvIExpZ2h0bmluZyBSZXNpc3RhbmNlDQorMTUgdG8gQWNjdXJhY3kgUmF0aW5nDQo=",
        "encodingError": "",
        "league": "Betrayal",
        "requestUrl": "https://www.poeprices.info/api?l=Betrayal&i=UmFyaXR5OiBSYXJlDQpNaXJhY2xlIEh1bmdlcg0KVmFhbCBCbGFkZQ0KLS0tLS0tLS0NCk9uZSBIYW5kZWQgU3dvcmQNClBoeXNpY2FsIERhbWFnZTogNjgtMTI3IChhdWdtZW50ZWQpDQpFbGVtZW50YWwgRGFtYWdlOiA0NS04NSAoYXVnbWVudGVkKQ0KQ3JpdGljYWwgU3RyaWtlIENoYW5jZTogNS4wMCUNCkF0dGFja3MgcGVyIFNlY29uZDogMS4zMA0KV2VhcG9uIFJhbmdlOiA5DQotLS0tLS0tLQ0KUmVxdWlyZW1lbnRzOg0KTGV2ZWw6IDY0DQpTdHI6IDExMw0KRGV4OiAxMTMNCi0tLS0tLS0tDQpTb2NrZXRzOiBSLUctQiANCi0tLS0tLS0tDQpJdGVtIExldmVsOiA3Ng0KLS0tLS0tLS0NCis0NjAgdG8gQWNjdXJhY3kgUmF0aW5nDQotLS0tLS0tLQ0KNDglIGluY3JlYXNlZCBQaHlzaWNhbCBEYW1hZ2UNCkFkZHMgNDUgdG8gODUgRmlyZSBEYW1hZ2UNCiszNyUgdG8gR2xvYmFsIENyaXRpY2FsIFN0cmlrZSBNdWx0aXBsaWVyDQorMzklIHRvIExpZ2h0bmluZyBSZXNpc3RhbmNlDQorMTUgdG8gQWNjdXJhY3kgUmF0aW5nDQo=",
        "retHeader": "000",
        "timeoutParam": 25
    }
}

**Comment by Eruyome** [comment]
Sorry for the late responses, do you still have those issues or where they temporary?
