### ISSUE TITLE
Malformed poe.ninja links

### ISSUE THREAD

**Issue by bokanov** [PoE-TradeMacro/POE-TradeMacro#922]
AHK version: 1.1.30.01
Windows version: Win 10 Home x64 1809 1773.316

Using quick lookup with poe.ninja uses 'filter=' where poe.ninja is expecting 'name='. The page opens just fine and to the correct item category but the individual item search fails because of the malformed request. 

If you manually change the generated url from 'filter=' to 'name=', the individual item search works properly.
![image](https://user-images.githubusercontent.com/47652421/52833920-7061cd80-309c-11e9-9e61-8454335efd15.png)
![image](https://user-images.githubusercontent.com/47652421/52833943-8a031500-309c-11e9-85fa-655477f0d64b.png)

**Comment by Eruyome** [comment]
Thanks, will be fixed in the next update.

**Comment by bokanov** [comment]
Thank you! Great stuff
