### ISSUE TITLE
Ctrl + D for uniques not working since v2.13.1

### ISSUE THREAD

**Issue by Urke9** [PoE-TradeMacro/POE-TradeMacro#926]
_TEMPLATE_ (Remove the explanations here from your post) 

Make sure:
* That you have checked the Wiki/FAQ before creating any issue.
* That poe.trade/GGG's website don't have any issues if loading the script takes too long or failes.

Information to include:
* AHK (including 32/64bit) version if you have any kind of script errors.
* Windows version could be relevant.

Fill out everything that may be relevant and remove everything except these informations below:  

AHK version:
Windows version:

**Comment by Urke9** [comment]
Ctrl + d is not working for uniques on the newest version of trade macro, i have no clue why but it works just fine on the previous version

**Comment by Eruyome** [comment]
Sorry for the late answer.

Are you sure that it's only for uniques or are all tooltips effected? This could be caused by having GDI+ tooltip enabled in the settings.

**Comment by FloxyTek** [comment]
I have the same problem its working for rares, but not for uniques

**Comment by JumpAttacker** [comment]
can confirm this issue
