### ISSUE TITLE
Wont start 

### ISSUE THREAD

**Issue by zNeeeL** [PoE-TradeMacro/POE-TradeMacro#927]
_TEMPLATE_ (Remove the explanations here from your post) 

Make sure:
* That you have checked the Wiki/FAQ before creating any issue.
* That poe.trade/GGG's website don't have any issues if loading the script takes too long or failes.

Information to include:
* AHK (including 32/64bit) version if you have any kind of script errors.
* Windows version could be relevant.

Fill out everything that may be relevant and remove everything except these informations below:  

AHK version:
Windows version: WIN 10 ENT 64 bit
[StartupLog.txt](https://github.com/PoE-TradeMacro/POE-TradeMacro/files/2919002/StartupLog.txt)

https://gyazo.com/75ae33831079286416df1a81b94caf71

**Comment by Eruyome** [comment]
Sprry for the late answer.

Your startuplog shows this HTTP response `Answer: HTTP/1.1 403 Forbidden` which suggests that your request gets stuck on the cloudflare protection page. I'm assuming that you sometimes get such a page where you have to solve a captcha when trying to access the pathofexile website.

Here's a related reddit thread https://www.reddit.com/r/pathofexile/comments/aw2p9j/trying_to_visit_pathofexilecom_and_i_get_this/.

If that's (still) the case then you'll likely have to talk to your provider to get you a new IP address, in the worst case if your provider can't solve it try using a VPN.

If this is not the issue in your case then the error still suggests that you have some issues with your connection to the pathofexile website.
