### ISSUE TITLE
Once restarted my pc, the trade macro keep asking code for command where it should have default 

### ISSUE THREAD

**Issue by dewutbal** [PoE-TradeMacro/POE-TradeMacro#929]
_TEMPLATE_ (Remove the explanations here from your post) 

Make sure:
* That you have checked the Wiki/FAQ before creating any issue.
* That poe.trade/GGG's website don't have any issues if loading the script takes too long or failes.

Information to include:
* AHK (including 32/64bit) version if you have any kind of script errors.
* Windows version could be relevant.

Fill out everything that may be relevant and remove everything except these informations below:  

AHK version:
Windows version:

**Comment by Eruyome** [comment]
Sorry can you describe that issue again? I don't quite understand what's happening.

**Comment by dewutbal** [comment]
Hi,

A window named 'Hotkey Conflict' that ask me to insert the hotkey for
several command, such as OpenWiki, CheckPrice, CheckDetailedPrice etc.

I tried fill all the command as in the default hotkey list such as ctrl + D
etc. Restart the script as the window's instruction but still popping out
the 'Hotkey Confilct' menu.

Thanks very much.

**Comment by Eruyome** [comment]
The conflict should be between the lutbot macro and trademacro. Trademacro can start this macro on startup and it always checks foir conflicts by reading that macros settings.ini.

Try looking at that.

**Comment by dewutbal** [comment]
I didn't use lutbot macro but trade macro is working well after I changed
the settings to default settings.

Most of the command is executed by typing '1' before this, I also don't why
but it is ok already.

Thanks very much for the program and replies.
