### ISSUE TITLE
[Still broken?] Broken advanced search window (mod text label width)

### ISSUE THREAD

**Issue by Eruyome** [PoE-TradeMacro/POE-TradeMacro#93]
![8bkqq5xt](https://cloud.githubusercontent.com/assets/16058242/20340611/b2622f2c-abe2-11e6-89e1-2d769c56df06.png)

**Comment by Eruyome** [comment]
Here's a development version to show the calculated text label width in a console window. ([Dropbox-Link](https://dl.dropboxusercontent.com/u/13620316/POE-TradeMacro.rar))

AHK text label widths don't scale with their content, therefore I calculate the their widths using the largest mod (character count). The other elements x-position is specified like this:
`x+10`
meaning "the right border of the previous element plus 10 pixels". This seems to be failing, though.


![unbenannt](https://cloud.githubusercontent.com/assets/16058242/20344357/b8135544-abf2-11e6-82d7-e25f64642a26.png)

**Comment by avgjoe** [comment]
Came here to report this very bug. Not sure if you were looking for feedback, but the release you posted on dropbox seems to work with all the tests that didn't display correctly with the previous release. Thanks.

**Comment by Eruyome** [comment]
The dropbox-version is exactly the same as the last release, except some added debug output. And yeah, I wanted some feedback.

**Comment by Eruyome** [comment]
I was able to encounter this error now, but I don't know how to replicate it. Can anyone help with that?
