### ISSUE TITLE
Overlays do not work in 2.13.1

### ISSUE THREAD

**Issue by walentaz** [PoE-TradeMacro/POE-TradeMacro#930]
AHK version: 1.1.26.01 32bit
Windows version: Windows 10 10.0.17763.253 64bit

Latest 2.13.1 trade macro won't display any overlays, tho it pops advanced search configuration.  I have backup of 2.12.1 and it works just fine. No errors, no crashes - it just doesn't react to quick price check, item stats, etc, anything that is shown in overlay.

Gonna stick with 2.12.1

**Comment by Eruyome** [comment]
Disable GDI+ tooltip in the settings.

**Comment by walentaz** [comment]
but that disables color customization (I use cyan on black). I guess I'll stick to older version, since I haven't had any issues with it and functionality is not a problem.

**Comment by Eruyome** [comment]
You will get issues though, especially when using the advanced search. New fractured mods, enchantments aren't implicits anymore etc...

GDI+ is broken, I still don't know why and there are more important things to do than to fix it at the moment,

**Comment by walentaz** [comment]
Okay, updated it to latest version, disabled GDI+ and still it doesn't work. WTF??

**Comment by Corsica96** [comment]
I hope we can get a fix to GDI+ soon! I really was digging the color custpmization.

**Comment by Eruyome** [comment]
It is fixed in the upcoming release.
