### ISSUE TITLE
Trade_macro wouldn't start

### ISSUE THREAD

**Issue by vmayhem** [PoE-TradeMacro/POE-TradeMacro#934]
AHK version: 1.1.30.01
Trade_macro version: 2.14.0
Windows 10 Pro 64-bit

Trade_macro folder is located in a custom directory E:\Games\New folder.
When I run the script it starting up until it tries to establish a connection to poe.trade, then it times out.
I get the following error after awhile
![2019-03-08 18_58_50-poe-trademacro](https://user-images.githubusercontent.com/48364882/54049733-01cce700-41e6-11e9-9f95-974f235608e4.png)

By the way, it's not a recent issue, had this issue for about a month or so. Reinstalled AHK and Trade_macro numerous times.

Any ideas?
Thanks!

**Comment by BasDaBas** [comment]
I got the same, But it's the first time i get this error, didn't had it with older versions

**Comment by Eruyome** [comment]
Closed because the issue is so old. Feel free to message again if the issues still persist.
