### ISSUE TITLE
TempHardcore not available

### ISSUE THREAD

**Issue by Orcbulge** [PoE-TradeMacro/POE-TradeMacro#935]
Cant change to pricecheck in Hardcore Synthesis. tried to double click the icon and swithch in the menu but it didnt work. I switched it but the prices are still only Standard and hardcore

AHK version: 2.14.0
Windows version: 10

**Comment by Supportic** [comment]
Cannot switch from standard to tmp league. After clicking OK it will not save the selection.

**Comment by Orcbulge** [comment]
Redownloaded and it ixed it now
