### ISSUE TITLE
Either wrong version number or update bug from 3/9 morning download

### ISSUE THREAD

**Issue by applepuppy** [PoE-TradeMacro/POE-TradeMacro#936]
After downloading the latest version of PoE Trade Macro from GetHub v.2.14.1 and running the macro I get an update notification prompt reporting that I'm running 2.14.0. This seems odd because it's marked as 2.14.1 but it's displaying a build number from one iteration ago.

When I hit the update button, it prompts me to overwrite the current version "Folder (D:\POE-TradeMacro) is not empty, overwrite it after making a backup?". The script then fails with red letter text stating that "the script could not run successfully."
 
![script error](https://user-images.githubusercontent.com/48388004/54074176-37a0b880-4244-11e9-9b2d-fde231516f14.jpg)

I am then returned to the update prompt screen and am only able to break the loop by hitting the close button. 

AHK version: 10.0
Windows version: 10 Pro 64 bit

**Comment by gabrieltaets** [comment]
I got the same error, even downloading latest (2.14.1) manually from GitHub, it says I have 2.14.0 and prompts for updating and fails just like that.
I'd suggest downloading 2.14.1 from GitHub and just ignoring the update prompt.

**Comment by Eruyome** [comment]
zip file is updated, for some reason the version file wasn't correctly uploaded.
