### ISSUE TITLE
Update recursion

### ISSUE THREAD

**Issue by oisterjosh** [PoE-TradeMacro/POE-TradeMacro#937]
AHK version:Version 1.1.26.01
Windows version: Windows 10

After updating to 2.14.1 (both by in-macro update button and by manually downloading from github), prompts to update from 2.14.0 to 2.14.1. Repeated many times

**Comment by zombodotcom** [comment]
same, ive also completely removed the old trade macro, and manually downloaded the new one and place it in, still says im at 2.14.0 when I just downloaded and am using the 2.14.1 zip from the releases lol

**Comment by Eruyome** [comment]
zip file is updated, for some reason the version file wasn't correctly uploaded.
