### ISSUE TITLE
Can't Search for Crafted Prefix

### ISSUE THREAD

**Issue by livejamie** [PoE-TradeMacro/POE-TradeMacro#938]
I think the crafted life isn't being read correctly?

https://i.imgur.com/wM9peli.png
![image](https://user-images.githubusercontent.com/49513/54079822-c0494400-4298-11e9-9171-48866a771ca6.png)

![image](https://user-images.githubusercontent.com/49513/54079830-e40c8a00-4298-11e9-97eb-2d6f7958988b.png)

```
Rarity: Rare
Blight Spiral
Iron Ring
--------
Requirements:
Level: 57
--------
Item Level: 72
--------
Adds 1 to 4 Physical Damage to Attacks
--------
+23 to maximum Energy Shield
24% increased Rarity of Items found
+12% to all Elemental Resistances
+44% to Lightning Resistance
+27 to maximum Life (crafted)
```

**Comment by Eruyome** [comment]
That should be fixed by now, can you confirm?
