### ISSUE TITLE
Items are searched only on Standard League

### ISSUE THREAD

**Issue by TheMarc258** [PoE-TradeMacro/POE-TradeMacro#939]
Hello,

I am playing on the new League Synthesis and always i am seraching for an item on the website it is set to Standard, however, i want the Synthesis League to be set. I am not very good programmer and i don't know how to fix the issue by myself.

Best regards,
One of POE-TradeMacro users :)

AHK version: v1.1.30.00
Windows version: 10 Home

**Comment by altimas** [comment]
I am having the same issue with the most recent version and my config is set to tempstandard like it's supposed to be.

**Comment by Winmx1** [comment]
I have the same problem, even after the "update" that I get when loading the script... any fix for this?

**Comment by Winmx1** [comment]
> Hello,
> 
> I am playing on the new League Synthesis and always i am seraching for an item on the website it is set to Standard, however, i want the Synthesis League to be set. I am not very good programmer and i don't know how to fix the issue by myself.
> 
> Best regards,
> One of POE-TradeMacro users :)
> 
> AHK version: v1.1.30.00
> Windows version: 10 Home

Okay so I figured out how to fix this! You have to go to C:/User/"username"/Documents
Then delete the PoE-TradeMacro folder, and restart the macro... and that's what worked for me!

**Comment by Winmx1** [comment]
> I am having the same issue with the most recent version and my config is set to tempstandard like it's supposed to be.

Okay so I figured out how to fix this! You have to go to C:/User/"username"/Documents
Then delete the PoE-TradeMacro folder, and restart the macro... and that's what worked for me!

**Comment by Eruyome** [comment]
Fixed for a while now.
