### ISSUE TITLE
Poe Trade macro stopped working after patch

### ISSUE THREAD

**Issue by kick-darkangel** [PoE-TradeMacro/POE-TradeMacro#94]
Just to let you know that at least for me after the 2.4.2 patch both poe trade macro and poe item stopped working, tried both the new 64 version of the game and the previous, reinstalled everything from scratch, also edited the macro for the new x64.exe filename and still not working, also fyi other macros that are more simple like terminate poe, check remaining etc after editing to the new path for the exe are working as usual.

**Comment by jn64** [comment]
There's more than just the exe name to change. You can look at #96 if you want to edit your own copy for now.

**Comment by Eruyome** [comment]
I fully expected this to happen, haven't had the time to check the new patch out so far.
