### ISSUE TITLE
poe.trade loading issues on Firefox

### ISSUE THREAD

**Issue by Elimitless** [PoE-TradeMacro/POE-TradeMacro#940]
When using Ctrl+Q or Ctrl+Alt+D "Open on poe.trade" option, one of the two situations happen.

1. If firefox is not already open, it opens the browser and loads the url successfully, however firefox is missing all extentions/addons, bookmarks, history... etc.
2. If firefox is already open the url fails to load. It stops loading and immediately displays a plain white webpage.

* AHK 1.1.30.01 Unicode 32-bit
* Windows 7 Pro 64-bit

Edit:
I noticed the links generated are http, However https is whats used any other time i visit poe.trade.

**Comment by Eruyome** [comment]
Is this still an issue and do you have it also with for exampl chrome (temporarily setting it as default browser or adding a browser path in the settings)?
