### ISSUE TITLE
script does not run

### ISSUE THREAD

**Issue by Altogolik** [PoE-TradeMacro/POE-TradeMacro#941]
https://i.gyazo.com/b8a8e7b951ac44a897e49691c855d022.png
script does not run

AHK version: Last
Windows version: 10 64bit

**Comment by LostC0ntrol** [comment]
i have the same problem and cant find a fix for it and iam not using any antivirus ...

**Comment by Eruyome** [comment]
Closed because the issue is so old. Feel free to message again if the issues still persist.
