### ISSUE TITLE
Merge_TradeMacro.ahk virus

### ISSUE THREAD

**Issue by Kecupko** [PoE-TradeMacro/POE-TradeMacro#943]
AHK version:  v1.1.30.01
Windows version: 8.1

Hello,
starting today my anti virus (avast) started to complain about virus after I turn on trade macro.
I am using 2.14.1 from the start and there was not any problem until today (I did not notice any update today, maybe I am wrong)
Do you know why? Thanks for your help :)

![1](https://user-images.githubusercontent.com/40704283/54209902-d6e0dc80-44de-11e9-9cce-367f80496540.PNG)

**Comment by kieran-boyle** [comment]
Funny,I have had exactly the same issue today with AVG despite there not being an update. (Win 7, 64 bit) been using for several seasons without issue until now.

**Comment by Itreax** [comment]
Hi guys i got exactly the same problem today, the problem happen only with this avast, I desactivate him for the moment and no problem. I hope that will be fixed soon (got Win 10 64 bits)

**Comment by kieran-boyle** [comment]
After updating AVG the problem seems fixed. Be worth checking for an update for avast

**Comment by besplash** [comment]
Avast update does not fix it. You have to add the folder to the exceptions for now. Hopefully something will be done about it, as having a folder as an exception sucks

**Comment by Fortyz** [comment]
Same problem as of this morning

**Comment by Kecupko** [comment]
So, did anyone find the way how to fix that?

**Comment by Fykee25** [comment]
Same problem
![shit](https://user-images.githubusercontent.com/49077231/55256069-7252ab00-525c-11e9-9de8-00c48912ecfa.png)

**Comment by abbacus86** [comment]
After auto updating using the main channel from a previously working Razunter/TradeMacroInit.ahk temp fix for synthesis flashback league applied. 
AHK V1.1.290.00
Windows 10

Flagged in AVG as IDP.Generic

**Comment by LillieSatou** [comment]
Uninstall AVG or Avast. They have a tendency to **bypass your exclusions and keep deleting said file(s).**

If you are NOT on Windows 10 yet, GET ON HERE. Microsoft actually made a half-DECENT scanner.

**Comment by Eruyome** [comment]
Can't do much about this. I have added some info to these issues to the FAQ and linked this thread.

**Comment by Ealstrom** [comment]
yep, this keeps happening, now I can't even unzip the files

![sshot-18](https://user-images.githubusercontent.com/82973077/115609814-65c7a200-a2be-11eb-9dd1-cf122441be22.png)
