### ISSUE TITLE
Item Stats Copy Format Not Working with PoB

### ISSUE THREAD

**Issue by coozmak** [PoE-TradeMacro/POE-TradeMacro#944]
This one is an issue / feature request.

Trying to import my current items to PoB and the value that's copied uses a different format than what's used by PoB for the crafted mod portion. I realize that this macro is designed to work with the pricing websites, but figure it could also maybe use an additional macro to copy the item for PoB. 

PoB uses the formatting shown below for +Max Energy Shield:
{crafted}{range:0.951}+(35-45) to maximum Energy Shield

Whereas what's copied using the macro:
+45 to maximum Energy Shield (crafted)

AHK version: 1.1
Windows version: Win10

**Comment by Pegoth** [comment]
The item info that gets copied is from the game not from PoE Trade Macro. That gets parsed by the script to be able to display other info (e.g. prices).
