### ISSUE TITLE
TradeMacro does not run

### ISSUE THREAD

**Issue by Wicke2d** [PoE-TradeMacro/POE-TradeMacro#945]
AHK version: 1.1.30.01
Windows version: 10 Pro

I opened it up like normal at first; Run_TradeMacro.ahk then start the game in windowed borderless mode. I soon noticed the script wasn't working, though the tray icon was still there. It disappeared soon thereafter, so I tried restarting it, but I got an error message stating Merge_TradeMacro.ahk was not found. I checked and sure enough it's not there. I updated the TradeMacro version to the latest, and after starting the script it behaved like normal, except that it promptly shut itself off. After that I get the same error message.

How do I fix this?

**Comment by Wicke2d** [comment]
Ok well, I did suspect it got removed due to an antivirus problem, like Avast that I'm using, I was just doubtful because I didn't think they did so without asking for permission or at least notifying before removing a file from my computer just like that.

Avast did indeed quarantine it. I restored it and made it an exception. Very strange that it can do that.

**Comment by Eruyome** [comment]
Well... hard to do anything about these antivir issues. It's always surprising how persistent they can be, if you make an exception for a folder the software should respect that.

I really don't know how to solve these issues.
