### ISSUE TITLE
macro freezes my pc

### ISSUE THREAD

**Issue by jayer7** [PoE-TradeMacro/POE-TradeMacro#946]
after the update i can't seem to run it properly. com freezes every time it starts. updated ahk and downloaded the previous versions it still happens

**Comment by Spirituus** [comment]
Got same issue, mouse cursor moves +- 80% slower as well as all performance, problem solved once poe trade macro is getting closed down. What's more important @ ALT CTR DEL screen speed of cursor getting back to normal. Like this since yesterday.

**Comment by OsirisArguello** [comment]
I have the exact same problem. Never had any issues until last update.
I'm running the macro on Win 7.

**Comment by ChupaUnkas** [comment]
Yeah same here it slows my mouse and really fucks with my PC.

**Comment by OsirisArguello** [comment]
Does anyone know if this has to do with the antivirus? I'm running Avast.

**Comment by zeru0** [comment]
I have the same problem. Also running Avast. Avast's behavior shield detected the merge script as a threat initially when I was updating to a new TradeMacro version, and that's the first time the problem started. However, even after excluding it in Avast, the issue repeats shortly after starting the macro.

**Comment by Padlen** [comment]
As soon as I enable macro, I get this [http://ipic.su/img/img7/fs/2.1552845704.png](url) After disabling macro GPU load falls back to 1-5%.

**Comment by TJDemigod** [comment]
I had the same problem.  The macro ran smoothly up until the most recent patch.

My Problem: Start macro, PC and mouse slows down, AHK shows as 'suspended' in task manager.
My Solution: AVG placed AHK into quarantine, remove it from quarantine and create an exception for it.

Macro has run smoothly since.

**Comment by jayer7** [comment]
can confirm after uninstalling avast the macro runs smoothly. using another anti virus instead this isnt the first time avast has been giving me unnecessary problems

**Comment by Fjolset** [comment]
I'm having the same problem. Any way to fix this without uninstalling avast?

**Comment by jayer7** [comment]
not any way i know for now but I'd recommend installing malwarebytes instead of avast. malwarebytes doesn't have this problem and it's a better alternative to avast for me

**Comment by RanBad** [comment]
> I'm having the same problem. Any way to fix this without uninstalling avast?

Protection>Virus Chest> choose the poe trade file (on the right side) "more" > restore and add as exception.

worked for me

**Comment by Eruyome** [comment]
Nothing I can do from my side.
I have added this to the FAQ page in the wiki.
