### ISSUE TITLE
Problem with advanced price check

### ISSUE THREAD

**Issue by Sumidor** [PoE-TradeMacro/POE-TradeMacro#948]
Hello,

I am having an issue when running the advanced trade check (Ctrl+Alt+D) I get the popup that asks for what variables to check but once i click on search nothing happens.

If I click on open in poe.trade button a browser open with the correct information.

If I use the regular price check (Ctrl+D) it works fine and gives me an estimated price.

AHK version: 1.1.30.01
Windows version: 10
Thanks,

**Comment by Eruyome** [comment]
Can you confirm whether there's still an issue? If so make sure that you don't have the GDI+ tooltip enabled in the ItemInfo settings.
