### ISSUE TITLE
Timeout When Searching Ctrl+D (Rares)

### ISSUE THREAD

**Issue by mucitrus** [PoE-TradeMacro/POE-TradeMacro#950]
I can search for Legendarys with CTRL + D with a fast respons, but not on RARES.
(I can search for Rares at the site itself without any delay)

The Issue started after the last update in version -> 2.14.1

Keep up the awesome work, love the plugin!

**Comment by iTzSTU4RT** [comment]
yeah same here!

**Comment by popers** [comment]
same here

**Comment by Eruyome** [comment]
Sorry for the late answer, my best guess is that this was a temporary issue with the connetion to poeprices.info and should be resolved.

I'm closing this issue but if you're still having issues just comment again.
