### ISSUE TITLE
Ctrl+D taking a long time and not responding

### ISSUE THREAD

**Issue by iTzSTU4RT** [PoE-TradeMacro/POE-TradeMacro#951]
When I hit Ctrl+D on an item it akes about 2 mintues to load getting price prediction and then comes up with:

ERROR:Client disconnected

AHK version: Latest (checked for update)
Windows version: Windows 10

**Comment by Eruyome** [comment]
Are you still experiencing this issue? 
If so, do you have a slow internet connection, or issues with that connection in general?
