### ISSUE TITLE
TradeMacro not showing results

### ISSUE THREAD

**Issue by mRniiat** [PoE-TradeMacro/POE-TradeMacro#952]
Started playing the current PoE League today and tried using the macro first time this league.
Advanced search (ctrl+alt+d by default) opens just fine, also options (F10), also Lutbot Macro starts fine automatically.
But no matter if clicking on search on advanced search or just hovering an item pressing ctrl+d, the search result, that usually shows some items including the prices does not appear.
Both the macro and PoE are running with admin privileges like always, there were no changes at all to my system.
Last time the macro definitely worked for me was around in the middle of the last league when i quit playing .. 
Rest of the macro works fine ( open in browser, open wiki, etc .. ) 

I'm running Win 10 Pro x64 on 16 Gigs DDR4 & a Ryzen 1600x with AHK v1.1.27.03

**Comment by mRniiat** [comment]
actually just managed to fix the issue.
i tried to disable the GDI+ and reenable it after restarting TradeMacro based on the comments on issue #926.
Just in case i'm not the only person having this issue

**Comment by martea** [comment]
Hmm, experiencing issues with ctrl+d, every other macro works but the window doesent pop

**Comment by dariumz** [comment]
Same Issue as Martea, all over keys are working, but not the price check hotkeys, even changed it to Alt+D to avoid the overlap, still nothing.
