### ISSUE TITLE
"Invalid Class String" Error

### ISSUE THREAD

**Issue by POE3759** [PoE-TradeMacro/POE-TradeMacro#956]
Windows 8.1 (64 Bit)
AHK: 1.1.30.01 

![Screenshot_1](https://user-images.githubusercontent.com/48732854/54634510-6cf2a500-4a93-11e9-8f94-0c22eaa0ff89.png)

**Comment by Eruyome** [comment]
Looking that up I can find a few references, I believe the error is related to WinHttpRequest.

1. https://www.autohotkey.com/boards/viewtopic.php?f=76&t=60409

2. https://autohotkey.com/board/topic/121389-invalid-class-string/ which links to 3.

3. https://autohotkey.com/board/topic/91673-tips-fix-the-error-0x800401f3-invalid-class-string/

The initial post in 3. describes a solution but I don't know whether that is applicable in your case.
