### ISSUE TITLE
Error at 2165 can not open maplist.txt

### ISSUE THREAD

**Issue by kronusss** [PoE-TradeMacro/POE-TradeMacro#958]
AHK version: AutoHotkey Unicode 64-biT
Windows version: WINDOWS 7 HOME premium sp1

![image](https://user-images.githubusercontent.com/48836655/54840193-a987f180-4c89-11e9-893d-82e04727cc28.png)

![image](https://user-images.githubusercontent.com/48836655/54840219-bb699480-4c89-11e9-9fb7-c05a6cc901ed.png)

Fresh installed, unzipped a few times. tried running as admin and got the same result. i searched for the same issue but i did not find. Sorry if i missed it. I deleted the files as described in the second error message. thank you in advance.

**Comment by Eruyome** [comment]
Sorry for the late answer, is this still an issue? If you please make sure that the mentioned file exists and can be openen manually with a text editor.
