### ISSUE TITLE
Script crashes after launch

### ISSUE THREAD

**Issue by Antoni0** [PoE-TradeMacro/POE-TradeMacro#960]
Hi there.

AHK version: 1.1.30.01
Windows version: 8.1

POE TradeMacro quietly crashes immediately after launch. After this, the restart becomes impossible due to the lack of the Merge_TradeMacro file. I have not found any log explaining the crash reason.

A bit more in steps:

1. I unpack the POE-TradeMacro-2.14.1.zip archive, for example, in the d: \ poe_macro directory
2. Run Run_TradeMacro.ahk (I tried it with administrator rights too)
3. A macro icon appears in the tray.
4. After some time (a few seconds) the icon disappears from the tray
5. Run_TradeMacro.ahk and Merge_TradeMacro.ahk are also missing in their places.
6. Re-unpacking in d: \ poe_macro is not possible. Archiver shows diagnostic message "Access Denied"

Before the Synthesis, everything worked fine. I ask you to help deal with the problem, perhaps there is some kind of log of this crash somewhere and the reason maybe is rather trivial. 

Thanks.

**Comment by audleman** [comment]
Same here. I'm going to try installing a previous release to see if it helps.

**Comment by Antoni0** [comment]
The AHK version 1.1.30.01 that I have installed is the latest stable at the moment. The next version 2.0 is in alpha, and apparently it refused to support backward compatibility.

Were you updated to version 2.0 alpha to fix the problem?

**Comment by Antoni0** [comment]
I solved the problem. My antivirus considered script behavior dangerous and blocked it by killing the process during execution. This left artifacts and locks, so until the system was rebooted, it was not even possible to unpack the files in the same directory. Also, as I understand it, the script, when launched, performs the merging of several scripts into the resulting script. This process did not end with antivirus.

Adding POE TradeMacro to anivirus exceptions made it possible to achieve stable execution of the script.
