### ISSUE TITLE
PIece of Brutality checks "non-unique" when using ctrl-D, no results

### ISSUE THREAD

**Issue by JaredKreft** [PoE-TradeMacro/POE-TradeMacro#961]
When you use CTRL-D on a Piece of Brutality, it checks the non-unique box in the search form on poe.trade so no results show up. POE Trade lists these as uniques.

**Comment by gibbed** [comment]
What gets copied to the clipboard when you CTRL-C one of these?

**Comment by JaredKreft** [comment]
Rarity: Unique

Second Piece of Brutality

Imperial Staff Piece

--------

Item Level: 84

--------

This item will transform when correctly arranged with other items.

**Comment by gibbed** [comment]
Looks like this is due to https://github.com/PoE-TradeMacro/POE-TradeMacro/blob/master/data/Uniques.txt not containing these items. Maybe needs an update?

**Comment by gibbed** [comment]
Oh, actually this is due to a hack put in place here:

https://github.com/PoE-TradeMacro/POE-TradeMacro/blob/master/resources/ahk/TradeMacro.ahk#L469

So it looks like poe.trade fixed this on their end.

**Comment by Eruyome** [comment]
Fixed.
