### ISSUE TITLE
Parsing the league data (json) from the Path of Exile API failed.

### ISSUE THREAD

**Issue by agGravity** [PoE-TradeMacro/POE-TradeMacro#963]
AHK version: v1.1.30.01 (Unicode 64-bit)
Windows version: Windows 10 Home Version 1809
POE-TradeMacro-2.14.1

![image](https://user-images.githubusercontent.com/49086369/55271561-0173b900-5285-11e9-8b8d-a40d4a50c1ed.png)

I've deleted the setting in document and the PoE-Trade Macro file and redownloaded. No success on either. No matter what I attempt I keep getting the same error. Been happening for the past 2 days.

I tried other troubleshooting found in this page and found no success

[StartupLog.txt](https://github.com/PoE-TradeMacro/POE-TradeMacro/files/3025148/StartupLog.txt)

**Comment by rigis1** [comment]
[+1](https://imgur.com/uqkQxOA)

**Comment by agGravity** [comment]
Disabling Anti-Virus doesn't work for me. Same error is repeated.

**Comment by fragfaq** [comment]
> Disabling Anti-Virus doesn't work for me. Same error is repeated.

Run from administrati and everything works perfectly. I hope it help

**Comment by agGravity** [comment]
> Run from administrati and everything works perfectly. I hope it help

I feel like an idiot. Issue resolved.
