### ISSUE TITLE
No option to select Flashback league in settings

### ISSUE THREAD

**Issue by Razunter** [PoE-TradeMacro/POE-TradeMacro#970]
v2.14.1

To fix it modify TradeMacro\resources\ahk\TradeMacroInit.ahk:
Remove `TradeFunc_CheckIfCloudFlareBypassNeeded()` from line 143 and put in on line 137 so it looks like this:
```
; }

TradeFunc_CheckIfCloudFlareBypassNeeded()

TradeGlobals.Set("Leagues", TradeFunc_GetLeagues())
Sleep, 200
ReadTradeConfig("", "config_trade.ini", _updateConfigWrite)
```

**Comment by Tyrael** [comment]
I can confirm that after this change I can see all of the leagues (including flashback and even the console ones) in the settings dropdown

**Comment by Byngalo** [comment]
Use NotePad++ for better quality of life!

**Comment by d5heilman** [comment]
Didn't work for me.

**Comment by Tyrael** [comment]
@d5heilman you have to quit the trademacro and after starting up the modified version you can change the league in the settings

**Comment by d5heilman** [comment]
It just tells me that file doesn't exist now when I go to restart.

**Comment by d5heilman** [comment]
How do you edit the script besides right-click open with notepad. As soon as I do that then it changes it from Autohotkey script to a text file.

**Comment by d5heilman** [comment]
Yea i give up, hopefully they update it soon.

**Comment by Razunter** [comment]
> How do you edit the script besides right-click open with notepad. As soon as I do that then it changes it from Autohotkey script to a text file. I tried adding .ahk to the end but that doesnt work either.

With [Notepad++](https://notepad-plus-plus.org/), for example, as it was mentioned above.

You can download modified file here: https://gist.github.com/Razunter/ec5dc969a0712de2dfa95e03b1f6a715

**Comment by d5heilman** [comment]
Great that worked, thank you!!!

**Comment by snapz** [comment]
I think this option blacklist our ip from cloudflare. I have cloudflare on path of exile website now all time i try to load a page. And i cant use the macro anymore.

**Comment by Razunter** [comment]
@snapz I don't see how this could be related. This code was executing before too, just in the wrong order.

**Comment by snapz** [comment]
I dont know but since this tweak, i have cloudflare verification on each page of path of exile website.
So i cant use anymore poe trade macro or import on pob by profile.

I hope it will work after some hour.

**Comment by Lox90** [comment]
@Razunter That's what my TradeMacroInit.ahk file looks like already, but it still doesn't let me select flashback league in the settings. Just hc/standard and tmphc/standard.

**Comment by Razunter** [comment]
@Lox90 have you tried downloading modified version from [here](https://gist.github.com/Razunter/ec5dc969a0712de2dfa95e03b1f6a715)?

**Comment by Lox90** [comment]
@Razhunter Thanks, It works now!

**Comment by joetunheim** [comment]
I tried both: changing manually, replacing the file from the link and lastly removed and unpacked the whole tm folder and repeated the steps. no flashback league.

**Comment by LoneWolfHowl** [comment]
Worked for me:
https://imgur.com/a/k427RdH

**Comment by joetunheim** [comment]
> Worked for me:
> https://imgur.com/a/k427RdH

lucky you.

**Comment by JoshMike** [comment]
This works thank you!
