### ISSUE TITLE
Hello I have a suggestion. with korean version in Kakao

### ISSUE THREAD

**Issue by Nameless0ne** [PoE-TradeMacro/POE-TradeMacro#974]
Today korea publishing POE so have another client name on it

so i modified 
POE-TradeMacro\resources\ahk\POE-ItemInfo.ahk file like that

GroupAdd, PoEWindowGrp, Path of Exile ahk_class POEWindowClass ahk_exe PathOfExile.exe
GroupAdd, PoEWindowGrp, Path of Exile ahk_class POEWindowClass ahk_exe PathOfExileSteam.exe
**GroupAdd, PoEWindowGrp, Path of Exile ahk_class POEWindowClass ahk_exe PathOfExile_KG.exe**
GroupAdd, PoEWindowGrp, Path of Exile ahk_class POEWindowClass ahk_exe PathOfExile_x64.exe
GroupAdd, PoEWindowGrp, Path of Exile ahk_class POEWindowClass ahk_exe PathOfExile_x64Steam.exe
**GroupAdd, PoEWindowGrp, Path of Exile ahk_class POEWindowClass ahk_exe PathOfExile_x64_KG.exe**

Could you include these fixes in the next patch?

**Comment by aRTy42** [comment]
Sure, I'll include that in the next ItemInfo version, so it will eventually be included in the TradeMacro. It should be in the next major version for Legion league.
