### ISSUE TITLE
Fallback Request Error During download

### ISSUE THREAD

**Issue by Flagshipfail** [PoE-TradeMacro/POE-TradeMacro#975]
I have been getting this error for the past week when trying to use the trade macro. Though it could have been cause the trade site was down, but I have had the issues at different times of day throughout the week. I reinstalled AHK and deleted the trade macro as well as moving the macro folder to different file paths. Not sure what to do.

![Error](https://user-images.githubusercontent.com/12223134/58771048-03007c80-8567-11e9-8e5b-53c595b13e5b.png)

AHK version:1.1.26.01
Windows version:Windows 10

**Comment by aRTy42** [comment]
Just to be clear: This only means that the Ctrl+C function on currency does not show the latest conversion to chaos rates. Ctrl+D on currency should work, because that uses poe.trade. Ctrl+D or Ctrl+Alt+D on other items should also work just fine.
It is entirely possible that you had several connection issues to poe.ninja. If you can manage without Ctrl+C for currency and you don't notice any other issues, then just keep using the script for now.

**Comment by Flagshipfail** [comment]
Several connection issues? 4-5 times a day for a week all at different times of day? I guess I forgot to mention I cant change leagues and I am stuck in the Xbox synthesis flashback

**Comment by Flagshipfail** [comment]
Just logged in to test the Ctrl+D and Ctrl+Alt+D and the all say Error predicted search has encountered an issue: Returned message: League is not active. Private leagues are not supported now.

**Comment by aRTy42** [comment]
Open the settings menu (double click on the black trademacro icon or right click -> settings). At the top center should be a league selection drop down menu. What do you have there?

**Comment by Flagshipfail** [comment]
The drop down has all the leagues it seems. When I am in game and try and change the league by doing Ctrl+L it gives me the error in the picture above.

**Comment by aRTy42** [comment]
Which league is selected in the drop down? "eventstandard" would be synth flashback (and I have no idea right now if the script recognises the xbox variant).

**Comment by Flagshipfail** [comment]
PS4 Synthesis event

**Comment by aRTy42** [comment]
Is PS4 synthesis flashback the league you want?
I'm not sure whether poe.ninja handles PS4/Xbox properly. The same is true for the predictive (machine learning) search function with Ctrl+D for rare items.
Does Ctrl+D work on uniques? Does Ctrl+Alt+D work on rares or uniques?

**Comment by Flagshipfail** [comment]
I think I wasted your time. The trade macro it seems to have defaulted to the console editions and as such caused the error. Once I changed the league in the settings it seems to have started up fine. Thank you for the help.

**Comment by aRTy42** [comment]
Ok. Well enough. At least it's fixed. Have fun in flashback.
