### ISSUE TITLE
ScrollTabLeft & ScrollTabRight

### ISSUE THREAD

**Issue by Jliu3155** [PoE-TradeMacro/POE-TradeMacro#977]
Hi, the Ctrl + Mousewheel Up/Down to move through stash tabs isn't working after downloading the latest macro

**Comment by Eruyome** [comment]
Works fine for me. Are you sure it's not disabled in the settings? You could also try resetting your config files. Right click the tray icon -> open user folder.

**Comment by Jliu3155** [comment]
Damn, that was a fast response. I just reinstalled everything and it works fine. Thanks
