### ISSUE TITLE
TradeMacro doesn't launch

### ISSUE THREAD

**Issue by HolyGasCan** [PoE-TradeMacro/POE-TradeMacro#979]
AHK version:
1.1.30.03 64bit
Windows version:
10 64bit

Screenshot: https://i.imgur.com/tK3WG9H.png

**Comment by TheOne320** [comment]
![image](https://user-images.githubusercontent.com/7705568/59183506-70666b80-8b6c-11e9-8151-ded56f864559.png)
The folder should like this. Are you then running it via "Run_TradeMacro.ahk"?

**Comment by Eruyome** [comment]
https://github.com/POE-TradeMacro/POE-TradeMacro/wiki/FAQ#22-running-the-macro-slows-downfreezes-my-pc

Make sure your antivir software isn't removing any files.

**Comment by HolyGasCan** [comment]
So turns out my antivirus ate the file so I added the folder into quarantine and now it's working like a charm. The folder should actually look like this https://i.imgur.com/gFHZo0R.png The fact that the file is hidden made me think that all the files were intact. Thanks for your help!

**Comment by Eruyome** [comment]
That's a bit unfortunate but I made it hidden to avoid users actually starting that file instead of the startup script,, which happenen before and was annoying.
