### ISSUE TITLE
Poe Trade don't start HELP ME PLS!

### ISSUE THREAD

**Issue by Odarude** [PoE-TradeMacro/POE-TradeMacro#985]
![image](https://user-images.githubusercontent.com/51658407/59203040-6724d100-8b63-11e9-801d-1263c01e1df9.png)

**Comment by aRTy42** [comment]
Did you try starting the script a while later? GGG's API had temporary issues earlier today.

**Comment by efraimip** [comment]
still having this issue myself too

**Comment by Belhor** [comment]
Having same issue.

**Comment by Eruyome** [comment]
Closed because the issue is so old. Feel free to message again if the issues still persist.
