### ISSUE TITLE
Why not just suggest a folder for installing? cant install on desktop, cant install in my documents, c drive? nope error. okay where then?

### ISSUE THREAD

**Issue by weswsketch** [PoE-TradeMacro/POE-TradeMacro#986]
This is literally the first thing i do when i use the program, why not just suggest a location if the program is so picky?  why is none of this explained?

**Comment by Eruyome** [comment]
How do you believe should I suggest that, it's not a real installation after all, just a "extract this zip file somewhere"? Any suggestion? People hardly read any FAQ/Instructions on any website so that's not the best way.

**Comment by nqrcqn** [comment]
In my opinion, update the instructions to just use a portable Autohotkey executable rather than installation. I have avoided trade macro a long time until today, when I realized I can use a portable Autohotkey rather than installing it, which I usually avoid.

**Comment by weswsketch** [comment]
After trying several places, i believe i just settled for my C:\Users\name\Downloads folder. Made a subfolder for addons, then dragged a trademacro shortcut to the desktop and finally got it working.

Desktop, as well as C drive and the path of exile folder all gave errors however.

**Comment by Eruyome** [comment]
Desktop caused a lot of permission issues in the past (not for everyone).
C drive in general can also be a bit finicky, especially when placing the folder directly on the drive root.
Same with the PoE folder itself, it's out of the question, it's bad to place files there for external tools.
`%userprofile%\Documents\PoE-TradeMacro` is being used as the macros user folder with config files etc, so it's also out.

Everything else should be fine though

**Comment by dovry** [comment]
%userprofile%\Documents\My Games\$FOLDERNAME

I call my $FOLDERNAME POE-addons
