### ISSUE TITLE
Improve connection security

### ISSUE THREAD

**Issue by nqrcqn** [PoE-TradeMacro/POE-TradeMacro#989]
- These addresses used in macro each support https, and can be easily replaced (http -> https). I have done so, without any issues.

```
http://poe.trade
http://currency.poe.trade
http://api.pathofexile.com
http://poedb.tw
http://pathofexile.gamepedia.com
```

- There might be security issues in curl.exe which is outdated. I suggest updating it to the latest version (7.65.1 at the moment).

**Comment by nqrcqn** [comment]
I missed that https://poe.trade searches later redirect to http, it is still better than nothing, but I wonder if we can enforce encryption there from client side (like https-everywhere), alternative is asking them to support https naturally

**Comment by HiPoEGH** [comment]
What lines in what file did you change? I want to do the same for my script.

**Comment by nqrcqn** [comment]
here: https://github.com/nqrcqn/POE-TradeMacro/commit/6ba0aa5d7b9539adfb8098b38d04053c50de68f2

you can replace curl.exe with latest version from here for peace of mind: https://curl.haxx.se/windows/

also if you want up to date card drop information you can get these files: https://github.com/nqrcqn/POE-TradeMacro/blob/update/data/DivinationCardList.txt https://github.com/nqrcqn/POE-TradeMacro/blob/update/data/MapList.txt

**Comment by Eruyome** [comment]
Finally updated curl, sorry for the wait.
