### ISSUE TITLE
Wrong life calculation

### ISSUE THREAD

**Issue by ricds** [PoE-TradeMacro/POE-TradeMacro#99]
Maximum life was supposed to be 109,5

![image](https://cloud.githubusercontent.com/assets/9935501/20457325/e7a0c1d2-ae6f-11e6-9d5d-ba1e13b8cb7e.png)

**Comment by Eruyome** [comment]
After some testing it seems this only happens when there are 2 sources of Strength (Implicit and Explicit mod).
