### ISSUE TITLE
Couldn't find currency on poe.trade's currency search

### ISSUE THREAD

**Issue by cothyris** [PoE-TradeMacro/POE-TradeMacro#991]
Hello, for the couple leagues already i have a problem with trade macro while trying to check currency prices like orbs or [fossils](https://cdn.discordapp.com/attachments/238871030049931264/587963727635021837/unknown.png), after switching to alternative currency search checking orbs price looks like [that](https://cdn.discordapp.com/attachments/238871030049931264/588332681507504139/unknown.png) but with the fossils problem stays the same. Searching for items prices works [fine](https://i.imgur.com/FIUmP7h.png). Uninstaling and downloading newest version doesn't help. Someone knows how to deal with problem like that? I would be grateful for any helps. Thanks in advance!

AHK version: 1.1.30.0
Windows version: 10

**Comment by Eruyome** [comment]
Closed because the issue is so old. Feel free to message again if the issues still persist.
