### ISSUE TITLE
Trade macro shows error after trying to initialize cookies.

### ISSUE THREAD

**Issue by Mirmoire** [PoE-TradeMacro/POE-TradeMacro#992]
Trade Macro v2.15.0
Windows 10 Pro
AutoHotkey 1.1.26.01

Received this error recently after using HitManPro to removed cookies and malware. Uninstalled shortly after its done and my TradeMacro starts to show this error. I redownloaded the TradeMacro but to no avail.
![Error](https://user-images.githubusercontent.com/51795236/59449217-3ed5f480-8e39-11e9-8c64-bbc22b7a8843.png)

**Comment by Mirmoire** [comment]
System Restore seems to have fixed it. As for what caused it, I have no idea. Probably have something to do with my Google Chrome Cookies being removed and perhaps blocked.

**Comment by Eruyome** [comment]
Sounds weird, but good to know that something like this could happen...
